### ISSUE TITLE
Skip syncing events where I'm free (by availability)

### ISSUE THREAD

**Issue by tsvi** [phw198/OutlookGoogleCalendarSync#1481] opened 2022-05-19 12:45 UTC
**Is your feature request related to a problem? Please describe.**
In our office, it's customary to send a calendar invite for the time when you're OOO, so people can take a cursory look at their calendar and see immediately that a teammate is unavailable.
These invites always have the following parameters: set the time to "Free" so you don't obstruct the other guy's schedule, No alarms, and No replies necessary. It's excellent for my Outlook calendar, but it's very annoying when looking at my Google calendar, and I get a bunch of Foo OOO, Bar OOO.

**Describe the solution you'd like**
Allow me to skip items in the calendar that have me as Free, or otherwise allow me to skip entries that take up the whole day.

**Describe alternatives you've considered**
Taking a look at this, I thought maybe to use some rule to change the category for these items in Outlook so I can use the existing "exclude/include category" option.

**Additional context**

**Comment by phw198** [comment] 2023-07-16 22:42
Thanks for raising. However, on review:
* Skipping all-day items (with the added option of only those that are Free) has been developed under #104 
* Skipping _any_ item that is Free is a duplicate of #825.

I will therefore close this issue - please track progress on the others.

**Closed as completed by phw198** 2023-07-16 22:42 UTC
Labels: duplicate, enhancement
