### ISSUE TITLE
OGCS Won't Start on Login

### ISSUE THREAD

**Issue by fairmarketvalue** [phw198/OutlookGoogleCalendarSync#584] opened 2018-08-31 10:52 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>
I use the installed version of OGCS Version 2.7.5.0 (alpha release). The app does not launch when I start my computer, or when I log back in after it sleeps, even though I have selected "Start on login" on the Application Behaviour" tab. After launching manually, it sometimes crashes and I need to restart it manually.

**Comment by jmiller123** [comment] 2018-09-01 01:26
I have the same issue with OGCS 2.7.5.0 not launching on logging into Windows. Running the latest version of Win10, if relevant. But no problem with the program crashing later. Just does not start up automatically as configured. Currently using 10 second delay option, but this makes no difference.
![ogcs settings](https://user-images.githubusercontent.com/10052005/44941024-53db0e80-ad64-11e8-8c42-d1e1918c3a02.PNG)

**Comment by phw198** [comment] 2018-09-01 12:01
Duplicate of #559

**Closed as completed by phw198** 2018-09-01 12:01 UTC
Labels: duplicate
