### ISSUE TITLE
Timezone could not be recognized

### ISSUE THREAD

**Issue by Nippey** [phw198/OutlookGoogleCalendarSync#587] opened 2018-09-06 05:58 UTC
https://gist.github.com/Nippey/5d3b41306d6df70c3cf2f8cd6c50c810#file-ogcalsync-log

**OGCS Version**: v2.7.6.0
**Installed or Portable**: Installed

**Problem Description**  
OGS told me it could not identify the time-zone of an Event created in Singapore. I am in German time-zone.
During the automatic reporting procedure (toggled unintentionally) the SW froze completely. Maybe because I am behind a proxy.

Therefore, I post the log here and also include snippets of the ICS invitation file.

**Steps to Reproduce the Issue**  
1. Sync the invitation created by a MS Outlook instance running in Singapore time-zone.

Regards
Nippey

**Comment by phw198** [comment] 2018-09-06 22:19
Hi @Nippey 

So fundamentally, this timezone problem isn't really an issue. The reason it reported the error is because the "timezone" of the organiser has been recorded simply as "Singapore" which isn't anything close to a proper timezone. However, after reporting this error, OGCS would default back to the timezone "Singapore Standard Time" as stored against the appointment, and sync that which would be fine in your situation.

So the real problems are:
* Why is the software the inviter is using storing a timezone string which isn't actually a timezone - that's not something OGCS can fix, though I'd be interested to know what software/application they're using
* Why did OGCS freeze after approving the automatic error reporting. It doesn't appear to be captured in your logfile either, but it's possibly a duplicate of #585 
   * If you could turn on error reporting in the Settings > App Behaviour and see if freezes again if you hit another error? If it does, you may need to turn off error reporting until I can determine what's happening.

**Closed as completed** 2018-11-25 00:59 UTC
