### ISSUE TITLE
"Sync Failed" errors cascade, can't close them all, have to kill app in Task Manager

### ISSUE THREAD

**Issue by pringleb** [phw198/OutlookGoogleCalendarSync#1069] opened 2020-08-25 18:35 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.4.0
**Installed or Portable**: Portable

**Problem Description**  
I randomly get an error when it does a sync and it cascades a bunch of "Sync Failed....... Try Again?" messages.  I can click Yes or No and get the same result.  I can't close the rest of the pop-up windows.  I have to kill the app in Task Manager, open it again, and it syncs just fine -- no changes to the calendar on either side. Is there a way to get it to not ask to sync again and just default to trying one more time and then giving up if it fails the second time? 

**Steps to Reproduce the Issue**  
1.  It happens randomly.  

**Any other information**  
Please see the attached image.
![ocgs](https://user-images.githubusercontent.com/32649426/91213792-bf4be280-e6d7-11ea-91ab-4e1d6eb29e0f.jpg)

**Comment by phw198** [comment] 2020-08-25 19:29
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by pringleb** [comment] 2020-08-26 18:18
It is 8/26 @ 1:14p right now and I came back to my computer and had one of
those boxes pop up.  Please find the last three logs attached.

Thank you,
Brian Pringle

**Comment by pringleb** [comment] 2020-09-01 12:54
Paul,

I had the following errors this morning.  I attached the last 3 log files.

[image: image.png]


Thank you,
Brian Pringle

**Comment by Ernst2020** [comment] 2020-09-04 21:35
Exactly the same thing here. If you can't close them, there is such a dialogue hiding between the one you are trying to close.

**Comment by phw198** [comment] 2020-11-01 16:39
Hi @pringleb 

:paperclips: Unfortunately, files and screenshots can't be attached to the ticket when replying by email - you need to log in to GitHub to upload files.

However, I think this is a duplicate of #1109 and should be fixed in v2.8.5

**Comment by pringleb** [comment] 2020-11-01 17:28
I installed the latest version on Wednesday and haven't gotten the error
yet.  I'll keep an eye on it and let you know.

Thanks,
Brian

**Comment by pringleb** [comment] 2020-11-10 19:38
I have only had that problem once since upgrading.  Before it was at least
once a day.  Thanks!

Brian

**Comment by phw198** [comment] 2020-11-22 15:40
Duplicate #1109

**Closed as completed by phw198** 2020-11-22 15:40 UTC
Labels: duplicate, old release
