### ISSUE TITLE
Sync fails if gmail event notifications contain only "Email events"

### ISSUE THREAD

**Issue by paultgordon** [phw198/OutlookGoogleCalendarSync#1358] opened 2021-12-16 17:36 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.2.0
**Edition**: Fails on both
**Sync Direction**: O->G

**Bug Description**  
Doing a sync O->G when your gmail calendar has only email events (not popup events) causing the sync to fail.

**Steps to Reproduce the Issue**  
1. Change gmail calendar settings to have email only events like photo attached. Instructions on how to change reminder settings are described well at: https://webapps.stackexchange.com/a/112905

**Any other information**  
I determined the issue by stepping through the code. This is caused by the issue that in:

GoogleCalendar.cs::getCalendarSettings() -> cal.DefaultReminders.Where(x => x.Method.Equals("popup")).OrderBy(x => x.Minutes.Value).First().Minutes.Value_

The .Where does not return any items so the .First throws an exception.

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7729318/OGcalsync.log)
![GoogleEventNotifSettings](https://user-images.githubusercontent.com/45945537/146420571-c893eff2-1fb4-4f92-a493-13251242ba7f.png)

**Comment by phw198** [comment] 2022-01-08 17:38
Thanks - though this is a duplicate of #1344 which has a hotfix posted.

**Closed as completed by phw198** 2022-01-08 17:38 UTC
Labels: bug, duplicate
