### ISSUE TITLE
Synch is failing because of Null Reference Exception

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#728] opened 2019-05-10 19:58 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Installed

**Problem Description**  
Sync was working fine but somewhere I made a calendar change it doesn't like, and now it is failing with the log report below.     I cannot trace these log messages to the specific calendar event that it is the cause -  otherwise I could give you a better explanation of what I did...
```
019-05-10 15:52:47,196 ERROR  6 OutlookGoogleCalendarSync.Console [0] -  Unable to reclaim orphan calendar entries in Outlook calendar.
2019-05-10 15:52:48,143 DEBUG  6 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2019-05-10 15:52:48,143 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2019-05-10 15:52:48,143 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2019-05-10 15:52:48,144 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-05-10 15:52:48,144 ERROR  6 OutlookGoogleCalendarSync.Console [0] -  Object reference not set to an instance of an object.
2019-05-10 15:52:51,576 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
```

**Steps to Reproduce the Issue**  
1. Do not know!
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2019-05-11 09:17
Duplicate of #689 - [hotfix available](https://github.com/phw198/OutlookGoogleCalendarSync/issues/689#issuecomment-480601660).

**Closed as completed by phw198** 2019-05-11 09:17 UTC
Labels: duplicate
