### ISSUE TITLE
wrong RRULE calculation in reoccurrence events

### ISSUE THREAD

**Issue by stauberix** [phw198/OutlookGoogleCalendarSync#1360] opened 2021-12-20 17:18 UTC
**OGCS Version**: v2.9.0.0  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
Reoccurrence whole-day events created in Outlook where the end date is set by a count or a end date are re-calculated to always have a UNTIL date-time. However this UNTIL date-time is not calculated correctly since it uses a time part. The UTIL date-time is correctly converted to UTC however due to the time-zone conversion it can happen that the day changes. If this happens then the last event of the event series may be missing.

The RFC5545 clearly says: The value of the UNTIL rule part MUST have the same value type as the "DTSTART" property.

Example Outlook event saved as .ics:
DTSTART;VALUE=DATE:20201229
RRULE:FREQ=MONTHLY;COUNT=12;BYDAY=TU;BYSETPOS=-1

My timezone is UTC+1 so OGCS re-calcs it to:
DTSTART;VALUE=DATE:20201229
RRULE:FREQ=MONTHLY;UNTIL=20211129T230000Z;BYDAY=TU;BYSETPOS=-1

This is wrong because the UNTIL should be 20211130 and not containing any time (the DTSTART has value type DATE). So in this case only 11 events are displayed and the last 20211130 is missing.

As workaround I set the end date in Outlook to one day more (20211201) then OGCS calculates it to UNTIL=20211130T230000Z and at least all events are displayed.

Best regards,
Armin

**Steps to Reproduce the Issue**  
See example above.

**Any other information**

**Comment by phw198** [comment] 2022-01-11 00:00
Pretty sure this is a duplicate of #1265 and thus fixed in v2.9.1.

Please upgrade to the latest alpha and confirm if the issue remains.

**Closed as completed** 2022-02-17 08:39 UTC
Labels: bug, duplicate, dormant, old release
