### ISSUE TITLE
Sync stops

### ISSUE THREAD

**Issue by OlleBacklund** [phw198/OutlookGoogleCalendarSync#228] opened 2017-06-02 14:26 UTC
Hi, 
I have just ugraded to 2.4.0.0 and the Outlook to Google stops.
I get the following message:
```
Sync started at 2017-06-02 16:20:38
Syncing from 2017-05-03 to 2017-11-30
Outlook → Google
--------------------------------------------------
Reading Outlook Calendar Entries...
100 Outlook calendar entries found.
--------------------------------------------------
Reading Google Calendar Entries...
98 Google calendar entries found.
2 are exceptions to recurring events.
--------------------------------------------------
Total inc. recurring items spanning sync date range...
Outlook 94, Google 96
--------------------------------------------------
0 Google calendar entries to be deleted.
0 Google calendar entries to be created.
--------------------------------------------------
Comparing 94 existing Google calendar entries...
WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]

WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]
```

**Comment by phw198** [comment] 2017-06-02 15:08
Hard to be 100% without your log file but I think this is a duplicate of issue #83 which has a fix posted.

**Comment by OlleBacklund** [comment] 2017-06-02 15:14
Here is the log file.

**Comment by phw198** [comment] 2017-06-02 16:12
Log files can't be attached via email.The implied suggestion was to try the fix on the other issue anyway...

**Comment by phw198** [comment] 2017-06-05 23:25
The hotfix was rolled in to v2.5.0, if you could confirm the issue is resolved after you've upgraded?

**Comment by OlleBacklund** [comment] 2017-06-07 07:23
Confirmed, it also worked after a while in v2.4.0

Thanks for your quick help.

**Closed as completed** 2017-06-07 07:45 UTC
Labels: duplicate
