### ISSUE TITLE
Crashing on Sync

### ISSUE THREAD

**Issue by jeffwashdeepiq** [phw198/OutlookGoogleCalendarSync#855] opened 2019-09-30 18:34 UTC
**OGCS Version**: v2.8.1  
**Installed or Portable**: Installed

**Bug Description**  

The application is crashing without an error message on Sync.  This happens after a reboot of my PC.  If I disconnect then retrieve my google credentials, it works great until the next time I shut down.

In the Windows Event log, I'm getting the two error entries:
```
Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getCalendarClientSecrets()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.spawnOauth()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<GetAuthenticated>b__14_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: OutlookGoogleCalendarSync.exe, version: 2.8.1.0, time stamp: 0x5d46bdb8
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0f0df9b0
Faulting process id: 0x41a8
Faulting application start time: 0x01d5779c685967e3
Faulting application path: C:\Users\jeff\AppData\Local\OutlookGoogleCalendarSync\app-2.8.1-alpha\OutlookGoogleCalendarSync.exe
Faulting module path: unknown
Report Id: 231199e1-9470-42fd-81eb-4396a633f7bf
Faulting package full name: 
Faulting package-relative application ID: 
```

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3672703/OGcalsync.log)

**Comment by phw198** [comment] 2019-10-02 14:19
Looks like a duplicate of #793 - there's a [hotfix posted there](https://github.com/phw198/OutlookGoogleCalendarSync/issues/793#issuecomment-519279918), which was also backported to v2.8.1.0.

Ie if you uninstall and reinstall v2.8.1 the issue should be gone.

**Closed as completed** 2019-10-20 12:58 UTC
Labels: bug, duplicate
