### ISSUE TITLE
Google Verification Error

### ISSUE THREAD

**Issue by medietri** [phw198/OutlookGoogleCalendarSync#979] opened 2020-04-16 12:59 UTC
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by jorgerds** [comment] 2020-04-17 15:02
when the connection with google will be ready, to be able to configure with gmail

**Comment by medietri** [comment] 2020-04-17 15:06
> when the connection with google will be ready, to be able to configure with gmail

Was working fine up until a few weeks ago...

**Comment by jorgerds** [comment] 2020-04-17 15:17
I need to install it due to an error when retracting the outlook calendar and when it asks me for the gmail account verification, image 1, the error of image 2 appears.
![OGCS 1](https://user-images.githubusercontent.com/63622843/79584889-a16cd200-8094-11ea-8fb4-05271665187b.JPG)
![OGCS 2](https://user-images.githubusercontent.com/63622843/79584892-a2056880-8094-11ea-8774-bd5db597fb9c.JPG)

**Comment by phw198** [comment] 2020-04-18 21:25
@medietri A duplicate of #915 

@jorgerds A [FAQ](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#page-cannot-be-displayed-after-authorising-ogcs-to-access-my-calendar)

**Closed as completed** 2020-04-18 21:25 UTC
Labels: duplicate, question
