### ISSUE TITLE
timezone mapping popup: couldn't it be avoided?

### ISSUE THREAD

**Issue by tdalon** [phw198/OutlookGoogleCalendarSync#939] opened 2020-01-09 08:27 UTC
I have updated to the new version and now get this popup requiring to map some appointment timezone to my system timezone.
I don't understand why it is required.
My system timezone does not change. Maybe it could be read from my Windows or Outlook settings. At least I shall only have to set it once for all.
I find this popup quite annoying.
Do I miss something here?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by phw198** [comment] 2020-01-14 21:47
You've not provided the timezone that OGCS is not able to automatically map to one on your computer, so it's not possible to say 100%.

But yes, it's likely you missed something: Issue #843 

However, there's a slight bug with it, in that it might not save the mapping your specify - resulting in repeated prompts for the same map. That's a bug that I was already working on fixing...

**Comment by phw198** [comment] 2020-01-14 22:13
:package: Repeated prompts should now be resolved with [hotfix v2.8.3.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4061839/v2.8.3.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by YasharF** [comment] 2020-01-21 19:40
I seem to have the same problem, as the following pop up, pops up often, even though my answer is always the same and slightly different than the default that is in the UI.  I just installed the hotfix to see if it fixes it.

![image](https://user-images.githubusercontent.com/6448697/72836812-30a74c80-3c42-11ea-92c7-1f760e055932.png)

**Comment by krambock** [comment] 2020-02-04 23:02
I can confirm that applying the hotfix fixes the issue.  I had the same problem and applied it.

**Comment by YasharF** [comment] 2020-02-20 17:53
I have been running hotfix v2.8.3.1 for 30 days at this point and have not seen that pop-up since installing the hotfix.

**Closed as completed** 2020-06-24 14:19 UTC
Labels: bug, resolved
