### ISSUE TITLE
Regular 'Google event update failed' / 'Value cannot be null. Parameter name: input'

### ISSUE THREAD

**Issue by knari77** [phw198/OutlookGoogleCalendarSync#1798] opened 2024-02-07 17:19 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
1. Almost every several minutes I see the message as in the attached picture below
2. If I click 'Yes' the sync goes well, without any error message.
3. But then in a few min it comes up again. It started after I updated the build to the latest Alpha version, I haven't had something like this before

**Steps to Reproduce the Issue**  
1. Nothing to do, just open the app and then you see it in a few min on the sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/74589649/d96fceb4-5369-41ef-897c-576c4ac9859f)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14197126/OGcalsync.log)

**Comment by schnodo** [comment] 2024-02-07 20:17
This looks like a duplicate of https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776.

**Comment by knari77** [comment] 2024-02-07 20:29
Yes, it looks so. I have just installed the hot fix, thanks

**Closed as not planned** 2024-02-07 20:30 UTC
Labels: bug, duplicate
