### ISSUE TITLE
After attaching to Outlook "The RPC server is unavailable." [0x800706BA]

### ISSUE THREAD

**Issue by KoalaBear84** [phw198/OutlookGoogleCalendarSync#765] opened 2019-06-19 07:09 UTC
**OGCS Version**: v2.8.0.1  
**Installed or Portable**: Installed

**Problem Description**  
2019-06-18 19:09:20,081 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

**Steps to Reproduce the Issue**  
No idea, logged back in and saw this screen.

**Any other information**  
No.

## Log

<details><summary>Log</summary>
<p>

```
2019-06-18 15:08:38,460 DEBUG  13 OutlookGoogleCalendarSync.Sync.Engine [0] -  Synchronising from Google to Outlook.
2019-06-18 15:08:38,461 INFO  13 OutlookGoogleCalendarSync.Console [0] -  Syncing Outlook ← Google
2019-06-18 15:08:38,728 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Scanning 14 Outlook appointments for orphans to reclaim...
2019-06-18 15:08:38,728 DEBUG  13 OutlookGoogleCalendarSync.Console [0] -  Checking for orphaned items...
2019-06-18 15:08:46,970 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  0 unclaimed.
2019-06-18 15:08:46,971 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google events to Outlook items...
2019-06-18 15:08:46,971 DEBUG  13 OutlookGoogleCalendarSync.Console [0] -  Matching calendar items...
2019-06-18 15:08:53,319 INFO  13 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be deleted.
2019-06-18 15:08:53,320 INFO  13 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be created.
2019-06-18 15:08:53,320 INFO  13 OutlookGoogleCalendarSync.Console [0] -  14 calendar entries to be compared.
2019-06-18 15:08:53,363 INFO  13 OutlookGoogleCalendarSync.Console [0] -  Comparing 14 existing Outlook calendar entries
2019-06-18 15:08:54,051 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  2019-04-29 09:30 (R) => "CEC inRiver Weekly Standup"
2019-06-18 15:08:54,052 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 4 exceptions in the sync date range.
2019-06-18 15:08:54,314 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  2018-09-12 10:00 (R) => "4 wekelijke meeting"
2019-06-18 15:08:54,314 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 2 exceptions in the sync date range.
2019-06-18 15:08:54,503 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2019-07-17 10:00:00
2019-06-18 15:08:54,653 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  2018-04-18 11:00 (R) => "Taakgroep .NET"
2019-06-18 15:08:54,654 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 711 exceptions in the sync date range.
2019-06-18 15:09:25,773 INFO  .NET SystemEvents OutlookGoogleCalendarSync.NotificationTray [0] -  Detected system timezone change.
2019-06-18 15:09:31,053 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2018-04-18 11:00:00
2019-06-18 15:09:31,217 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2018-08-22 11:00:00
2019-06-18 15:09:31,375 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2018-11-14 11:00:00
2019-06-18 15:09:31,513 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2018-12-26 11:00:00
2019-06-18 15:09:31,655 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  2017-02-02 06:00 (R) => "Thuiswerkdag"
2019-06-18 15:09:31,656 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 1 exceptions in the sync date range.
2019-06-18 15:09:31,738 DEBUG  13 OutlookGoogleCalendarSync.Recurrence [0] -  Found Outlook exception for 2019-06-20 06:00:00
2019-06-18 15:09:31,807 DEBUG  13 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  2016-05-31 16:00 (R) => "Herinnering:  Uren compleet maken afgelopen maand"
2019-06-18 15:09:31,814 INFO  13 OutlookGoogleCalendarSync.Console [0] -  0 entries updated.
2019-06-18 16:08:57,889 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Scheduled sync triggered.
2019-06-18 16:08:57,941 WARN  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Automated sync triggered whilst previous sync is still running. Ignoring this new request.
2019-06-18 16:08:57,941 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Background worker is busy? A:False
2019-06-18 16:08:58,066 INFO  .NET SystemEvents OutlookGoogleCalendarSync.NotificationTray [0] -  Detected system timezone change.
2019-06-18 16:08:58,601 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'CompletedSyncs' updated to '65'
2019-06-18 16:08:58,603 INFO  1 OutlookGoogleCalendarSync.Console [0] -  Sync finished with success!
2019-06-18 16:08:58,888 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '2019-06-18 15:08:07'
2019-06-18 16:08:58,890 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Tuesday, June 18, 2019 @ 16:09:58
2019-06-18 16:08:59,702 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  De-referencing all Outlook application objects.
2019-06-18 16:09:00,334 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Disconnecting from Outlook application.
2019-06-18 19:09:05,505 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Scheduled sync triggered.
2019-06-18 19:09:05,521 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Scheduled sync started (AutoSyncTimer).
2019-06-18 19:09:06,794 WARN  1 OutlookGoogleCalendarSync.Console [0] -  There does not appear to be any network available! Sync aborted.
2019-06-18 19:09:07,260 INFO  .NET SystemEvents OutlookGoogleCalendarSync.NotificationTray [0] -  Detected system timezone change.
2019-06-18 19:09:08,779 INFO  1 OutlookGoogleCalendarSync.Console [0] -  Another sync has been scheduled to automatically run in 15 minutes time.
2019-06-18 19:09:08,789 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Tuesday, June 18, 2019 @ 19:24:08
2019-06-18 19:09:09,303 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attaching to the already running Outlook process.
2019-06-18 19:09:09,305 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attachment failed - Outlook is running without GUI for programmatic access.
2019-06-18 19:09:09,306 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Starting a new instance of Outlook.
2019-06-18 19:09:20,056 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Setting up Outlook connection.
2019-06-18 19:09:20,081 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.InvalidCastException: Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
2019-06-18 19:09:20,209 DEBUG  1 OutlookGoogleCalendarSync.Forms.ErrorReporting [0] -  Asking user if they want to automatically report errors.
```

</p>
</details>

**Comment by phw198** [comment] 2019-07-06 22:06
Summary:
* Outlook is not running, a sync completed successfully, then detached.
* Computer goes to sleep?
* Computer awakes 3 hours later, reattaches to Outlook OK (with no 0x800706BA)
* Then errors straight after with 0x800706BA, possibly on `GetNamespace("mapi")`

@KoalaBear84 Was this a one off or repeatable? It's odd because there's lot of error handling for this when attaching to Outlook, but not for the step directly after. I'm not sure why Outlook would suddenly become unavailable like that...

**Comment by phw198** [comment] 2019-07-07 11:15
Actually, I think the issue is that OGCS started syncing too quickly after resuming the computer - before the network was available. It should then just "disconnect" from Outlook, but instead it was first reconnecting and then failing because it couldn't communicate properly (due to no network!).

:package: This should now be resolved with [hotfix v2.8.0.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3365539/v2.8.0.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by KoalaBear84** [comment] 2019-07-07 11:19
Thanks! Haha. I was still in the process of typing a response I started an hour ago or so.

"Maybe it was in sleep, but I'm not sure. Looking at the logs it looks like it.

A one off. Unfortunately I have no idea either. The only thing that could be done is (even more) error handling."

So, now it probably is fixed by another mechanisme. I will apply this tomorrow at work. You might want to close the issue sooner, as it happens maybe rarely and it might be open for an undetermined period.

**Comment by phw198** [comment] 2019-07-07 11:46
:package: OK, a few more tweaks in [v2.8.0.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3365573/v2.8.0.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) but that should be it!

I'll probably pull this into the next alpha release regardless whether you can confirm a definite fix - I think it may be the cause of a few gremlins in other tickets too (#754)...

**Closed as completed** 2019-08-03 09:57 UTC
Labels: bug, waiting fix confirmation
