### ISSUE TITLE
failure 412  every 15 minutes no update possible

### ISSUE THREAD

**Issue by MarcCo1** [phw198/OutlookGoogleCalendarSync#1286] opened 2021-09-16 11:08 UTC
**OGCS Version**: v2.9.00
**Edition**: Installed 
**Sync Direction**: O->G 
**Bug Description**  

It's been 2 weeks now that i get the failure message
_Unable to add new entries into the Google Calender
Precondition failed [412-precondition failed]
Sync aborted after 1 failed attempts!_
This message apears every 15 minutes.

1. i have updated to the latest version (problem started in previous version)
2.  i have disconected the google acount and retrieved it again (although after disconecting and before retrieving after restart the original google account was still shown in the Connected account box)

**Steps to Reproduce the Issue**  
1. failure starts on automated sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7177159/OGcalsync.log)

**Comment by WarningU2** [comment] 2021-09-16 15:06
Getting the same error.   Started a couple of days ago.   I restart the sync normally and it completes successfully,   In  one instance I had to shutdown OGS as it was in a recursive fail for 412 ... must of had about 50 errors before I caught it.   In the log see this ... 
```
021-09-15 08:53:27,326 FAIL  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1764] -  Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]

2021-09-15 08:53:27,327 WARN  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1820] -  Unhandled API exception.
2021-09-15 08:53:27,328 ERROR  18 OutlookGoogleCalendarSync.Console [278] -  Updated event failed to save.
2021-09-15 08:53:27,337 ERROR  18 OutlookGoogleCalendarSync.Console [278] -  Precondition Failed [412=PreconditionFailed]
2021-09-15 08:53:27,385 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [28] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]

2021-09-15 08:53:27,388 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131500,-2146233088; Location: MoveNext() in <Unknown File>
2021-09-15 08:53:27,390 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [65] -     at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
Log attached.  
[OGcalsync.log.2021-09-15.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/7178919/OGcalsync.log.2021-09-15.txt)

**Comment by phw198** [comment] 2021-09-17 21:47
@MarcCo1 `14/09/2021 14:00 (R) "KWM-LES 3"` is the problematic series, and I cannot quite work out the how you've arrived at a series that:
* Starts on Tues 14-Sep, recurs every week and end on Thurs 23-Sep (odd end date?)
* Tues 14-Sep occurrence is deleted
* Tues 21-Sep occurrence is deleted
* an occurence on Sun 19-Sep exists, perhaps moved from 14-Sep?

It looks like the series is created by someone else and you're invited? Can you remember the sequence of events? Did they send an invite, then cancel it/rearrange some of the dates?

**Comment by phw198** [comment] 2021-09-17 22:08
@WarningU2 Do you by any chance have something other than OGCS that might be updating Google events at the same time OGCS is syncing??

**Comment by WarningU2** [comment] 2021-09-17 23:27
Hi Paul.   I don't believe so.  The only thing that would update it would if I was signed into Google updating the calendar.   I wasn't.   But the Google calendar is "shared".   My wife also has access to the same calendar.   She was not actively updating it at the time of the error though.   Outlook is open at the same time.   

Hang on ... I just remembered there were two instances of OGCS running and I exited one of them before resyncing.   Not sure why there were two instances running but maybe thats key.

**Comment by phw198** [comment] 2021-09-18 16:54
@WarningU2 Ah yes, two instances at the same will be the cause - and this reminds me that there may also be [some obscure bug](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1052#issuecomment-767997598) related to upgrading a portable release of OGCS that causes two to run.

If you continue to encounter two instances of OGCS running, can you:
* Start Task Manager > Details > Right click column header > Select columns > Check "Command Line"
* Confirm the command line entry for both OutlookGoogleCalendarSync.exe processes running
<br/>

* Open `regedit` and navigate to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`
* Confirm what the value is for `Outlook Google Calendar Sync` key

**Comment by MarcCo1** [comment] 2021-09-20 07:03
Hello Phw198
Thank you for taking a look to my problem.
I do't know what went wrong regarding this (recurent) invitation 'KWM- Les3.'
I removed the appointment on 19-10 and now the program is running smoothly as before.
Your sollution did the trick; thanks for solving.
Now i know where to look and solve in the future if such a failure occurs.
Maybe one more question.
After failure the programm starts to try again afster 15 minutes. This results in a lot of popup screens which have to be deleted one by one.
Is it possible to change this 15 minutes frequency yourself?

**Comment by phw198** [comment] 2021-09-25 20:55
@MarcCo1 No, the retry frequency isn't configurable, but there is an enhancement suggestion on #1190 for automatically closing popup messages.

**Closed as completed by phw198** 2021-09-25 20:55 UTC
Labels: bug

**Comment by phw198** [comment] 2022-08-13 11:13
:link: #1524
