### ISSUE TITLE
At any time the app delete all the task on gmail calendar and recreate all

### ISSUE THREAD

**Issue by saff2323** [phw198/OutlookGoogleCalendarSync#529] opened 2018-05-22 19:15 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v 2.7.4.0  
**Installed or Portable**: Installed

**Problem Description**  
\<At any time the app delete all the task on gmail calendar and recreate all>

**Steps to Reproduce the Issue**  
1.  sync the with the button
2. the app delete all tasks on calendar and recreate all
[OGcalsync.log.2018-04-24.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2028231/OGcalsync.log.2018-04-24.txt)

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-05-22 20:51
OGCS doesn't sync tasks - do you mean tasks or meetings/appointments?

If the latter, then this is a possible duplicate of issue #440 - do you have more than one computer syncing to the same Google calendar with 2-way sync configured?

Your logfile also shows you running `v2.7.2`, not `v2.7.4`. Is this right? Have you upgraded?

**Comment by saff2323** [comment] 2018-05-23 14:51
this mi today log, from the last version. v2.7.4.0
the issue is: everytime when I sync delete and recreate al tasks, and for my is a problem.

**Comment by phw198** [comment] 2018-05-23 15:32
:paperclips: Files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

You haven't answered any of my questions. Once again, OGCS doesn't sync tasks.

**Comment by saff2323** [comment] 2018-05-23 16:10
--->   meetings to my gmail calendar
--->  I think is not the same issue, I just have one computer suncing
---> My file is attached now to the case
    On Tuesday, May 22, 2018, 2:51:14 PM CST, Paul Woolcock <notifications@github.com> wrote:  
 
 
OGCS doesn't sync tasks - do you mean tasks or meetings/appointments?

If the latter, then this is a possible duplicate of issue #440 - do you have more than one computer syncing to the same Google calendar with 2-way sync configured?

Your logfile also shows you running v2.7.2, not v2.7.4. Is this right? Have you upgraded?

**Comment by saff2323** [comment] 2018-05-23 16:18
![image](https://user-images.githubusercontent.com/39534855/40437440-97a6032c-5e72-11e8-8359-275c58ef7c7b.png)

**Comment by saff2323** [comment] 2018-05-23 16:18
![image](https://user-images.githubusercontent.com/39534855/40437479-aeb5e53c-5e72-11e8-9ccf-2e08de367f28.png)

**Comment by phw198** [comment] 2018-05-23 16:29
Do you know what your email domain is hosted on? It doesn't appear to be Exchange. How is the connection to it set up in Outlook - IMAP?

Basically the immutable ID for each meeting are all changing - I've only seen this on Apple iCloud calendars before.

Please could you turn on CSV file creation in the Settings > Application Behaviour. You'll then need to 
- run a sync
- zip up the CSV files somewhere
- run another sync that deletes and recreates everything
- zip up the new CSV files
- upload the zips for me to assess

I can then see what bits of the ID are changing...

**Comment by saff2323** [comment] 2018-05-23 16:38
I conecting to my Outlook a Teamwork calendar to sync to Gmail.

the files you need to change the extension from .txt to .rar to unrar

[Sync 1.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2031979/Sync.1.txt)
[Sync 2.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2031980/Sync.2.txt)

**Comment by saff2323** [comment] 2018-05-23 16:55
[Sync 3.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/2032032/Sync.3.txt)


1 more group of files after one sync

**Comment by phw198** [comment] 2018-05-24 21:42
Thanks @saff2323 - yes it looks like the `EntryID` is changing for the same calendar item between syncs :disappointed: 

:package: However, I think [this hotfix v2.7.4.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2036581/v2.7.4.1.zip) may help ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

With any luck, it won't recreate everything, but it will still want to update every synced item in Google, which is far from ideal!

I see you should be able to subscribe to a [Teamwork calendar in Google via an ICAL feed](http://support.teamwork.com/projects/calendar/viewing-your-teamwork-projects-calendar-in-google-calendar) - does that not fit your needs?

**Comment by saff2323** [comment] 2018-05-25 00:10
thanks, I try this fix.
I can't subscribe to teamwork direct because when I mark completed a task it disappear from my google calendar, and I need to see past events on my calendar.
your app delete 0 days in past if I need.
Thanks
    On Thursday, May 24, 2018, 3:42:36 PM CST, Paul Woolcock <notifications@github.com> wrote:  
 
 
Thanks @saff2323 - yes it looks like the EntryID is changing for the same calendar item between syncs 😞
 
 📦 However, I think this hotfix v2.7.4.1.zip may help (see instructions for applying).

With any luck, it won't recreate everything, but it will still want to update every synced item in Google, which is far from ideal!

I see you should be able to subscribe to a Teamwork calendar in Google via an ICAL feed - does that not fit your needs?

**Comment by saff2323** [comment] 2018-05-26 04:44
Perfect, the issue is solved. this release is good. 
![image](https://user-images.githubusercontent.com/39534855/40572587-0ed65e5a-606d-11e8-831b-f0da569c65ae.png)

thank you so much

**Comment by saff2323** [comment] 2018-05-29 14:59
Thanks

**Closed as completed** 2018-07-15 21:42 UTC
Labels: resolved
