### ISSUE TITLE
OGCS deleting event series created in Outlook with no end date

### ISSUE THREAD

**Issue by SamuelStevenson** [phw198/OutlookGoogleCalendarSync#1095] opened 2020-09-30 18:29 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
I've got the **When** setting at 1 day in the past and 60 days in the future. When an event series is created in Outlook that has no end date, it seems to get deleted from both calendars.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5307560/OGcalsync.log)

**Comment by danji77** [comment] 2020-10-29 15:11
I seem to have same problem but it is not the end date that is the problem. I think it is because the first entry is prior to your "past syn date" which is 1. Since the item has a date before the  number of past days, it wants to delete the item, although the recurrence makes it relevant to keep. I am on 2.8.0.0.

**Comment by phw198** [comment] 2020-10-31 19:41
@SamuelStevenson The only real issue I can see in your log file is following you requesting a cancellation of the sync and it failing to get the end date of an appointment:
```
2020-09-30 11:22:40,630 INFO  7 OutlookGoogleCalendarSync.Console [0] -  Scanning Outlook calendar...
2020-09-30 11:22:40,693 WARN  1 OutlookGoogleCalendarSync.Sync.AbortableBackgroundWorker [0] -  Aborting background thread...
2020-09-30 11:22:40,704 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Threading.ThreadAbortException: Thread was being aborted.
2020-09-30 11:22:40,706 INFO  1 OutlookGoogleCalendarSync.Sync.AbortableBackgroundWorker [0] -  Aborted.
2020-09-30 11:22:40,718 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131530;-2146233040
2020-09-30 11:22:40,718 WARN  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Sync thread forcefully aborted!
2020-09-30 11:22:40,726 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_End()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.FilterCalendarEntries(Items OutlookItems, Boolean filterBySettings, Boolean noDateFilter, String extraFilter, Boolean suppressAdvisories)
2020-09-30 11:22:40,869 DEBUG  7 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Unable to get End date for: 11/17/2020 7:00 PM => "AGM - KATI"
2020-09-30 11:22:40,884 ERROR  7 OutlookGoogleCalendarSync.Console [0] -  Unable to access the Outlook calendar.
2020-09-30 11:22:41,037 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
2020-09-30 11:22:41,043 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131527;-2146233049
2020-09-30 11:22:41,048 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Threading.ThreadAbortException: Thread was being aborted.
2020-09-30 11:22:41,053 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131530;-2146233040
2020-09-30 11:22:41,058 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.FilterCalendarEntries(Items OutlookItems, Boolean filterBySettings, Boolean noDateFilter, String extraFilter, Boolean suppressAdvisories)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetCalendarEntriesInRange(Boolean suppressAdvisories)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass20_0.<Start>b__0(Object o, DoWorkEventArgs args)
2020-09-30 11:22:41,063 FAIL  7 OutlookGoogleCalendarSync.Sync.AbortableBackgroundWorker [0] -  Thread was being aborted.
```
What was the item date and subject that was getting deleted? Are you sure it's being picked up correctly - [check the date formatting](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items) you have is working correctly.

Could you [upgrade to v2.8.5](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.5-alpha) and reproduce the issue so it shows in your log files please.

@danji77 No that's not how it works - any recurring series that spans the synced date range is in scope. Unless that is you are using Outlook 2003? In which case that might be a duplicate of #1051...

**Closed as completed** 2021-01-24 02:03 UTC
Labels: bug, more info needed, dormant, old release
