### ISSUE TITLE
Mismatch between recurring items' end dates

### ISSUE THREAD

**Issue by invalidCards** [phw198/OutlookGoogleCalendarSync#636] opened 2018-12-03 15:39 UTC
**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
An event in Outlook has the recurring rule "every Wed and Thu from 10-10-2018 to 20-12-2018", and lasts all day every time. In Outlook, the last time this event occurs is on the 20th. Once synced to Google, the last time this event occurs is on the 19th.

**Steps to Reproduce the Issue**  
1. Create an event in Outlook that lasts all day, and have the final occurrence be on one of the selected weekdays.
2. Sync to Google.
3. Observe that the event doesn't repeat for the last time, and shows that it repeats until one day before the actual ending date.

**Any other information**  
I assume this is a mismatch between the way both calendar systems handle "until" dates, with Google cutting off before the start of the day, and Outlook afterwards. It would be nice to have consistency in this case, i.e. make the synced event last a day longer.

**OGcalsync.log**
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2640121/OGcalsync.log)

**Comment by phw198** [comment] 2018-12-28 17:44
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by [downloading the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

The issue you describe is likely due to timezones and may well already be fixed.

**Comment by bpitrain** [comment] 2019-07-01 16:16
I have the same issue as this which I noticed for all recurring events ending after 1st July 2019.  I just updated from v2.7.0 to the latest version and the issue remains.

**Comment by phw198** [comment] 2019-07-05 06:30
@bpitrain Have you performed a full sync (`Shift`+ Sync) sync upgrading?

**Comment by bpitrain** [comment] 2019-07-05 09:56
Hi Paul,

 

I hadn’t because I wasn’t aware of the shift option, but I’ve just tried it and it hasn’t made any difference.

 

I’ve attached 2 screenshots of one of the affected appointments so you can see.

 

If you need any log files etc to help track the issue down just let me know.  I’ve resorted to manually adding an additional, single event on the last day of the series as a work round at the moment but of course this isn’t ideal.

 

Regards

 

Mark

 

 

-- 

Mark Adams  TechIOSH                  bpi group

 

Tel: 01685 886357  Fax: 01685 886342

 

bpi consultancy ltd is a company registered in Wales, Company No: 04080104 whose registered office is Office 8, Venture Wales Building, Depot Road, Aberdare, CF44 8DL.

**Comment by bpitrain** [comment] 2019-07-05 11:26
Hi Paul,

 

As soon as I sent you the last response I realised that been impacted again by the bug in the sync. (I’m not having a moan just want to try and clarify the issue to help you solve it.)

 

So Outlook has my work calendar and Google my personal calendar along with shared calendars for my wife.  I have a separate Google calendar (shared with my main personal one) that is the one that I use your software to sync my Outlook with.  That way I can see or not see my work schedule, overlaid on my personal calendar, by making that visible or invisible.

 

So last night I booked flights for my wife returning on a day when I had no business appointments so that I could collect her from the airport. (Oct 3rd)

 

So today when I got into the office I opened my work Outlook calendar to find that I did have an appointment on Oct 3rd – the last day of a 4 day weekly recurring event that only had the 1st 3 events showing in Google.  I had missed this issue as being the 1st week of October I hadn’t seen the previous 3 Sept appointments on the Oct page.

 

I then tried your shift sync suggestion and that didn’t make any difference. I then added my wife’s trip into Outlook as a multi day event and did another full sync.

 

As you can see from the attached screenshots, the multi day event comes across correctly but the recurring event is still missing it’s last day as although Google sees it reoccurring weekly on a Thursday it thinks it ends on the 2nd Oct (Wednesday) and not the 3rd.

 

Looking back I can see that this was not an issue on any recurring events before the end of March 2019.  I didn’t have any recurring events in April, but it did affect a recurring event in May I just didn’t notice it at the time.

 

Hope this helps you to find the issue.

 

Regards

 

Mark

 

 

 

-- 

Mark Adams  TechIOSH                  bpi group

 

Tel: 01685 886357  Fax: 01685 886342

 

bpi consultancy ltd is a company registered in Wales, Company No: 04080104 whose registered office is Office 8, Venture Wales Building, Depot Road, Aberdare, CF44 8DL.

**Comment by phw198** [comment] 2019-07-05 12:35
Thanks for the updates. Initial thoughts are that maybe this is a daylight saving problem and not timezone. Are you in a DST zone and are the problem recurring series only for those crossing a daylight saving change?

(Note, you can't upload files to GitHub via email so I can't see those screenshots).

**Comment by bpitrain** [comment] 2019-07-05 12:57
I'm in the UK so we are currently on BST (British Summer TIme = GMT +1)

The issues are not with series that are crossing a change but they are series that are wholly in the BST time period.  The series are 'full day events' and I guess it's not impossible that Google thinks the series ends at midnight GMT which would be 11pm on the previous day BST, but then wouldn't it think it starts earlier too?

Also I've been using this software for years and I've never had this issue before.

I've pasted the files directly here for you to see, hopefully.
![sync3](https://user-images.githubusercontent.com/52420794/60723880-c8567f00-9f2c-11e9-8c6c-b6b5fe2e17c0.PNG)
![sync4](https://user-images.githubusercontent.com/52420794/60723881-c8567f00-9f2c-11e9-8bb1-db773255a8ed.PNG)
![sync5](https://user-images.githubusercontent.com/52420794/60723882-c8567f00-9f2c-11e9-87b2-976cf3005b1c.PNG)
![sync6](https://user-images.githubusercontent.com/52420794/60723884-c8567f00-9f2c-11e9-9065-13ae149166b8.PNG)

**Comment by phw198** [comment] 2019-07-06 17:40
Thanks - as we suspected, it's down to DST and yes, the recurrence rule end time is an hour early: `RRULE:FREQ=WEEKLY;UNTIL=20191002T230000Z`

**Comment by phw198** [comment] 2019-07-06 20:49
:package: This should now be resolved with [hotfix v2.8.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3365013/v2.8.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by bpitrain** [comment] 2019-07-08 08:50
Sorry I think I'm missing something with installing this hotfix as I can't get it to run.

I confirmed I was on the right version and opened the application directory.

In the directory was the .exe file and a subdirectory app-2.8.0-beta.

I renamed the .exe to .old and created an app-2.8.0-alpha as per the instructions and copied the hot-fix executable into it, which I then ran.

The app appears to load but doesn't open.  I'm wondering if the presence of the beta folder is the issue?

**Comment by phw198** [comment] 2019-07-08 09:42
Try the [instructions again](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#find-the-location-where-the-application-executable-is-running-from) - looks like you changed the wrong executable...

The subdirectory is `app-2.8.0-beta`, so within that directory, copy the executable and then overwrite the original with the hotfix.

**Comment by bpitrain** [comment] 2019-07-08 09:59
OK I understand now, I think the bit in the instructions about being on an Alpha Released confused me that hotfixes were classed as alphas.

I can confirm that putting it in the beta directory worked and that the patch has fixed the problem.

My last recurring appointments now appear in gCal correctly.

Many thanks

**Closed as completed** 2019-08-03 09:54 UTC
Labels: bug, timezones, resolved
