### ISSUE TITLE
Issue: "Event Update failed" O -> G,   and multiple "Instance no longer exists" G -> O  

### ISSUE THREAD

**Issue by DWB111** [phw198/OutlookGoogleCalendarSync#1451] opened 2022-04-28 15:08 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by DWB111** [comment] 2022-04-28 15:30
Issue: "Event Update failed" O -> G,   and multiple "Instance no longer exists" G -> O 

OGCS v 2.9.4.0, Outlook 2019
Laptop
Syncing both directions

IN O->G phase, receive multiple "Event Update failed" (sometimes for when change or move event, sometimes for an older event.  But in reality, G SOMETIMES updates in spite of message.  Always asks if want to continue.
IN G -> O phase, receive multiple "Instance no longer exists", but program continues to run.
In Outlook, for failed, have tried going back and deleting original entry and add new,and  deleting same event in G, then syncing only O->G.  This often works, but on later syncs, for recurring event, may have a problem with same event but on different date of recurrence.
Definitely need to close outlook between tries, presumably cache issue.
Problem began with upgrade to Outlook 2019 from 2007.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8584134/OGcalsync.log)

**Comment by DWB111** [comment] 2022-04-28 15:33
Sorry about all the edits etc- clearly don't know how this works

**Comment by dirkdewulf** [comment] 2022-04-29 07:07
I think I have the same problem

**Comment by DWB111** [comment] 2022-04-29 23:13
Looks like a problem with v2.9.4.  installed 2.9.0 and that version is working ok.

**Comment by phw198** [comment] 2022-05-02 17:50
Think this is a duplicate of #1432 - please try the hotfix posted there.

**Closed as completed by phw198** 2022-05-02 17:50 UTC
Labels: bug, duplicate
