### ISSUE TITLE
OGCS crashes constantly

### ISSUE THREAD

**Issue by u723896** [phw198/OutlookGoogleCalendarSync#982] opened 2020-04-29 07:38 UTC
**OGCS Version**: v2.8.3  
**Installed or Portable**: POrtable

**Problem Description**  
Recently my company changed the Outlook program, this caused that my Calendar is now in a different mailbox, but I cannot update the mailbox, as it immediately produces an error:
Application unexpectedly terminated
Window handle already exists
![Capture](https://user-images.githubusercontent.com/64522085/80571439-ed0c6d80-89fc-11ea-9643-fc346094006a.PNG)

**Steps to Reproduce the Issue**  
1. Start OGCS
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4550301/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2020-04-29 23:47
Sounds like a duplicate of #944 which has a hotfix posted.

**Comment by u723896** [comment] 2020-04-30 07:51
Thanks, it working now :-)

Chris

**Closed as completed** 2020-05-05 14:17 UTC
Labels: duplicate
