### ISSUE TITLE
Error Precondition Failed [412]

### ISSUE THREAD

**Issue by asgreenb** [phw198/OutlookGoogleCalendarSync#986] opened 2020-05-06 14:41 UTC
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4587408/OGcalsync.log)

Version | 2.8.0.0
-- | --
Running From | C:\Portable_OGCS_v2.8.0\OutlookGoogleCalendarSync.exe
Config In | C:\Portable_OGCS_v2.8.0\settings.xml
Subscription | N/A
Timezone DB | 2020a

**Sync Direction**: O->G 

**Bug Description**  
popup - synch item failed. Update google event failed to save. Continue with synch?

**Steps to Reproduce the Issue**  
Just wait for the next auto-synch

**Any other information**  

:paperclip: Attach your `OGcalsync.log` file.
DONE

**Comment by phw198** [comment] 2020-05-08 19:37
> FAILURE TO FOLLOW THESE STEPS MAY RESULT IN YOUR ISSUE SIMPLY BEING CLOSED!  
1. Upgrade to the latest alpha release to check if the problem is already fixed. 

Also a duplicate of #528

**Closed as completed** 2020-05-08 19:37 UTC
Labels: bug, duplicate, old release
