### ISSUE TITLE
prevent outlook from starting automatically

### ISSUE THREAD

**Issue by marcopatr** [phw198/OutlookGoogleCalendarSync#596] opened 2018-09-17 22:14 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
It seems like OGCS causes Outlook to start. Can this be prevented somehow?

**Comment by phw198** [comment] 2018-09-17 22:52
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

If you are on an version v2.7.3 or earlier, due to a [GitHub change](https://github.com/phw198/OutlookGoogleCalendarSync/issues/497) you will need to [download the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by phw198** [comment] 2018-09-17 22:52
Duplicate of #535

**Closed as completed by phw198** 2018-09-17 22:52 UTC
