### ISSUE TITLE
Google Sync issue

### ISSUE THREAD

**Issue by mattnotl33t** [phw198/OutlookGoogleCalendarSync#1061] opened 2020-08-18 01:21 UTC
Hello,
I have been using this for a couple years now, and i think that the issue is on google's end. Maybe.
I have my system currently running version 2.8 and i started it up with outlook (from office 365) running. My default browser (Chrome) opens up with a page to select the google account that i need to authenticate with. i select the desired account and the following page reports that "Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."
when i go into the google security checkup under the 3rd party apps it says that it is an unverified developer
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5087598/OGcalsync.log)
Thanks,
Matt

**Comment by phw198** [comment] 2020-08-18 07:37
Duplicate of [915](https://github.com/phw198/OutlookGoogleCalendarSync/issues/915#issuecomment-563376974)

**Closed as completed** 2020-08-18 07:37 UTC
Labels: duplicate
