### ISSUE TITLE
Do you have a MAC version?

### ISSUE THREAD

**Issue by dylankohlstadt** [phw198/OutlookGoogleCalendarSync#448] opened 2018-01-31 09:57 UTC

**Comment by phw198** [comment] 2018-01-31 22:04
Duplicate of #159

**Closed as completed by phw198** 2018-01-31 22:04 UTC

**Comment by dylankohlstadt** [comment] 2018-02-01 08:30
Hi there

Nope, not a duplicate. I don’t use iCal, I use Outlook Calendar on a MAC.

Please help.
Ta
dk

**Comment by phw198** [comment] 2018-02-01 12:31
Yes, a duplicate. I guess you didn't read the whole ticket. StevenBoatman had responded explaining how to get iCal to sync with a Google calendar and then continued the request for OGCS on MAC - same as you.
