### ISSUE TITLE
ERROR: Unable to connect to the Google calendar. 

### ISSUE THREAD

**Issue by Beverrlly** [phw198/OutlookGoogleCalendarSync#1108] opened 2020-10-26 19:44 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5441066/OGcalsync.log)

**OGCS Version**: **v2.8.4.0**
**Edition**: **Installed** / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Sync can't seem to connect with my Google calendar.  I tried disconnecting and re-connecting the account and it was able to retrieve my calendars one time (enough for me to choose which calendar) but wasn't able to sync.

**Steps to Reproduce the Issue**  
Attempting to sync normally or doing a full sync.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by ForumFerret** [comment] 2020-10-26 20:22
I'm seeing the same behavior on 2.8.0.0

**Comment by billjaq65** [comment] 2020-10-26 20:58
I'm seeing the same behavior on 2.8.3.0.

**Comment by rb-github-user** [comment] 2020-10-26 21:05
Version 2.8.4.0
Similar issue. Error message:

2020-10-26 21:52:05,411 ERROR  6 OutlookGoogleCalendarSync.Console [0] -  Failed to retrieve master for Google recurring event outside of sync range.
2020-10-26 21:52:08,495 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]

2020-10-26 21:52:08,495 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131500;-2146233088
2020-10-26 21:52:08,495 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [0] -     bei Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Google.Apis.Requests.ClientServiceRequest`1.Execute()
   bei OutlookGoogleCalendarSync.GoogleOgcs.Calendar.GetCalendarEntriesInRange(DateTime from, DateTime to)
   bei OutlookGoogleCalendarSync.Recurrence.GetGoogleMasterEvent(AppointmentItem ai)
   bei OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   bei OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass20_0.<Start>b__0(Object o, DoWorkEventArgs args)
2020-10-26 21:52:08,495 ERROR  6 OutlookGoogleCalendarSync.Console [0] -  Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]
2020-10-26 21:52:11,380 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to abandon further syncs.
2020-10-26 21:52:11,386 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Sync aborted after 1 failed attempts!
2020-10-26 21:52:11,490 INFO  1 OutlookGoogleCalendarSync.Console [0] -  Another sync has been scheduled to automatically run in 120 minutes time.
2020-10-26 21:52:11,595 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Montag, 26. Oktober 2020 @ 23:52:11 + Push
2020-10-26 21:52:16,920 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Create the timer for the push synchronisation

**Comment by phw198** [comment] 2020-10-26 23:17
Duplicate of #1107 and [comment here](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1107#issuecomment-716875652).

**Closed as completed by phw198** 2020-10-26 23:17 UTC
Labels: bug, duplicate

**Comment by rb-github-user** [comment] 2020-10-27 09:01
Many thanks! Much appreciated. Will send a donation when it works.

Kind Regards
Rahoul Bhasin



Paul Woolcock <notifications@github.com> schrieb am Di., 27. Okt. 2020,
00:18:
