### ISSUE TITLE
Event update failed. Timezone?

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#1431] opened 2022-04-14 21:05 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.9.4.0
**Edition**:  Portable  
**Sync Direction**: O->G

**Bug Description**  

Event update failed. Object reference not set to an instance of an object.

**Steps to Reproduce the Issue**  

**Any other information**  

![image](https://user-images.githubusercontent.com/6989799/163474867-d09705d0-0f2c-4223-87e3-710b8a9315ad.png)

I updated my timezone in Outlook from UTC-8 to UTC-7 before this occurred if that helps.

```
2022-04-14 14:00:05,136 INFO  10 OutlookGoogleCalendarSync.Console [282] -  Comparing 16 existing Google calendar entries
2022-04-14 14:00:05,228 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 4/18/2022 1:00 PM => "Reports Demo"
2022-04-14 14:00:05,268 DEBUG  10 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [762] -  Retrieving the meeting organiser's timezone ID.
2022-04-14 14:00:05,280 ERROR  10 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-04-14 14:00:05,282 ERROR  10 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-04-14 14:00:05,391 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-14 14:00:05,392 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-04-14 14:00:05,393 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-04-14 14:00:05,394 DEBUG  10 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
2022-04-14 14:00:05,457 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.

```

**Comment by phw198** [comment] 2022-04-24 19:14
No, the timezone change is a red herring - this is a duplicate of #1422

**Closed as completed by phw198** 2022-04-24 19:14 UTC
Labels: bug, duplicate
