### ISSUE TITLE
Installing BCM installs OGCS instead

### ISSUE THREAD

**Issue by shrerr** [phw198/OutlookGoogleCalendarSync#588] opened 2018-09-12 04:58 UTC
I tried removing in any way possible:
Regularly from the control panel
Manually deleting all residues including registry and files.
I have tried this link too https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall
I created a new User on the machine too
I have tried from the safe mode from a rescue disk
and more...
nothing helps the program keeps popping up.
Do you have any special tool that can completely remove it?
eventually, I'll have to format my PC all just because of this software.
Hope to find an answer

**Comment by phw198** [comment] 2018-09-12 17:50
When you say "it keeps popping up" - 
* when does it pop up? On startup/login to Windows? 
* what version of OGCS starts?
* is the "start on startup" option checked in the settings? Does unchecking that stop it from appearing on login?
* are you able to [provide your OGcalsync.log file](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file) after the program starts

**Comment by shrerr** [comment] 2018-09-14 04:40
Hello and thank you for your replay
* It pops up when I try to install or repair Bussines contact manager from an executable file called: BCM2010-BCMSetup-x64-he-IL.exe or BCM2010-ServerWizard-x86-he-IL.exe file. 
when it pops up It also prevents the installation progress of these programs. 
*The version is 2.7.0.0 
*no it doesn't start on startup.
* there are two files the link is:  https://gist.github.com/shrerr/5fa9c44282aa8a6af07ec68ad67e5995

**Comment by phw198** [comment] 2018-09-14 10:04
Wow, really strange installing a different product is triggering opening of OGCS 😕 

Could you:
* [upgrade to 2.7.6](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.7.6-alpha/Setup.exe)
* Run OGCS
* Close OGCS
* Go to Control Panel and uninstall OGCS
* Do either of these directories still exist:
   * C:\Users\sharm\AppData\Local\OutlookGoogleCalendarSync\app-2.7.0-beta\
   * C:\Users\sharm\AppData\Local\OutlookGoogleCalendarSync\app-2.7.6-alpha\

Is the problem resolved? If not, which version of OGCS is now starting when you install Business Contact Manager?

**Comment by phw198** [comment] 2018-09-22 21:36
I didn't actually say to delete anything. But assuming you have the following under `C:\Users\sharm\AppData\Local\OutlookGoogleCalendarSync`:
* directory: app-2.7.0-beta
* directory: packages
* file: OutlookGoogleCalendarSync.exe
* file: app.ico
* file: Update.exe

1. Open a CMD window
1. `cd C:\Users\sharm\AppData\Local\OutlookGoogleCalendarSync`
1. `update.exe --uninstall 2.7.0-beta`

The files should all disappear and you're left with `Update.exe` and `.dead` - just delete the parent directory:
1. `rm *`
1. `cd ..`
1. `rmdir OutlookGoogleCalendarSync`

**Comment by phw198** [comment] 2018-10-07 22:48
Are you saying that under the OGCS `About` tab the `Running From` path is the same as the one you have deleted?!  

It's quite simply not possible for a program, OGCS or other, to run from a location that has been deleted...

**Comment by aawinther** [comment] 2018-11-11 21:06
I've got excatly the same problem. Uninstall everything + manual, deleting cache files cleaning with superantispyware,, restart. and when trying to install BCM for outlook, ogcs opens instead

**Comment by aawinther** [comment] 2018-11-15 08:10
Thank you very much! problem solved!

**Comment by aawinther** [comment] 2018-11-15 08:11
Hi Paul,

 

Thanks alot!!!

 

I’ve fixed the problem, hardly remember how I did it J

 

Something like forcing uninstallation via the ”hard way” through a function in Superantispyware.

Manual removal.

Finally going back to recovering from an earlier point.

Maybe some of above as “admin”

 

All programs is ok now.

 

I have earlier used your program on my old laptop, and I enjoyed it very much, great, useful, easy.

 

Sorry but I dare not reinstall, going through this nightmare again J

 

Thanx again for your assistance, and the pleasure I had using it over the last couple of years.

Med venlig hilsen/Best Regards

 

Aage Winther  

 <http://www.foodpackaging.dk/> cid:image001.png@01D46E9C.E1721290 

 

Food Packaging                                          

Aage Winther

Teglholmsgade 20

2450 København SV

www.foodpackaging.dk <http://www.foodpackaging.dk/> 

 

Tlf. +45 48 48 48 06

Mob. +45 21 77 80 46

 

 

 

Have a GREAT day.

 

Best Regards

Aage

 

 

 

 

Fra: Paul Woolcock [mailto:notifications@github.com] 
Sendt: 15. november 2018 01:24
Til: phw198/OutlookGoogleCalendarSync
Cc: aawinther; Mention
Emne: Re: [phw198/OutlookGoogleCalendarSync] Can not remove or uninstall or get rid of Outlook Google Calendar Sync (#588)

 

Ahhh, so the problem is with BCM - the installer is absolute rubbish and calls the installer for OGCS instead.

https://www.slipstick.com/outlook-bcm/bcm-installer-tries-to-install-a-different-program/

**Closed as completed** 2018-11-24 16:25 UTC

**Comment by aawinther** [comment] 2018-11-25 06:37
Perfect! Everything is ok! Great – Thank you

 

Fra: Paul Woolcock [mailto:notifications@github.com] 
Sendt: 24. november 2018 17:25
Til: phw198/OutlookGoogleCalendarSync
Cc: aawinther; Mention
Emne: Re: [phw198/OutlookGoogleCalendarSync] Installing BCM installs OGCS instead (#588)

 

@aawinther <https://github.com/aawinther>  I think you misunderstand the content in the link I posted. There is no need for anti-spywares or nightmares - the problem is that the BCM install extracts its files to a folder, but then fails to run the Setup.exe in the extracted folder! Instead, if there is a Setup.exe in the same folder as the downloaded BCM file, it will run that - which could likely be OGCS 🙄

So it's as simple as:

1.	Uninstall OGCS in Add remove programs
2.	Download BCM to eg your Downloads folder
3.	Make sure there is no Setup.exe file (OGCS or otherwise) in the Downloads folder
4.	Install BCM.
