### ISSUE TITLE
Wrong time zone added to google events

### ISSUE THREAD

**Issue by Tom2527** [phw198/OutlookGoogleCalendarSync#848] opened 2019-09-19 15:52 UTC
**OGCS Version**: v2.8.0
**Installed or Portable**:  Portable

**Bug Description**  
The events added from Outlook to Google have the wrong time zone. Sort off. What happens is all my devices are on GMT+2. But the Google Events get “GMT+2 Central European Time: Berlin” while I’m at “GMT+2 Central European Time: Brussels”. As they are essentially the same time zone, maybe OGCS doesn’t differentiate between them? Because my Outlook machine clearly has Brussels as the time zone. 

The problem is that I add my Google Calendar to a macOS Calendar and there the difference does matter as they are essentially treated as different time zones. So all my events have the start hour and the GMT+2 start hour (which is the same) listed, which is very annoying. 

**Steps to Reproduce the Issue**  
1. Standard usage of OGCS and syncing from outlook to google 

**Any other information**  
Any additional information that may help troubleshoot the issue. 
:paperclip: Attach your `OGcalsync.log` file.

**Comment by BrandonGriffis** [comment] 2019-09-19 21:55
I think this might be a duplicate of my bug:
https://github.com/phw198/OutlookGoogleCalendarSync/issues/843

Can you check your OGcalsync.log and see if there's anything mentioning the timezone? Specifically a line about "Picking the first offset match regardless of country."

You can find your OGcalsync.log by opening the app and going to:
Settings > Application Behavior > Open Log

If so, can you comment on my issue with your specifics as well? I'm guessing this will get marked as a duplicate of it once Paul is available to look through them, so having more contributors on mine will help focus the issue.

**Comment by phw198** [comment] 2019-12-10 00:03
Yep, almost certainly a duplicate of #843, which now has a proposed fix posted for testing.

**Closed as completed** 2020-01-07 21:49 UTC
Labels: bug, duplicate
