### ISSUE TITLE
Add ability to suppress all deletion confirmations

### ISSUE THREAD

**Issue by ryanwkirby** [phw198/OutlookGoogleCalendarSync#608] opened 2018-10-02 20:42 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed**: Installed

**Problem Description**  
There is no way to suppress ALL deletion confirmations. Un-toggling the "Disable deletions" checkbox only suppresses the individual event deletion confirmations but there is still one popup each time a sync will delete some events.

**Steps to Reproduce the Issue**  
1. Configure ogcs with defaults
2. Set the direction to Outlook -> Google
3. Ensure the "Merge with existing entries" setting is unchecked
4. Ensure the "Disable deletions" setting is unchecked
5. Ensure the "Confirm deletions" setting is unchecked
6. Manually add an event to the Google calendar
7. Start sync
8. You will encounter a popup confirming the deletion

**Any other information**

**Comment by phw198** [comment] 2018-10-03 02:57
I think you should find the popup is asking for confirmation that _all_ items in Google are going to be deleted. This is a safety measure and not going to be removed. Once OGCS is syncing normally this popup should not keep recurring. 

If it does, something else is wrong - but then that's likely fixed by upgrading to the latest alpha release.

**Comment by phw198** [comment] 2018-10-03 03:09
:link: Likely duplicate of #554

**Comment by ryanwkirby** [comment] 2018-10-09 00:57
Yes - this is indeed the popup I was referring to. Perhaps I can provide a bit more context about what I'm trying to accomplish.

I (and many others) must run OGCS on a laptop with Outlook installed. When the laptop is powered down, the calendar stops syncing. To resolve this, I'm syncing new calendar events as they appear when my laptop is off by using a small tool provided by Microsoft (https://goo.gl/oAGqj4). This at least gets me basic calendar info like event title, date, etc, but is missing major metadata like attendees, etc.

I was hoping to use your tool to essentially overwrite / (or wipe-out entirely) all these events created by microsoft-flow each time ogcs runs, replacing them with events that have all the great info that ogcs pulls over. I know it's really more designed to be used with its own calendar, but either a new "Overwrite existing entries" checkbox, or a "never show this warning again" for the "all items in Google are going to be deleted" would get me 100% of the way there, and I'd be more than happy to support the project if this is implemented.

Hopefully, that explains it, and I don't want to sound unappreciative - the tool is awesome and thanks for all the time you've put into it.

**Comment by phw198** [comment] 2018-10-09 06:56
Ah OK, that makes a little more sense. Though the Microsoft documentation says:

> To fill some gap between Outlook protocol and Google Calendar protocol, the flow have to remove all updated events from Google Calendar and recreate them again.

So every night, the flow deletes your calendar contents and then every day OGCS does too?! Not ideal 🙂

Could you simply create a "flow" calendar in Google so Flow and OGCS each maintain their own appointments and don't fight? In the morning you can check that new calendar to see if anything has been added overnight before OGCS has run on the laptop?

**Closed as completed** 2019-05-19 18:20 UTC
