### ISSUE TITLE
New setup will not open

### ISSUE THREAD

**Issue by kennym8** [phw198/OutlookGoogleCalendarSync#747] opened 2019-06-03 19:52 UTC
I have new pc with Windows 10. I downloaded setup.exe, double-clicked it, apparently it was installed as it shows in list of apps, but nothing happens.

**Comment by ThePunish3r** [comment] 2019-06-03 21:21
I appear to be having the same issue, Windows 10 LTSB.  Installer ran and shows the application installed in program files but will not start.  Trying the portable version I get this error in the application log;

Faulting application name: OutlookGoogleCalendarSync.exe, version: 2.8.0.0, time stamp: 0x5cf2f1fb
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2848, time stamp: 0x5c7f6171
Exception code: 0xe0434352
Fault offset: 0x000db152
Faulting process id: 0x4e0
Faulting application start time: 0x01d51a51b24e8a4d
Faulting application path: C:\Users\BLAHBLAHBLAH\AppData\Local\OutlookGoogleCalendarSync\app-2.8.0-beta\OutlookGoogleCalendarSync.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2379f2ee-32ff-40c1-b322-ee20bc359799
Faulting package full name: 
Faulting package-relative application ID:

**Comment by CloudyMcFox** [comment] 2019-06-03 22:56
Same. Under a debugger it says FileNotFound Exception looking for "settings.xml"

**Comment by phw198** [comment] 2019-06-04 07:09
Thanks for reporting this guys :+1: 
However, it's a duplicate of #744, so please try the hotfix as posted there.

**Closed as completed** 2019-06-04 07:09 UTC
Labels: duplicate
