### ISSUE TITLE
Auto-update from 2.8.3-alpha to 2.8.4.0 failed

### ISSUE THREAD

**Issue by maVenmills** [phw198/OutlookGoogleCalendarSync#1039] opened 2020-07-08 21:39 UTC
**OGCS Version**: v 2.8.3-alpha
**Installed or Portable**: Installed

**Problem Description**  
Auto-update prompt to 2.8.4.0 fails.

**Steps to Reproduce the Issue**  
1. OGCS configured to launch on startup.
2. OGCS finds update and asks if I want to commence update.
3. Click Yes
4. Error advising unable to update, request to manual update.

**Any other information**  
Logs advise following
```
2020-07-09 07:33:49,757 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Currently installed version: 2.8.3-alpha
2020-07-09 07:33:49,772 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Found 1 newer releases available.
2020-07-09 07:33:49,773 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Found a new alpha version: 2.8.4.0
2020-07-09 07:33:53,250 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Release notes retrieved.
2020-07-09 07:33:53,297 INFO  24 OutlookGoogleCalendarSync.Forms.UpdateInfo [0] -  Showing new release information.
2020-07-09 07:34:07,967 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Download started...
2020-07-09 07:34:10,303 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Download complete.
2020-07-09 07:34:10,304 DEBUG  19 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=0e78a9f4292a7ad39bee2c28303377c1&ec=squirrel&ea=download&el=from%3D2.8.3.0%3Bto%3D2.8.4.0%3Bsuccessful
2020-07-09 07:34:10,309 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Applying the updated release...
2020-07-09 07:34:10,380 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  System.TypeLoadException: Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.23.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
2020-07-09 07:34:10,389 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131522;-2146233054
2020-07-09 07:34:10,395 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -     at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
2020-07-09 07:34:10,398 DEBUG  19 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=0e78a9f4292a7ad39bee2c28303377c1&ec=squirrel&ea=download&el=%3Bfailed
2020-07-09 07:34:10,401 ERROR  19 OutlookGoogleCalendarSync.Updater [0] -  Failed upgrading OGCS. Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.23.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
```

Log file attached:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4893383/OGcalsync.log)

**Comment by phw198** [comment] 2020-07-10 07:16
Thanks, but this is a duplicate of #926 and should be fixed in 2.8.4 (i.e. OK for the _next_ upgrade).

**Closed as completed** 2020-07-10 07:17 UTC
Labels: duplicate
