### ISSUE TITLE
Still looping on "Google authorisation token needs updating"

### ISSUE THREAD

**Issue by tcharp38** [phw198/OutlookGoogleCalendarSync#427] opened 2018-01-08 10:48 UTC
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
While it was working before OGCS no longer works since some weeks and loops on "Google authorisation token needs updating". I' ve redone the Google authentication process several times but no profress. I could not understand what made OGCS broken but might be due to proxy server changes.
Need help to understand.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
Here is latest log
```
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  C:\Users\charpent\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  OUTLOOK SETTINGS:-
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Service: DefaultMailbox
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Mailbox/FolderStore Name: 
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Default Calendar
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Category Filter: Exclude
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Categories: Perso
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Filter String: g
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  GOOGLE SETTINGS:-
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: 
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Personal API Keys: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Identifier: 
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Secret: 
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit in effect: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit last reached: 01/01/2000 00:00:00
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Assigned API key: 653617509806-2nq341ol8ejgqhh2ku4j45m7q2bgdimv.apps.googleusercontent.com
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  SYNC OPTIONS:-
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   Main
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncDirection: Outlook ↔ Google
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInThePast: 1
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInTheFuture:120
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncInterval: 0
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncIntervalUnit: Hours
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Push Changes: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddDescription: True; OnlyToGoogle: True
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddReminders: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseGoogleDefaultReminder: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      ReminderDND: False (22:00-06:00)
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddAttendees: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MergeItems: True
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DisableDelete: True
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ConfirmOnDelete: True
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesPrivate: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Obfuscate Words: False
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  PROXY:-
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Type: IE
2018-01-08 11:31:02,410 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  APPLICATION BEHAVIOUR:-
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleTooltipWhenSyncing: True
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartOnStartup: True; DelayedStartup: 30
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    HideSplashScreen: N/A
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartInTray: False
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseToTray: True
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseNotClose: True
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleWhenMinimising: True
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Portable: False
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    CreateCSVFiles: False
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    VerboseOutput: False
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Logging Level: DEBUG
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ABOUT:-
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Alpha Releases: False
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Subscribed: 01-janv.-2000
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Timezone Database: 2017c
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ENVIRONMENT:-
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Current Locale: fr-FR
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Date Format: dd/MM/yyyy
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Time Format: HH:mm
2018-01-08 11:31:02,426 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Completed Syncs: 0
2018-01-08 11:39:56,710 DEBUG  1 OutlookGoogleCalendarSync.GoogleCalendar [0] -  Authenticating with Google calendar service...
2018-01-08 11:39:56,710 INFO  1 OutlookGoogleCalendarSync.GoogleCalendar [0] -  No refresh token available - need user authorisation.
2018-01-08 11:40:07,747 DEBUG  1 OutlookGoogleCalendarSync.GoogleCalendar [0] -  User has provided authentication code.
2018-01-08 11:40:08,423 WARN  1 DotNetOpenAuth.Messaging [0] -  Multiple message types seemed to fit the incoming data: {AccessTokenSuccessResponse (2.0),
UnauthorizedResponse (2.0),
}
2018-01-08 11:40:08,423 INFO  1 OutlookGoogleCalendarSync.GoogleCalendar [0] -  Refresh and Access token successfully retrieved.
2018-01-08 11:40:11,482 INFO  1 OutlookGoogleCalendarSync.GoogleCalendar [0] -  Google API keys and refresh token are being updated.
2018-01-08 11:44:57,741 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'AssignedClientIdentifier' updated to ''
2018-01-08 11:44:57,741 DEBUG  1 OutlookGoogleCalendarSync.ApiKeyring [0] -  Getting keyring.
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKey [0] -  OGCS Default = ACTIVE
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKey [0] -  OGCS PW 001 = DISABLED
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKey [0] -  OGCS KW 001 = DISABLED
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKeyring [0] -  There are 3 keys.
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKeyring [0] -  1 keys are active.
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.ApiKeyring [0] -  Picking a Standard key.
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'AssignedClientIdentifier' updated to '653617509806-2nq341ol8ejgqhh2ku4j45m7q2bgdimv.apps.googleusercontent.com'
2018-01-08 11:44:58,771 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'AssignedClientSecret' updated to 'tAi-gZLWtasS58i8CcCwVwsq'
2018-01-08 11:44:58,787 INFO  1 OutlookGoogleCalendarSync.MainForm [0] -  Your Google authorisation token needs updating.
The process to reauthorise access to your Google account will now begin...
```

**Comment by phw198** [comment] 2018-01-08 12:08
Please upgrade to latest alpha by [downloading the latest setup.exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe).

**Comment by phw198** [comment] 2018-01-22 23:32
If the issue still remains on the latest alpha, it's likely a duplicate of #439 which is being worked on.

**Closed as completed by phw198** 2018-01-22 23:32 UTC

**Comment by tcharp38** [comment] 2018-01-23 13:33
Hi. Sorry for late reply. I did not see your answer.
I've just tried your proposed setup.exe. Unfortunately it is killed by my company antivirus SW (Symantec Endpoint protection) since it detects a WS.Malware type in it. No idea why and I can't disable it. So I'm stuck.
I use this opportunity to tell you how great is this SW (at least was) to me. So many thanks. Hope I could reuse it soon. Maybe the next official package will pass this antivirus check phase.

**Comment by phw198** [comment] 2018-01-23 14:51
OK, hopefully the next beta v2.7 should be out very soon and you can upgrade.

**Comment by tcharp38** [comment] 2018-01-30 14:36
Hi Paul.
2.7 solved my issue. It passed antivirus SW and sync is back.
Thanks for this powerful tool. I just sent a small donation.

By the way, Im sending "outlook specific (perso) category to google". Is there a way to have the opposite and get Google to Outlook as specific category too (perso) ?

Cheers
Fabrice
