### ISSUE TITLE
 Authenticating with Google Preparing to authenticate with Google. Handshake successful.   Unable to get the list of Google calendars. The following error occurred:  Request had insufficient authentication scopes. [403=Forbidden]

### ISSUE THREAD

**Issue by cnagda** [phw198/OutlookGoogleCalendarSync#1955] opened 2024-08-28 14:36 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0.0
**Edition**: Installed / Portable  
**Sync Direction**: O->G

**Bug Description**  
Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.
Unable to get the list of Google calendars. The following error occurred:
Request had insufficient authentication scopes. [403=Forbidden]

**Steps to Reproduce the Issue**  
1. Go to Settings
2. Click on Retrieve Calendars

**Any other information**  
* Tried reinstalling, removing and re adding Google account
* This is a new issue, hasn't happened before
[OGcalsync.log](https://github.com/user-attachments/files/16784951/OGcalsync.log)

:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment] 2024-08-29 08:34
Duplicate of #1937

**Closed as not planned by phw198** 2024-08-29 08:34 UTC
Labels: bug
