### ISSUE TITLE
Automatic filtering of events to sync

### ISSUE THREAD

**Issue by Wibblyw** [phw198/OutlookGoogleCalendarSync#1064] opened 2020-08-18 14:05 UTC
**Is your feature request related to a problem? Please describe.**
Cannot avoid syncing all Outlook items to Google, even those I consider 'pollute' my Google calendar

**Describe the solution you'd like**
Perhaps based on the obfuscation feature, use text matching in events to _automatically_ block their syncing, like can be done for certain categories.

**Describe alternatives you've considered**
I can apply categories to my Outlook events and prevent syncing that way, but it means I have to manually apply a category to each and every event I don't (or do) want synced.

**Comment by CennoxX** [comment] 2022-06-21 09:31
Duplicate of #334

**Closed as completed** 2022-07-24 15:16 UTC
Labels: duplicate, enhancement
