### ISSUE TITLE
Multiple Sync Failed

### ISSUE THREAD

**Issue by CStan77** [phw198/OutlookGoogleCalendarSync#1100] opened 2020-10-15 06:14 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
Hello,
every day I have multiple 'Sync Failed' windows

**Steps to Reproduce the Issue**  
1. Clic 'Start Sync' when I closed all the windows 'Sync Failed'

**Any other information**  
In LOG multiple  : 
> Message[Quota exceeded for quota group 'default' and **limit 'Queries per day'** of service 'calendar-json.googleapis.com']
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5382772/OGcalsync.log)
![error](https://user-images.githubusercontent.com/72907176/96084121-cd8bd300-0ebe-11eb-880f-6967f3ce8f80.png)
![sync_option](https://user-images.githubusercontent.com/72907176/96084135-d1b7f080-0ebe-11eb-8082-9d8652d96612.PNG)

**Comment by eknox76** [comment] 2020-10-15 17:39
I am having the same problem.

**Comment by phw198** [comment] 2020-10-15 18:58
Duplicate of #1053

**Closed as completed** 2020-10-15 18:58 UTC
Labels: bug, duplicate
