### ISSUE TITLE
_ExchangeUser.get_PrimarySmtpAddress() - item not found

### ISSUE THREAD

**Issue by IanNettleton** [phw198/OutlookGoogleCalendarSync#722] opened 2019-05-03 07:16 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0
**Installed or Portable**: Installed

**Problem Description**  
Not syncing a Recurring Series at all - it recognises the invite but:

"4 Google calendar entries to be created.
Creating ........ Google calendar entries
2019/06/16 09:30 "Gathering Knocker's"
Event creation failed.
The item could not be found.
Operation aborted after 1 failed attempts!_ "

**Steps to Reproduce the Issue**  
1. \<Update>done
1. MS Outlook (MS Office 365 Business) recurring series invites received - does not sync

**Comment by phw198** [comment] 2019-05-04 17:06
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by IanNettleton** [comment] 2019-05-07 14:12
anyone of these should do

**Comment by phw198** [comment] 2019-05-07 14:16
:paperclips: Files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by IanNettleton** [comment] 2019-05-07 14:50
got it

**Comment by IanNettleton** [comment] 2019-05-07 14:53
Error - " we don't support that file type"

**Comment by phw198** [comment] 2019-05-07 15:16
What file type are you trying to upload? Despite the link in your original post and my original reply says to "change the filename extension from .log to .txt.", it appears [GitHub now supports upload of `.log` files](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests) anyway...

**Comment by IanNettleton** [comment] 2019-05-07 17:49
Error from trying to upload the log file?

**Comment by IanNettleton** [comment] 2019-05-09 08:07
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3160960/OGcalsync.txt)
[OGcalsync 2.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3160961/OGcalsync.2.txt)

**Comment by IanNettleton** [comment] 2019-05-09 08:08
hopefully now that I am listening to instructions, this will work. However, not being a techie - instruction needed to be specific - you need to remove the date after txt  or the filename extension otherwise it does not load

**Comment by phw198** [comment] 2019-05-11 09:40
Thanks for the pointer - I've now updated the instructions to cover previous day's log files with the file naming of `OGcalsync.log.yyyy-mm-dd` :+1: 

OK, it appears you have a couple of issues - the first being:
```
2019-05-07 16:10:58,473 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 2019/06/16 09:30 => "Gathering Knocker's"
2019-05-07 16:10:58,474 DEBUG  17 OutlookGoogleCalendarSync.Console [0] -  2019/06/16 09:30  "Gathering Knocker's"
2019-05-07 16:10:58,902 ERROR  17 OutlookGoogleCalendarSync.Console [0] -  Event creation failed.
2019-05-07 16:10:58,903 ERROR  17 OutlookGoogleCalendarSync.Console [0] -  The item could not be found.
2019-05-07 16:10:58,990 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The item could not be found.
2019-05-07 16:10:58,990 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0xB7940201;-1215036927
2019-05-07 16:10:58,991 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._ExchangeUser.get_PrimarySmtpAddress()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.GetRecipientEmail(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateAttendee(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments)
```
The other is a duplicate of #672.

**Comment by phw198** [comment] 2019-05-11 10:18
:package: Please could you check if this is resolved with [hotfix v2.7.8.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3168906/v2.7.8.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If it doesn't work, please change your logging level to `FINE`, reproduce the issue and upload your log file again.

Thanks!

**Comment by IanNettleton** [comment] 2019-05-13 08:54
Thanks Paul, haivng problems extracting the file. Any suggestions?

**Comment by phw198** [comment] 2019-05-14 15:44
Depends on the problems your getting, but the instructions previously linked to should step you through the process.

**Comment by IanNettleton** [comment] 2019-05-14 20:14
Hi I cannot extract the file - any suggestions

**Comment by IanNettleton** [comment] 2019-05-14 20:22
![image](https://user-images.githubusercontent.com/50229229/57729537-b415a480-7696-11e9-9f6f-7b9c25fcd2d8.png)

**Comment by phw198** [comment] 2019-05-14 21:56
I'm not really sure what I'm looking at there. Are you saying you have extracted the hotfix successfully now and the same issue is still occurring? 

If so, I said "If it doesn't work, please change your logging level to FINE, reproduce the issue and upload your log file again."...

**Comment by IanNettleton** [comment] 2019-05-20 12:59
Hi I have set the logging level to fine now. Please note though  my wife upgraded the version to 2.7.9.0 :( 
before I could send the new logs. Herewith the new log files
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3198004/OGcalsync.log)

**Comment by phw198** [comment] 2019-05-20 23:23
OK, but yes, the point was to get the logging under version 2.7.8.8 as the logging I need is not in 2.7.9.0

:package: I've merged v2.7.8.8 into v2.7.9.0 and produced [hotfix v2.7.9.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3200108/v2.7.9.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes and upload you logfile again.

**Comment by IanNettleton** [comment] 2019-05-27 05:45
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3222006/OGcalsync.log)

Thanks Paul - unless I've done somehting wrong, I seem to be getting the same errors. I am more concerned about the errors from an Outlook series of meetings. The sync seems to produce errors if one of the meetings in the series gets altered. Cheers

**Comment by phw198** [comment] 2019-05-28 14:29
:package: Please could you try again with [hotfix v2.7.9.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3228109/v2.7.9.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and provide your log file again.

The error you are getting with `UIF speak to Phumlani again` is due to a bug in v2.7.8 when items were copy-and-pasted or click-and-dragged in Outlook. This item will need deleting and recreating before it can be synced to Google.

**Comment by phw198** [comment] 2019-06-09 00:54
Any update on v2.7.9.5?

**Comment by IanNettleton** [comment] 2019-06-26 06:48
Sorry Paul.
I am now on V2.8.0.0 and the syncing seems to be working. However, I think
there is an API issue now "google daily free calendar quota is exhausted".
I assume this is on  your project side?
Tx for your assistance
[image: image.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by phw198** [comment] 2020-02-15 21:14
Closing this off to be tracked afresh under #951

**Closed as completed by phw198** 2020-02-15 21:14 UTC
Labels: bug, waiting fix confirmation
