### ISSUE TITLE
Text in UI is not aligned 

### ISSUE THREAD

**Issue by Yuvbm** [phw198/OutlookGoogleCalendarSync#1437] opened 2022-04-17 10:31 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8501377/OGcalsync.log)

**Steps to Reproduce the Issue**  
The text in the UI is not aligned properly 
See screen shots
![Screenshot 2022-04-17 133048](https://user-images.githubusercontent.com/103881903/163710696-839b7c1a-05af-46c5-a908-dc6e5a0e18e4.jpg)
![Screenshot 2022-04-17 133100](https://user-images.githubusercontent.com/103881903/163710701-f62357ee-1b2a-4f72-85bd-5d9983a41591.jpg)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment] 2022-04-24 19:53
This is a duplicate of #1329 really - could you provide your Windows display settings as per https://github.com/phw198/OutlookGoogleCalendarSync/issues/1329#issuecomment-954724830 on that issue?

**Comment by Yuvbm** [comment] 2022-04-25 05:56
Indeed this seems like a duplicate and here is a screen shot of my setting.

![image](https://user-images.githubusercontent.com/103881903/165028783-e7ec772d-0e62-4767-a44f-578e756a2d0c.png)

**Comment by Yuvbm** [comment] 2022-05-25 09:22
I know this issue is a duplicate though am not clear if a fix is in the working or additional info is required.
Thanks !

**Comment by phw198** [comment] 2022-06-05 13:49
The custom scaling factor does't replicate the problem on my system, so I don't know how to fix it without knowing the root cause. Are there any other customisations you have applied to windows? Eg non-default fonts?

**Comment by Yuvbm** [comment] 2022-06-06 11:12
My scale was set to 110% which is under the 'advance scaling settings' and when setting it to 100%, which is one of the choices in the drop down menu, the issue indeed does not show. This leads me to believe it is the non standard scaling being the key driver. In any case, I'm happy to share anything that is relevant from my machine configuration if and when needed.

> The custom scaling factor does't replicate the problem on my system, so I don't know how to fix it without knowing the root cause. Are there any other customisations you have applied to windows? Eg non-default fonts?

**Closed as completed** 2022-07-15 08:44 UTC
Labels: bug, duplicate, dormant
