### ISSUE TITLE
Continuous error: Event creation failed. The item could not be found.

### ISSUE THREAD

**Issue by mgdmg** [phw198/OutlookGoogleCalendarSync#835] opened 2019-09-10 08:05 UTC
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  

A couple of months ago my OGCS started to pop-up notifications saying:

> Event creation failed.
> The item could not be found.

I have updated it to the latest alpha edition and I'm still getting the same error every 2 hours (corresponding to my sync schedule).

I have not found anyone with a similar issue so I have no clue to what could be causing this error.

Thanks in advance!

**OGcalsync.log**  
https://gist.github.com/mgdmg/2e6673b534057da622496c384bda76a6#file-ogcalsync-log-2019-09-09

**Comment by mgdmg** [comment] 2019-09-19 09:50
Anyone experiencing similar trouble?
I would really appreciate some help - any suggestion really.

**Comment by phw198** [comment] 2020-02-15 20:11
Log file excerpt of the error:
```
2019-09-09 23:43:01,186 INFO  3 OutlookGoogleCalendarSync.Console [0] -  Creating 1 Google calendar entries
2019-09-09 23:43:01,439 DEBUG  3 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 31/07/2019 15:00 => "FW: Lighthouse Sessions: Service Design in the Digital Era by Prof. Ivanka Visnjic from ESADE "
2019-09-09 23:43:01,440 DEBUG  3 OutlookGoogleCalendarSync.Console [0] -  31/07/2019 15:00  "FW: Lighthouse Sessions: Service Design in the Digital Era by Prof. Ivanka Visnjic from ESADE "
2019-09-09 23:43:01,530 DEBUG  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Retrieving the meeting organiser's timezone ID.
2019-09-09 23:43:01,780 ERROR  3 OutlookGoogleCalendarSync.Console [0] -  Event creation failed.
2019-09-09 23:43:01,780 ERROR  3 OutlookGoogleCalendarSync.Console [0] -  The item could not be found.
2019-09-09 23:43:01,835 ERROR  3 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The item could not be found.
2019-09-09 23:43:01,835 ERROR  3 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0xA9340201;-1456209407
2019-09-09 23:43:01,835 ERROR  3 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._ExchangeUser.get_PrimarySmtpAddress()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.GetRecipientEmail(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateAttendee(Recipient recipient, Boolean isOrganiser)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments)
```

The logging level needs increasing to `FINE`, the error reproducing the logfile uploading again, please.

**Comment by phw198** [comment] 2020-02-15 20:36
I believe this is a duplicate of #951, so going to investigate this over there.

**Closed as completed by phw198** 2020-02-15 20:36 UTC
Labels: duplicate, more info needed
