### ISSUE TITLE
Unable to sync with outlook

### ISSUE THREAD

**Issue by MHerron435** [phw198/OutlookGoogleCalendarSync#988] opened 2020-05-09 17:44 UTC
**Are you already using OGCS?**
Provide the version number.2.8.0.0

**Describe the question you have**
A clear and concise description of your question and what you would like clarifying.

I am getting the following message each time I try to sync.  It happens for every event. How can I fix this?

New event failed to save.
You need to have writer access to this calendar. [403=Forbidden]

**Comment by phw198** [comment] 2020-05-10 12:13
Duplicate of #826, #918.

**Closed as completed by phw198** 2020-05-10 12:13 UTC
Labels: question
