### ISSUE TITLE
switching between profile give unhandled exception - see attachment

### ISSUE THREAD

**Issue by ahmedalagamy** [phw198/OutlookGoogleCalendarSync#1515] opened 2022-07-28 06:37 UTC
**OGCS Version**: v2.9.5.0 alpha
**Installed or Portable**: Portable

**Problem Description**  
switching between profiles give unhandled exception error

**Steps to Reproduce the Issue**  
1. Start with 'a' profile
2. do full sync
3. switch to the other profile
4. error will occur

**Any other information**  
see attachments 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/92061
![error](https://user-images.githubusercontent.com/70011717/181437355-aaf0deb6-117d-431e-be80-1532d2d471f3.PNG)
11/OGcalsync.log)

**Comment by madsskoett** [comment] 2022-07-31 18:15
second that.
Removing line 480 in MainForm.cs `ddPrivacy.Items.Clear();` does the trick

**Comment by phw198** [comment] 2022-08-16 23:49
Duplicate of #1480 which has hotfix posted.

**Closed as completed by phw198** 2022-08-16 23:49 UTC
Labels: duplicate
