### ISSUE TITLE
Recurring items in Outlook changing to Private

### ISSUE THREAD

**Issue by BiornR** [phw198/OutlookGoogleCalendarSync#347] opened 2017-09-26 11:05 UTC
When setting "Set entries as private in Google Calendar" any recurring appointment in Outlook is first synced over to Google. The item then gets synced back to Outlook and is marked as "Private".

Changing the "Private" flag back in Outlook and syncing again does not solve the problem - the flag gets set back to "Private" again.

**Comment by HerrRiebmann** [comment] 2017-09-28 11:41
+1 on that!
From my point of view, the feature is implemented wrong. Every **new** entry should be marked as private (_Due to setup_). All **existing** entries should keep their privacy setting.

It happens often, that I change private appointments in my office calender. They must be kept private! (_Works by design_)
Otherwise, public entries from my work, must stay public, even when I change them from my private account. That currently does not work.

**Comment by phw198** [comment] 2017-09-30 15:49
So certainly there was a bug for two-way sync using "Set entries as private" feature. 

@HerrRiebmann I'm not sure what you mean by only new entries should be marked as private. _Anything_ that is synced by OGCS to the target calendar should be private, that's the point. By default OGCS will only sync changes though.

:package: Anyway, this should now be resolved with ~~[hotfix v2.6.2.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1346532/v2.6.2.2.zip)~~ [hotfix v2.6.2.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1347292/v2.6.2.5.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes.

**Comment by phw198** [comment] 2017-10-01 09:59
@fors6630 Not sure if you 2-way sync, but tagging you FYI.

**Comment by HerrRiebmann** [comment] 2017-10-02 13:13
With **new**, I meant all entries created in Google, should appear as private in O365.
But modified entries shouldn´t. They have to keep its privacy setting. For example:
Entry is created in O365 as public. After enhancing some infos in google, it must stay public.
Hope that is clear enough.

Btw. the standalone hotfix-EXE did not work for me. I had to replace all files from 2.6.2 alpha.

**Comment by phw198** [comment] 2017-10-02 16:15
@HerrRiebmann So I think you're saying:
1. Set OGCS to 2-way sync, with synced entries in Outlook being marked private.
1. Create an Outlook item as public
1. Sync it to Google.
1. Edit it in Google (keeping it still public).
1. Sync it back to Outlook - Outlook needs to remain Public.

As it's currently designed, that's not going to work - everything synced to the target Outlook calendar will be marked private. You would have 2 options:
1. Don't edit items in Google
1. After the Outlook item becomes private, reset it to public.

I could look at an additional settings - 
a) For **created** items in target calendar, mark as private
b) For **updated** items in target calendar, mark as private

I think that would cater for your need?

The hotfix isn't standalone...did you read the instructions for applying it?

**Comment by HerrRiebmann** [comment] 2017-10-04 12:45
Yes, option **a)** would make my daily use-case possible. Highly appreciated :)

From my point of view it makes no sense to change the setting for **updated** items. When an entry is created in Outlook, it must keep its privacy state. Event when it gets modified (_from wherever_).
Outlook is the owner and responsible for the privacy option.
Whatever, with you suggested option it would be possible to do so 👍 

Thank you very much for your time and efforts!!!

**Comment by phw198** [comment] 2017-10-14 12:37
:package: OK, this should now work as discussed with [hotfix v2.6.2.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1384642/v2.6.2.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes!

**Closed as completed** 2017-10-22 15:22 UTC
Labels: bug, waiting fix confirmation

**Comment by BiornR** [comment] 2017-10-22 18:02
Thx! Works great now.
