### ISSUE TITLE
Push Outlook changes immediately Not Working

### ISSUE THREAD

**Issue by Rob-EmoryDay** [phw198/OutlookGoogleCalendarSync#496] opened 2018-03-20 13:33 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**:  2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
The "Push Outlook changes immediately" sync is not working. This worked flawlessly for a couple of years, but stopped about two weeks ago. I have to manually sync the calendars. 

**Steps to Reproduce the Issue**  
1. Select the "Push Outlook changes immediately" sync option
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1829488/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1829490/OGcalsync.log)

**Any other information**  
[Gist Log](https://gist.github.com/phw198/f2e9dc0ba1c0264608f7004449029aa9)

**Comment by phw198** [comment] 2018-03-21 22:33
Thanks for reporting this

:package: It should now be resolved with [hotfix v2.7.2.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1835449/v2.7.2.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes!

**Comment by Rob-EmoryDay** [comment] 2018-03-22 12:38
Hi,

After following the instructions see instructions for applying<https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix> the new .exe file wouldn’t open.

Should I uninstall and reinstall?

Thanks,

ROb

**Comment by phw198** [comment] 2018-03-22 14:27
Ah, you'll need to install the latest alpha version first (download directly from website) and then apply the hotfix on top of that.

**Comment by phw198** [comment] 2018-03-28 07:30
@aabarbee Can you confirm you are definitely running the hotfix? Check in the `About` tab it says v2.7.2.1. Note, if you make a change to an Outlook item whilst OGCS is actively syncing, this will not trigger a subsequent sync.

@Rob-EmoryDay Any further feedback?

**Comment by Rob-EmoryDay** [comment] 2018-03-28 10:52
Hi Paul,

I’m not able to install the latest alpha version. Each attempt results in the 2.7.2.0 version remaining. Do I need to delete registry files in addition to uninstalling the program?

Thanks,

Rob

**Comment by aabarbee** [comment] 2018-03-28 16:18
Hi Paul @phw198 yes I was able to confirm I was running the hotfix yesterday when I first downloaded it!

**Comment by phw198** [comment] 2018-03-28 16:45
OK, I've also confirmed there's still a problem. The hotfix seems to make Push syncing detect changes for longer than before, but it still stops working after a certain amount of time. Will need to look in to it further.

@Rob-EmoryDay v2.7.2 _is_ the latest alpha, so you now just need to apply the hotfix (copy the new `.exe` over the top of the v2.7.2 `.exe`).

**Comment by phw198** [comment] 2018-03-30 15:28
So [it would appear](https://social.msdn.microsoft.com/Forums/office/en-US/74f61f85-8db7-408b-97b5-5e50deb42776/loosing-inboxitemsitemadd-event-again?forum=outlookdev) (and [here](https://www.add-in-express.com/creating-addins-blog/2011/10/24/outlook-newmail-solution-options/)) that the `Item.ItemAdd` and `Item.ItemChange` events are completely unreliable! :angry: 

Looks like I'm going to have to rework the Push mechanism almost entirely...!

**Comment by phw198** [comment] 2018-03-30 17:12
:package: Duly reworked - [hotfix v2.7.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1864222/v2.7.2.3.zip) available ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), and again make sure it's applied at least on top of v2.7.2.0.

Let me know how it goes!

**Comment by aabarbee** [comment] 2018-04-03 02:28
Hi @phw198 !  The sync is working for me as far as I can tell.  thank you again!
One last question, it's taking up a lot of my CPU on a new computer right now so I am hoping that you can share instructions for "scheduling" syncing - I am thinking once every 2 hours or every 4 hours?  I believe you mentioned that as a possibility.

**Comment by phw198** [comment] 2018-04-03 15:57
@aabarbee I've been testing today too, and it looks good to me too :+1: 

[Check the user guide](https://phw198.github.io/OutlookGoogleCalendarSync/guide/syncoptions#when) for configuration, but basically set the `Interval` to a non-zero value:
![image](https://user-images.githubusercontent.com/11843015/38260597-ec1d26fe-375f-11e8-86e9-7427b52c846b.png)

**Comment by aabarbee** [comment] 2018-04-03 16:17
Thanks @phw198 , I did try that before asking because I thought it would be there - when I set interval period to 2 hours, the sync is still running continuously.  The moment that a sync ends, another sync begins.  I also tested out the configuration of unchecking "Push Outlook changes immediately" WITH a non-zero interval, and sync is still continuous.  I confirmed I'm running hotfix v2.7.2.3  If you can give guidance on that I will watch for it!  Very happy the sync is happening now

**Comment by phw198** [comment] 2018-04-03 17:00
:spiral_notepad: Could you provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file))?

**Comment by aabarbee** [comment] 2018-04-03 18:16
Hi!  I dont know if it's private or not, so I just emailed it to your ogcs@paulwoolcock.co.uk email

**Comment by phw198** [comment] 2018-04-03 21:11
@aabarbee So your log file starts at 09:07:35 and has 76 Push Sync requests within 1m45s! Given the log shows no sign of starting OGCS, do you leave it running and just standby or hibernate your computer?

I'm also suspicious that you have more than one version of OGCS running, as you have "Start on startup" set and possibly the original `OutlookGoogleCalendarSync.exe` file as well as the `OutlookGoogleCalendarSyncHotfix20180402.exe` which you are also running?

Could you make sure OGCS is entirely shut down - check the Task Manager that there are no processes still there. Then start it up and see if it behaves better....and whether the problems start after resuming from standby?

**Closed as completed** 2018-04-17 19:07 UTC
Labels: bug, high, resolved
