### ISSUE TITLE
Failed to retrieve Google event

### ISSUE THREAD

**Issue by UmbraChimera** [phw198/OutlookGoogleCalendarSync#538] opened 2018-06-11 16:54 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4.0
**Installed or Portable**: Installed

**Problem Description**  
\Constantly getting 'Failed to retrieve Google event' errors when trying to sync calendars. Below are screenshots from the errors and I'm also attaching a log file.
![image](https://user-images.githubusercontent.com/5304649/41245348-d3f04538-6d75-11e8-9af2-dfa403459a6d.png)

![image](https://user-images.githubusercontent.com/5304649/41245340-cc51999e-6d75-11e8-9b13-6d5395ddd953.png)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2090958/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. \Click Start Sync

**Any other information**  
\ Worked just fine yesterday no software or OS updates were performed. Updated from 2.7.0.0 to 2.7.4.0 and issue still persist

**Comment by phw198** [comment] 2018-06-11 21:50
This is a duplicate of issue #510. Please could you apply the hotfix v2.7.3.1 there and set logging level to `FINE`.

From the logfile you uploaded, it looks like it can't find e.g. the following appointments in Google, but they exist in Outlook - any idea why? Can you see them in Google?

`1/26/2018 6:46 AM (R) => "Daily Huddle"`
`5/18/2018 8:40 AM (R) => "Staffing Form"`

**Comment by phw198** [comment] 2018-08-18 10:04
Fix posted on issue #510

**Closed as completed by phw198** 2018-08-18 10:04 UTC
Labels: duplicate
