### ISSUE TITLE
"You've Changed One of the Recurrences

### ISSUE THREAD

**Issue by teendoc** [phw198/OutlookGoogleCalendarSync#1441] opened 2022-04-21 17:59 UTC
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.4.0  
**Edition**: Installed / **Portable**  
**Sync Direction**: G->O / O->G / **O<->G**

**Bug Description**  

When synching outlook to google, I get these error messages that continue after restarting the program and outlook:

_You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again.
If this keeps happening, please restart OGCS._

**Steps to Reproduce the Issue**  
1. Go to...Sync tab
1. Click on...Start Sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  This started with my upgrade to version 2.9.4.0.
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8533635/OGcalsync.log)

**Comment by tnjgb** [comment] 2022-04-23 10:29
2.9.4.3 hotfix does not fix this issue and may not have been intended to.

**Comment by phw198** [comment] 2022-04-24 12:12
@teendoc Thanks, though this is a duplicate of #1432 so I'll close this and track on that ticket.

@tnjgb Correct, hotfix v2.9.4.3 is unrelated to this error.

**Closed as completed by phw198** 2022-04-24 12:12 UTC
Labels: bug, duplicate
