### ISSUE TITLE
Invalid time zone definition error messsage.

### ISSUE THREAD

**Issue by patakyzs** [phw198/OutlookGoogleCalendarSync#1528] opened 2022-08-26 09:36 UTC
**Hi,
I have some issues with the sync of some meeting invite which are coming from different time zone. (specially which are coming from Mukachevo).
Can you pls check and advise?
You can contact with me: pataky.zsolt@gmail.com.

I have attached the log file also.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/9432001/OGcalsync.log)

Thanks,
Zsolt**

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by ej1024** [comment] 2022-08-26 13:54
I am also having this issue.  It happens for me when people who are from Europe send out meeting notices.  It has only happened for about a week for me.

```
Sync version: 2.9.0.0

Sync started at 8/26/2022 8:54:21 AM

Syncing from 8/25/2022 to 10/26/2022

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

25 Outlook calendar entries found.

Scanning Google calendar...
25 Google calendar entries found.

4 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...

Sync cancellation requested.

Repeated cancellation requested - forcefully aborting sync!

Failed to retrieve master for Google recurring event outside of sync range.

Thread was being aborted.

Finding Calendar Entries
Scanning Outlook calendar...

25 Outlook calendar entries found.

Scanning Google calendar...
25 Google calendar entries found.

4 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 25, Google 25
Checking for orphaned Google items
Matching calendar items...


0 Google calendar entries to be deleted.

0 Google calendar entries to be created.

25 calendar entries to be compared.

Comparing 25 existing Google calendar entries
8/9/2022 9:30 AM  "Weekly Project Meeting"


Attribute

Change

Start TimezoneEurope/Kiev → Europe/Kyiv
End TimezoneEurope/Kiev → Europe/Kyiv

2 attributes updated.

Updated event failed to save.
Invalid time zone definition for start time. [400=BadRequest]

Sync aborted after 2 failed attempts!
```

**Comment by phw198** [comment] 2022-08-28 18:49
Duplicate of #1525 which has a hotfix posted.

**Closed as completed by phw198** 2022-08-28 18:49 UTC
Labels: bug, duplicate

**Comment by patakyzs** [comment] 2022-08-28 19:09
Hi Paul,

So what is the solution?
Can you play advise?

Thanks,
Zsolt

Paul Woolcock ***@***.***> ezt írta (időpont: 2022. aug. 28.,
Vas 20:49):

**Comment by phw198** [comment] 2022-08-28 19:11
Apply the hotfix on the issue I linked to.

**Comment by patakyzs** [comment] 2022-08-28 19:41
Thanks a lot. Problem solved.

Paul Woolcock ***@***.***> ezt írta (időpont: 2022. aug. 28.,
V, 21:11):
