### ISSUE TITLE
Outlook->Google directional sync doesn't delete cancelled recurring meeting instances

### ISSUE THREAD

**Issue by jackr1w** [phw198/OutlookGoogleCalendarSync#969] opened 2020-03-24 16:31 UTC
**OGCS Version**: v2.8.3  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
When a recurring series is created in Outlook, and then one item of the series is moved and made an exception, and then it gets cancelled by originator - the cancellation doesn't propagate to Google, because the exception doesn't match the event. I can't attach the sync log due to some sensitive info in it, but I can paste the relevant parts where the problem shows up Here:
```
2020-03-24 18:04:51,780 FINE  6 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-24 18:04:51,781 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  18/09/2018 8:15 (R) => "Whatever weekly sync"
2020-03-24 18:04:51,782 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 93 exceptions that will now be iteratively compared.
2020-03-24 18:04:51,788 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is deleted and outside date range being synced: 17/09/2018
2020-03-24 18:04:51,808 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is deleted and outside date range being synced: 24/09/2018
2020-03-24 18:04:51,876 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is outside date range being synced: 26/09/2018
2020-03-24 18:04:51,894 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is deleted and outside date range being synced: 01/10/2018
2020-03-24 18:04:51,962 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is outside date range being synced: 09/10/2018
2020-03-24 18:04:52,038 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is outside date range being synced: 16/10/2018
2020-03-24 18:04:52,111 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is outside date range being synced: 23/10/2018
2020-03-24 18:04:52,129 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is deleted and outside date range being synced: 29/10/2018
...
2020-03-24 18:04:59,555 FINE  6 OutlookGoogleCalendarSync.Recurrence [0] -  Exception is outside date range being synced: 17/03/2020
2020-03-24 18:04:59,574 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for deleted Outlook exception:-
2020-03-24 18:04:59,575 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 23/03/2020
2020-03-24 18:04:59,576 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  Google exception event is not cached. Retrieving all recurring instances...
2020-03-24 18:04:59,576 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all recurring event instances from Google.
2020-03-24 18:05:00,152 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 1 received.
2020-03-24 18:05:00,457 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 2 received.
2020-03-24 18:05:00,777 DEBUG  6 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 3 received.
2020-03-24 18:05:00,997 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  No matching Google Event recurrence found.
2020-03-24 18:05:00,998 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  The Outlook appointment is deleted, so not a problem.
```
The wrong part is this:
`2020-03-24 18:04:59,575 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 23/03/2020`
The original date is no longer interesting, because the event has already been made an exception and moved to a different date. Thus the comparison is expected to fail, because in Google the event is already on a new date.

**Steps to Reproduce the Issue**  
1. Use Outlook --> Google sync.
2. Use another "Master" Outlook to create events that would be accepted on the "Synced" Outlook that is running sync.
2. Create a recurring series of events in Master Outlook with weekly recurrence. Accept in Synced Outlook. Make sure the series appear on Google.
3. Take one event in the series on Master Outlook and move it to a different date. Accept in Synced Outlook. Make sure the event is updated in Google (sometimes doesn't happen - another bug).
4. Cancel this event in Master Outlook, accept (deletion) in Synced Outlook.
5. Observe the Google event not being deleted.

**Any other information**  
Sorry, couldn't attach the log. Sensitive information.

**Comment by phw198** [comment] 2020-05-05 16:26
Unfortunately I've been through the steps you gave and it hasn't replicated the problem you describe - the moved and then cancelled occurrence is deleted in Google.

> The original date is no longer interesting, because the event has already been made an exception and moved to a different date.  

While I understand why this would seem logical, in fact both Outlook and Google store the original date of any series occurrences that have been moved, so using this for comparison is the only way to track such changes.

Questions for you:
1. Is the recurring meeting an all-day event or not? (Pretty sure it's not all-day)
1. For the occurrence being moved, what date was it being moved from and to?
1. What is your sync date range (number of days in past and future)?
1. What version of Outlook are you using?

**Comment by jackr1w** [comment] 2020-05-05 20:05
Hi Paul,

Hopefully the provided answers below would help in reproduction.

1. Recurring meeting is not an all-day event, it's a regular 1-hour meeting
usually.
2. Moving that isn't replicated is usually moving forward by several days.
Moving the hours within the same day is replicated.
3. Sync is set to: 3 days in the past, 60 days in the future, each 1 hour,
push Outlook changes immediately.
4. It's the latest Outlook 2019 or whatever Office 365 is now calling
itself. Version 2003, build 16.0.12624.20422, monthly channel, 32-bit.
Barely found this in the program...

Thank you for looking into it.
William.

**Comment by phw198** [comment] 2020-06-14 14:04
:package: This [v2.8.3.18.zip build](https://github.com/phw198/OutlookGoogleCalendarSync/files/4776523/v2.8.3.18.zip) now has extra debug logging to try and investigate a bit further what the problem is ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Will need everything between the lines
```
2020-03-24 18:04:51,780 FINE  6 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-24 18:04:51,781 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  18/09/2018 8:15 (R) => "Whatever weekly sync"
2020-03-24 18:04:51,782 DEBUG  6 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 93 exceptions that will now be iteratively compared.
```
and when it has finished processing that appointment - there's going to be **a lot** of lines given this recurring meeting has been running for years!

**Comment by jackr1w** [comment] 2020-06-14 15:49
Thank you Paul.
I'll try to catch one instance of such an occurrence happening and provide
you the information.
However, I've made some experiments locally and played with the settings,
and I think after I've changed one setting - things have been running
smoothly and I didn't notice these occurrences anymore.
The change was extending the sync from 3 days back to 14 days back. Not
sure if that was the culprit, but it seems like this setting affected the
range of the movement keeping things in sync. E.g. if I relocate a meeting
1 week into the future - previously it would not sync correctly, and now it
does.
If I don't notice any such misses happening within the next couple of weeks
- I'll let you know that this case can be considered closed, as the misses
were fairly frequent before.
Thanks,
William.

**Comment by phw198** [comment] 2020-06-14 17:49
OK, that now makes sense and I don't think there is any point in trying the v2.8.3.18. 

This only affects recurring items where the _original date_ of exception item has fallen out of they sync window (too far in the past), the newly scheduled date for it is still in scope but the organiser has then cancelled it.

In this scenario, because the exception is deleted, Outlook only stores the original date - there is no other information available to use! Therefore OGCS sees it as out of scope for sync and doesn't do anything. It's a limitation of Outlook and nothing I can do about it....aside from record it as a [limitation](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations#past-recurring-meeting-instance-rescheduled-then-cancelled-by-organiser).

Extending the sync window further in the past is the only workaround here :+1:

**Comment by jackr1w** [comment] 2020-06-14 18:10
Thank you Paul, now with your explanation it makes sense to me as well. I
think it falls into the pattern I've observed, and now with sync going
enough backwards it has indeed been taken care of, as the occurrences of an
exception to a recurring meeting being dragged into the future over 2 weeks
time are extremely rare, and when the range was -3 days it was very common
to fall out of it.

I'm very glad this was eventually figured out and resolved. The workaround
seems to be working well enough to cover the vast majority of the cases.
Thanks for documenting the limitation, I'm sure it might be of help to
others in the future.

Thanks a lot!
William.

**Closed as completed** 2020-06-14 18:13 UTC
Labels: triage
