### ISSUE TITLE
Can't open app.

### ISSUE THREAD

**Issue by ElenitaG** [phw198/OutlookGoogleCalendarSync#839] opened 2019-09-11 20:55 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
I have just downloaded the app and it synced perfectly.  I wanted to revisit the settings, but I can't open the app.  The app also froze several times when I was setting it up and would not close when pressing the"X" button.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2019-09-11 22:13
Have you checked for any other popups maybe in the background? I'm wondering if Outlook has a security alert that needs accepting?

**Comment by ElenitaG** [comment] 2019-10-11 01:41
I keep getting the following message when 
```
Sync version: 2.8.0.0

Sync started at 10/10/2019 10:10:27 AM

Syncing from 10/10/2018 to 10/10/2020

Outlook ↔ Google

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.

Finding Calendar Entries
Scanning Outlook calendar...

338 Outlook calendar entries found.

Scanning Google calendar...
354 Google calendar entries found.

18 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 338, Google 355

Syncing Outlook → Google
Checking for orphaned items
Matching calendar items...


0 Google calendar entries to be deleted.

0 Google calendar entries to be created.

331 calendar entries to be compared.

Comparing 331 existing Google calendar entries
0 entries updated.

Syncing Outlook ← Google
Checking for orphaned items...
Matching calendar items...


0 Outlook calendar entries to be deleted.

4 Outlook calendar entries to be created.

331 calendar entries to be compared.

Creating 4 Outlook calendar entries
10/4/2019 2:00 PM "Piano lesson"
10/9/2019 10:45 AM "Exercise of"
10/22/2019 10:10 AM "Dr. Mitchell"
12/6/2019 10:30 AM  "Blood donation"

Comparing 331 existing Outlook calendar entries

Unable to update existing entries in the Outlook calendar.

The object does not support this method.

Operation aborted after 1 failed attempts!I sync. 
```

**Comment by ElenitaG** [comment] 2019-10-11 01:42
![image](https://user-images.githubusercontent.com/55212479/66618336-c1cc4900-eba6-11e9-8130-f1b9a97588ae.png)

**Comment by phw198** [comment] 2019-10-20 15:26
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

:spiral_notepad: If you can replicate the problem, provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by phw198** [comment] 2019-11-24 12:25
Likely duplicate of #897

**Closed as completed** 2019-11-24 12:25 UTC
Labels: duplicate, dormant, old release
