### ISSUE TITLE
The synchronisation failed - check the Sync tab for further details.  

### ISSUE THREAD

**Issue by chanel2020** [phw198/OutlookGoogleCalendarSync#1096] opened 2020-10-01 05:55 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by chanel2020** [comment] 2020-10-01 05:59
The following error was encountered during sync:-ERROR: Unable to connect to the Google calendar.  
Sync aborted after 1 failed attempts!
I uninstalled the program and reinstalled with the same issue.  The ver. 2.8.4.0
After trying to Sync you get Error Message "The synchronisation failed - check the Sync tab for further details.  Do you want to try again"  Yes or No.     Any idea what the issue is?

**Comment by tnjgb** [comment] 2020-10-01 07:03
Mine was doing the same then at 08:00 (BST or UTC+1) it suddenly started working again.

**Comment by swannpichon** [comment] 2020-10-01 07:36
probably your wifi / internet connection I suppose

**Comment by tnjgb** [comment] 2020-10-01 07:56
Nothing to do with Internet connection, Google Calendar was working fine in Chrome.

**Comment by Kevode** [comment] 2020-10-06 04:17
Same issue with Chanel2020.

Also, Outlook calendar is still not syncing to Google calendar even though OGCS shows 0 entries found and sync finished with success!

**Comment by tnjgb** [comment] 2020-10-06 07:01
Exactly the same again today would not sync until 08:00 BST. Google calendar was/is working fine on Windows Chrome and Android device. I was wondering if the Google API quota had been exceeded and resets at this time?

**Comment by KaiDK** [comment] 2020-10-08 07:01
I have the same here:

2020-10-08 08:58:14,258 WARN  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:xxxxxxx'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]

**Comment by tnjgb** [comment] 2020-10-08 07:18
Again this morning, it works again after 08:00 BST.

Perhaps those who have donated to the project can have a priority on number of queries?

**Comment by Falklan** [comment] 2020-10-16 04:32
> I have the same here:
> 
> 2020-10-08 08:58:14,258 WARN 17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] - Google.Apis.Requests.RequestError
> Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
> Errors [
> Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:xxxxxxx'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
> ]

My last successful sync was 2020/10/01 and now I'm receiving this same error.

**Comment by Kevode** [comment] 2020-10-16 05:08
Don't worry about it. I've uninstalled OGCS and use a different free
program that works really well if not better.

**Comment by Falklan** [comment] 2020-10-16 12:20
Mine is actually working again after I disconnected and reconnected to the gmail account.

**Comment by wicketr** [comment] 2020-10-20 05:03
> Don't worry about it. I've uninstalled OGCS and use a different free program that works really well if not better.

And what alternate program would that be @Kevode ?

**Comment by Kevode** [comment] 2020-10-20 06:38
http://www.pppindia.com/calendar-sync/index.html

**Comment by tnjgb** [comment] 2020-10-20 10:18
Getting an using a personal Google OAuth API overcomes this problem.

**Comment by phw198** [comment] 2020-10-25 14:35
Duplicate of #1035 which has a hotfix posted.

**Closed as completed by phw198** 2020-10-25 14:35 UTC
Labels: bug, duplicate
