### ISSUE TITLE
Items getting synced to wrong calendar

### ISSUE THREAD

**Issue by WaruMetal** [phw198/OutlookGoogleCalendarSync#534] opened 2018-05-31 21:02 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  

The user in question has two separate accounts running in Outlook.  Let's call them A and B.  He is using OutlookGoogleCalendarSync in order to synchronize calendar events on account B.  What happens periodically is that items when added (presumably from the google account) will start showing up on account A in Outlook instead of account B.

Here's what I think happens based on what I've seen.  In the sync settings, the "Default" inbox is inbox A, so we setup the app to sync to an alternate inbox B.  For some reason how, the application seems to set itself back to the default position.  Usually after I open the program, change it back, it starts syncing properly again, but this keeps happening over and over.

Is there an easy way to resolve this?

**Steps to Reproduce the Issue**  
1.   Setup two accounts in Outlook
2.   Set sync to Alternate inbox
3.  Setup regular interval syncing
4.  Wait

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-05-31 21:46
Thanks for reporting this.

:arrow_double_up: Could you confirm if this still occurs on the latest release - download it [directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

:spiral_notepad: If it does, then please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)) taken as soon as you notice the problem occur.

**Comment by WaruMetal** [comment] 2018-06-01 15:04
Thank you for your quick response.  I will give this a try and report back.  You may not hear anything right away, as it doesn't seem to happen immediately, but I will report what progress we find.  Thanks!

**Comment by fors6630** [comment] 2018-06-13 18:51
Hello again Paul - 

First, I want to say I like the new graphics and details on the sync tab.  Nice improvement and much easier to read!

Second, I can confirm this issue still exists in the 2.7.4.0 alpha version (zip file) which I downloaded yesterday.   I came here looking for this existing issue, and found Waru had it already. 
 
In my case, I should be syncing from Google to Outlook, however Outlook items are going to Google.  

Upon troubleshooting, I first discovered that the OGCS Sync Option setting for "Direction" was set to "Outlook to Google", meaning it didn't maintain my prior setting.  

After fixing that, I manually deleted all the Outlook events from my Google Calendar since I don't want them there.  Then, when again syncing, the Outlook Calendar items showed back up on Google Calendar.  

Log is attached.  Please LMK when you have a new built to test and I will be happy to help.  

Thank you for your efforts!
--Rob

**Comment by phw198** [comment] 2018-06-13 22:34
Hi @fors6630 - thanks for the feedback on the updated sync output 🙂

However, what you're reporting sounds different from @WaruMetal - he's saying OGCS forgets to sync to the alternate calendar in Outlook; you're staying it forgets which _direction_ to sync.

But how did you set up the v2.7.4 zip? Which settings.xml file is it using? If you had to reauthorize OGCS to access Google you likely got a brand new default settings file which would sync from Outlook to Google. Your log file doesn't show from start-up of OGCS so I can't really tell... Would be good to create a separate issue though if you want to continue investigating this.

Cheers

**Comment by fors6630** [comment] 2018-06-18 15:44
Hi Paul - I'll reopen a separate issue as suggested, if I see this behavior continue.  First I'm going to try a fresh deployment of the 2.7.4 zip, cleaning the old versions to ensure no leftover files, better than I did on the prior post.  Hopefully I won't see this continue.  Thanks!

**Comment by phw198** [comment] 2018-10-14 11:54
:package: This should now be resolved with [v2.7.6.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2476343/v2.7.6.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) for both alternate mailbox and shared calendar problems.

Please let me know how it goes.

**Comment by amprior** [comment] 2018-10-14 13:31
Genius! confirmed fixed for my user's application.

**Comment by phw198** [comment] 2018-10-14 15:27
@amprior Thanks for the quick testing (wasn't sure how reproducible the issue was for you) and for subsequent donation :slightly_smiling_face:

**Comment by amprior** [comment] 2018-10-15 10:37
Ah the delights of remote control of User's PC's :-)

**Closed as completed** 2018-11-25 23:10 UTC
Labels: bug, resolved
