### ISSUE TITLE
No shared calendar found ".

### ISSUE THREAD

**Issue by JohnJ62** [phw198/OutlookGoogleCalendarSync#215] opened 2017-05-22 23:41 UTC
Version 2.4.0.0
Problem proiduced when OGCS opened
Yes, happens eveey time opened. Displays dialofue box as:
Could not find shared calendar for".

I was using this on a XP laptop with Outlook 2003 and a pop related email calendar and it worked fine. Now on a WIn10 laptop with Outlook 2013, again with the same calendar linked to a pop email. The settings look the same.

I get this warning and then as it hasn't found the calendar. Then when starting the sync it attempts to delete all existing entries...and I have to click no to all dialogue box "Delete Confirmation" selection boxes as each is shown. There are many (last time I counted the "No" options I had to click and there were 53) and some times after reaching the end of them all it simply goes around again...and again and cycles through the whole set of entries prompting me to delete them, the same quantity again and again.

It does pass new entries from the calendar to the phone's google calendar and in reverse when last tested.

Sometimes I get a "Outlook appointment update failed. Continue with synchronisation?" message and if I click "Yes" find it's at the end anyway. The last entry the states "Sync finished with success!" 

I have attached one undated text file and the most recent dated "log" file having cagnged it to a txt file.

Many thanks

John

**Comment by phw198** [comment] 2017-05-23 12:17
Duplicate of issue #211 and no sign of log files attached to either ticket.

**Closed as completed by phw198** 2017-05-23 12:17 UTC
Labels: duplicate
