### ISSUE TITLE
Constantly trying to sync with no new calendar entries

### ISSUE THREAD

**Issue by jbjb2018** [phw198/OutlookGoogleCalendarSync#1177] opened 2021-02-19 02:40 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.6.0 
**Installed or Portable**: Installed

**Problem Description**  
Pops up in my taskbar and continuously tries to sync, even though no new calendar entries are being added.
It's been like this for the last 2 updates.

**Steps to Reproduce the Issue**  
1. Install in Windows 10, Home
2. Watch it consistently update

**Any other information**  
It doesn't matter if you stop the sync, it will continue to try to sync again. find 0 entries and repeat until you exit it.

**Comment by phw198** [comment] 2021-02-21 10:21
:spiral_notepad: In order to receive support, please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

Possible duplicate of #1161.

**Comment by kfinnett** [comment] 2021-02-25 16:31
I am having the same issue, which only started to happen with version 2.8.6.0. It constantly synchronises despite no schedule being in place, my CPU running at 65% constantly as a result (and draining laptop battery very quickly!)

**Comment by Maurice84** [comment] 2021-02-25 18:02
I'm also having this issue since 2.8.6.0. I've added my OGcalsync.log to this ticket, but I'm afraid you don't see much details why this is happening. I executed the application and let it sync a few times in a row and uploaded the log.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6044940/OGcalsync.log)

**Comment by mawid6** [comment] 2021-02-26 12:00
Hello,
I am also having this issue. It constantly syncs. 

I first (like a long time ago, maybe a year ago) disabled the push outlook changes immediately, I thought that was the problem. Then I gradually increased the schedule, I have had it at four hours for months but it makes no difference. The thing just syncs and starts a new sync, and on. The notifications are constant.  It is really annoying.

Here is an image of it currently syncing. It seems stuck on something. But notice how the next sync is scheduled like two minutes away, despite having four hours as the schedule!
![image](https://user-images.githubusercontent.com/77722885/109297419-42d6bf80-7832-11eb-8b1b-a66e107af309.png)

Here are my settings (I just set the previous days to 0, just trying to get it as simple as possible to get it to work):

![image](https://user-images.githubusercontent.com/77722885/109297335-1f137980-7832-11eb-8b1b-49590a107b6e.png)


Again, this has been a problem for quite a long time now, but I have not taken the time to report it.

I will also, like @Maurice84 , try and turn on verbose logging and upload the log, FWIW.

Thanks for a great tool that is really helping me out!
BR! /marcus

**Comment by phw198** [comment] 2021-02-27 18:39
@Maurice84 You have logging turned off, so there's basically nothing in your log file :slightly_smiling_face: 

> It constantly synchronises despite no schedule

This matches #1161, so closing as a duplicate.

**Closed as completed by phw198** 2021-02-27 18:39 UTC
Labels: duplicate
