### ISSUE TITLE
Wrong time of a periodic schedule

### ISSUE THREAD

**Issue by frederhe** [phw198/OutlookGoogleCalendarSync#281] opened 2017-07-25 11:28 UTC
Hello,

I think I have found a bug related to the time zone and winter/summer time.

I had a schedule meeting from India that put the meeting from 9 to 10AM during winter time in Europe.
During summer time, this meeting is from 10AM to 11AM (due to summer time in france), the original meeting time in india didn't change since India don't have any summer/winter time.

On outlook, the schedule is automatically shift according to winter/summer time in france. when sync this to google calendar, it is sync with winter time event in July (this is the bug)

my configuration is one way only from outlook to google

I used portable apps 2.2 and updated to latest 2.5.2, bug stills present.
timezone db is 2017b

**Comment by mtalexan** [comment] 2017-07-25 18:10
Duplicate of #67 , same problem with a different effect.

**Closed as completed** 2018-08-19 22:45 UTC
Labels: duplicate
