### ISSUE TITLE
Multiple OGCS instances & PreconditionFailed [412] on Sync

### ISSUE THREAD

**Issue by gmtrucks297** [phw198/OutlookGoogleCalendarSync#1052] opened 2020-07-30 17:48 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0 
**Edition**: Installed
**Sync Direction**: O->G 

**Bug Description**  
At various times syncing will fail. I receive two messages, one right after the other. One saying the sync failed on a specific item and then that the sync has failed entirely. I've noticed that there are multiple instances of OGCS open when this happens most of the time, so I close both down and then manually restart the program. This fixes it for a while but the issues come back (maybe after my computer has gone to sleep and I login, but I'm not entirely sure). I also receive a lot of messages to confirm deletions when I know that an event has not really been cancelled. I assume this is due to the multiple open instances.  

This has been happening for at least a few months now. Uninstalling and reinstalling, as well as upgrading to 2.8.4.0 did not solve the issue. 

**Steps to Reproduce the Issue**  
1. Start or wake computer (I have OGCS start on login)

**Any other information**  
Log file and screenshots attached.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5002875/OGcalsync.log)
![OGCS_error1_revision](https://user-images.githubusercontent.com/54927266/88956016-f9050700-d259-11ea-84dc-701d2f22dc42.jpg)
![OGCS_error2_revision](https://user-images.githubusercontent.com/54927266/88956030-fdc9bb00-d259-11ea-9e01-0ccd3b9e4088.jpg)

**Comment by haasp2** [comment] 2020-07-31 09:00
I have exactly the same issue. My first attempt was to check, why it gets started twice. I found, that in SETTINGS under Application Behaviour the Start on Login with a delay of (60) seconds if set. In the Autostart of Windows 10 (Settings->App->Autostart) it was also included.
I've taken out the entry in the Windows 10 but left the selection under OGCS SETTINGS under Application Behaviour the Start on Login with a delay of (60) seconds. Now it doesn't start at all, but when started manually, has no issue sync issues anymore.
Consecutive (de-selection of the Start on Login -Saving - closing the app- starting the app - setting the "Start on Login" - saving - closing the app- logging off -rebooting - loging on) did not start OGCS automatically as supposed.

**Comment by phw198** [comment] 2020-08-08 13:28
@gmtrucks297 Are you _intentionally_ running more than one instance of OGCS? Or is as @haasp2 is reporting, you have it set to auto start on startup and somehow it ends up running multiple instances?

**Comment by gmtrucks297** [comment] 2020-08-08 13:42
The latter, as @haasp2 reports. I have it set to auto start on startup with
a short delay. I'm not sure how, but yes, it ends up running multiple
instances for some reason.

**Comment by phw198** [comment] 2020-08-17 22:03
There are two ways to see the startup configuration for Windows10 as set with OGCS:
1. Windows Task Manager > Start-up tab > Right click OGCS > Enable | Disable
1. Start > Settings > Apps > Startup > OGCS > Toggle On / Off

By disabling the startup of OGCS via either method will override any selection of "start on startup" within OGCS itself. 
@haasp2 Not quite sure what you meant by "I've taken out the entry in the Windows 10"...

The registry key that controls what to run on startup is found in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` - there should only be **one** entry for OGCS.

Could you also check in Windows Explorer if you have manually added a shortcut for OGCS to `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup`? If so, this would explain two instances of OGCS.

Also, if you see two instances of OGCS running in Task Manager:
1. Go to Details tab
1. Right-click on a column heading and `Select Columns`
1. Scroll down to `Command Line` and check the box
1. Click OK and expand that new column
1. Confirm what the two command lines are for the OGCS instances running - e.g. the same?

**Comment by gmtrucks297** [comment] 2020-08-19 17:25
I looked at the registry keys and I see only one entry for OGCS:
[image: image.png]

I also don't see a shortcut in OGCS in that location:
[image: image.png]

Using the second method for selecting the startup settings, I see OGCS
toggled on right now. I'll toggle it off and report back if anything
changes. Thank you!

**Comment by haasp2** [comment] 2020-08-24 07:03
Hi Paul, 
OGCS is not starting automatically at the moment.
If you need a more systematic analysis, let me know and I can try several variants at a later date.

The current settings are as follows:

1. Windows Task Manager > Start-up tab > Right click OGCS > **Deaktivated** <-- corrected (has been stated "enabled" erroneously)
2. Start > Settings > Apps > Startup > OGCS > Toggle **Off**
3. In OGCS under Settings > Application Behaviour > **Start on login, with Delay 60 seconds**
4. Under %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup **no manual entry**
5. in the registry only one entry is there with the following Value **C:\Users\my_userename\AppData\Local\OutlookGoogleCalendarSync\app-2.8.4-alpha\OutlookGoogleCalendarSync.exe /d:60**

Regards,
Pius

**Comment by mikek70** [comment] 2020-08-28 07:40
I see the same behaviour as @haasp2 still running 2.8.0.0 - I believe it started with some Windows Update (maybe to 2009, but no longer sure). If I can provide any details, let me know.

**Comment by haasp2** [comment] 2020-08-28 09:59
Dear all,
After several tries I did a systematic testing and could not reproduce the problem. 
I have noted down what I tested and what the result was and as a consequence of the testing I **assume**, that it might have to do with an previous installation of an older Version of OGCS or a consecutive update of it.

To help you, I provided also my suggestions on how to get the things right so OGCS starts only once.
Have a look and try it.

Kind regards,
Pius

[OGCS Testing and Resolution_2.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/5141441/OGCS.Testing.and.Resolution_2.pdf)

**Comment by mikek70** [comment] 2020-08-28 10:50
Thanks @haasp2 - deactivating "Start on login" - rebooting and reactivating "Start on login" fixed the issue for me as well!

**Comment by TheJacksonian** [comment] 2021-01-27 03:33
I too (Alpha 2.8.6.0) was getting this error and it turned out since updating my portable OCGS files that it was indeed running twice. Since 'resetting' the auto start, with the application running once, I've not had the Error 412 issue.

I noted it here too. https://github.com/phw198/OutlookGoogleCalendarSync/issues/1145

**Comment by phw198** [comment] 2021-01-30 18:12
Would be good to understand if this multiple-instance behaviour is triggered specifically during/after an upgrade.

**Comment by phw198** [comment] 2021-09-19 12:41
Did anyone encounter this again upon upgrade to v2.9.0? If so, before [applying the workaround](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1052#issuecomment-682460440), could you:

* Start Task Manager > Details > Right click column header > Select columns > Check "Command Line"
* Confirm the command line entry for both OutlookGoogleCalendarSync.exe processes running
<br/>

* Open regedit and navigate to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
* Confirm what the value is for Outlook Google Calendar Sync key

For the record, I've tried numerous upgrades and can't replicate this behaviour at all...

**Comment by TheJacksonian** [comment] 2021-09-20 00:40
My process (due to machine restrictions at work) is to quit out of OGCS, then copy the files over from the Portable.zip, then restart by clicking on the OutlookGoogleCalendarSync.exe process.
I've just done this with v2.9.1.0 and it's working fine, I've not seen this issue since I reported it in January.

**Closed as completed** 2021-11-06 08:40 UTC
Labels: bug, dormant, triage

**Comment by phw198** [comment] 2022-08-13 11:14
:link: #1524
