### ISSUE TITLE
Push Sync is failing. Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by fyates** [phw198/OutlookGoogleCalendarSync#1209] opened 2021-04-15 13:40 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

Hello,

I have been getting the "Push Sync is failing. Object reference not set to an instance of an object" error when I launch Outlook in the morning and check OGCS to see if things are syncing. I'm running Windows 10 x64 and I think the computer is coming from a Sleep state.
I got this error in the last version I was running, and the alpha 2.8.6.0. I will attach logs for both.
I use the installed versions.
I sync O -> G

1. I wake up my computer and login.
2. I launch Outlook.
3. OGCS is in the system tray and I open it to check if things are syncing.
4. Error message is displayed on the screen.
5. I can sync manually if I remember to do it.

![image](https://user-images.githubusercontent.com/79935181/114878311-f715b080-9db4-11eb-8e14-3bc8f07c9fe4.png)
[OGcalsync.log.2021-03-16.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6318414/OGcalsync.log.2021-03-16.log)
[OGcalsync.log.2021-04-14.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6318415/OGcalsync.log.2021-04-14.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6318420/OGcalsync.log)

**Comment by phw198** [comment] 2021-04-18 12:50
:package: I haven't been able replicate this issue, or therefore test the fix, but please see if the issue is now resolved with [hotfix v2.8.6.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6331256/v2.8.6.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by fyates** [comment] 2021-04-18 17:27
Thank you so much. I followed the instructions and applied the fix. I will keep an eye on it for the next few weeks as meetings are added to my work calendar. I will come back and post an update then. I appreciate your help!

**Comment by Rosmaninho** [comment] 2021-04-25 17:30
I also applied this fix. I'll report back at next sync to say if it's fixed or not.

**Comment by fyates** [comment] 2021-05-03 19:51
I have been watching things closely for the past two weeks since I applied the fix, and everything is working seamlessly. No errors at all and every meeting for work is showing up in my personal calendar. Thank you so much!

**Closed as completed** 2021-05-09 19:12 UTC
Labels: bug, resolved
