### ISSUE TITLE
Appointment Update Failed

### ISSUE THREAD

**Issue by WarningU2** [phw198/OutlookGoogleCalendarSync#1419] opened 2022-04-07 15:10 UTC
**OGCS Version**: v2.9.3.9
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**

Initially thought this was a repeat of issue #1395 but realize the error is different since applying the hotfix for that issue.   A snippet of the full log attached below.   Appears related to a reoccurring appointment update failed.   Doesn't happen immediately after OGCS start.   Successfully syncs for a period of time and then fails for reasons unknown.   
```
2022-04-07 10:56:38,147 ERROR  22 OutlookGoogleCalendarSync.Console [278] -  Appointment update failed.
2022-04-07 10:56:38,148 ERROR  22 OutlookGoogleCalendarSync.Console [278] -  Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
2022-04-07 10:56:38,244 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
2022-04-07 10:56:38,245 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004002,-2147467262; Location: GetCOMIPFromRCW() in <Unknown File>
2022-04-07 10:56:38,245 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.MAPIFolder.get_EntryID()
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 173 
```
**Steps to Reproduce the Issue**  
1. After the initial error if you run sync again it will continuously fail.   (see pic attached).

2. To stop the error (temporarily) exit from OGCS and restart.  Wait a min and then run sync which completes successfully,  

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8444157/OGcalsync.log)
![pic1](https://user-images.githubusercontent.com/44507492/162231349-b073f5f7-7041-4a2b-830d-c76390cdc852.png)

**Comment by phw198** [comment] 2022-04-10 18:40
Hi @WarningU2 This looks like a duplicate of #1406, so I'll close and track there.

Thanks for confirming restarting OGCS is only a temporary fix, however :+1:

**Closed as completed by phw198** 2022-04-10 18:40 UTC
Labels: bug, duplicate
