### ISSUE TITLE
OGCS always appears in open apps when ALT - TAB pressed

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#1355] opened 2021-12-12 00:55 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.2.0
**Edition**: Installed   
**Sync Direction**: O<->G

**Bug Description**  
Since I upgraded to v2.9.2.0, the OGCS app always appears in the list of apps when I press ALT-TAB. It is strange, it never used to appear in the list of apps but has since I upgraded to this latest version. The app does not show in the taskbar but it appears with the other apps (icons) in the group of hidden icons. Is there a way to remove the app from within the list of ALT-TAB. It just means occasionally I select it by mistake and app opens when I mean to select another app.

Thanks

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7697964/OGcalsync.log)

**Comment by phw198** [comment] 2022-01-08 17:15
Duplicate of #1343 which has a hotfix.

**Closed as completed by phw198** 2022-01-08 17:15 UTC
Labels: bug, duplicate

**Comment by Flying-Roger** [comment] 2024-10-14 08:06
The same problem reappeared with version 2.11.0.0
Due to this, I often kill OGCS while closing my open apps before putting my PC in standby (sleep) mode and I have to relaunch OGCS when I awake my PC.

**Comment by phw198** [comment] 2024-10-19 12:07
@Flying-Roger Still works fine for me on 2.11.0 and Windows 11. Are you sure you still have the "Minimise to tray instead of taskbar" option set?

Can you provide a screen shot of the OGCS icon not being in the taskbar, but it is showing in the alt-tab application list?

**Comment by Flying-Roger** [comment] 2024-10-19 14:05
After reading your message, I screened again all the options and finally found the tab "Application Behaviour" that I did not spot initially.
I looked for the famous option in all other tabs, of course to no avail.
Thank you Paul for your help and sorry for disturbing.
Maybe this post will help another user making the same mistake as I did ;-)
