### ISSUE TITLE
Outlook sync since updated

### ISSUE THREAD

**Issue by Stuwilli1** [phw198/OutlookGoogleCalendarSync#592] opened 2018-09-15 15:17 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----
Its been a while since we communicated, this time after the new install to 2.7.6.0, this week, my Outlook is not syncing. I can't find an error in the settings (but could be, lol).

Tried to sync and change settings.  Additionally, if I try to click on the alternative calendar it states none exist and defaults back to my Gmail.

Very confused on this one, fikes attached.  Thanks,

Stuart
![capture ogcs](https://user-images.githubusercontent.com/39503028/45587776-8e05ed80-b8d8-11e8-97ac-bc8b073f5a8d.JPG)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2385845/OGcalsync.log)

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by Stuwilli1** [comment] 2018-09-26 15:51
Yes still an issue and it takes 30-40 minutes to sync but eventually does. 

Stuart

**Comment by phw198** [comment] 2018-10-14 22:59
Duplicate of #599.

**Closed as completed by phw198** 2018-10-14 22:59 UTC
Labels: duplicate
