### ISSUE TITLE
Support for multiple calendars (personal and work for example)

### ISSUE THREAD

**Issue by benaltair** [phw198/OutlookGoogleCalendarSync#458] opened 2018-02-06 09:29 UTC
I'd love to see the option to sync different Outlook calendars to separate Google Calendars with each sync. They could run concurrently or one after the other, but would be logically separate processes.

This would use the same main structure of having bilateral sync between two calendars, just doubling that process for two other unique calendars.

**Comment by phw198** [comment] 2018-02-06 15:30
Duplicate of #165 

Please up-vote the other ticket, though it is [already in the pipeline](https://github.com/phw198/OutlookGoogleCalendarSync/projects/3).

**Closed as completed by phw198** 2018-02-06 15:30 UTC
