### ISSUE TITLE
Multiple copies of a whole day event created

### ISSUE THREAD

**Issue by stud0709** [phw198/OutlookGoogleCalendarSync#387] opened 2017-11-10 07:07 UTC
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1460341/OGcalsync.log)
![2017-11-10_07h50_53](https://user-images.githubusercontent.com/31960113/32646452-e54a94d6-c5ec-11e7-9105-be4bc9e26f83.png)

**OGCS Version**: v2.6.2.0  
**Installed or Portable**: Installed

**Problem Description**  
An event seems to be synced mutiple times to google calendar. Unfortunately, I cannot remember the details about how this event was created (d&d or entered). There are events with the same title on Nov. 20 and Dec. 12, which have been duplicated. Other events with this very title were synced properly or **not synced at all**. I'm getting an idea, that some of the events are displaced to the wrong date due to some matching issue

**Steps to Reproduce the Issue**  
sorry, unknown

**Any other information**  
despite some smaller bugs, it is a great tool :)

**Comment by phw198** [comment] 2017-11-11 20:43
Sounds like a duplicate of #314, which had work to resolve in v2.6.3. Appointments created in Outlook by copy and paste prior to this will like have the issue you are reporting.

If you are the owner of the appointment and able to recreate it from scratch, then that would be the simplest solution...

**Closed as completed** 2018-01-02 18:34 UTC
Labels: dormant
