### ISSUE TITLE
Failure in first run after install.

### ISSUE THREAD

**Issue by joncb01** [phw198/OutlookGoogleCalendarSync#770] opened 2019-07-01 06:37 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.800
**Installed or Portable**: Installed

**Problem Description**  
Run OGCS after install. Outlook login dialog pops up but cannot enter password before OGCS reports error and Outlook login dialog closes

**Steps to Reproduce the Issue**  
1. Run OGCS

**Any other information**  
Installed in another laptop for this account and works fine. Wanting to sync from whatever computer I am on at the time.
Did the Office Repair as suggested.
Running Office 2016 in WIN 10 on the Slow Ring of the Windows Insider Program (Version 1903 Build 18362.175)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3344159/OGcalsync.log)

**Comment by phw198** [comment] 2019-07-11 22:39
Hi,

I don't think OGCS is reporting the error your are encountering properly. 

This was also being investigate on #752 and there is a [hotfix posted there](https://github.com/phw198/OutlookGoogleCalendarSync/issues/752#issuecomment-500114996) - could you try it out and see if it a reports a different error number (and therefore wiki solution)?

Thanks!

**Comment by phw198** [comment] 2019-07-28 20:45
Duplicate of #783

**Closed as completed** 2019-07-28 20:45 UTC
Labels: duplicate
