### ISSUE TITLE
Failed to retrieve master for Google recurring event - Fails to Sync

### ISSUE THREAD

**Issue by smiller2421** [phw198/OutlookGoogleCalendarSync#212] opened 2017-05-22 01:39 UTC
Total inc. recurring items spanning sync date range...
Failed to retrieve master for Google recurring event.
The following error was encountered during sync:-
Object reference not set to an instance of an object.
Operation aborted after 1 failed attempts!

**Comment by phw198** [comment] 2017-05-22 12:14
Duplicate of Issue #82.

**Closed as completed by phw198** 2017-05-22 12:14 UTC
Labels: bug, duplicate
