### ISSUE TITLE
need OGCS for MacOS

### ISSUE THREAD

**Issue by flohfeld** [phw198/OutlookGoogleCalendarSync#1192] opened 2021-03-18 20:08 UTC
**Is your feature request related to a problem? Please describe.**
it is not possible to use ical or google with an outlook calendar link for company exchange server

**Describe the solution you'd like**
release a OGCS Version for MacOS Big Sur

**Describe alternatives you've considered**
using ic loud calendar instead of google

**Comment by phw198** [comment] 2021-03-26 15:42
Duplicate of #159

**Closed as completed by phw198** 2021-03-26 15:42 UTC
Labels: duplicate, enhancement
