### ISSUE TITLE
Starting OGCS fails [0x800706BE]

### ISSUE THREAD

**Issue by pitaki** [phw198/OutlookGoogleCalendarSync#282] opened 2017-07-25 14:00 UTC
After win10 boot, I received announcement (for only little while visible) that my Outlook and OGCS are running in different admin levels. After that I started OGCS and it gave me an error message. 
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1173370/OGcalsync.zip)

**Comment by pitaki** [comment] 2017-07-30 08:57
It worked for a while and after reboot... this happened

COM exception encountered. Please log an Issue on GitHub and upload your OGcalsync.log file.

[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1185549/OGcalsync.zip)

**Comment by solarmax1** [comment] 2017-08-02 21:39
I have a similar issue.  The OGCS splash screen pops up, then quickly closes.  App is not running in the background.  Sending log file via email.

**Comment by phw198** [comment] 2017-08-02 23:16
@pitaki 
1. Your first logfile is `CO_E_SERVER_EXEC_FAILURE` - so a duplicate of issue #268.
1. Your second logfile is `0x800706BE` and a brand new error I've never seen before.

Whilst I'll look to handle the second error better, the issue is still related to setting a delay on OGCS startup, same as I've told you multiple times now. You seem to have downgraded from v2.5.2.7 back to v2.5.2.0 - any reason for this?

@solarmax1 You'll need to upload your OGcalsync.log file for me to verify the exact issue you're getting [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by solarmax1** [comment] 2017-08-02 23:42
Hi Paul,

The log file should be in your email.

**Comment by phw198** [comment] 2017-08-02 23:53
@pitaki 
:package: `0x800706BE` should now be resolved with [Hotfix-v2.5.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1195569/v2.5.2.12.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes.

**Comment by phw198** [comment] 2017-08-03 00:03
@solarmax1 Ah yes, it landed in my spam. You're getting a `0x80029C4A` which is [mentioned in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80029c4a---type__e__cantloadlibrary) - see if that helps.

**Comment by solarmax1** [comment] 2017-08-03 11:55
That fixed it!  Thank you!

Mark

**Closed as completed** 2017-08-11 08:20 UTC
Labels: bug, low, resolved
