### ISSUE TITLE
There is a problem with this item - it will not be synced. 

### ISSUE THREAD

**Issue by orphanpiglet** [phw198/OutlookGoogleCalendarSync#1899] opened 2024-07-01 06:09 UTC
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.5.0 
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I have started getting the following error message with several Outlook items, which fail to sync to GC: "There is a problem with this item - it will not be synced. One or more items in the folder you synchronized do not match. To resolve the conflicts, open the items, and then try this operation again."

I don't know which folder or conflicts it refers to, so I don't know how to resolve the issue.

The two events that are currently producing this error and not recurring, but have both been modified since being created.

**Steps to Reproduce the Issue**  
1. Go to Sync
2. Click on Start Sync
3. 3. Two events produce the above error and do not sync.
[OGcalsync.log](https://github.com/user-attachments/files/16048500/OGcalsync.log)

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by benjaminrapp-vSTI** [comment] 2024-07-04 11:31
same problem here. in installed as well as portable version. Alpha and normal version.

**Comment by phw198** [comment] 2024-07-15 18:50
Looks like a duplicate of #1869

**Closed as not planned** 2024-07-18 20:25 UTC
Labels: bug, duplicate
