### ISSUE TITLE
Multiple prompts of Sync Failed error message box

### ISSUE THREAD

**Issue by McoreD** [phw198/OutlookGoogleCalendarSync#372] opened 2017-10-22 21:50 UTC
Hi, 

I have OGCS sync every 10 mins.
When the internet is down and OGCS attempts to sync, it would prompt another Sync Failed error message box.

https://lh3.googleusercontent.com/-DENPaafAB6g/WeydTZpJ_gI/AAAAAAAAI3k/DN4-e_H6mQ8w9gGAHPZ6zXtN5PbvLrT1gCHMYCw/s0/2017-10-22_21-29-46.png

Would it be possible to only prompt once, and in the next instance of the error, detect that it has already prompted it before and not prompt anymore?

**Comment by Edgarze** [comment] 2017-10-30 22:34
Same issue here....Very annoying. Wife is complaing, pushing to replace application :-(

**Comment by phw198** [comment] 2018-01-13 19:59
Duplicate of #47

**Closed as completed by phw198** 2018-01-13 19:59 UTC
