### ISSUE TITLE
Sync feature request: exclude all day events from sync

### ISSUE THREAD

**Issue by rmdodhia** [phw198/OutlookGoogleCalendarSync#1501] opened 2022-06-21 17:38 UTC
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
I sync from outlook to google, but I have a ton of all day events that I'd like to exclude from appearing in google. Is there an existing way to do that? Or can it be included as an option?

**Steps to Reproduce the Issue**  

**Any other information**

**Comment by phw198** [comment] 2022-07-24 15:19
Duplicate of #104

**Closed as completed by phw198** 2022-07-24 15:19 UTC
