### ISSUE TITLE
Can't Sync on Windows 11 Pro

### ISSUE THREAD

**Issue by Boomer451** [phw198/OutlookGoogleCalendarSync#1729] opened 2023-11-03 17:26 UTC
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13252949/OGcalsync.log)

> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)

**OGCS Version**: v2.10
**Edition**: Full version installed  
**Sync Direction**: O->G

**Bug Description**  
OGCS worked fine on my previous desktop PC, a Dell XPS-8700 running Win10 Pro and Outlook 2016. That PC died and was replaced with a Dell XPS-8950 running Win11 Pro (latest build). 
Outlook 2016 was successfully installed.
OGCS v2.10 was successfully installed and configured.
OGCS sync appeared to run successfully but calendar entries were not added to my Google calendar on my Samsung Galaxy S20 FE smartphone.

**Steps to Reproduce the Issue**  
1. Ran "sync now..."

**Any other information**  
Performed an uninstall of OGCS and deleted all references on the 8950.
Performed a repair install of Outlook 2016.
Install OGCS v2.9 (full version) successfully. Configured it successfully.
Updated to OGCS v2.10. Configured it successfully.
Ran multiple syncs but again Google calendar on Samsung Galaxy S20 FE not being updated.

**Comment by phw198** [comment] 2023-11-04 17:52
You need to check https://calendar.google.com to see if the synced items are showing there. If they are, then the problem is with your phone, which is out of scope for OGCS.

**Comment by Boomer451** [comment] 2023-11-05 16:50
Thank you for the suggestion. I did check my online Google calendar and the events are not shown. I suspect that since all was well under Windows 10, Outlook 2016, and OGCS the introduction of Windows 11 has somehow caused the issue. Again thank you for your attention.

Regards,
Gary Cota

**Comment by bdurrer** [comment] 2023-11-09 07:09
@Boomer451 According to your log, OGC only found 5 calendar entries in Outlook and 2 in your calendar

```
2023-11-03 12:56:12,101 DEBUG  1 OutlookGoogleCalendarSync.Console [230] -  Syncing from 10/27/2023 to 1/3/2024
2023-11-03 12:56:12,101 DEBUG  1 OutlookGoogleCalendarSync.Console [230] -  Outlook → Google
2023-11-03 12:56:12,148 INFO  18 OutlookGoogleCalendarSync.Console [296] -  Finding Calendar Entries
2023-11-03 12:56:12,227 INFO  18 OutlookGoogleCalendarSync.Console [296] -  Scanning Outlook calendar...
2023-11-03 12:56:12,583 INFO  18 OutlookGoogleCalendarSync.Console [296] -  5 Outlook calendar entries found.
2023-11-03 12:56:12,928 INFO  18 OutlookGoogleCalendarSync.Console [296] -  Scanning Google calendar...
2023-11-03 12:56:15,463 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [277] -  Retrieving all events from Google: 10/27/2023 -> 1/3/2024
2023-11-03 12:56:15,644 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [291] -  Page 1 received.
2023-11-03 12:56:15,645 DEBUG  18 OutlookGoogleCalendarSync.Recurrence [409] -  Identifying exceptions in recurring Google events.
2023-11-03 12:56:15,645 DEBUG  18 OutlookGoogleCalendarSync.Recurrence [417] -  Found 0 exceptions.
2023-11-03 12:56:15,646 INFO  18 OutlookGoogleCalendarSync.Console [296] -  2 Google calendar entries found.
2023-11-03 12:56:16,566 INFO  18 OutlookGoogleCalendarSync.Console [296] -  Outlook 3, Google 3
2023-11-03 12:56:16,660 DEBUG  18 OutlookGoogleCalendarSync.Console [294] -  Checking for orphaned Google items
2023-11-03 12:56:16,676 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1052] -  Scanning 3 Google events for orphans to reclaim...
2023-11-03 12:56:16,676 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1102] -  0 unclaimed.
2023-11-03 12:56:16,676 DEBUG  18 OutlookGoogleCalendarSync.Sync.Engine+Calendar [516] -  Synchronising from Outlook to Google.
2023-11-03 12:56:16,676 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1179] -  Comparing Outlook items to Google events...
```

```
2023-11-03 12:56:16,676 INFO  18 OutlookGoogleCalendarSync.Console [296] -  Matching calendar items...
2023-11-03 12:56:16,951 INFO  18 OutlookGoogleCalendarSync.Console [296] -  0 Google calendar entries to be deleted.
2023-11-03 12:56:16,951 INFO  18 OutlookGoogleCalendarSync.Console [296] -  0 Google calendar entries to be created.
2023-11-03 12:56:16,952 INFO  18 OutlookGoogleCalendarSync.Console [296] -  3 calendar entries to be compared.
```

it only mentions one (recurring) entry, "U.S. NAVY BIRTHDAY":


did you maybe 
- point the tool at the wrong calendars in outlook and google? 
- select a time range too narrow?
- define filters omitting all entries?

**Comment by phw198** [comment] 2023-11-09 18:27
Thanks for the support @bdurrer - appreciated!

I also note the system date time format includes AM/PM (`tt`), which I think can cause problems:
```
2023-11-03 12:52:58,827 INFO  1 OutlookGoogleCalendarSync.Settings [402] -    Short Date Format: M/d/yyyy
2023-11-03 12:52:58,827 INFO  1 OutlookGoogleCalendarSync.Settings [403] -    Short Time Format: h:mm tt
```
Have a look at [this wiki section for more info](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-isnt-it-finding-any-outlook-calendar-items).

**Comment by Boomer451** [comment] 2023-11-09 21:47
Mr. Woolcock:

Thank you for the follow-up. I will give this a try but it won't be for a week or two as I'm currently involved with a new project. I appreciate your continued support and interest.

Gary Cota

**Comment by Boomer451** [comment] 2023-12-18 20:14
Hello, hope you are all doing well.

I revisited the problem I'm having and am still not able to sync my Outlook 2016 calendar (on Windows 11 Pro) with my Gmail Calendar (on Samsung S20 FE). 

I performed a fresh install of OGCS; the configuration and settings all appear to be functioning on the PC side. I've included a copy of the log for your review.

As I noted in the original report, OGCS worked flawlessly under Windows 10 Pro and prior to my purchasing a new Dell XPS 8950 that had Win11 Pro pre-installed.

Here are some additional details that may be relevant to the issue:

+ I'm using POP rather than MAPI. No particular reason other than for my existing Outlook rules and folders and I've been too lazy to convert to MAPI.

+ There are 4 individual Comcast.net email accounts configured in Outlook that feed into a single .PST file that is set as the default (in Outlook) and as the alternative calendar (in OGCS).

I know this isn't in your OGCS domain but do you think it could be a setting on my Google online account blocking the Gmail Calendar update from Outlook? To be frank, I rarely use Gmail and haven't really changed any of the defaults that I'm aware.

Have a good holiday and take care.
Gary Cota

**Comment by phw198** [comment] 2023-12-21 14:43
:paperclips: Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email - please log in to GitHub to upload files.

I'm not sure if your logfile will show you changing the format of your date, but that's what I previously suggested you try...

> do you think it could be a setting on my Google online account blocking the Gmail Calendar update from Outlook?

Definitely not - as already pointed out, OGCS is not detecting the items apparently in Outlook to start with, either because you have selected the wrong calendar folder or because the date-time format needs tweaking.

All the best and enjoy your Christmas!

**Closed as completed** 2024-01-29 08:34 UTC
Labels: bug, dormant
