### ISSUE TITLE
Google Sync errors

### ISSUE THREAD

**Issue by JakeS8745623** [phw198/OutlookGoogleCalendarSync#1062] opened 2020-08-18 05:21 UTC
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0
**Edition**: Installed / Portable: ??
**Sync Direction**: O<->G

**Bug Description**  

I'm getting synchronization errors. Have updated to latest alpha version, it synced once successfully now not working again.
The main error seems to be
```
WARN  7 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]
```

**Steps to Reproduce the Issue**  
1. Click the Sync tab
1. Click on Start Sync Button

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5088356/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5088352/OGcalsync.log)

**Comment by phw198** [comment] 2020-08-20 00:00
Thanks @JakeS8745623 - however, this is a duplicate of #1053 which has a hotfix posted.

**Closed as completed by phw198** 2020-08-20 00:00 UTC
Labels: bug, duplicate
