### ISSUE TITLE
Updated event failed to save. Precondition Failed [412=PreconditionFailed]

### ISSUE THREAD

**Issue by Nutmegger555** [phw198/OutlookGoogleCalendarSync#1129] opened 2020-11-29 23:19 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
This error appears in log. Attaching the log and the screenshot
Updated event failed to save. Precondition Failed [412=PreconditionFailed]

**Steps to Reproduce the Issue**  
This happens during every sync, manual or automatic

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file - attached
![Unknown](https://user-images.githubusercontent.com/75186645/100556296-63ad6a00-326f-11eb-8850-c3a0883b6af3.jpeg)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5613091/OGcalsync.log)

**Comment by phw198** [comment] 2020-12-20 16:29
Old version and duplicate of #528

**Closed as completed by phw198** 2020-12-20 16:29 UTC
Labels: bug, duplicate, old release
