### ISSUE TITLE
sync failed 

### ISSUE THREAD

**Issue by PJWM** [phw198/OutlookGoogleCalendarSync#1086] opened 2020-09-16 06:11 UTC
<

Sync version: 2.8.0.0

Sync started at 16-9-2020 07:56:27

Syncing from 15-9-2020 to 17-9-2021

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

154 Outlook calendar entries found.

Scanning Google calendar...

The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Finding Calendar Entries
Scanning Outlook calendar...

154 Outlook calendar entries found.

Scanning Google calendar...

The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Operation aborted after 2 failed attempts!

Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

**Comment by rolomartini** [comment] 2020-09-16 07:23
Hi all,

same issue happened to me. I am not a programmer or IT at all.
What I did was:

- restart my PC (windows 7)
- upgrade OGCS to 2.8.4 alpha version.

Now, the syncronisation works fine and no bug windows is pop-uping.

**Comment by kapustor** [comment] 2020-09-16 08:11
Hi @PJWM 
Thank you for your great software! Donated to you :)
Facing the same issue on 23:00 - 23:59 PST every day. As I understand, the reason is in "Quota per day" in project 653617509806.
1. Why do we need to sync to this project? Is it mandatory? What information do we provide to this project?
2. Can we not use this project?
3. Can you please rise quota per day for this project? You can do it here: https://console.developers.google.com/apis/dashboard , then "Google Calendar API", then Quotas, and rise quota "Queries per day", by default it is 1000000.

**Comment by Snowman779** [comment] 2020-09-22 06:46
Same problem here.
I can't retrieve the google calendars.

`

Sync version: 2.8.0.0

Sync started at 22.09.2020 08:34:08

Syncing from 15.09.2020 to 12.01.2021

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

51 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Finding Calendar Entries
Scanning Outlook calendar...

51 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Operation aborted after 2 failed attempts!
Another sync has been scheduled to automatically run in 15 minutes time.


Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Authenticating with Google
Preparing to authenticate with Google.
Handshake successful.


Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]`

**Comment by avohns** [comment] 2020-09-22 07:00
Same here, tested 2.8.0 and 2.8.4.0: "
Unable to get the list of Google calendars. The following error occurred:
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]"

**Comment by Raskub** [comment] 2020-10-26 18:07
Same problem here.

Version 2.8.0.0
--



Sync version: 2.8.0.0

Sync started at 26/10/2020 18:53:37

Syncing from 25/10/2020 to 26/12/2020

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

1 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Finding Calendar Entries
Scanning Outlook calendar...

1 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Operation aborted after 2 failed attempts!
Another sync has been scheduled to automatically run in 120 minutes time.


Unable to get the list of Google calendars. The following error occurred:

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

**Comment by famco75** [comment] 2020-10-26 20:42
[image: image.png]

**Comment by phw198** [comment] 2020-10-26 23:20
Duplicate of #1053.

Comments from @famco75 and @Raskub today is duplicate of #1107

**Closed as completed by phw198** 2020-10-26 23:20 UTC
Labels: bug, duplicate
