### ISSUE TITLE
Error when retrieving google calendar: "Sign in with Google temporarily disabled for this app"

### ISSUE THREAD

**Issue by isoAdvector** [phw198/OutlookGoogleCalendarSync#932] opened 2020-01-03 09:16 UTC
**OGCS Version**: v2.3.8.0  
**Edition**: Installed   
**Sync Direction**:  O->G 

**Bug Description**  
Unable to Retrieve my Google Calendar from Settings -> Google.

**Steps to Reproduce the Issue**  
1. Downloaded Alpha setup.exe file from here: https://phw198.github.io/OutlookGoogleCalendarSync/
2. Ran it
3. In Settings -> Google pressed Retrieve Calendars
4. Chose my google account in the browser popping up
5. Get message from google account: "Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In."

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4018593/OGcalsync.log)

**Comment by phw198** [comment] 2020-01-03 09:47
Duplicate of #915

**Closed as completed** 2020-01-03 09:48 UTC
Labels: bug, duplicate
