### ISSUE TITLE
Outlook 2016 v1803 build 9126.2152 breaks OGCS

### ISSUE THREAD

**Issue by 0schr0eder** [phw198/OutlookGoogleCalendarSync#517] opened 2018-04-23 17:21 UTC
Sync breaks:

Sync version: 2.7.3.0
Sync started at 4/23/2018 1:14:19 PM
Syncing from 4/22/2018 to 5/24/2018
Outlook → Google
Operation aborted 

[de-ided.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1939324/de-ided.log)

----

The following started happening about 10 days ago. I believe a Microsoft update was installed.

**Installed or Portable**: Installed

**Problem Description**  
```
2018-04-23 13:09:32,470 DEBUG  18 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Adding listener for Explorer 'Inbox - ********@**********.com - Outlook'
2018-04-23 13:09:32,501 DEBUG  18 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2018-04-23 13:09:32,501 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ArgumentNullException: Value cannot be null.
Parameter name: source
2018-04-23 13:09:32,501 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2018-04-23 13:09:32,501 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass16_0.<Start>b__0(Object o, DoWorkEventArgs args)
2018-04-23 13:09:32,501 ERROR  18 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null.
2018-04-23 13:09:32,501 ERROR  18 OutlookGoogleCalendarSync.Console [0] -  Parameter name: source
2018-04-23 13:09:35,057 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
```

**Steps to Reproduce the Issue**  
1. Installed 2.7.3, also tested w 2.6.6 - same behavior. (After it worked smoothly for month since some 2.6.x version)

**Any other information**  
I think this was broken by an Outlook/Exchange update....

**Comment by phw198** [comment] 2018-04-23 21:42
The log file you uploaded seems to be truncated? Could you try providing it again?

**Comment by 0schr0eder** [comment] 2018-04-23 23:26
I deleted the previous log and restarted OGCS.
Log (175 lines) and screenshot attached.

Thank you for your response!

Olaf

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1940344/OGcalsync.log)
![fail](https://user-images.githubusercontent.com/16760613/39158170-7e29bb9e-472c-11e8-9fd9-64d911ce2f52.png)

**Comment by phw198** [comment] 2018-05-12 18:09
Hi @0schr0eder 

Is this still a problem? I've been scratching my head over it and can't see where the issue is. My suspicion is the line `OutlookItems.Restrict(filter)` in `FilterCalendarEntries()` - which is an MS API function, so maybe a bug has been introduced?

What exact build of Outlook are you running? v1803 build 9126.**2152** [released on April 11](https://support.office.com/en-us/article/version-and-build-numbers-of-update-channel-releases-ae942449-1fca-4484-898b-a933ea23def7?ui=en-US&rs=en-US&ad=US#bkmk_byversion) and is on the Monthly Channel, so with any luck you've picked up a bug that will be/has been resolved in May.

If it is still a problem, could you up the logging level to `FINE` and reproduce the problem so I can see more closely where it's failing?

Thanks!

**Comment by 0schr0eder** [comment] 2018-05-12 21:49
Hey Paul,

So - it was still occurring last week and that's why I had turned it off. Just set the log level to fine and now it works all the sudden .....?!
It's not the log level - set it back to debug and it still works. Rather I think it's the timing (another MS update that fixed this issue?)
I am running version 1804 9226.2114 Click to run monthly channel. You can close and I will use and monitor it.

Thank you for your support!

Olaf

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by phw198** [comment] 2018-05-12 22:49
Glad it's working again! Looks like v1804 build 9226.2114 came out on 25 April, so I guess you picked that up in the last few days and it was indeed a MS bug - the dangers of being on the monthly channel :wink:

**Closed as completed** 2018-05-12 22:50 UTC
