### ISSUE TITLE
Crashes after latest update

### ISSUE THREAD

**Issue by HeavyG603** [phw198/OutlookGoogleCalendarSync#798] opened 2019-08-08 15:39 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: 2.8.1.0
**Installed or Portable**: Installed

**Problem Description**  
\<Crashes on load>

**Steps to Reproduce the Issue**  
1. \<Run after updating>
1. 

**Any other information**  
\<Update here
![image](https://user-images.githubusercontent.com/37811026/62716845-d33f7c00-b9d0-11e9-9f60-bbb2d61b059b.png)
>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3482531/OGcalsync.log)

**Comment by phw198** [comment] 2019-08-08 16:06
Duplicate of #793 - which has a hotfix posted.

**Closed as completed** 2019-08-08 16:06 UTC
Labels: duplicate
