### ISSUE TITLE
Latest (preview) version of Outlook does not seem to be supported

### ISSUE THREAD

**Issue by x3n0n10** [phw198/OutlookGoogleCalendarSync#1641] opened 2023-05-04 09:17 UTC
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.7.0 
**Edition**: Installed  
**Sync Direction**: O->G

**Bug Description**  
A preview version of Outlook recently became available to enable using a toggle in the top-right of Outlook. This upgrades the application to the following versions:
Outlook v1.2023.425.600 (Production)
Client v20230421002.16

Starting OGCS after upgrading Outlook seems unresponsive, until after a couple of minutes when a message box appears saying Outlook has been unresponsive. Even though it seems to work just fine.

**Steps to Reproduce the Issue**  
1. Exit OGCS
2. Upgrade Outlook using the 'New Outlook' toggle in the top-right corner
3. Switch to the new version when it has finished downloading (by clicking the 'Switch' button)
4. Make sure all mailboxes are accessible again (I had to go through 2FA again)
5. Start OGCS and wait until the mentioned 'unresponsive' message box appears

**Any other information**  
Any additional information that may help troubleshoot the issue.  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11395779/OGcalsync.log)

**Comment by phw198** [comment] 2023-05-06 13:18
Duplicate of #1640

**Closed as completed** 2023-05-06 13:19 UTC
Labels: bug, duplicate
