### ISSUE TITLE
Syncing frequency not seeming to push

### ISSUE THREAD

**Issue by aabarbee** [phw198/OutlookGoogleCalendarSync#504] opened 2018-03-27 05:45 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<I cannot determine how often the Push is happening.>

**Steps to Reproduce the Issue**  
1. \<I listed my settings below, but I created test appointments, and until I opened the desktop app, and manually hit the "Sync" button, the appointment would not populate from Outlook into Google calendar>
1. 

**Any other information**  
\<I chose the following settings, "Push Outlook changes immediately", "Start on Login with 0 seconds", "Start in tray", "X minimizes application not closes application.>

**Comment by phw198** [comment] 2018-03-27 07:20
This is likely to be a duplicate of issue #496 which has a hotfix posted (pending confirmation it works).

**Closed as completed** 2018-03-27 07:20 UTC
Labels: duplicate

**Comment by aabarbee** [comment] 2018-03-27 18:26
Thank you again Paul.  @phw198 
I have one quick question - Outlook is now "pushing" but how often will Google calendar push to outlook?  There's no setting for "Google Push" that I can see, and if Push isnt possible, I want to know if I need to push the Sync Button in OGCS every time, or if there's another way.  
Best,
Mandy

**Comment by phw198** [comment] 2018-03-27 18:52
So the hotfix on #496 works?

It's not technically possible to push from Google, but if you have two way sync then whenever a change happens in Outlook, it will sync from Google to Outlook afterwards.

Alternatively, you'd need to and/or configure a scheduled sync.

**Comment by aabarbee** [comment] 2018-03-28 02:11
@phw198 It all seems to be working - thank you again!  May I just ask if you can point me how to configure a scheduled sync for the future?  Much appreciate the help! - Mandy

**Comment by aabarbee** [comment] 2018-03-28 04:47
@phw198  It's only working intermittently :(  I waited a few hours tonight for something to sync from outlook to google, and it didnt.  When I pushed Sync button, it synced right away

**Comment by phw198** [comment] 2018-03-28 07:27
Please post updates regarding Push hotfix to #496 - #504 has been closed as a duplicate.

Scheduled syncs are configured by setting an interval greater than zero. Press F1 for full documentation.
