### ISSUE TITLE
Alternate Mailbox will not keep setting

### ISSUE THREAD

**Issue by briancole25** [phw198/OutlookGoogleCalendarSync#621] opened 2018-10-22 15:23 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Alternate Mailbox will not keep my setting>

**Steps to Reproduce the Issue**  
1. \<Click Settings Tab>
2.  Click Alternate mailbox
3.  Use pull down to select the mailbox I want to sync to
4.  Click Save
5.  Exit out of program(Outlook Google Calendar Sync) completely
6.  Reopen Outlook Google Calendar Sync
7.  Click on settings Tab - now it shows different mailbox - usually archive
8.  Is there a way to force that in the setup.XML?

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-10-27 23:50
Thanks for reporting, though it looks like a duplicate of issue #611, which now has a hotfix posted if you would like to test that.

**Closed as completed by phw198** 2018-10-27 23:50 UTC
Labels: duplicate
