### ISSUE TITLE
Failure to delete exception to recurring event 

### ISSUE THREAD

**Issue by galexmay** [phw198/OutlookGoogleCalendarSync#1753] opened 2023-12-13 14:24 UTC
**OGCS Version**: v2.10.0.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
I have deleted an event as an exception to a recurring event. The deletion was carried out in Google calendar but is not replicating/deleting on my Outlook calendar. 

**Steps to Reproduce the Issue**  
1. Create a recurring event in the Google calendar
2. Sync the event to Outlook calendar
3. Delete one occurrence of the recurring event in the Google calendar
4. Sync the calendars and note that the event is not deleted from the Google calendar

Attached are my log file and the ics renamed in a zip as the ics raw would not upload.
[Jazz Jam.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13661733/Jazz.Jam.zip)
[231213 OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13661734/231213.OGcalsync.log)

**Comment by ghnogueira** [comment] 2023-12-13 15:18
Same issue here.

**Comment by phw198** [comment] 2023-12-17 19:15
Likely a duplicate of #1653 and fixed long ago.

**Comment by galexmay** [comment] 2023-12-17 19:23
![20231217_192249](https://github.com/phw198/OutlookGoogleCalendarSync/assets/16396594/e74b8ffa-d6ef-4513-b6f7-6939bf58ddf0)

WTF! According to OGCS, I am running the latest version.

**Comment by phw198** [comment] 2023-12-17 22:33
At the top of the issue template when raising a bug, as well as the [guidance](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#found-a-bug) for reporting a bug, request issues are reproduced on the latest alpha release.

If you can indeed reproduce the issue on the latest alpha, this issue can be reopened.

**Comment by ghnogueira** [comment] 2023-12-22 13:37
Hi Paul. I'm using the latest alpha release (2.10.1) and the issue sadly remains. Tthe steps described by galexmay are perfect. I have several recurring events on Google which I have deleted singular ocurrences there, but my Outlook calendar still shows those appointments.

**Comment by ghnogueira** [comment] 2023-12-22 13:40
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/13752866/OGcalsync.log)

I hope it helps

**Comment by phw198** [comment] 2023-12-22 21:06
@ghnogueira Thanks for the log, but can you give me a clue on the name and time of series that has the deleted occurrence and the date of that occurrence?

> I'm using the latest alpha release (2.10.1)

No, when you checked, it actually said "Failed to check for ZIP release." - which is because GitHub changed how they present their pages which broke the mechanism.

:arrow_double_up: Please manually upgrade to the latest release, [v2.10.2.0](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.10.2-alpha/Setup.exe), though issue #1653 was resolved in v2.10.1 and that was for O->G also.

**Comment by phw198** [comment] 2023-12-22 23:03
Yep OK, I've traced the issue [back to a hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1593#issuecomment-1474868477) in v2.9.6.4.

:package: This should now be resolved with [hotfix v2.10.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13757228/v2.10.2.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by galexmay** [comment] 2023-12-23 16:47
Windows claims the hotfix link above contains a virus. How can I be sure
that it doesn't?

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/16396594/66686031-2c59-4341-944c-ed2826e0a9e1)

**Comment by phw198** [comment] 2023-12-23 19:58
Well the entire code base is open source and It would be rather self defeating to openly publish infected software. But there's no accounting for antivirus false positives.

Code signing it may help - I'll see if I can do that in a bit...

:package: [Now signed v2.10.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13760178/v2.10.2.12.zip) - see if that helps at all.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `37DEB209` Exe = `2D0BEECB`

**Comment by galexmay** [comment] 2023-12-24 10:24
How do we know that it is a false positive?
I'm not suggesting you would have deliberately published infected software,
but how do we know that it hasn't become infected?

**Comment by phw198** [comment] 2023-12-24 19:55
Well that's what code signing should prove - that it's not been tampered with since it was published. Are you saying the signed version of the hotfix is also being reported?

If I didn't publish it infected, and your computer isn't infected, that would just leave GitHub servers as infected which is rather unlikely. Much more likely that your antivirus (MS Defender?) heuristics can't distinguish between genuine software programmatically connecting to Outlook mailbox accounts to sync calendar data and bad-actor software mining for email addresses and the like.... 

The executable [CRC](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs) before I uploaded it is: `2D0BEECB` - you can compare yours.

**Comment by galexmay** [comment] 2023-12-25 06:38
As your post previously said "I'll see if I can do that in a bit", I didn't realise that you had already posted the signed code. I didn't get another notification of the edit.
Signing the code did solve the virus quarantine problem and I've tested the hotfix and it works.
Thanks

**Comment by ghnogueira** [comment] 2023-12-26 12:04
> Yep OK, I've traced the issue [back to a hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1593#issuecomment-1474868477) in v2.9.6.4.
> 
> 📦 This should now be resolved with [hotfix v2.10.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13757228/v2.10.2.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> 
> Please let me know how it goes.

:)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/66975674/e8cd70f0-1071-4dc2-8455-4af9e3de146f)

I don't know if these were all within the timespan, but it seems it got solved. I'll keep monitoring.

Thanks a lot as always, Paul!

**Comment by jezzaaa** [comment] 2024-01-05 03:47
In case it helps anyone else, this fixed my issue when syncing O->G. Thanks @phw198!

That reminds me, it's about time I clicked on that Donate button again.

**Comment by phw198** [comment] 2024-01-05 08:07
Thanks for confirming and the donation @jezzaaa 😊

**Comment by ghnogueira** [comment] 2024-01-08 17:49
> Yep OK, I've traced the issue [back to a hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1593#issuecomment-1474868477) in v2.9.6.4.
> 
> 📦 This should now be resolved with [hotfix v2.10.2.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/13757228/v2.10.2.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> 
> Please let me know how it goes.

Long due, but just dropped a small donation, @phw198... sadly not enough to hide splashscreen or to be the size of your contribution to my daily life with this app, but it was as much as the BRL->GBP exchange rate allows me. Thanks a lot as always!

**Comment by phw198** [comment] 2024-01-21 12:55
Any and all amounts are appreciated @ghnogueira - thanks so much! 🙂

**Comment by ghnogueira** [comment] 2024-01-21 13:47
Your work is unbelieavable!

**Closed as completed** 2024-01-21 17:41 UTC
Labels: bug, recurring appointment, resolved
