### ISSUE TITLE
Config XML File Profile Save and Load

### ISSUE THREAD

**Issue by doubled136** [phw198/OutlookGoogleCalendarSync#1202] opened 2021-04-02 17:14 UTC
I have a few different Sync workflows (copying items between different calendars), so it would be nice to have a Save/Load feature with a Dropdown to select different XML config files to streamline the action.

Other options currently are to manually change settings for each sync or to rename config files to change "Profiles" manually.

This is fairly low priority overall.  Thank you again!

**Comment by phw198** [comment] 2021-04-18 19:42
This is really a duplicate of #165 for syncing multiple calendars and configuration profiles.

Until development of that is completed, have a read through that issue as you could achieve them same by running multiple instances of OGCS each with their own XML config file.

**Closed as completed by phw198** 2021-04-18 19:42 UTC
Labels: duplicate, enhancement
