### ISSUE TITLE
Outlook-Google reoccurring meetings out of sync (x hours earlier/later)

### ISSUE THREAD

**Issue by redespace** [phw198/OutlookGoogleCalendarSync#1019] opened 2020-06-23 12:08 UTC
I am having the same issue :( My Outlook calendar shows correct times, but in Google it shows 1 hour earlier :S 
Both my Windows and Outlook show UTC+1 and my Google Calendar also shows correct time zone (GMT+2).

This seems to be affecting only reoccurring meetings for some reason.
Please help!

_Originally posted by @redespace in https://github.com/phw198/OutlookGoogleCalendarSync/issues/713#issuecomment-648102553_

**Comment by phw198** [comment] 2020-06-23 20:38
I can't help if you do not [follow the guidance](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#submitting-an-issue) for submitting a bug - namely ensuring you are running the latest alpha, have reproduced the problem and then submitted your `OGcalsync.log` file.

**Comment by redespace** [comment] 2020-06-24 12:52
@phw198 Sorry my bad. Wasn't aware of the needed info.
1. Running version 2.8.0.0
2. Nothing I did. Reocurring meetings have always been copied in the wrong time slot
3. Yes, it is reproducible. 
4. https://gist.github.com/redespace/18435724ae7dddbedcf3f083c16cdf0b

Example: "AAA Meeting" is a recurring event that starts a 15:00 (CET) but Google shows 14:00.
Hope it helps

**Comment by phw198** [comment] 2020-06-25 22:57
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by [downloading the latest version directly from the project website](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.4-alpha).

You should find the issue is fixed with that release - probably easiest to delete the item(s) with the issue in Google and let OGCS re-create it. Once confirmed resolved, also can force a full sync my pressing `Shift`+clicking `Sync`.

**Closed as completed** 2020-08-17 22:34 UTC
Labels: dormant, old release
