### ISSUE TITLE
unable to update existing entries in outlook

### ISSUE THREAD

**Issue by amandus88** [phw198/OutlookGoogleCalendarSync#750] opened 2019-06-05 11:22 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>unable to update existing entries in outlook

**Steps to Reproduce the Issue**  
1. \<Update>
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3256908/OGcalsync.log)

1. 

**Any other information**  
\<Update here>

**Comment by mliebe** [comment] 2019-06-05 15:32
Same issue, which first started showing up yesterday under V 2.7.0.  Updated to V 2.8.0, but issue remains.  Did delete recurring event that was shown in warning in 2.8.0, but that did NOT fix the issue.   After deletion of the offending recurring event, that even WAS created by OGCS, but after the "comparing entries" notice came up, system crashed (see screen shot
![systemcrash20190605](https://user-images.githubusercontent.com/13685550/58969306-5859ab00-876c-11e9-814e-a14bcfac9a80.jpg)

Also including synclog.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3257864/OGcalsync.log)

**Comment by Tjw4020** [comment] 2019-06-05 15:43
Similar issues.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3257913/OGcalsync.log)
![image](https://user-images.githubusercontent.com/51413642/58970304-2c97ee80-8787-11e9-80b6-b0bcddc1f47e.png)

**Comment by amandus88** [comment] 2019-06-05 16:33
I have The same message

**Comment by mliebe** [comment] 2019-06-07 16:32
Even though I am still getting the same error message as before when I run the app, it looks like (at least most) of the entries are still somehow making it up to Google from Outlook.    Given the error message and what it implies, I'm not sure why that's happening, but as long as I simply ignore the error message (for now) my NEW Outlook entries are making it up.   I'll do further investigation as to other behavior.  Thank you.

**Comment by phw198** [comment] 2019-06-09 15:15
@amandus88 There is a problem with trying to create an exception on 15-Sep-2019 to your recurring series in Outlook for "Landbouwweekend middelkerke". Please could you increase the logging level to `FINE`, reproduce the problem and then resubmit your `OGcalsync.log` file?

**Comment by phw198** [comment] 2019-06-09 15:23
@mliebe Not the same error at all. "The RPC server is unavailable" normally indicates Outlook was closed in the middle of OGCS running a sync. Solution would be to not close Outlook.

_(Enhancement developed under #754)_

**Comment by amandus88** [comment] 2019-06-11 07:51
I have changed the logging lvel to fine and still the same problem. Than I hav dleted the agenda item on the 15 sept and put it again in the calendar and now everything is working fine

**Comment by phw198** [comment] 2019-06-16 12:58
@amandus88 Glad you worked around the issue, but that won't help me fix the underlying problem so others don't encounter it. Do you still have the logfile covering the error after you had turned on logging to `FINE`? It will probably be in a file called `OGcalsync.log.2019-06-11`.

Thanks

**Comment by amandus88** [comment] 2019-06-18 16:39
I made a log file this evening because I have still a problem. I made the log file with level fine
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3302523/OGcalsync.log)

**Comment by phw198** [comment] 2019-06-18 16:44
@amandus88 Er, I think that's just because [Google Calendar is currently down](https://twitter.com/OGcalsync/status/1140992051019952128)!

Updates can be found [here](https://www.google.com/appsstatus#hl=en-GB&v=issue&sid=2&iid=cc21ebe3962430b2e4ae2b52e3dde98f).

**Comment by Tjw4020** [comment] 2019-06-24 19:07
I have attached todays log file of error.

 

 

Tom Whalen

Email: tjwbear@gmail.com

Cell:    +1.412.780.7592

 

“Silence in the face of evil is itself evil. Not to speak is to speak.  Not to act is to act.” Dietrich Bonhoeffer.

**Comment by phw198** [comment] 2019-06-25 17:57
@Tjw4020 No you haven't...

:paperclips: Files can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

**Comment by mliebe** [comment] 2019-06-25 18:30
> @mliebe Not the same error at all. "The RPC server is unavailable" normally indicates Outlook was closed in the middle of OGCS running a sync. Solution would be to not close Outlook.
> 
> _(Enhancement developed under #754)_

Outlook did not appear to close (and no user intervention was done to close it either).  Outlook remained open before, during, and after OGCS ran.   STILL getting the same error, but entries are still being posted to Google - so as long as I ignore the error message, things seem to be working.

**Comment by phw198** [comment] 2019-07-06 21:35
@mliebe As I said, #754 has a change that may help the issue you are seeing - I've just posted a development build for that, if you want to try it.

@Tjw4020 Issue #766 is reporting the same as you were (if that's what your later log file was about too).

As @amandus88's original issue has been worked around, this ticket will be closed.

**Closed as completed by phw198** 2019-07-06 21:35 UTC
Labels: more info needed
