### ISSUE TITLE
Sync between three calendars

### ISSUE THREAD

**Issue by scotthosking** [phw198/OutlookGoogleCalendarSync#994] opened 2020-05-17 07:26 UTC
Is it possible to sync between three calendars?

e.g, two Outlook calendars and one Google calendar

**Comment by phw198** [comment] 2020-05-17 15:21
Hi @scott-hosking 

Yes, [with a bit of work](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#syncing-multiple-calendars).

Duplicate of #165

**Closed as completed** 2020-05-17 15:22 UTC
Labels: duplicate, enhancement
