### ISSUE TITLE
Filter Categories values Missing

### ISSUE THREAD

**Issue by FlickLaser** [phw198/OutlookGoogleCalendarSync#975] opened 2020-04-08 12:16 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
Where does the Settings get the available Categories from Outlook in order to filter them?

I can see a couple that are no longer valid in my Outlook, and many categories that I DO use are not listed

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by RealHarlequin** [comment] 2020-05-30 14:02
Also v2.8.0.0
Office 365
I have similar problems except I am finding when sychronising Outlook to Google OGCS removes the colour of items previous to ones currently synchronising.

**Comment by phw198** [comment] 2020-06-26 13:38
OGCS pulls them directly from the mailbox where the categories are stored. You can right-click the list and select "Refresh" if you have made any category changes since starting OGCS.

If you are syncing with an "Alternative mailbox", then I believe some users have reported that it fails to retrieve the categories from there properly...in which case that would be a duplicate of #832

**Closed as completed** 2020-08-17 22:35 UTC
Labels: dormant
