### ISSUE TITLE
Recurring item sync issue

### ISSUE THREAD

**Issue by ABrannen** [phw198/OutlookGoogleCalendarSync#248] opened 2017-06-22 04:29 UTC
After the upgrade to the latest version, I am having a sync error.  Playing with the "days in the future" variable, I've discovered that it is something on August 31 or September 1 that is the issue - it will not sync out past that date (yesterday I could sync 70 days, today only 69, etc).  However, there is no recurring item on those days on either the google or outlook calendars.   I've even removed and recreated any calendar item from August 30-September 2 and it has not changed the error.

Attached is the log where it wouldn't work at 70, did work at 69, and then again didn't work at 70.

Thank you, this program has been a lifesaver!
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1093643/OGcalsync.txt)

**Comment by phw198** [comment] 2017-06-23 23:34
Hi @ABrannen, this issue looks like a duplicate of #234 which has a hotfix posted. If you could also confirm if that resolves your issue, it'd be appreciated.

Cheers!

**Closed as completed** 2017-06-23 23:34 UTC
Labels: duplicate

**Comment by ABrannen** [comment] 2017-06-24 00:27
Confirmed fixed, thank you!
