### ISSUE TITLE
Error log created on daily startup of Outlook with OGCS.

### ISSUE THREAD

**Issue by Veggie352** [phw198/OutlookGoogleCalendarSync#1101] opened 2020-10-20 08:37 UTC
Every day I start Outlook I get an error log created by OGCS which pops up. I have uninstalled OGCS and reinstalled but issue is the same. What can I do to resolve the issue?

I have attached the log.

Thanks

Brian

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5407343/OGcalsync.log)

**Comment by phw198** [comment] 2020-10-25 13:52
The error in your log file is one that is transient, so I wouldn't expect it to occur _every_ day?

Nevertheless, the error reported in your log is a duplicate of #1053, which has a hotfix. Thanks!

**Closed as completed by phw198** 2020-10-25 13:52 UTC
Labels: bug, duplicate

**Comment by Veggie352** [comment] 2020-10-26 00:06
It seems to occur most days but not every day. I have tried to follow the details on the hotfix but it is a level too detailed for my limited computer knowledge. For example, I have tried to follow the instructions but the OAuth consent screen asks to choose between internal or external user type. This was not on the web page instructions so not sure what to choose.

Also looking at the post, I also have to request to you to increase the quota. Is this possible please?

Thanks

**Comment by phw198** [comment] 2020-10-31 18:25
@Veggie352 You can download [v2.8.5 Setup.exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.5-alpha) which contains this hotfix. Not sure what you mean by internal or external user type...

**Comment by Veggie352** [comment] 2020-10-31 21:45
Thanks for the update. The internal or external user type was one of the questions that was asked in the set up.

**Comment by phw198** [comment] 2020-10-31 22:01
Well I assumed that's what you meant yes - just that I've never seen any mention of "internal or external user type" during set up!

![image](https://user-images.githubusercontent.com/11843015/97790870-72e3be00-1bc4-11eb-9d26-1f7426ed54dd.png)
![image](https://user-images.githubusercontent.com/11843015/97790872-7d05bc80-1bc4-11eb-8b99-38ee82a31b80.png)

**Comment by Veggie352** [comment] 2020-10-31 22:34
When I followed the instructions to create my own credentials, this was the screen that appeared, which was not covered by the instructions. I was assuming the response was Internal but did not want to risk it
