### ISSUE TITLE
Errror with recurring event exceptions

### ISSUE THREAD

**Issue by bszathmary** [phw198/OutlookGoogleCalendarSync#444] opened 2018-01-23 22:50 UTC
[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1657901/OGcalsync.zip)
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
\<Errror with recurring event exceptions>

**Steps to Reproduce the Issue**  
\<Not applicable, see log file>

**Any other information**  
\<N/A>

**Comment by phw198** [comment] 2018-01-23 23:32
So if we take the first error listed for `24-Sep-17 (R) => "Geburtstag Ulrike Vogt"`, does that event exist in either Google or Outlook? Is it that the first occurrence of a recurring series has been deleted?

:arrow_double_up: Can you reproduce this problem on the latest alpha? Upgrade by [downloading its `Setup.exe` file](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.5-alpha/Setup.exe) and running it.

**Comment by bszathmary** [comment] 2018-01-24 07:21
Dear Paul,

Thank you very much for your prompt response! I downloaded version 2.6.5.0 and the error is unfortunately still there.

I checked the calendars at it looks like the event you refer to below exists in Outlook but was deleted in Google.

Current log file attached.

Thanks
Balazs

**Comment by phw198** [comment] 2018-01-24 15:42
Yes, the damage (deletion of Google events) is already done in a previous version, so v2.6.5 won't fix that - but hopefully the reason it happened in the first place is now fixed.

To recover the situation, you could either check Deleted Items for that Google calendar and restore them items, and/or [follow the guidance here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#fixing-a-stubborn-calendar-sync-with-full-sync).

**Closed as completed** 2018-12-29 22:28 UTC
