### ISSUE TITLE
Upgrade 2.7.0 to 2.8.0 - settings.xml not created

### ISSUE THREAD

**Issue by KoalaBear84** [phw198/OutlookGoogleCalendarSync#744] opened 2019-06-03 13:19 UTC
**OGCS Version**: v2.8.0
**Installed or Portable**: Installed

**Problem Description**  
It does not start anymore.

**Steps to Reproduce the Issue**  
1. Start it

**Any other information**

The settings.xml is missing, I didn't delete it (myself). I also created and empty settings.xml, then it shows the "reset" dialog, but it does not reset it, it just removes the settings.xml. The software does not create a new settings.xml file.

Also uninstalled it, removed ALL files matching OutlookGoogleCalendarSync, but this did not fix it.

Logfile:
```
2019-06-03 15:08:17,761 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [0] -  Initialising error reporting to OFF
2019-06-03 15:08:17,780 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.0.0
2019-06-03 15:08:17,781 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Started automatically.
2019-06-03 15:08:17,781 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Invoked with arguments: --squirrel-install 2.8.0-beta
2019-06-03 15:08:17,781 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Users\username\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2019-06-03 15:08:17,783 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
2019-06-03 15:08:17,783 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purge complete.
2019-06-03 15:08:17,784 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  No settings.xml file found in C:\Users\username\AppData\Roaming\Outlook Google Calendar Sync
2019-06-03 15:08:22,415 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [0] -  Initialising error reporting to OFF
2019-06-03 15:08:22,437 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.0.0
2019-06-03 15:08:22,437 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Started interactively.
2019-06-03 15:08:22,437 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Invoked with arguments: --squirrel-firstrun
2019-06-03 15:08:22,437 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Users\username\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2019-06-03 15:08:22,438 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
2019-06-03 15:08:22,438 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purge complete.
2019-06-03 15:08:22,439 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  No settings.xml file found in C:\Users\username\AppData\Roaming\Outlook Google Calendar Sync
```

**Comment by phw198** [comment] 2019-06-03 14:59
So does your log file just get stuck at that last line of `No settings.xml file found in`?

If so, the very next thing that should happen is the creation of the `settings.xml` file, so I would imagine there is some kind of lock somewhere that is preventing this happening. You could check Task Manager for any other `outlookgooglecalendarsync.exe` processes, use [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to investigate what's got the lock, or maybe just reboot...

**Comment by KoalaBear84** [comment] 2019-06-03 19:50
Thanks for your comment. Yes, this is the full log, runned it twice.

It does not create the settings.xml at all, it only deletes it. And when run the second time it also does not create one. I didn't thought of rebooting.. But it unfortunately does not fix it. There are no other processes running.

I really have no idea why this is happening. Never had any problems with 2.7.0, but it might not specifically be related to a version. Is there anything we can do with a crash dump file?

**Comment by mulvak** [comment] 2019-06-03 23:47
I've just downloaded and tried to install on two separate Windows 10 Pro/Outlook 2016 64bit machines.  I tried both Install and Portable.  Both give the same log entry below, the setup runs, I see the small splash icon, then nothing.  Just this entry in the log:
```
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.0.0
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Started interactively.
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Invoked with arguments: --squirrel-firstrun
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Users\matt\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purge complete.
2019-06-03 08:25:46,333 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  No settings.xml file found in C:\Users\matt\AppData\Roaming\Outlook Google Calendar Sync
2019-06-03 08:29:36,993 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [0] -  Initialising error reporting to OFF
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.0.0
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Started interactively.
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Users\matt\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purge complete.
2019-06-03 08:29:37,008 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  No settings.xml file found in C:\Users\matt\Desktop\New folder
```
It isn't either finding or creating the settings.xml during install.
```
Event Log App error:
Faulting application name: OutlookGoogleCalendarSync.exe, version: 2.8.0.0, time stamp: 0x5cf2f1fb
Faulting module name: KERNELBASE.dll, version: 10.0.17134.753, time stamp: 0x976ea24c
Exception code: 0xe0434352
Fault offset: 0x00111942
Faulting process id: 0x724c
Faulting application start time: 0x01d51a3969525686
Faulting application path: C:\Users\matt\AppData\Local\OutlookGoogleCalendarSync\app-2.8.0-beta\OutlookGoogleCalendarSync.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 824d0d6b-4d23-4e86-bbdb-a0b67f3c2254
Faulting package full name: 
Faulting package-relative application ID: 

Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32)
   at System.Xml.XmlDownloadManager.GetStream(System.Uri, System.Net.ICredentials, System.Net.IWebProxy, System.Net.Cache.RequestCachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(System.Uri, System.String, System.Type)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(System.String, System.Xml.XmlReaderSettings, System.Xml.XmlParserContext, System.Xml.XmlResolver)
   at System.Xml.XmlReaderSettings.CreateReader(System.String, System.Xml.XmlParserContext)
   at System.Xml.XmlReader.Create(System.String, System.Xml.XmlReaderSettings, System.Xml.XmlParserContext)
   at System.Xml.Linq.XDocument.Load(System.String, System.Xml.Linq.LoadOptions)
   at OutlookGoogleCalendarSync.XMLManager.ExportElement(System.String, System.Object, System.String)
   at OutlookGoogleCalendarSync.Settings.set_Subscribed(System.DateTime)
   at OutlookGoogleCalendarSync.Settings.setDefaults()
   at OutlookGoogleCalendarSync.Settings.get_Instance()
   at OutlookGoogleCalendarSync.Settings.InitialiseConfigFile(System.String, System.String)
   at OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(System.String[])
   at OutlookGoogleCalendarSync.Program.Main(System.String[])
```
Thanks!

**Comment by phw198** [comment] 2019-06-04 06:58
:package: This should now be resolved with [hotfix v2.8.0.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3250913/v2.8.0.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)). 

Please apply this after having installed v2.8.0.0 and it has crashed on start. Let me know how it goes!

**Comment by KoalaBear84** [comment] 2019-06-04 07:36
Great! It works! You can adjust the labels and close the issue.

**Closed as completed** 2019-06-04 10:27 UTC
Labels: bug, high, install/upgrade, resolved

**Comment by phw198** [comment] 2019-06-04 10:33
🙈 Note, I have back-ported this fix into v2.8.0.0 and re-released it.

**Comment by kennym8** [comment] 2019-06-04 18:58
Does this mean I can uninstall and reinstall with the newer version? I downloaded the hotfix, but it is a zip file, I don't have WinZip! What else opens this for free?

**Comment by KoalaBear84** [comment] 2019-06-04 19:08
Windows defaultly has zip support. Right click and "Extract files..".

But you can also download a new copy of the updated 2.8.0 with the hotfix included.

**Comment by kennym8** [comment] 2019-06-04 20:03
OK, thank you! I downloaded the updated app, installed it and configured it and used it! All Looks fine, except: in About, it shows as Version 2.7.0.0. I clicked Check for Update and I get error “unable to check for new version”.  Why?

**Comment by phw198** [comment] 2019-06-04 21:22
@kennym8 Failure to upgrade will be due to issue #497 so you'll need to upgrade manually - download the `Setup.exe` [from here](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.0-beta/Setup.exe) for v2.8. 

I'll also make v2.8 available from the main project website again, now the bug's confirmed fixed.

**Comment by kennym8** [comment] 2019-06-04 22:02
Thank you!
