### ISSUE TITLE
Does not sync a rescheduled meeting

### ISSUE THREAD

**Issue by Frodsh** [phw198/OutlookGoogleCalendarSync#216] opened 2017-05-24 23:45 UTC
Hi, 

I've updated to the latest version, however if a meeting is rescheduled in Outlook, it does not sync that with google, even though the program reports that the sync was successful.

**Comment by phw198** [comment] 2017-05-25 00:02
Not enough information. Has the rescheduled meeting already been synced with Google, just that it's not updating? Is it recurring? Is the whole series rescheduled or just a single occurrence? Are you 2-way syncing?

:page_facing_up: Please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)] and stare which item is not syncing.

You could try forcing a comparison of all items by shift-clicking the Sync button.

**Comment by Frodsh** [comment] 2017-05-25 00:44
Sorry, I wasn't sure how much information you would need.

The meeting has been synced with Google, but it doesn't update to the rescheduled time. It is a one off meeting. I'm also doing 2-way syncing.

I'm not too sure how highlight stuff in a text document, but the meeting is 'SmedTech Action Plan - Status Update' and was originally scheduled for 9am today, but has been resheduled to 9am on June 1. I've had this issue for a number of other meetings in the past few weeks.

I attempted to using the shift-click method, but it changed the meeting in Outlook back to the original time as that is what was in google.

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1027623/OGcalsync.txt)

Thanks for looking into this.

**Comment by phw198** [comment] 2017-06-10 22:40
When you say the meeting has been rescheduled, is this by someone else and you're invited to that meeting? If so, this would be a duplicate of issue #225 - let me know if the hotfix posted there works for you.

**Comment by Frodsh** [comment] 2017-06-12 06:26
Thanks.

I've run the hotfix and I'll let you know how it goes. Just have to wait for someone to reschedule a meeting on me now.

**Comment by phw198** [comment] 2017-08-26 19:27
Can I assume this issue has been resolved?

**Comment by Frodsh** [comment] 2017-08-27 10:40
Sorry, I should have replied a week or so ago when I finally had a reschedule. 

Things are looking good at the moment. Only really had one rescheduled meeting and that worked. But I'll keep an eye on it and let you know if I have any further problems. Until then you can consider this resolved.

Thanks for your help.

**Closed as completed** 2017-10-01 07:45 UTC
Labels: resolved
