### ISSUE TITLE
Outlook "All day" items is not synchronized to Google calendar.

### ISSUE THREAD

**Issue by glerak** [phw198/OutlookGoogleCalendarSync#1165] opened 2021-02-04 09:58 UTC
**OGCS Version**: v2.8.5.0  
**Installed or Portable**: Portable

**Problem Description**  
No "All day" items in Outlook are synchronized with google. They seem invisible to OGCS.

**Steps to Reproduce the Issue**  
1. Add a new item ("AAA" for example) to Outlook with the "All Day" attribute. "Start time" and "End time" are now "0:00" in outlook.
2. This item is invisible to OGCS when you start the synchronization process. No change in reported items from the outlook.

**Any other information**  
The problem is generally with items where "Start time" and "End time" are the same.
Im on Outlook 365 ProPlus. 
~~In v2.8.5 no problems.~~

(I am sorry for my english)

**Comment by phw198** [comment] 2021-02-15 21:40
I don't believe there's any changes in this area between v2.8.5 and v2.8.6 - have you actually tried reverting back to OGCS v2.8.5 and seeing if it starts picking up these all-day appointments? Should be fairly straight forward to do given you are running the portable edition.

I've certainly just tried to replicate the issue on v2.8.6 and cannot; it works fine for me.

**Comment by glerak** [comment] 2021-02-16 08:51
I tested it and its little bit more complicated.

I made new empty callendar in my outlook (OGCS_test).
I used my old empty callendar in google (Deník Gallok).

I made "_test_2.8.5" folder with OGCS 2.8.5 and "_test_2.8.6" folder with 2.8.6.
I set logging level for "All" in both versions.
I deleted all logs in both folders.  
I made synchronization from OGCS 2.8.6 and with 2.8.5. Both the same result (all entries counters are 0).

I made items in outlook (at 16.2.2021 date) - viz IMG_01.png. I'm not able to switch Outlook to english language, sorry about it.
 - "OGCS_1 - simple item"
 - "OGCS_2 - all day item" 
 - "OGCS_3 - recurrency (part of day)" - recurrency is each Tuesday, duration 30min, 3-times repeat.
 - "OGCS_4 - recurrency (all two days)"  - recurrency is each Tuesday, duration 2 days, 3-times repeat.

Well, I'm starting "_test_2.8.5" version. There I see 4 items in Outlook, they are synchronized to outlook (4 items in outlook, 4 items in google).
(!) Next, Synchronization is launched (triggered?)  (still in "_test_2.8.5", without any restart app or so) and the "OGCS_4 - recurrency (all two days)" item is deleted (it was invisible in outlook).
The next Sync from this version (without restart app) is 3 items in outlook, 3 items in google.
I closed "_test_2.8.5" version.
Result is in IMG_02.png and 2.8.5-OGcalsync.log.

I'm launched "_test_2.8.6" version (without any changes in calendars).
Started sync process. App says Outlook 3, Google 3.
I made new item in outlook "OGCS_5 - recurrency (all two days)". Viz IMG_03.png.
Started Sync, app says 4 Outlook Items, 3 Google items. One google item is created.
Next sychronization - 4 Outlook Items, 4 Google items. 

It's not the same as when I wrote the issue :-\ The "simple all day" items is working now for me :-\

Thanks for the application btw.

[2.8.5-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5987230/2.8.5-OGcalsync.log)
[2.8.6-OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5987231/2.8.6-OGcalsync.log)
![IMG_01](https://user-images.githubusercontent.com/4548671/108038808-92034000-703b-11eb-8b11-bb82eca4e88f.png)
![IMG_02](https://user-images.githubusercontent.com/4548671/108038809-929bd680-703b-11eb-9f0e-149fefede999.png)
![IMG_03](https://user-images.githubusercontent.com/4548671/108038811-929bd680-703b-11eb-8529-adf67baa1792.png)

**Comment by phw198** [comment] 2021-02-20 21:23
Thanks for the detailed testing and feedback @glerak. Seems you were getting #1123 on v2.8.5 and have also confirmed the issue is resolved in v2.8.6.

I will close this issue out now.

**Closed as completed by phw198** 2021-02-20 21:23 UTC
Labels: duplicate, old release
