### ISSUE TITLE
Alt+Tab menu shows OGCS open, even though it's minimised to task bar

### ISSUE THREAD

**Issue by cooltobelou** [phw198/OutlookGoogleCalendarSync#1351] opened 2021-11-29 01:22 UTC
**OGCS Version**: v2.9.2.0  
**Installed or Portable**: Portable

**Problem Description**  
Recently the application has started showing up in the Windows Task Switcher (a.k.a the Alt+Tab menu) even when it is minimised to the system tray. This never used to happen, so I'm not sure if this is something Windows has done or an OGCS bug. There isn't a way I've found to stop it appearing in the Alt+Tab menu without fully closing it. Anyway it's not a massive issue, but if there's a way to prevent it showing up when pressing Alt+Tab unless the UI is actually open in a window, I'd love to know.

Application Behaviour options enabled:
Start on login
Start in tray
Minimise to tray instead of taskbar
Close button minimises window instead of terminating application
Make application portable

See screenshot which shows OGCS appearing when pressing alt+tab even though it is minimised to the system tray. There is no real preview of the window shown because it's not really open.

![image](https://user-images.githubusercontent.com/95195673/143794461-1a1b6e8e-ce94-4f43-9216-1626ca26caa6.png)

**Comment by phw198** [comment] 2021-12-02 23:15
Thanks for reporting @cooltobelou However, this is a duplicate of #1343 which should have a hotfix posted.

**Closed as completed by phw198** 2021-12-02 23:15 UTC
Labels: duplicate

**Comment by cooltobelou** [comment] 2021-12-03 00:10
Thanks Paul - working perfectly now!
