### ISSUE TITLE
Version 2.5.0 wants to delete all my recurring appointments from Outlook, why?!

### ISSUE THREAD

**Issue by draeburn** [phw198/OutlookGoogleCalendarSync#230] opened 2017-06-06 15:52 UTC
As the title suggests, as soon as I ran the new version it asked to delete all my recurring appointments. Any ideas how to fix this? It worked fine in previous versions...

Deleting 7 Outlook calendar entries...
Not deleted: 22/07/2016 (R) => "Marc Birthday"
Not deleted: 24/07/2016 (R) => "Mum"
Not deleted: 04/07/2016 (R) => "Eric Astoin Birthday"
Not deleted: 08/11/2016 (R) => "Anita Birthday"
Not deleted: 06/10/2016 (R) => "Hans Birthday"
Not deleted: 28/10/2016 (R) => "Dad Birthday"
Not deleted: 12/03/2017 (R) => "Curt Birthday"
Done.

ps: Very annoying you can't attach log files to this forum any more!

[OGcalsync - Copy.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1055638/OGcalsync.-.Copy.txt)

**Comment by phw198** [comment] 2017-06-06 17:16
It would appear that none of those events still exist in Google. If they do, then their event ID has changed and no longer matches what is held against the Outlook appointment.

If we take the "Mum" appointment, can you confirm if that exists on 24/07/2016? If it does, can you follow the [instructions here](http://googleappstroubleshootinghelp.blogspot.co.uk/2012/09/how-to-find-troubleshooting-information.html) to determine what its ID now is. Outlook currently thinks it is `k0emnitpbepiddidscenkkni8k`.

Once you've confirmed whether these items exist in Google or not, then I can work out a way to resolve this. In fact, it would be helpful if you could turn on the CSV creation and upload them too...

BTW, why are all these people less than a year old? :wink: Was it you that had altered the annual recurring events to within a year to workaround an issue in v2.4.0 that is now fixed?

Yup I don't know why GitHub don't like .log files - I think they're trying to push [using gist](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#posting-your-ogcalsynclog-file) maybe?

**Comment by draeburn** [comment] 2017-06-07 08:53
Hi there, thanks for the speedy reply!

You are correct, none of those recurring appointments exist in Google any more. Even worse, I deleted one in calendar, then recreated it, but OGCS still deletes it! (It was "Susu Raeburn's Birthday", and you can see from the log it attempts to delete it from google).

I have no idea why they show as 1 year old, they are most certainly older than that! :) I have looked at the appointments and they are all set for 50 occurrences. Interestingly I can't select "no end date" for any recurring appointment, which might be a limitation or policy set by the Exchange admins at work.

I have attached the CSV file as you requested...

PS: I also spotted you need to change the link on the "About" tab of OGCS as it still points to Codeplex...just sayin' ;)

PPS: ARRGGHH GitHub doesn't support CSV files either....grrrrr

[CSV and Log file 070617.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1057409/CSV.and.Log.file.070617.zip)

d

**Comment by phw198** [comment] 2017-06-07 12:51
OK, I've marked this as both a bug and an enhancement. A bug because, assuming you didn't manually delete the Google items, it shouldn't have got in to this situation; and an enhancement because the workaround will be to temporarily set it to a 1-way sync from O --> G to recreate the items and then back to 2-way. However, that'll require a little bit of work on my part first.

For the bug, would you be able to provide the log file that covers the deletions?

**Comment by draeburn** [comment] 2017-06-07 21:04
Thanks, and here is the latest log.....

The item deleted called "VGE Engagement Plan" is one where the time was changed from 9.00 to 9.15 and now OGCS wants to delete it, so I'll post the CSV files etc. on issue #225 for you.

[OGcalsync - Copy.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1059313/OGcalsync.-.Copy.txt)

**Comment by phw198** [comment] 2017-06-10 20:47
:package: With [Hotfix-v2.5.0.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1066092/Hotfix-v2.5.0.2.zip) you should now be able to do a one-off 1-way sync from Outlook :arrow_right: Google to recreate your missing items and then switch back to 2-way sync. 

[See instructions for applying hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) - let me know how it goes.

For the deletion with `VGE Engagement Plan`, comparing what you've uploaded on #225 and on the 7 June on this ticket, I can see that part of the Outlook Appointment Entry ID has changed. I think this gives me enough information for a fix! :tada:

**Comment by draeburn** [comment] 2017-06-11 22:23
I think that has fixed it....did the one way, and it re-created the recurring invites, and then a 2-way sync didn't give any errors or deletions....THANKS!!! Will let you know about the meeting change one later. Cheers, d

**Closed as completed** 2017-06-12 14:24 UTC
Labels: bug, enhancement, medium, resolved
