### ISSUE TITLE
Past Meeting Requests in Outlook Copied to Future Dates are Deleted from Outlook and Not Synced to Google

### ISSUE THREAD

**Issue by Lusayalumino** [phw198/OutlookGoogleCalendarSync#946] opened 2020-01-19 00:28 UTC
**OGCS Version**: v2.8.3.0
**Edition**: Installed
**Sync Direction**: O<->G
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4082101/OGcalsync.log)

**Bug Description**
- When copying Meeting Request (in Outlook) from 1/11/2020 to 1/18/2020, during sync, OGCS is trying to delete them from Outlook.
- I have "Confirm Deletions" checked so I tell it no
- Items do not appear in Google

**Steps to Reproduce the Issue**  
- Copy past Meeting Request in Outlook
- Paste on Future Date in Outlook
- SYNC OGCS
- OGCS tries to delete the newly pasted future Outlook Meeting Request
- OGCS does not create the meeting in Google

**Comment by phw198** [comment] 2020-01-25 22:56
Sounds like a duplicate of #924 

Do you have OGCS running when you make a copy of the Outlook appointment?

**Comment by Lusayalumino** [comment] 2020-01-28 00:49
Yes, I did have OGCS running when I was doing that in Outlook.

**Comment by phw198** [comment] 2020-02-01 20:56
Could you shut down Outlook and OGCS and restart them, then repeat the copy-paste test. In your `OGcalsync.log` file it should then show a line `Item paste event caught.`? Can you confirm this happens? (In the logfile you uploaded, it does not include this).

If it does, then it would seem at some point that paste event detection is no longer occurring, and you'll need to figure out what causes that to happen (eg opening a calendar window and then later closing it).

**Comment by Lusayalumino** [comment] 2020-02-09 20:10
Did as you asked, having same problem. Log file attached. Indeed, Item paste event caught is still missing. Any ideas as how to troubleshoot the paste event detection failure?

**Comment by phw198** [comment] 2020-02-09 21:17
:paperclips: Files and screenshots can't be attached to the ticket when replying by email - please log in to GitHub to upload files.

So OGCS doesn't capture any paste event even after straight after a restart of outlook and OGCS?

**Comment by Lusayalumino** [comment] 2020-02-10 21:59
The problem is very intermittent... however, I found a very strange behavior. When I manually create the missing entry in Google and resync, although Google is telling Outlook to delete the Meeting Request -- if I change the category in Outlook, the category and Color change on the entry in Google. So they are connected but OGCS still is trying to delete the Outlook version.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4183252/OGcalsync.log)

**Comment by phw198** [comment] 2020-02-15 15:03
So a paste event was caught, but logged as follows:
```
2020-02-10 12:52:00,855 INFO  19 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Item paste event caught.
2020-02-10 12:52:00,861 DEBUG  19 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  We've got 1 items selected for copy.
2020-02-10 12:52:00,867 DEBUG  19 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  The item is not an appointment item.
```
* Was this the time you did the test cut and paste?
* Are you copy and pasting, cut and pasting, or click and dragging the existing meeting item?
* Is the item a stand alone meeting, or an occurrence of a recurring series?
* What is the name of the meeting you are testing with?

The behaviour you have observed with the categories is what I would expect to see for a recurring series - individual occurrences can't have a separate category assigned, so if you changed the series category in Outlook, every recurring item in Google would update too.

**Comment by Lusayalumino** [comment] 2020-02-15 22:37
Unfortunately, I’m not positive if that was the time I had done it or not.

I CTRL+CLICK&DRAG the appointments / meeting requests to do the Copy / Paste.

They are not reoccurring.

Some Misc Points that May Be Factors:
- There is a ZOOM Webinar URL in the Location Field.

-The meeting requests will have a fair amount of information in the Notes Field (perhaps 1 – 2 paragraphs).

-The only difference between the meeting requests I copy / paste is one character in the title. For example “Conflict Management Coaching with Mike Smith Part A”; “…. Part B”, etc.

 Perhaps on occasion OGCS sees a URL in the Location field and thinks it’s not a meeting?

**Comment by phw198** [comment] 2020-02-16 00:24
Ok, could you repeat the test and check the log file - if there's a line again that says `The item is not an appointment item.` then we might have something to go on...

**Comment by Lusayalumino** [comment] 2020-03-05 12:27
I haven't forgotten about this -- but haven't experienced the error in a while. I'm assuming it's useless to produce a log until the error occurs?

**Comment by phw198** [comment] 2020-03-08 13:39
@Lusayalumino Indeed - only worth uploading the logfile once the issue has presented itself again.

**Comment by swaldman3** [comment] 2020-06-12 10:19
I've been seeing something similar to this - meeting invites that are sent by a particular person in Outlook don't transfer to Google, and on two-way sync they get deleted from Outlook. I'd been baffled as to why it only happened with appointments from this one person, and hence had refrained from reporting - but It seems quite plausible that the person in question is copying old meetings to make the new ones. 

Doing a one-way full sync Outlook->Google fixes it, so long as I catch it before the deletion occurs.

I'll try to remember to capture a log next time.

**Closed as completed** 2021-10-30 08:40 UTC
Labels: bug, more info needed, dormant
