### ISSUE TITLE
Event Creation Fails

### ISSUE THREAD

**Issue by jesseelliott** [phw198/OutlookGoogleCalendarSync#1126] opened 2020-11-19 20:23 UTC
OGCS Version: 2.8.5.0
Edition: Installed
Sync Direction: O<->G

Bug Description:
Every time it syncs, a dialog pops up requiring user input before continuing. I have all confirmations off. The popup is due to an event creation failing (see log), but there is no information provided about which event, so I have no idea how to resolve the issue.

Steps to Reproduce the Issue
1. Click on Sync
[~~OGcalsync.log~~]()

**Comment by eddydee123** [comment] 2020-11-23 14:23
Looks like a dupe of https://github.com/phw198/OutlookGoogleCalendarSync/issues/1123

**Comment by jesseelliott** [comment] 2020-11-25 18:33
No, I've seen that one too. I think this is different.

**Comment by phw198** [comment] 2020-11-29 15:04
@jesseelliott The issue is with an attendee of 
> 11/12/2020 2:00 PM => "FW: Invitation: NKrypt and ICR : Blackjack working group @ Weekly from 4pm to 5pm on Thursday (EDT)
```
2020-11-19 13:14:31,083 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [370] -  Processing >> 11/12/2020 2:00 PM => "FW: Invitation: NKrypt and ICR : Blackjack working group @ Weekly from 4pm to 5pm on Thursday (EDT)"
2020-11-19 13:14:31,084 DEBUG  16 OutlookGoogleCalendarSync.Console [279] -  11/12/2020 2:00 PM  "FW: Invitation: NKrypt and ICR : Blackjack working group @ Weekly from 4pm to 5pm on Thursday (EDT)"
2020-11-19 13:14:31,155 DEBUG  16 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [672] -  Retrieving the meeting organiser's timezone ID.
2020-11-19 13:14:31,156 WARN  16 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [804] -  Could not find timezone ID based on given description. Attempting some fuzzy logic...
2020-11-19 13:14:31,157 DEBUG  16 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [857] -  It appears to be an IANA timezone already!
2020-11-19 13:14:31,305 ERROR  16 OutlookGoogleCalendarSync.Console [277] -  Event creation failed.
2020-11-19 13:14:31,306 ERROR  16 OutlookGoogleCalendarSync.Console [277] -  The item could not be found.
2020-11-19 13:14:31,376 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The item could not be found.
2020-11-19 13:14:31,378 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xF7940201,-141295103; Location: get_PrimarySmtpAddress() in <Unknown File>
2020-11-19 13:14:31,380 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._ExchangeUser.get_PrimarySmtpAddress()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.GetRecipientEmail(Recipient recipient) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 520
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateAttendee(Recipient recipient, Boolean isOrganiser) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 1687
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 411
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 329
```
They apparently are an Exchange user, but have no primary email set - you would need to increase your logging level to `FINE` in order to see which recipient is causing the problem.

:package: However, please try the workaround I have added in for [hotfix v2.8.5.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5612347/v2.8.5.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jesseelliott** [comment] 2020-12-01 20:00
The 2.8.5.10 Hotfix worked like a charm. Great work, thank you!

PS Are you able to strike the sensitive data (like email addresses) from the comments and unattach the log file by chance?

**Closed as completed** 2021-01-23 21:31 UTC
Labels: bug, resolved
