### ISSUE TITLE
Dragging an existing appointment to a new date with data already there occasionally triggers a delete

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#396] opened 2017-11-22 15:55 UTC
Dragging an existing appointment to a new date with data already there occasionally triggers a delete.

And the delete action appears random in itself, as sometimes the appointment being moved via drag is triggered for delete after the move appears to be successful (delete message a couple of minutes later), and other times it is an existing appointment that is in the receiving date of the drag.

Dragging from outlook calendar to same outlook calendar, within same month. 

Using just released 2.6.4.0, although the problem did occur in 2.6.3.0.

**Installed or Portable**: Installed

Problem is not consistent, and not always able to replicate. Not sure what the exact scenario(s) are that cause the invalid delete action to be triggered.

**Comment by phw198** [comment] 2018-12-29 22:49
Duplicate of #487 - click-and-drag is the same as a cut-and-paste action.

**Closed as completed by phw198** 2018-12-29 22:49 UTC
