### ISSUE TITLE
2.7.0 won't start [0x800401F3 (CO_E_CLASSSTRING)]

### ISSUE THREAD

**Issue by erchegyia** [phw198/OutlookGoogleCalendarSync#712] opened 2019-04-09 09:05 UTC
**OGCS Version**: v2.7.0.0 (reproducible on v2.7.8.0)  
**Installed or Portable**: Installed (reproducible with portable)

**Problem Description**  
OGCS won't start
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3058028/OGcalsync.log)

**Steps to Reproduce the Issue**  
1. install 2.7.0
2. Start OGCS
3. Splash screen appears
4. GitHub opens on browser
5. "OGCS Error Encountered" window appears 

**Any other information**  
Happens after migration to a new PC (same application, OS and Outlook version as the previous)

**Comment by phw198** [comment] 2019-04-09 22:20
Basically seems to a bad install of Office which hasn't registered it's DLLs properly.

Mostly you were getting:
`System.Runtime.InteropServices.COMException: Invalid class string (Exception from HRESULT: 0x800401F3 (CO_E_CLASSSTRING))`
with some later occurences of:
`System.Runtime.InteropServices.COMException: Interface not registered (Exception from HRESULT: 0x80040155)`

The [second error is covered here](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80040155---interface-not-registered), but are you saying this resolved through several reboots?

**Comment by phw198** [comment] 2019-05-19 16:05
On review, looks like a duplicate of #679 which has hotfix improvement posted.

**Closed as completed by phw198** 2019-05-19 16:05 UTC
Labels: dll hell
