### ISSUE TITLE
Item deleted when organiser reschedules in Outlook 2016 (2-way sync)

### ISSUE THREAD

**Issue by thelordsmurf** [phw198/OutlookGoogleCalendarSync#225] opened 2017-06-01 18:29 UTC
I'm not sure if this is the same behavior as #224 
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1045714/OGcalsync.log.txt)
, so I'm putting it here and making a new request as well, but I have noticed some meetings that are rescheduled by someone else then getting deleted by the sync process. If an appointment is made by someone else, then they send me an updated time and I accept it, I think that sometimes with a sync it gets deleted. It's quite concerning as I have missed appointments because of this! I'm also on Outlook 2016 and sync 2.4. I don't know if this was happening since I went to 2.4 or Outlook 2016 but those two things happened at near the same time.
Thanks.

**Comment by phw198** [comment] 2017-06-05 23:03
Mainly a note to self: I think this is due to a tightening up of matching items between Outlook and Google in v2.4

**Comment by thelordsmurf** [comment] 2017-06-06 13:50
Not sure if this was supposed to be addressed in 2.5, but I did confirm it on a sync today that at least when someone else reschedules an event in Outlook, sync deletes it entirely from Google calendar, then I think on the next sync it sees it not there on google and deletes it from Outlook. I have turned on confirm deletions and stopped these manually at the moment, if anyone else needs that workaround.
However, when I manually stop deletion, it doesn't add the event back to Google (so every time it asks to delete the event from Outlook).

**Comment by draeburn** [comment] 2017-06-06 16:20
@phw198 @thelordsmurf I have exactly the same issue....was reported on Codeplex so not sure of Github case number.

**Comment by phw198** [comment] 2017-06-06 18:43
@draeburn Found it - issue number #59.

:thought_balloon: Ahhh, issue management is almost a pleasure on GitHub. Compared to CodePlex anyway...

**Comment by draeburn** [comment] 2017-06-07 21:07
Here are the CSV files, as the appointment "VGE Engagement Plan" was changed by the organiser from 9.00 to 9.15 and OGCS asked to delete the 9.00 appointment from Google (I allowed it to), and then on the next sync tried to delete the 9.15 from Outlook. Any ideas?

You now have two sets of CSV's I've uploaded, before and after this error which hopefully will allow you to compare?

cheers
d

[Outlook Google Calendar Sync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1059323/Outlook.Google.Calendar.Sync.zip)

**Comment by phw198** [comment] 2017-06-10 21:29
Awesome, thanks @draeburn. As posted on your other issue, a section of the Outlook EntryID is changing, but I think we can ignore this part of the ID without causing additional problems.

:package: This should now be resolved with [Hotfix-v2.5.0.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1066125/Hotfix-v2.5.0.3.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes!

**Comment by draeburn** [comment] 2017-06-11 22:19
thanks, will let you know on this one....

**Comment by phw198** [comment] 2017-06-24 01:18
So have you guys had a meeting rescheduled since the hotfix? Do we think the issue is resolved?

**Comment by draeburn** [comment] 2017-06-24 08:18
Yes! Sorry, I should have got back to you, but all appears to be working well....many thanks!

**Comment by thelordsmurf** [comment] 2017-06-24 15:59
I'll do a test and try again, but at the moment it does keep asking to delete things that were deleted from the google cal previously as I reported above.

**Comment by phw198** [comment] 2017-07-08 20:47
@davidarduini yes, looks like a different issue - could you raise a new issue ticket for investigation separately?

**Closed as completed** 2017-07-08 20:47 UTC
Labels: bug, medium, resolved
