### ISSUE TITLE
Sync fails after upgrade to 2.8.7.0

### ISSUE THREAD

**Issue by DannyBeanz** [phw198/OutlookGoogleCalendarSync#1218] opened 2021-05-10 08:34 UTC
----

**OGCS Version**: v2.8.7.0 alpha
**Installed or Portable**: Portable

**Problem Description**  
Updated standalon OGCS to latest 2.8.7.0 alpha release, and it cannot connect to Outlook at all.  Receive the error "Object reference not set to an instance of an object." regardless of Outlook being open, opened before OGCS or opened after OGCS.

**Steps to Reproduce the Issue**  
1. Upgrade
2. Perform sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6450650/OGcalsync.log)

**Comment by salvadofamily** [comment] 2021-05-10 10:19
Apologies if I am putting this in the wrong place, I'm new to github. I get what seems to be the same error but was getting the same error on 2.8.7 before upgrading.

attachment --> [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6451312/OGcalsync.log)

Get error in synch window:
Unable to update existing entries in the Google calendar.
Object reference not set to an instance of an object.

**Comment by cfeuer** [comment] 2021-05-10 11:14
Same for me:

OGCS Version: v2.8.7.0 alpha
Installed or Portable: Installed

Problem Description
Updated standalon OGCS to latest 2.8.7.0 alpha release, and it cannot connect to Outlook at all. Receive the error "Object reference not set to an instance of an object." regardless of Outlook being open, opened before OGCS or opened after OGCS.

Steps to Reproduce the Issue

Upgrade
Perform sync

Logfile: 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6451605/OGcalsync.log)

**Comment by MasterKantok** [comment] 2021-05-10 12:27
I have the same issue after upgrading to 2.7.8.0 alpha
 "Object reference not set to an instance of an object." regardless of Outlook being open, opened before OGCS or opened after OGCS.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6451971/OGcalsync.log)

**Comment by phw198** [comment] 2021-05-10 14:54
:package: Thanks for reporting! This should now be resolved with [v2.8.7.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6452972/v2.8.7.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by cfeuer** [comment] 2021-05-10 15:15
> 📦 Thanks for reporting! This should now be resolved with [v2.8.7.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6452972/v2.8.7.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
> 
> Please let me know how it goes.

Works for me! Thank you!

**Comment by jmathis0517** [comment] 2021-05-10 15:51
v2.8.7.1.zip works for me. Thanks

**Closed as completed** 2021-05-10 21:20 UTC
Labels: bug, resolved

**Comment by phw198** [comment] 2021-05-10 21:30
This has now been back-ported and re-released as v2.8.7.0.

**Comment by MasterKantok** [comment] 2021-05-11 06:49
Works for me 
Thank you :-)
