### ISSUE TITLE
Execption on UNTIL on recurring event

### ISSUE THREAD

**Issue by jorgenbosman** [phw198/OutlookGoogleCalendarSync#907] opened 2019-11-27 12:39 UTC
I got an exception when syncing google -> outlook. It seems that thhe code in Recurrence.cs/buildOutlookPattern has changed in the latest version 2.8.2 alpha from yyyyMMdd to yyyyMMddTHHmmssZ. However I'm getting yyyyMMdd in the UNTIL part, so parseExact won't work

 DateTime endDate = DateTime.ParseExact(ruleBook["UNTIL"], "yyyyMMddTHHmmssZ", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.AdjustToUniversal);

<details><summary>Log:</summary>

```
2019-11-27 13:31:07,053 DEBUG  16 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 23/08/2009 (R) => "Thys Gustaaf's Birthday"
2019-11-27 13:31:07,080 FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Start Timezone
2019-11-27 13:31:07,080 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: Romance Standard Time
2019-11-27 13:31:07,080 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: Romance Standard Time
2019-11-27 13:31:07,080 FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing End Timezone
2019-11-27 13:31:07,080 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: Romance Standard Time
2019-11-27 13:31:07,080 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: Romance Standard Time
2019-11-27 13:31:07,082 FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Start time
2019-11-27 13:31:07,083 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 23/08/2009 0:00:00
2019-11-27 13:31:07,083 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 23/08/2009 0:00:00
2019-11-27 13:31:07,084 FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing End time
2019-11-27 13:31:07,084 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 24/08/2009 0:00:00
2019-11-27 13:31:07,084 ULTRA-FINE  16 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 24/08/2009 0:00:00
2019-11-27 13:31:07,088 FINE  16 OutlookGoogleCalendarSync.Recurrence [0] -  Building a temporary recurrent Appointment generated from Event
2019-11-27 13:31:07,099 FINE  16 OutlookGoogleCalendarSync.Recurrence [0] -  Analysing Event RRULEs...
2019-11-27 13:31:07,099 DEBUG  16 OutlookGoogleCalendarSync.Recurrence [0] -  Converting RRULE:FREQ=YEARLY;UNTIL=**20190822**
2019-11-27 13:31:07,099 FINE  16 OutlookGoogleCalendarSync.Recurrence [0] -  Building Outlook recurrence pattern
2019-11-27 13:31:07,116 ERROR  16 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
2019-11-27 13:31:07,117 ERROR  16 OutlookGoogleCalendarSync.Console [0] -  String was not recognized as a valid DateTime.
2019-11-27 13:31:07,186 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  System.FormatException: String was not recognized as a valid DateTime.
2019-11-27 13:31:07,186 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131537;-2146233033
2019-11-27 13:31:07,186 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console navigating.
2019-11-27 13:31:07,186 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at OutlookGoogleCalendarSync.Recurrence.buildOutlookPattern(Event ev, AppointmentItem ai, RecurrencePattern& oPattern)
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
```
</details>

**Comment by phw198** [comment] 2019-11-27 22:38
Duplicate of #870 which has a hotfix posted.

**Closed as completed by phw198** 2019-11-27 22:38 UTC
Labels: duplicate
