### ISSUE TITLE
Fails to sync properly when outlook appointments created via copy/paste

### ISSUE THREAD

**Issue by SuperDuperCoach** [phw198/OutlookGoogleCalendarSync#390] opened 2017-11-13 20:31 UTC
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**
I have a simple setup of one local outlook calendar syncing to my central google calendar.
I create a lot of appointments in Outlook by copying a previous appointment and pasting (say, to a few weeks later than the original appointment).
When I do so, on the next sync, these outlook appointments created through the copy-paste are not replicated into the google calendar. Then on the next sync after that, the outlook calendar appointments created through the copy-paste are deleted!
[Note that I have no opportunity to use the “recurring” appointment feature of outlook as there is not sufficient regularity to the appointments. Also note I use copy-paste rather than re-type new appointments each time because it is much faster and less cumbersome, given there is quite a bit of info in each appointment]
**Steps to Reproduce the Issue**  
Set up a sync from a local outlook to a central google
In outlook, take an existing appointment, copy it with cntrl-c, go to the next week, replicate it with cntrl-v, edit the new entry just to make sure it looks right, or make some changes (doesn’t affect the problem), save it.
Make a sync happen.
Make another sync happen.
Voila – pasted appointment in outlook is gone

**Any other information**  
.

**Comment by phw198** [comment] 2017-11-13 21:03
Hi @SuperDuperCoach - that's a duplicate of #224 and fixed in v2.6.3

**Closed as completed** 2018-01-02 18:34 UTC
Labels: duplicate
