### ISSUE TITLE
Start and end times must either both be date or both be dateTime.

### ISSUE THREAD

**Issue by michgal2k** [phw198/OutlookGoogleCalendarSync#844] opened 2019-09-15 21:23 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  Failure to sync
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3614288/OGcalsync.log)

\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by michgal2k** [comment] 2019-09-21 01:30
Just curious - still having the same issue.  Please help me get my life synced.

Did NOT mean to close issue....how do we reopen?

**Comment by michgal2k** [comment] 2019-09-21 01:32
Above issue closed in error

**Comment by michgal2k** [comment] 2019-09-21 14:40
Here is todays logfile - same issues. Please help
[OGcalsync 0921.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3638769/OGcalsync.0921.txt)

**Comment by michgal2k** [comment] 2019-09-27 01:48
HI Paul -While waiting for you to reply - I installed the Alpha release  2.8.1 and tried the scan again.  I am getting the same error and do not know how to fix it.  Please help me!!!

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3660524/OGcalsync.log)

**Comment by phw198** [comment] 2019-09-28 18:21
Looks like there's a problem with the "Detroit" calendar entry.

:package: Could you apply [2.8.1.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3665856/2.8.1.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)), reproduce the error and then upload your log file again?

Thanks

**Comment by michgal2k** [comment] 2019-09-28 20:16
I am getting the same error message with the alpha build.  Please reopen

**Comment by phw198** [comment] 2019-09-29 20:23
Basic comprehension is failing you. I never said it was fixed, I said "reproduce the error and then upload your log file again". Without your logfile I cannot progress this issue further.

**Comment by michgal2k** [comment] 2019-09-29 20:26
OK- got me there!!!  It’s been a tough few weeks!!!!  I apologize.

I deleted the Detroit post and it works now.  Since it was in the past – I am not going to worry about it.

Love your product – keep up the good work.

Sorry to be flighty

**Comment by phw198** [comment] 2019-09-29 20:34
OK, but that means I can't provide a fix to stop it happening again, or prevent others encountering it. Would be appreciated if you can upload your logfile from when you tried v2.8.1.11 yesterday (remember you have to log in to GitHub to upload files).

**Comment by michgal2k** [comment] 2019-09-29 22:00
Since I deleted the offending item - OGCS has been run since.  I no longer have a logfile with the error,  Sorry Will not let that happen again

**Comment by phw198** [comment] 2019-11-11 23:33
:package: Hotfix applied onto v2.8.2.0 - [v2.8.2.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3833597/v2.8.2.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by phw198** [comment] 2019-12-02 01:03
Update on behalf of a user running v2.8.2.9:
```
2019-12-01 14:33:44,130 INFO  10 OutlookGoogleCalendarSync.Console [0] -  Comparing 56 existing Google calendar entries
2019-12-01 14:33:44,942 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -  12/31/2019 12:00 AM (R) => "ISACA Dues Drop Dead date"
2019-12-01 14:33:44,943 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 1 exceptions that will now be iteratively compared.
2019-12-01 14:33:45,014 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for Outlook exception:-
2019-12-01 14:33:45,015 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 31/12/2019
2019-12-01 14:33:45,032 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -    Current  date: 31/12/2019
2019-12-01 14:33:45,036 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -  Google exception event is not cached. Retrieving all recurring instances...
2019-12-01 14:33:45,038 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all recurring event instances from Google.
2019-12-01 14:33:45,286 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 1 received.
2019-12-01 14:33:45,287 DEBUG  10 OutlookGoogleCalendarSync.Recurrence [0] -  Matching Google Event recurrence found.
2019-12-01 14:33:45,309 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 12/31/2019 (R) => "ISACA Dues Drop Dead date"
2019-12-01 14:33:45,318 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.EventColour [0] -  Retrieving calendar Event colours.
2019-12-01 14:33:45,572 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.EventColour [0] -  11 colours found.
2019-12-01 14:33:45,898 DEBUG  10 OutlookGoogleCalendarSync.Console [0] -  12/31/2019   "ISACA Dues Drop Dead date"
2019-12-01 14:33:45,898 DEBUG  10 OutlookGoogleCalendarSync.Console [0] -  AttributeChangeEnd time12/31/2019 12:00:00 AM → 1/1/2020 12:00:00 AM
2019-12-01 14:33:45,989 DEBUG  10 OutlookGoogleCalendarSync.Console [0] -  1 attributes updated.
2019-12-01 14:33:46,246 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Saving timestamp when OGCS updated event.
2019-12-01 14:33:46,495 WARN  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Start and end times must either both be date or both be dateTime. [400]
Errors [
	Message[Start and end times must either both be date or both be dateTime.] Location[ - ] Reason[invalid] Domain[global]
]

2019-12-01 14:33:46,500 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Start DateTime: 
2019-12-01 14:33:46,501 DEBUG  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  End Date: 2020-01-01
2019-12-01 14:33:46,504 WARN  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Start and end times must either both be date or both be dateTime. [400]
Errors [
	Message[Start and end times must either both be date or both be dateTime.] Location[ - ] Reason[invalid] Domain[global]
]

2019-12-01 14:33:46,505 ERROR  10 OutlookGoogleCalendarSync.Console [0] -  Updated event exception failed to save.
```
John,
So it looks like this event `12/31/2019 (R) => "ISACA Dues Drop Dead date"` has no start date at all, which shouldn't be possible. Could you provide the order in which changes were made, eg:
1. Created all-day recurring appointment in Outlook on 31-Dec-2019
1. Synced it to Google
1. In Outlook, change the occurrence for 31-Dec-2019 to ??-???-20??
1. Synced it to Google = error

Or steps to that effect. Also, what is the recurrence pattern that you have set?

**Comment by jcagpn** [comment] 2019-12-02 02:40
Hey P...
Well thanks for the complement.  Here is my best shot on the order of my process:
I deleted the original ISACA reoccurring event as it didn't show up on my phone,  The order I always use is
1. Create reoccurring event, private, 2 week advance notice, add color, SAVE
2. Do other even/calendar changes
3. Sometimes I don't do anything and let OGCS sync in the next scheduled sync process.  If important and needs syncing I'll do it but I'm pretty sure in this case I let OGCS sync on schedule.
4. In this ISACA (as I have noticed other times) the reoccurring symbol circle hand a diagonal line through it which means the reoccurring process was turned off.. (have no idea how that happens but I needed to make sure that event was working) so I removed the reoccurring part and reentered the same information/dates and that fixed it.
Before sending you this update, I completely removed the event and did an OGCS sync and it worked, Then I recreated the ISACA event, made it reoccurring, and OGCS synced it and it worked. 
So all seems to be working fine.
If there is a way that users like me can identify things that might be the error causing issue, it might save you a ton of work. Maybe a small script that produces results and possible solutions, and it all is copied to GitHub?!
Let me know if you need anything else.
J
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3909204/OGcalsync.log)

**Comment by jcagpn** [comment] 2019-12-02 18:33
Also my  recurrence pattern is set at 4 hours

**Comment by phw198** [comment] 2019-12-08 11:23
Thanks. Appears to be simply a case of:
1. Create all-day Outlook recurring series and sync
1. Remove recurrence and sync
1. Reinstate recurrence, sync and error

:package: This should now be resolved with [v2.8.2.17.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3936143/v2.8.2.17.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jcagpn** [comment] 2019-12-08 14:51
Yes Paul, it appears that is the case.  I have noticed over time that the reoccurring function is sometimes lost.  The icon shows a line through it that signifies it is no longer reoccurring and the only way to reinstate it is to delete it and recreate it.  This is an Outlook 365 issue not OGCS.  

Thank you for your help and I am glad I could participate in its resolution.

Take care and have good holidays.

John

**Comment by phw198** [comment] 2019-12-08 16:46
> signifies it is no longer reoccurring and the only way to reinstate it is to delete it and recreate it.  

Not quite accurate - it signifies that _particular_ occurrence of the recurring series has been changed somehow and is now an "exception" to the series. Why this is happening is out of scope of OGCS (unless there's another bug :wink:) but you can override the exception by editing the recurring series (eg edit recurrence start time and revert afterwards) - when you click `OK`, Outlook should warn you will loose any exceptions:
![image](https://user-images.githubusercontent.com/11843015/70392651-1559e800-19da-11ea-81ba-b3627b1284b5.png)

So just to confirm, are you saying you have tested the hotfix v2.8.2.17 and it works?

**Comment by jcagpn** [comment] 2019-12-08 22:35
Appreciate the clarification.

I did the update to 2.8.2.9.  I didn’t get a notice that 2.8.2.17 was available.

John

**Comment by phw198** [comment] 2019-12-08 22:41
The notification was in my earlier post - there won't be any automated update or notification for hotfix releases.

**Comment by jcagpn** [comment] 2019-12-08 23:18
Yes Paul you are right the new release was in a previous post. 

I’ll install it today and get back with you.

**Comment by phw198** [comment] 2019-12-14 21:49
:spiral_notepad: Rolling this in to the next release regardless.

**Comment by jcagpn** [comment] 2019-12-14 23:55
Was out of town on business.  Installed 2.8.2.17 and it works great.  Not sure what you did, but have not had one issue since installing it.

**Closed as completed** 2019-12-16 00:05 UTC
Labels: bug, waiting fix confirmation
