### ISSUE TITLE
Proxy failure: "Authentication failed because the remote site closed the transport stream."

### ISSUE THREAD

**Issue by xwq01** [phw198/OutlookGoogleCalendarSync#616] opened 2018-10-15 08:22 UTC
**OGCS Version**: v2.7.6.0  
**Installed or Portable**: Portable

**Problem Description**  
OGCS used to work in our company using Windows 7. Last week we were migrated to Windows 10. Now the authorisation doesn't work anymore - probably due to some security settings (see attached log). I manage to get OGCS to run and sync successfully from outside the corporate network. Is there any chance to get it working, any work-around I can try on my side?

**Steps to Reproduce the Issue**  
1. Start Sync
1. Sync fails at "Authenticating with Google"
1. Error message: Unable to communicate with Google services.
```
    2018-10-15 08:46:39,039 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Scheduled sync triggered.
    2018-10-15 08:46:39,040 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Scheduled sync started (AutoSyncTimer).
    2018-10-15 08:46:39,246 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.7.6.0
    2018-10-15 08:46:39,246 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync started at 15.10.2018 08:46:39
    2018-10-15 08:46:39,246 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Syncing from 09.10.2018 to 11.10.2019
    2018-10-15 08:46:39,247 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Outlook → Google
    2018-10-15 08:46:39,531 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Authenticating with Google
    2018-10-15 08:46:39,544 DEBUG  17 OutlookGoogleCalendarSync.Console [0] -  Preparing to authenticate with Google.
    2018-10-15 08:46:40,008 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Getting keyring.
    2018-10-15 08:46:40,280 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS Default = ACTIVE
    2018-10-15 08:46:40,280 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS PW 001 = DISABLED
    2018-10-15 08:46:40,281 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS KW 001 = DISABLED
    2018-10-15 08:46:40,281 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  There are 3 keys.
    2018-10-15 08:46:40,281 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  1 keys are active.
    2018-10-15 08:46:40,281 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Picking a Standard key.
    2018-10-15 08:46:40,282 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Authenticating with Google calendar service...
    2018-10-15 08:46:40,282 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Google credential file location: C:\Users\Test\Documents\Apps\OutlookGoogleCalendarSync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
    2018-10-15 08:46:40,284 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  User has provided authorisation and credential file saved.
    2018-10-15 08:46:40,285 INFO  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Refresh and Access token successfully retrieved.
    2018-10-15 08:46:40,285 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token expires 13.10.2018 00:22:20
    2018-10-15 08:46:40,285 DEBUG  16 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token needs refreshing.
    2018-10-15 08:47:00,429 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung.
    2018-10-15 08:47:00,430 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131500;-2146233088
    2018-10-15 08:47:00,431 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  InnerException:-
    2018-10-15 08:47:00,431 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Net.WebException: Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden..
    2018-10-15 08:47:00,431 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131509;-2146233079
    2018-10-15 08:47:00,432 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  InnerException:-
    2018-10-15 08:47:00,432 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  System.IO.IOException: Fehler bei Authentifizierung, da die Gegenseite den Transportstream geschlossen hat.
    2018-10-15 08:47:00,433 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131620;-2146232800
    2018-10-15 08:47:00,433 WARN  16 OutlookGoogleCalendarSync.Console [0] -  Unable to communicate with Google services.
```

**Comment by xwq01** [comment] 2018-10-15 15:19
Sorry, I forgot to mention that we're behind a proxy. The connection through the proxy works for OGCS on Windows 7 but not on the new Windows 10 setup. I attached the full log from startup to the first cconnection failure (on Windows 10). In the log file I redacted some entries (e.g. proxy name).
[OGcalsync2.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2479336/OGcalsync2.log)

BTW in the latestes OGCS version, there is a startup delay of 1-2 minutes between starting the application until the splash screen is shown (and the first log entry).

**Comment by phw198** [comment] 2018-10-16 17:00
It does look like your proxy is blocking authentication to Google (as well as connections to Google Analytics, which isn't too surprising), but it is talking out to GitHub OK when checking for OGCS updates etc.

Might be worth seeing if an intermediary proxy like [cntlm](http://cntlm.sourceforge.net/) could help?

**Comment by xwq01** [comment] 2018-10-17 05:53
Thanks for looking into it! Two things which seem strange to me (but I don't have any technical understanding of proxies):
1. OGCS works with same proxy under Windows 7
1. Pretty much all Google web services work in the browser (IE, Firefox) including GMail and Calendar (but not Google Drive)

Using a proxy like cntlm is probably against all our IT policies. I might give it a go anyway.

**Comment by phw198** [comment] 2018-10-17 11:53
>1. OGCS works with same proxy under Windows 7

Are you absolutely sure? Do you have access to a Windows 7 machine still that you can test this on? I'm thinking that maybe the proxy infrastructure/configuration was changed around the same time you upgrade to Windows 10...

The browser interface will be different to the API authentication mechanism - and as I mentioned, the "browser" type calls within OGCS to check for updates and so forth do still work for your proxy. As cntlm can manage your authentication, it's possible that this might make OGCS work for you. I found it was pretty forward to get going (assuming you have install rights):
1. Install cntlm
2. Edit `c:\program files(x86)\cntlm\cntlm.ini`
3. Add in your username, domain and password (you can hash it later if it works)
4. start the cntlm service (`net start cntlm`)
5. Set OGCS to use a custom proxy with `localhost:3128`

Alternatively, if you have a laptop, you could take it home to connect without a proxy, authenticate and pick up a Google access token, and then with a bit of luck you might be OK back in the office...

**Comment by xwq01** [comment] 2018-10-17 14:50
>>  OGCS works with same proxy under Windows 7
>
>Are you absolutely sure? Do you have access to a Windows 7 machine still that you can test this on? I'm thinking that maybe the proxy infrastructure/configuration was changed around the same time you upgrade to Windows 10...

Yes, I'm sure. I still have to old machine and tested it in parallel. It uses the same proxy (at least according to the settings and information in the log file).

> As cntlm can manage your authentication, it's possible that this might make OGCS work for you. I found it was pretty forward to get going (assuming you have install rights):

In this case it won't work as I don't have install privileges. Tough luck!

> Alternatively, if you have a laptop, you could take it home to connect without a proxy, authenticate and pick up a Google access token, and then with a bit of luck you might be OK back in the office...

I tried it at home - it worked (as expected). But when re-connecting it here it still needs to refresh the access token (which fails).

**Comment by phw198** [comment] 2018-10-17 23:47
OK, interesting. My gut feel is there is a problem with your certificate chain ([this article](https://cs.mailstore.com/index.php?/Knowledgebase/Article/View/120/5/erro-message-authentication-failed-because-the-remote-party-has-closed-the-transport-stream) also matches) - maybe your proxy uses a self signed certificate and you don't have the full certificate chain on your Win10 machine?? 

As per [this SO article](https://stackoverflow.com/questions/18454292/system-net-certificatepolicy-to-servercertificatevalidationcallback-accept-all-c), the below build ignores certificate errors. Note, this is just to prove if the problem is certificate related, not to be used ongoing as it's not secure.

:package: [Build v2.7.6.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2489637/v2.7.6.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes. Also what version of .Net Framework do you have on both the Win7 and Win10 machine?

**Comment by xwq01** [comment] 2018-10-18 11:10
I managed to "fix" my problem by playing around with the proxy settings. We have different proxy addresses which are automatically set depending on location. I tries different addresses and found one which works. It looks like they are set up differently.

Btw, build v2.7.6.6 didn't fix the issue. If it helps, I can do further tests. Otherwise you can close this issue.

Thanks again for the support!

**Comment by phw198** [comment] 2018-10-18 16:43
Glad you found a working solution. TBH, I don't think this is something that should be worked around or fixed within OGCS - it seems like one of the proxies in your farm is misconfigured. Most of the hits for the error you were getting are related to continuing to use TLS1.0 or TLS1.1, which are rapidly being deprecated in favour of TLS1.2. 

So in all likelihood the proxy is using an old encryption transport layer protocol or a weird cipher suite, or untrusted certificates. If your proxies are public facing, you could use [tools like SSL Labs](https://geekflare.com/ssl-test-certificate/) to check them, but probably one for your corporate IT to investigate...

**Closed as completed** 2018-10-18 16:44 UTC

**Comment by cees2349** [comment] 2018-10-19 05:47
Thanks for your help. With a bit of moving and shoving I got the system back on line again. Still do not know where the actual problem was.

**Comment by phw198** [comment] 2018-10-19 06:33
@cees2349 glad to hear it...but your posts seem to be going all over the place! I'm guessing this a follow up to your comment that popped up on a [markdown document](https://github.com/phw198/OutlookGoogleCalendarSync/commit/28dd2aacc9c9ada9ea1e3be65b05bf12c9756d3e#commitcomment-30934494)?
