### ISSUE TITLE
keep getting same message.  Don't know how to fix it.

### ISSUE THREAD

**Issue by ElenitaG** [phw198/OutlookGoogleCalendarSync#853] opened 2019-09-29 23:38 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

![image](https://user-images.githubusercontent.com/55212479/65841473-a03ea800-e2f0-11e9-910e-f7390a9eec48.png)
**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2019-09-30 08:35
Please follow the guidance when posting issues - at a minimum, state the version of OGCS you are using.

:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by phw198** [comment] 2019-10-20 15:43
Duplicate of #839

**Closed as completed by phw198** 2019-10-20 15:43 UTC
Labels: duplicate
