### ISSUE TITLE
Lots and lots of "Sync failed" boxes

### ISSUE THREAD

**Issue by mfalkvidd** [phw198/OutlookGoogleCalendarSync#1109] opened 2020-10-27 08:56 UTC
**Are you already using OGCS?**
2.8.0.0

**Describe the question you have**
Sometimes I get lots and lots of error messages. Closing them all takes about a minute. Is there a configuration change I can do to avoid these messages?

![image](https://user-images.githubusercontent.com/893502/97278528-2f8ef580-183a-11eb-9868-08394138ddf3.png)

**Comment by cboynton-lenslock** [comment] 2020-10-27 15:58
Follow-up 4

Hey @phw198! I've been getting the steady one dialog pop-up for the past few weeks with version 2.8.5. Today, our Internet went down and the bug resurfaced. A lot of dialogs appeared suddenly.

It's tricky, but in order to close each one, I need to click on the main window title bar "Outlook Google Calendar Sync" and then I am able to get focus on the next dialog to click "No". So, 2 clicks for closing each dialog.

Once the dialogs were closed and the Internet returned, all is well again.

![dialogs](https://user-images.githubusercontent.com/38633288/99744356-67c9d280-2a8c-11eb-9890-d4b37c6748d9.png)

-----

Follow-up 3

Thank you for the confirmation @phw198! I'm sure the entire community appreciates the work your team has done to make living in an Outlook world tolerable.

I'm still receiving a daily sync dialog error with 2.8.5.0, however, it's a single dialog and easily closed. While potentially annoying for some users, it is acceptable for my use case.

Therefore, it's actually not an error requiring my confirmation, but rather a notification that I haven't supplied my own Google key. In other words, for the free users, would they be able to login with their own Google account to activate this key? Does the Google API allow for a dynamic key generation?

I do see under "Show advanced/developer options" that you can provide your own Google OAuth API token once the "Calendar API" is enabled. Does this correct this sync issue?

I can imagine it's difficult to facilitate a fair queueing algorithm for 1,000,000 users on a free key (let's assume you are wildly successful in this project). If it's not possible to use a personal key or difficult for some, perhaps this is a solid reason to upgrade to a professional version? Perhaps it's a matter of hard limiting the number of sync requests per day per user?

There is a definite companion product here... convincing people to switch away from Outlook (advantages/disadvantages), and how to do it. I know a lot of people that would likely love to switch if they only knew how.

-----

Follow-up 2

It also appears that there are only Alpha and Beta versions available as GitHub tags. I will update the program to the latest Alpha and see how it is working (v2.8.5 as of the time of this writing).

https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.8.5-alpha

-----

Follow-up 1 

This appears to be a duplicate post. There are several other issues referring to this behavior already.

https://github.com/phw198/OutlookGoogleCalendarSync/issues/1085

-----

I am also having this "issue". I doubt this is intended behavior.

Version: 2.8.0.0
Running From: C:\Users\C\AppData\Local\OutlookGoogleCalendarSync\app-2.8.0-beta
Config In: C:\Users\C\AppData\Roaming\Outlook Google Calendar Sync
Subscription: N/A
Timezone DB: 2020d

Additionally, I noticed Outlook starts and prompts for 10 minutes of access from outside apps. After accepting (no permanent exception offered), and the 10 minutes lapses, the OGCS failures begin. If you leave the application running for an extended period of time, this behavior occurs. Once these dialogs appear, it appears you cannot interact with them. That is when you click on "Yes" or "No", nothing happens. You have to click on the application in the taskbar to bring up the most recent dialog in order to click "No" or "Yes".

I do see that this may be a "beta" release based on the "Running From" path. I will attempt to run an older version. That said, I downloaded this version not expecting it to be a beta.

<img width="401" alt="Sync Failed" src="https://user-images.githubusercontent.com/38633288/97326805-98be3b00-1831-11eb-8647-ea0ff1f43f19.png">

**Comment by phw198** [comment] 2020-10-31 16:30
Not intended behaviour no, but it should be fixed in v2.8.5.

The problem occurs when the Google quota is exhausted - in fact OGCS v2.8.0.0 did handle this properly too, whereby subsequent syncs would be delayed until after new daily quota became available. But Google helpfully changed the error being returned when quota was exhausted, so OGCS would keep trying to sync....and failing.

**Comment by mfalkvidd** [comment] 2020-10-31 23:22
Great work, thanks!

**Comment by Ernst2020** [comment] 2020-11-10 20:19
Using the hotfix 2.8.4.8 and having this annoying problem every couple days. If 4.8.5 solves this, is it safe to install the alpha 4.8.5?
Alpha status sounds scary... don't want to ruin my work agenda...

**Comment by phw198** [comment] 2020-11-22 15:42
@Ernst2020  Order of "scariness":-
1. Beta release - annually-ish
2. Alpha release - monthly-ish
3. Hotfix - a bug fix on top of an alpha

Ie 2.8.4.8 is more scary than 2.8.5.0

**Closed as completed by phw198** 2020-11-22 15:42 UTC
Labels: question
