### ISSUE TITLE
Can't interact with donation popup ("spread the word" popup) when OGCS dialogs are displayed

### ISSUE THREAD

**Issue by SVNKoch** [phw198/OutlookGoogleCalendarSync#1188] opened 2021-03-12 18:59 UTC
**OGCS Version**: v2.8.6.0
**Edition**: Portable  

**Bug Description**  
OGCS opened a dialog to rerun the Sync as it failed (due to exhausted quota).
In the mean time (not sure if before or after dialog) OGCS had opened the "Help Promote OGCS" popup.
I was not able to close this pop up using [x] or the close button as it did not accept inputs because a dialog was open.
However I could still interact with the dialog underneath via keyboard without seeing it.

possible Fixes:
make the Donation PopUp Banner not blocked by open dialog boxes in main window
close popup when dialog opens / wait with popup until dialog is cleared

**Comment by phw198** [comment] 2021-03-14 13:57
Exhausted quota shouldn't produce a blocking popup - it just returns updates into the main `Sync` tab and delays the next scheduled sync to when there should be quota (there are some bug fixes in that delay since v2.8.6.0).

However, I can reproduce this by:
1. Running a sync that triggers promotion window, leave it open
2. Let a new scheduled sync run that causes a popup messagebox, which appears behind the promotion window

**Comment by phw198** [comment] 2021-03-14 14:05
:package: This should now be resolved with [hotfix v2.8.6.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6136798/v2.8.6.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Closed as completed** 2021-05-09 19:12 UTC
Labels: bug, resolved
