### ISSUE TITLE
Meeting syncs to wrong day

### ISSUE THREAD

**Issue by oughgh** [phw198/OutlookGoogleCalendarSync#537] opened 2018-06-08 23:49 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.4.0
**Installed or Portable**: Installed

**Problem Description**  
Outlook meeting shows up in Google Calendar on the wrong day. Meeting is created/hosted by someone in a different time zone on a different day (for example, in China). The synced meeting shows up at the correct time for my timezone, but on the wrong day.

**Steps to Reproduce the Issue**  
Example for illustrative pusposes:
1. Recurring meeting (in Outlook) is created/hosted by someone in China on Tuesdays and Fridays at 7am China time.
2. Host invites me to the meeting, so it correctly displays on my Outlook calendar in Arizona time on Mondays and Thursdays at 4pm. (China is 15 hours ahead of Arizona)
3. OGCS creates an event on my google calendar in Arizona time at 4pm... but on Tuesdays and Fridays instead of Mondays and Thursdays. It appears to use the time from my local timezone, but day/date from the meeting organizer/host's timezone.

**Any other information**  
I have another non-recurring meeting from the same organizer (same timezone issues) - for example, also hosted on Friday at 7am China time / Thursday at 4pm Arizona time, and OGCS synced this one correctly to Thursday (instead of Friday like the example in the previous paragraph)... maybe the fact that it is a recurring meeting is an issue? Note that neither China nor Arizona use daylight savings time (Arizona is on MST year-round)... if that matters at all. This does not appear to be a new issue - I've had this issue for at least a year, just upgraded to 2.7.4.0 today, and it is still present. I know it was also present in 2.6.0.0, if not many earlier versions as well.

**Comment by phw198** [comment] 2018-06-09 07:15
Looks like a duplicate of issue #67 which has a hotfix posted.

**Comment by oughgh** [comment] 2018-06-09 16:01
Success! Thanks for the quick response Paul, and thanks for developing a
great tool that I use every day.

**Closed as completed** 2018-06-09 16:14 UTC
Labels: duplicate
