### ISSUE TITLE
Application Unexpectedly terminated: value cannot be null. Parameter name: oldValue

### ISSUE THREAD

**Issue by AidanFleming** [phw198/OutlookGoogleCalendarSync#1357] opened 2021-12-13 01:38 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: Newest, just recently updated.
**Installed or Portable**: Installed

**Problem Description**  
Cannot open app at all, when click to open, get a popup error box that read:
Application Unexpectedly terminated
 value cannot be null. 
 Parameter name: oldValue
![Capture2](https://user-images.githubusercontent.com/18625498/145739477-af8f81bc-26fb-41fc-b6e2-82573a0ffefa.PNG)

**Steps to Reproduce the Issue**  
1. Open app
1. 

**Any other information**  
Just recently updated to lastest, been fine.

**Comment by rolavarrias** [comment] 2021-12-30 19:53
Hi. a need you help. I have same problem. I update at last versión alpha, but my problem continue. I use OGCS whit outlook 2016. At inicialiced the app say this error: 

Application Unexpectedly terminated
value cannot be null.
Parameter name: oldValue

Thanx for you help.
Best Regards.

**Comment by mapeit** [comment] 2022-01-05 15:14
I have the same problem. Working on a PC with Windows 11 Home..

**Comment by phw198** [comment] 2022-01-05 18:06
:spiral_notepad: Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by AidanFleming** [comment] 2022-01-07 01:22
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7825645/OGcalsync.log)


> 🗒️ Please provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by mapeit** [comment] 2022-01-07 13:18
Please find OGcalsync.log attached.
Thank you.

**Comment by mapeit** [comment] 2022-01-07 13:22
Please find it attached
Best regards.

**Comment by phw198** [comment] 2022-01-23 12:52
This looks to be a duplicate of #1282, which has a [hotfix posted](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1282#issuecomment-985117533) - please follow the guidance there and post a comment on that issue after applying.

@mapeit Unfortunately GitHub doesn't support submitting files and screenshots to the ticket when replying by email, however I suspect you need to following #1282 too.

**Closed as completed** 2022-02-20 14:29 UTC
Labels: duplicate, dormant
