### ISSUE TITLE
The specified key was not present in the dictionary

### ISSUE THREAD

**Issue by MassimoMeridio** [phw198/OutlookGoogleCalendarSync#1339] opened 2021-11-12 08:52 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0
**Edition**: Installed 
**Sync Direction**:   O->G

**Bug Description**  
When start the sync I recive the message "La chiave specificata non era presente nel dizionario"

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7526133/OGcalsync.log)

**Comment by phw198** [comment] 2021-11-13 21:27
Duplicate of #1289 - please apply the hotfix available there.

**Closed as completed by phw198** 2021-11-13 21:27 UTC
Labels: bug, duplicate
