### ISSUE TITLE
Event update failed. GMeet and appointment body empty.

### ISSUE THREAD

**Issue by RedRocksAZ** [phw198/OutlookGoogleCalendarSync#1810] opened 2024-02-27 18:10 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed / Portable  
**Sync Direction**: G->O 

**Bug Description**  
2 messages...Event update failed.
Value cannot be null.  Parameter name: input

Also...Google event update failed.  Continue with synchronisation.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
My Google calendar does get updated.  I have attached a screenshot.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14424057/OGcalsync.log)
![OGCS screenshot](https://github.com/phw198/OutlookGoogleCalendarSync/assets/161505954/148d8c43-47b6-4c5d-b74b-d5d7c3b95b42)

:paperclip: Attach your `OGcalsync.log` file.

**Comment by Fafner1976** [comment] 2024-02-28 07:20
https://github.com/phw198/OutlookGoogleCalendarSync/issues/1776

**Comment by FilippoLepri** [comment] 2024-03-13 06:25
> #1776

I'm experiencing the same, but I had actually already applied the hotfix ... in fact I am running 2.10.3.1.

It solved at first, but it seems the problem came back.

I guess I am misunderstanding something. :)

**Comment by phw198** [comment] 2024-03-16 16:33
@FilippoLepri  Please post evidence (namely your OGcalsync.log file) of the error you are getting under v2.10.3.1

**Comment by FilippoLepri** [comment] 2024-03-25 08:35
> @FilippoLepri Please post evidence (namely your OGcalsync.log file) of the error you are getting under v2.10.3.1

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14740896/OGcalsync.log)

I'm very sorry for both:
- my late reply (terribly busy period)
- the fact that I can't be more precise (for the same reason as above... I have a few seconds): a little while ago I encountered the same error and it should be included in the file I attach, but now the synchronization seems to end correctly! (Which hasn't happened in WEEKS.)

I hope the attached file will help you better than the poor analysis I can do now.

**Comment by BauplanungOberlaustitz** [comment] 2024-03-27 07:25
Hi @phw198, 
I got the same problem with the latest version of OGCS. How can I post my logfile? Upload doesn't work.
Thanks in advance, 
Alexander

**Comment by paulandersonsco** [comment] 2024-03-28 09:00
I am having the same issue with 2.10.3.1. It is intermittent. And if I re-sync, it often doesn't re-occur. But I seem, to be getting it at least once per day. Log file from today attached and if you search for 'Value cannot be null' in the logs you will see it from this morning.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14786771/OGcalsync.log)

**Comment by phw198** [comment] 2024-03-28 15:45
Thanks @FilippoLepri @paulandersonsco, looks like this is a different occurrence of the same underlying problem 🙁 

:package: This should now be resolved with [hotfix v2.10.3.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14792036/v2.10.3.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `CDC9BA8E` Exe = `D8AAD363`

Please let me know how it goes.

**Comment by RedRocksAZ** [comment] 2024-03-28 16:43
This worked for me.  Many thanks.

RedRocksAZ

**Comment by phw198** [comment] 2024-03-28 17:26
@RedRocksAZ Your issue was already fixed by #1776 - you weren't hitting the issue fixed under v2.10.3.8 (though this does include _both_ fixes).

**Comment by FilippoLepri** [comment] 2024-03-29 07:37
> Thanks @FilippoLepri @paulandersonsco, looks like this is a different occurrence of the same underlying problem 🙁
> 📦 This should now be resolved with hotfix v2.10.3.8
> Please let me know how it goes.

Applied, thank you very much.
The first sync worked, but my problem actually seemed to be not always recurring, so: do you want me to do a specific test?
If you do, let me know exactly what I have to try and I will do it. (Don't hold your breath as I'm terribly busy, but I will do it.)

FL

**Comment by phw198** [comment] 2024-03-30 13:46
Thanks @FilippoLepri - I think the steps to reproduce/test the fix are:
1. Create a new Outlook item with no body/description
2. Ensure OGCS Settings under Google tab are set to sync Google Meet details
3. Sync to Google

**Comment by phw198** [comment] 2024-04-01 12:39
I'm going to pull this hotfix into the next alpha anyway - I'm pretty confident it fixes the issue, but if you are able to confirm it that would still be appreciated.

**Closed as completed** 2024-04-01 16:09 UTC
Labels: bug, waiting fix confirmation

**Comment by BauplanungOberlaustitz** [comment] 2024-04-02 06:48
@phw198 Thank you!

**Comment by FilippoLepri** [comment] 2024-04-02 06:59
> 1. Create a new Outlook item with no body/description

![01](https://github.com/phw198/OutlookGoogleCalendarSync/assets/41188835/a5eda9e3-7d88-4c4e-9e43-dea99bb1c099)

> 2. Ensure OGCS Settings under Google tab are set to sync Google Meet details

Are you referring to the "include meet conferences" option? ... if you are, here it is:
![02](https://github.com/phw198/OutlookGoogleCalendarSync/assets/41188835/76cd9ecf-bfe0-4c05-9a02-50bf968e4af6)

> 3. Sync to Google

:)
![03](https://github.com/phw198/OutlookGoogleCalendarSync/assets/41188835/c119e41c-63c8-4b9a-addb-de3215a6685e)

Did I do everything right?

FL

**Comment by phw198** [comment] 2024-04-02 07:13
Yes, that all looks correct - thanks for confirming @FilippoLepri! 👍🏻

**Comment by paulandersonsco** [comment] 2024-04-09 11:13
Thanks Paul for working on this issue. Apologies for the delayed response, but I was on vacation last week over the Easter break, so only got around to applying the latest release yesterday. All seems to be good so far with no issues occuring. Much appreciated, Paul.
