### ISSUE TITLE
Deletion message of new appointments

### ISSUE THREAD

**Issue by kathl1** [phw198/OutlookGoogleCalendarSync#479] opened 2018-02-28 12:12 UTC
----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
I have an outlook and google 2 way synced. When I add an appointment in Outlook it says when syncing that it wants to Delete this one... There is however also synchronisation. How do I get rid of the delete message which is unapropiate in this case.

**Steps to Reproduce the Issue**  
1. Place an appointment in Outlook
2. Start syncing

**Any other information**

**Comment by phw198** [comment] 2018-02-28 12:54
Upgrade? v1.2.3.4 is very old. I'm not even sure it ever existed... :wink: 

"There is however also synchronisation." - what does this mean?

How are you adding the item in Outlook? Copying an existing item that's already been synced?

**Comment by kathl1** [comment] 2018-02-28 12:58
I am using version: 2.7.0.0.

Looks like the problem is occuring with copied items indeed.

**Comment by phw198** [comment] 2018-02-28 13:57
So as long as OGCS v2.7 is open when you copy the Outlook item, it should prevent this problem from occurring. 

:spiral_notepad: Can you reproduce the problem with OGCS running and then copying an already synced item? If so, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

If the item you original reported was copied when OGCS was not running, you can probably work around the issue by temporarily performing a one-way sync from Outlook to Google.

**Comment by wilderstefan** [comment] 2018-03-16 10:46
V 2.6.0.0
Appointments are told all invited persons (in outlook) to have been deleted. But there was no deleting process - the appointment is still in the calendar. 

I guess due to the sync, gcal can't read these appointments properly. 

Because the message comes every time from the synced calendar in gcal, 
[Calendar name] <[lotsofnumbersandletters]@group.calendar.google.com>
 It names the referred appointment (date, time, title) and tells in red letters "This event has been canceled."

these appointments

-  are all shared with other persons in outlook

- are (all) recurrently appointments

- are all created in outlook

I'm not very happy doing tests, because by every false message of a deleted appointment, my team is pretty upset.

Have you ever heard of this issue?

thanks in advance

**Comment by phw198** [comment] 2018-03-18 12:50
@wilderstefan This isn't the issue the OP was reporting, but sure - documented [here in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google). Mitigated from v2.6.2 by turning on email cloaking feature.

**Comment by phw198** [comment] 2018-03-31 07:12
@kathl1 I think this is now a duplicate of #487, for which a hotfix has been posted - see if that helps.

**Closed as completed** 2018-05-13 22:42 UTC
