### ISSUE TITLE
Recurring Outlook entry works for recurrence by end date but not by number of occurrences

### ISSUE THREAD

**Issue by sjsdoc60** [phw198/OutlookGoogleCalendarSync#1035] opened 2020-07-06 15:01 UTC
Using 2.8.4.0.  Outlook to Google one way.  Testing recurring entries.  When I created new entry and ended recurrence in Outlook by stopping after 2 occurrences, it did move the first entry to Google but no recurrent entries.  This was tested multiple times.  I then switched to recur until an end date.  This worked fine.  I created an entry called Test for 1/2 hour with correct category in all tests of the sync.  The txt file is really the xml file.
Thanks

[calendar.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4879700/calendar.log)

[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4879704/settings.txt)

**Comment by phw198** [comment] 2020-07-19 00:17
Regardless of whether Outlook is set to a recurring number or an end date, OGCS converts them both to the end date. From your log I can see the following tests - as far as I can see the `UNTIL` date looks to be correct for them in that they should show two occurrences. The third "tets" entry would certainly show two occurrences as you've selected an end date between 2 and 3 weeks after the first:
```
2020-07-06 08:18:36,887 DEBUG  29 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 7/7/2020 3:00 PM (R) => "test"
2020-07-06 08:18:36,888 DEBUG  29 OutlookGoogleCalendarSync.Console [0] -  7/7/2020 3:00 PM   "test"
2020-07-06 08:18:36,981 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2020-07-06 08:18:36,999 DEBUG  29 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;UNTIL=20200714T150000Z
...
2020-07-06 08:23:09,703 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 7/7/2020 3:00 PM (R) => "test"
2020-07-06 08:23:09,704 DEBUG  24 OutlookGoogleCalendarSync.Console [0] -  7/7/2020 3:00 PM   "test"
2020-07-06 08:23:09,779 DEBUG  24 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2020-07-06 08:23:09,789 DEBUG  24 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;UNTIL=20200714T150000Z
...
2020-07-06 08:53:09,748 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 7/14/2020 2:00 PM (R) => "tets"
2020-07-06 08:53:09,748 DEBUG  24 OutlookGoogleCalendarSync.Console [0] -  7/14/2020 2:00 PM   "tets"
2020-07-06 08:53:09,832 DEBUG  24 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2020-07-06 08:53:09,851 DEBUG  24 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;UNTIL=20200731T140000Z
```
I've also tested it and can't reproduce the issue you are reporting. Can you confirm the first two are the ones only showing 1 occurrence?

**Comment by phw198** [comment] 2020-07-19 13:11
Would also be helpful if you could:
* export the problematic 2x occurence series in Outlook as an `.ics` file and upload here
* confirm your Windows system timezone
* confirm the Google calendar timezone (global settings)
* confirm the Google timezone for the specific calendar you are syncing to

**Comment by sjsdoc60** [comment] 2020-07-19 14:42
ok.  but will take some time.  had health issue.

**Comment by phw198** [comment] 2020-07-25 20:27
Update from @sjsdoc60 posted to wrong issue (1031), copied below:
> Here is an example of a missed calendar item in Outlook 365 supposed to go to Google on a one way sync.  The recurring item is 'Key Updates, hosted by xxxx' on Monday July 27, 2020.  This is 115PM local time.  It is a every 2 week recurring item.  Categorized as EPIC/HI correctly.  It should be copied over to Google.  The recurrence goes from 6/29/20 to 7/27/20 which is the date of the missing item.  I did remove and re-add in the category.  Either OGCS is not seeing it or thinks it doesn't need to add to Google.  Tried several times today.  It is interesting that the recurrence date ends on the same date as the last occurrence of the meeting.  Maybe that is the problem?  
[settings.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4948474/settings.txt)  
[calendar.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/4948475/calendar.txt)

**Comment by phw198** [comment] 2020-07-25 20:35
OK, but I still need the information for all the bullet-points in my [previous post](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1035#issuecomment-660641818)...

**Comment by sjsdoc60** [comment] 2020-07-25 20:40
All 3 time zones are mountain time, checked. Will create an ice file from outlook.

**Comment by sjsdoc60** [comment] 2020-07-25 20:49
Unable to export the appt above to an .ics file.  Error: 'The operation Failed. The messaging interfaces returned an unknown error. If the problem persists, restart Outlook.'  I did retry the operation after restart and same error.  Attached is a picture of the outlook appt. Best I can do.
[2020-07-25_14-48-23.pdf](https://github.com/phw198/OutlookGoogleCalendarSync/files/4976413/2020-07-25_14-48-23.pdf)

**Comment by phw198** [comment] 2020-10-04 16:37
Hi @sjsdoc60 - hope you are well? Any chance you have been able to test the hotfix on this issue - would like to get it into the next release if possible...

**Comment by sjsdoc60** [comment] 2020-10-05 02:08
I have been using it.  I did a test today and there is still one bug.
Create an Outlook recurring event starting on a Monday (I used Oct 5). Have
it recur until Monday, Oct 26.  All is fine EXCEPT the last occurrence on
Monday Oct 26 which is in Outlook, never appears in Google calendar.  The
other appts do.

Best

**Comment by phw198** [comment] 2020-10-10 17:41
I can't troubleshoot on such limited information. 

1. Is the recurring series all day or for a specific time?
1. If for a specific time, what?
1. What timezone is being used?
1. Did you create the appointment series or organised by someone else, as per [your previous PDF](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1035#issuecomment-663904579)?

I suspect this is some oddity related to DST ending on the 25-Oct in Europe, but 1-Nov in the US...

Please raise a new GitHub issue to track this new problem.

**Comment by sjsdoc60** [comment] 2020-10-10 17:48
On Sat, Oct 10, 2020 at 11:41 AM Paul Woolcock <notifications@github.com>
wrote:
   

>    1. Is the recurring series all day or for a specific time? i did 5pm-6pm
>    2. If for a specific time, what? 
>    3. What timezone is being used? US Mountain time
>    4. Did you create the appointment series or organised by someone else,
>    as per your previous PDF? I did appt
>
> I suspect this is some oddity related to DST ending on the 25-Oct in
> Europe, but 1-Nov in the US...
>

 unlikely as I am in us and this was before time change over.
In either case, did you try what I said?   It is not limited information.

**Comment by phw198** [comment] 2020-10-10 19:04
The time the series was started or created isn't relevant to when it ends and DST. However, although the occurrence on 26-Oct is an hour earlier in Europe compared to the other occurrences, that isn't the reason for the bug.

17:00 Mountain Time is 00:00 the _next day_ in UTC, so I've now confirmed the last occurrence was getting missed. (This is why detail is so important - I can't spend all my time trying all manner of permutations).

:package: Hopefully now fully resolved with [v2.8.4.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5359750/v2.8.4.14.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!

**Comment by phw198** [comment] 2020-10-25 12:44
@sjsdoc60 Any better luck with v2.8.4.14?

**Comment by sjsdoc60** [comment] 2020-10-25 13:06
That particular problem is fixed.  Nothing else outstanding at this time.

**Comment by phw198** [comment] 2020-10-25 13:26
@sjsdoc60 Awesome - thanks for the quick response!

**Closed as completed** 2020-10-25 19:16 UTC
Labels: bug, timezones, resolved
