### ISSUE TITLE
ERROR - The given key was not present in the dictionary

### ISSUE THREAD

**Issue by PhaserVectis** [phw198/OutlookGoogleCalendarSync#1290] opened 2021-09-22 08:43 UTC
**OGCS Version**: v2.9.1.0  
**Installed or Portable**: Installed

**Problem Description**  
When trying to sync my calendars, I get the following error message: "The given key was not present in the dictionary"
This occurs just after "Checking for orphaned Google items"

**Steps to Reproduce the Issue**  
I just hit the Start Sync button, or let it sync automatically - both routes result int he same issue.

**Any other information**  
Log file contents:
```
2021-09-22 09:34:42,333 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Sync version: 2.9.1.0
2021-09-22 09:34:42,333 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Sync started at 9/22/2021 9:34:38 AM
2021-09-22 09:34:42,334 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Syncing from 9/21/2021 to 11/22/2021
2021-09-22 09:34:42,334 DEBUG  1 OutlookGoogleCalendarSync.Console [226] -  Outlook → Google
2021-09-22 09:34:42,602 DEBUG  1 OutlookGoogleCalendarSync.Telemetry [32] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=3493936ba2d92473dc899fe5c65b7226&ec=ogcs&ea=sync&el=calendar
2021-09-22 09:34:42,603 INFO  11 OutlookGoogleCalendarSync.Console [282] -  Finding Calendar Entries
2021-09-22 09:34:42,704 INFO  11 OutlookGoogleCalendarSync.Console [282] -  Scanning Outlook calendar...
2021-09-22 09:34:43,087 INFO  11 OutlookGoogleCalendarSync.Console [282] -  11 Outlook calendar entries found.
2021-09-22 09:34:43,126 INFO  11 OutlookGoogleCalendarSync.Console [282] -  Scanning Google calendar...
2021-09-22 09:34:43,474 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [269] -  Retrieving all events from Google: 9/21/2021 -> 11/22/2021
2021-09-22 09:34:43,768 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [283] -  Page 1 received.
2021-09-22 09:34:43,769 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [403] -  Identifying exceptions in recurring Google events.
2021-09-22 09:34:43,769 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [411] -  Found 1 exceptions.
2021-09-22 09:34:43,769 INFO  11 OutlookGoogleCalendarSync.Console [282] -  20 Google calendar entries found.
2021-09-22 09:34:43,846 INFO  11 OutlookGoogleCalendarSync.Console [282] -  1 are exceptions to recurring events.
2021-09-22 09:34:44,100 INFO  11 OutlookGoogleCalendarSync.Console [282] -  Total inc. recurring items spanning sync date range...
2021-09-22 09:34:44,502 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [269] -  Retrieving all events from Google: 7/28/2021 -> 7/29/2021
2021-09-22 09:34:44,746 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [283] -  Page 1 received.
2021-09-22 09:34:44,747 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1012] -  Scanning 4 Google events for orphans to reclaim...
2021-09-22 09:34:44,763 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1062] -  1 unclaimed.
2021-09-22 09:34:44,797 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [519] -  Event "Check up on Danish" does not have Outlook EntryID stored.
2021-09-22 09:34:44,845 INFO  11 OutlookGoogleCalendarSync.Console [282] -  Outlook 11, Google 20
2021-09-22 09:34:44,895 DEBUG  11 OutlookGoogleCalendarSync.Console [280] -  Checking for orphaned Google items
2021-09-22 09:34:45,149 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1012] -  Scanning 20 Google events for orphans to reclaim...
2021-09-22 09:34:45,428 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1062] -  12 unclaimed.
2021-09-22 09:34:45,428 INFO  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1066] -  12 unclaimed orphan events found.
2021-09-22 09:34:45,428 INFO  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1068] -  These will be kept due to configuration settings.
2021-09-22 09:34:45,428 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1098] -  Checking for Events that have been duplicated.
2021-09-22 09:34:45,477 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
2021-09-22 09:34:45,477 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131577,-2146232969; Location: get_Item() in <Unknown File>
2021-09-22 09:34:45,477 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.<>c.<CleanDuplicateEntries>b__46_1(Event e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 1100
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CleanDuplicateEntries(List`1& google) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 1099
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 536
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass24_0.<Start>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 217
2021-09-22 09:34:45,478 ERROR  11 OutlookGoogleCalendarSync.Console [278] -  The given key was not present in the dictionary.
2021-09-22 09:34:47,813 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [200] -  User opted to abandon further syncs.
2021-09-22 09:34:47,813 FAIL  1 OutlookGoogleCalendarSync.Console [276] -  Sync aborted after 1 failed attempts!
2021-09-22 09:34:47,836 INFO  1 OutlookGoogleCalendarSync.Console [282] -  Another sync has been scheduled to automatically run in 15 minutes time.
2021-09-22 09:34:47,856 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [18] -  Next sync scheduled for Wednesday, September 22, 2021 @ 9:49:47 AM
2021-09-22 09:34:47,872 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [116] -  De-referencing all Outlook application objects.
2021-09-22 09:34:47,907 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [131] -  Disconnecting from Outlook application.
```

**Comment by phw198** [comment] 2021-09-22 12:35
Thanks, but this would be a duplicate of #1289.

**Closed as completed by phw198** 2021-09-22 12:35 UTC
Labels: duplicate

**Comment by PhaserVectis** [comment] 2021-09-22 15:42
Yep - searched for a previous mention, but failed to find it before.  The fix on https://github.com/phw198/OutlookGoogleCalendarSync/issues/1289 works for me too.

Thank you
