### ISSUE TITLE
Application Fails During Sync

### ISSUE THREAD

**Issue by JRBird84** [phw198/OutlookGoogleCalendarSync#796] opened 2019-08-07 11:46 UTC
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3476782/OGcalsync.log)

**OGCS Version**: v2.8.1.0  
**Installed or Portable**: Installed

**Problem Description**  
Immediately after the update to the newest version, the application fails after initiating a sync.

**Steps to Reproduce the Issue**  
1. Open Application
2. Click the Start Sync Button
3. Application Shuts down without any warning

**Any other information**  
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/3476792/OGcalsync.txt)

**Comment by phw198** [comment] 2019-08-07 21:43
Duplicate of #793 

Thanks for reporting - there's a hotfix posted on the other issue.

**Closed as completed by phw198** 2019-08-07 21:43 UTC
Labels: duplicate
