### ISSUE TITLE
Incorrectly deleting Outlook entries when synching if Event A was copied to Event B on a different date/time

### ISSUE THREAD

**Issue by ionizer5** [phw198/OutlookGoogleCalendarSync#224] opened 2017-06-01 03:56 UTC
Situation:

Outlook <-> Google synch 
-Merge w/ existing entries

Date Range: 1 day past to 365 days in the future

Case (Assume Today is 6/1/2017)
-Event A on 5/15/2017 in outlook and synched with google
-Action: In outlook 2016, ctrl-c the event in calendar
-Action: In calendar, pick a different date, let's just say 6/2/2017 (In outlook 2016 when you first click a date this will make it white, you then have to hit hit escape to make it a paste-able event)
-Action: Ctrl-v to paste the event, thus making a copy of the Event A, but creating a new Event B on 6/2/2017
-Action: Synch runs, recognizes 2 outlook events, 1 google event item.  It then proceeds to DELETE the outlook item.

WHY?  It works for every other case and if you manually create the event B it works fine.  But something about outlook 2016 and copying events must maintain some kind of unique identifier being used?

I can't say for certain if this problem exists prior to outlook 2016 where the copy/paste function was slightly different, because I Was using a different synch app to do so and never had the issue.

**Comment by thelordsmurf** [comment] 2017-06-01 18:28
Hi all,
I'm not sure if this is the same behavior, so I'm putting it here and making a new request as well, but I have noticed some meetings that are rescheduled by someone else then getting deleted by the sync process. If an appointment is made by someone else, then they send me an updated time and I accept it,   I think that sometimes with a sync it gets deleted. It's quite concerning as I have missed appointments because of this! I'm also on Outlook 2016 and sync 2.4. I don't know if this was happening since I went to 2.4 or Outlook 2016 but those two things happened at near the same time.
Thanks.
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1045709/OGcalsync.log.txt)

**Comment by phw198** [comment] 2017-06-03 22:39
Well, I know *why* this is happening, but I'm stumped at the moment on how to resolve it.

Basically, when an O item is synced to G, special fields in the O item are updated with the G unique IDs so as to create a link between the two. When an O item is copied, these special fields are also copied and furthermore the unique ID for the Outlook item changes (else it wouldn't be unique). So now the copied O item _looks_ like it has a synced G counterpart, but there is no match in G for it. For two-way sync the problem is this situation signifies to OGCS that the G item has been deleted and therefore requires the O item to be deleted on the next sync!

I was hoping that the copied item's creation timestamp would be newer than the OGCS sync timestamp - an invalid situation would would indicate the item is a copy....but unfortunately the copied item also copies the source creation time :unamused: Any other mechanism I can currently think of jeopardises the authentic user deletion of a G item that _should be_ replicated back to O.

**Comment by ionizer5** [comment] 2017-06-04 01:36
First, I am honored by your reply.  Glad my use case was sufficient enough to understand the why.  

So I guess there is no other unique information that can be used in the comparison of the outlook entry to the google entry?  

As I understand it, you are basically saying that an outlook copy event basically looks identical to the orginal event when viewed from a google calendar basis.

Would changing the time of the day, adding location, changing the notes or anything else contribute to a unique entry?

I am just trying to see if i can simply modify the subject after the copy in order to make it unique and i am not privy to what the identifiers are that make it unique.

**Comment by thelordsmurf** [comment] 2017-06-04 04:18
I'm just a bit confused as to why this is happening now and not previously.
Is there something new in the event characteristics? I just don't remember
this being an issue before.
Thanks

**Comment by ionizer5** [comment] 2017-06-04 23:31
> I'm just a bit confused as to why this is happening now and not previously. Is there something new in the event characteristics? I just don't remember this being an issue before.

I wonder if it is because of outlook's new means of copying/pasting.  Before one just used to copy/paste, but now you have to unselect your click via esc in order to not paste an all day event

maybe before it included different information in the copy/paste and now it's just doing something differently?

way to test would be to acquire outlook 2010 (not sure about anything later) and compare it to outlook 2016 and copy/paste events

**Comment by phw198** [comment] 2017-06-05 22:57
@thelordsmurf I'm pretty sure that although very closely related, issue #225 is different problem - and one that should hopefully have a more straight forward fix...!

**Comment by draeburn** [comment] 2017-06-06 15:43
@thelordsmurf actually I reported issue #225 6 months ago, so it's not fairly new!

**Comment by phw198** [comment] 2017-09-10 21:20
:package: This should now be resolved with [hotfix v2.6.1.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1290941/v2.6.1.8.zip) - [see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix), and make sure it is applied over the top of v2.6.1.0.

Please let me know how it goes!

**Comment by ionizer5** [comment] 2017-09-11 02:19
Hi, just tried the hotfix, doesn't seem to be working:

Steps:
(1) I closed/exited the existing synch executable from tray.
(2) I renamed my old .exe based on the executable direction found in about.
(3) I unzipped the new hotfix file.
(4) I placed said file in the same folder in #2
(5) I ran said executable and confirmed in msconfig.exe that there are no further parameters when executing
(6) I received (instantly) a "OutlookGoogleCalendarSync has stopped working" popup with the following details:

Description:
  Stopped working

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	OutlookGoogleCalendarSync.exe
  Application Version:	2.6.1.8
  Application Timestamp:	59b5abb2
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23864
  Fault Module Timestamp:	595fa536
  Exception Code:	e0434f4d
  Exception Offset:	0000c54f
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt


I did not reboot or close outlook.  I'll try some of those things, but consider the above an open issue unless I come back to restate.

**Comment by ionizer5** [comment] 2017-09-11 02:20
Confirming this file just does not run on windows or something is wrong with it.  Closed outlook, tried to run it, instantly get the error.

I replaced my old one and it runs fine.  However, I will note that I am presently on version 2.3.0.0

please let me know if my older version is an issue.

**Comment by ionizer5** [comment] 2017-09-11 02:21
I am only seeing notice about a beta of 2.5.0.0 and nothing about 2.6.0.0

**Comment by phw198** [comment] 2017-09-11 06:45
Yeah, that's never ever going to work. I did say "make sure it is applied over the top of v2.6.1.0." - you're miles behind! 

Upgrade to v2.5, then you should get notified about 2.6, upgrade again,  then check the box for alphas and go to v2.6.1, then finally apply the hotfix...

**Comment by gnubee40** [comment] 2017-09-11 07:32
Interesting. I will try this and see, if it cuts the cake. Will have to upgrade first though. 
@ionizer5: This issue with copied appointments is also present for me in Outlook 2010. So I don't think it is specific to Outlook 2016.

**Comment by gnubee40** [comment] 2017-09-11 08:02
Ok - i applied the hotfix. 
1. I create a test event in subfolder calendare Outlook (EKKO)
2. I 1-way-sync my subfolder Outlook (EKKO) to my subcalendar Google (Echokalender). 
3. It syncs as expected
4. I copy/paste it to the next day.
5. It syncs, but with the SAME date and time as the original event. So now it's a doublet on the same day in google.
6. I press shift+Sync button. The copied event gets updated in google with the correct date and time. 

So far so good. 

7. I switch to 2-way sync and delete one of the google test appointments. 
8. run shift+sync - OGCS asks to delete the appointment. Great.¨
It also asks to delete a bunch of other appointments in outlook, which it shouldn't. This is why I don't run 2-way sync right now. 

BTW: I have another sync program, which displays the same behaviour: deleting the same appointments in outlook, which OGCS asks to delete. So I suspect, there have been made changes to google calendar rather than to outlook.

What possibly would be good to add : 

- if you run 1-way sync with shift or an extra option, the events get updated so they are totally aligned (all tags). don't know if is possible with Google's crappy ID system.
- Just make a check box to do the thorough sync every time. It seems to work best for me right now.

**Comment by gnubee40** [comment] 2017-09-11 08:40
OK - now I switched to default calendar sync instead of subfolders. 

1. I copied test event to the default calendar
2. Ran 2-way sync between default google and outlook calendar
3. Test event (which was copied before on the sub-folder) copied over again.

So a partial success

**Comment by phw198** [comment] 2017-09-11 08:58
@gnubee40 I'd need to see your logfile and what happened around the step "4. I copy/paste it to the next day.". Shift-sync shouldn't be required to get things back in order for a copy/paste in Outlook.

The incorrect deletes in Outlook for step 8 - might you have copy/pasted the associated items in Google at some point?

Why is the default calendar sync only a partial success? The item is now in a different calendar so no longer the same object - I'd say syncing it "again" would be expected behaviour...

**Comment by gnubee40** [comment] 2017-09-11 11:56
It's definitely what I would expect, but it didn't quite happen like that before. Partial success, because there is the other issue still. It was my impression, that appointments copied between sub-calendars are not synced correctly. It was when I started to have my 2nd outlook calendar last month (which i share with others) that the problems took off. But maybe I'm wrong. looking back in my email correspondance, I see I did contact the other sync software provider with an issue about deleted outlook appointments in June already.

Regarding the appointments NOT to be deleted: I don't copy paste in Google. That's quite cumbersome - you would have to edit the appointment in order to make a duplicate. I am not quite sure if the other sync program has messed something up with these appointments, so they not sync.

Maybe I was unclear. 
I create an appointment. Then copy it to the day after. When i 1-way sync Outlook to Google, in Google both copy and orignal end up on the same day and time (of the orignal appointment). Solution is to shift sync. I post a log. 
Just repeated it. I noticed, that if i edit the copied appointment it gets synced over correctly. But if I just copy it to another day, the date and time in google will be the same as the original.

![image](https://user-images.githubusercontent.com/5459195/30273910-5ecff8e4-96fb-11e7-807a-849c0ba1e184.png)
![image](https://user-images.githubusercontent.com/5459195/30273349-f10cfeda-96f8-11e7-908d-cc2c2384a026.png)

**Comment by gnubee40** [comment] 2017-09-11 12:02
How do I post the log? It keeps saying that the file type is not supported even though it's txt???

**Comment by phw198** [comment] 2017-09-11 19:40
:spiral_notepad: [Instructions for posting logfile](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file).

**Comment by ionizer5** [comment] 2017-09-11 19:59
i will try to upgrade later tonight and test.  because the alert always said it was a beta, i didnt realize there were later non-beta versions.

@gnubee40 - I was using this for copying from one date to another in the same calendar

Scenario:
Event occurs at 9pm Friday
same event, location, etc is now also occuring 11pm next friday.  It's not reoccuring and you dont know until the next week, so its easier to copy/paste rather than constantly create new meeting and everything

**Comment by gnubee40** [comment] 2017-09-12 08:09
Ok - this seemed to have been a temporary issue? Or maybe the version I ran yesterday was still the old one, as I did not delete it, just ran the new exe file. This time I have renamed the old folder version before running the hotfixed alfa version. 
1. I tried to replicate the error described in my previous post and was unable to do so. The copied appointments now sync with correct time and date both in 1- and 2-way sync regardless of the copied event being edited or not. WELL DONE!

![2017-09-12 09_48_32-ekko - nino emanuel landler regionh dk - microsoft outlook](https://user-images.githubusercontent.com/5459195/30314675-b88185fa-97a1-11e7-8df7-cadf1db0d55b.png)

2. I then copied from sub- to default calendar and 2-way synced again without trouble. 

3, I proceeded to DELETE the test items, NOT in outlook, but this time in GOOGLE. After immediately pressing sync, it would not sync over. First at second sync the deletion request popped up. This is probably because the deletion has to work it's way through google's servers, before it takes effect at sync. 

So overall: everything works as expected. The only remaining issue is those 8 appointments OGCS keeps bugging me to delete, because they are seemingly not affiliated with their google counterparts. But this is probably another issue (might be related though).

**Comment by gnubee40** [comment] 2017-09-12 12:30
I now resolved the other issue by doing a google-> outlook sync.  OGCS deleted the 12 (not 8) appointments it did not recognize in Outlook and replaced them with new versions, which are now linked with the google appointments. I disabled Merge option, which might have helped here. I had to do that for both outlook calendars to resolve the issues.
I notice, that this 1-way sync updates all attributes of synced outlooked appointments with time-zones. But I don't think this attribute missing was the cause, because I saw some of the O appointments syncing fine without having it.
I hope the situation doesn't arise again. For safety I will keep the "Confirm deletions" option checked.

A way to save different sync settings in profiles would be a nice next addition to this good package.

Thanks for the help!

**Comment by ionizer5** [comment] 2017-09-13 01:35
seems going from 2.5.0.0 to 2.6.0.0 is not helping with alpha release b/c i got this originally from codeplex?

guess i have to manually download 2.6.0.0...trying now

**Comment by ionizer5** [comment] 2017-09-13 01:49
ok so finally on the hotfix version.

I copied a friday meeting to the next friday,

when i did, i got some out of memory issue on my pc - i dont have memory issues
so i closed outlook, opened it again

in the sync status window it says:
Object reference not set to an instance of an object.

so i went to get the log file, but there is no log for today's date.  the last log file is OGcalsync.log.2017-09-11.1 from yesterday.

then i realized the date format is no longer used so i found the log:
OGcalsync.log and have attached it

you can see the null reference at the bottom.

[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1297934/OGcalsync.txt)

**Comment by ionizer5** [comment] 2017-09-13 01:50
i've reverted back to the non-hot fix in the interim

**Comment by ionizer5** [comment] 2017-09-13 01:53
PS: when i later check the meeting "A" that i copied from this friday to meeting "B" for next friday:

The meeting "A" was now gone from outlook and gmail and meeting B was the only one there

i know this because i marked meeting B with "Test 2" in the description, in order to differentiate beyond the date.

seems like this one is tricky or did i do something wrong along the way?

**Comment by gnubee40** [comment] 2017-09-14 07:51
@ionizer5 
I use the portable version (cannot install anything on this office machine). I wonder, if your old settings are the problem.

EDIT: Added links on for some of these instructions. It seems that the codeplex versions of OGCS had files different places compared to the github versions. So definitely a good idea to delete the old version including settings.

 I don't think OGCS writes anything in the windows registry? It writes is settings to XML files(?). But if you haven't checked "portable version", it will write this settings in your user profile, not in the program folder. For a fresh start:

1. STOP OGCS (in tray)
2.  rename or delete the old program folder
3.  Purging the old settings 
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Uninstall#removing-any-remnants
4.  download latest alfaversion 2.6.**1** from this github page https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.6.1-alpha/Setup.exe
5.  apply the hotfix (ie. rename old exe file and replace with hotfix version).
Maybe RESTART PC here?
6.  Then start up hotfixed version and apply the correct settings
7.  Then enable "confirm deletions". OGCS will ask for every deletion. But if you press "No" it won't remember it and ask again at next sync.
8.  2-way sync your calendars
9.  see if there are some appointments on either side which do not link (OGCS asks to delete those).
10. If there are, you need to 1-way sync either way. This will create new linked appointments for those not linked. (possibly you need to disable "merge with existing appointments"). Then you can permit to delete the old ones.
11. If all looks in sync, you can repeat your experiment with the copied appointments.

Hope it helps. It really seems to work fine for me now.

Regards

**Comment by phw198** [comment] 2017-09-16 17:23
Thanks for the help here @gnubee40 and confirmation that you believe this is resolved. I spent a large portion of last weekend working on it and really thought I'd cracked it...really hope it is!

You're right the the location of the installed version of OGCS has changed since v2.6, but that _shouldn't_ cause problems with the settings file which is stored in the users roaming profile directory. Looks like @ionizer5 is exclusively using the portable version too, with the portable option checked, so the settings file would be the in the same folder as the ogcs executable.

@ionizer5, looks like the notification to upgrade portable OGCS from v2.5 to v2.6 wasn't working because I'd failed to update the relevant file on CodePlex to trigger this. Too eager to leave CodePlex well behind, but this is now done. :wink: 

The error you got at the end of your test on v2.6.1.8 I think is unrelated to this ticket and been around for several releases. I'm just tidying up some of the code, but hope to have v2.6.2 out by the end of the weekend, if you could then upgrade again.

**Comment by gnubee40** [comment] 2017-10-17 12:33
Hey! Just opened and closed a new issue. Might not be new. Just post it
here for your reference.

https://github.com/phw198/OutlookGoogleCalendarSync/issues/370

Best regards Nino

Mvh
Nino Landler

**Closed as completed** 2017-10-22 15:22 UTC
Labels: bug, medium, resolved
