### ISSUE TITLE
2.9.5.0 Profile Switching Error

### ISSUE THREAD

**Issue by Malli88** [phw198/OutlookGoogleCalendarSync#1487] opened 2022-05-25 06:27 UTC
**OGCS Version**: v2.9.5.0
**Edition**: Installed  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Unhandled reception during profile switch (profile switch is not working)

**Steps to Reproduce the Issue**  
1. Go to Settings
2. Click on Profiles
3. Select a Profile

**Any other information**  
`For information about invoking JIT Debugging
instead of this dialog box, see the end of this message.
```
************** Exception text **************
System.ArgumentException: The items collection cannot be changed if the DataSource property is set.
   at System.Windows.Forms.ComboBox.CheckNoDataSource()
   at System.Windows.Forms.ComboBox.ObjectCollection.Clear()
   at OutlookGoogleCalendarSync.Forms.Main.UpdateGUIsettings_Profile() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 480.
   for OutlookGoogleCalendarSync.SettingsStore.Calendar.SetActive() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Calendar.cs:line 207.
   at OutlookGoogleCalendarSync.Forms.Main.ddProfile_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1073.
   for System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   for System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   for System.Windows.Forms.ComboBox.WndProc(Message& m)
   for System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   for System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
<details>

```
************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4510.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
OutlookGoogleCalendarSync
    Assembly-Version: 2.9.8170.39370.
    Win32-Version: 2.9.5.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/OutlookGoogleCalendarSync.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4488.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4488.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4390.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
log4net
    Assembly-Version: 2.0.12.0.
    Win32-Version: 2.0.12.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/log4net.DLL.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4190.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4470.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
Squirrel
    Assembly-Version: 1.9.0.0.
    Win32-Version: 1.9.0.1.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Squirrel.DLL.
----------------------------------------
Splat
    Assembly-Version: 1.6.2.0.
    Win32-Version: 1.6.2.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Splat.DLL.
----------------------------------------
System.Management
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4435.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly-Version: 2.5.0.0.
    Win32-Version: 2.5.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Log4Net.DLL.
----------------------------------------
Google.Cloud.Logging.V2
    Assembly-Version: 2.3.0.0.
    Win32-Version: 2.3.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.V2.DLL.
----------------------------------------
Google.Protobuf
    Assembly-Version: 3.17.3.0.
    Win32-Version: 3.17.3.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Protobuf.DLL.
----------------------------------------
Google.Cloud.Logging.Type
    Assembly-Version: 2.1.0.0.
    Win32-Version: 2.1.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Cloud.Logging.Type.DLL.
----------------------------------------
Google.Api.Gax
    Assembly-Version: 2.10.0.0.
    Win32-Version: 2.10.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.DLL.
----------------------------------------
Google.Api.CommonProtos
    Assembly-Version: 1.7.0.0.
    Win32-Version: 1.7.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.CommonProtos.DLL.
----------------------------------------
Google.Api.Gax.Grpc
    Assembly-Version: 2.10.0.0.
    Win32-Version: 2.10.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Api.Gax.Grpc.DLL.
----------------------------------------
Google.Apis.Auth
    Assembly-Version: 1.54.0.0.
    Win32-Version: 1.54.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Auth.DLL.
----------------------------------------
Google.Apis.Core
    Assembly-Version: 1.54.0.0.
    Win32-Version: 1.54.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Core.DLL.
----------------------------------------
Grpc.Core
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.22.1.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.DLL.
----------------------------------------
Grpc.Core.Api
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.22.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Core.Api.DLL.
----------------------------------------
Grpc.Auth
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.22.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Grpc.Auth.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 13.0.0.0.
    Win32-Version: 13.0.1.25517.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Newtonsoft.Json.DLL.
----------------------------------------
System.Numerics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll.
----------------------------------------
System.Runtime.Serialization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4455.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll.
----------------------------------------
System.Data
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4455.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.
----------------------------------------
System.Xml.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll.
----------------------------------------
NuGet.Squirrel
    Assembly-Version: 3.0.0.0.
    Win32-Version: 3.0.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NuGet.Squirrel.DLL.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
SMDiagnostics
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4455.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll.
----------------------------------------
System.ServiceModel.Internals
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4455.0 built by: NET48REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll.
----------------------------------------
System.RunTime.Serialization.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Runtime.Serialization.resources.dll.
----------------------------------------
NodaTime
    Assembly-Version: 2.4.13.0.
    Win32-Version: 2.4.13.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/NodaTime.DLL.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
Microsoft.mshtml
    Assembly-Version: 7.0.3300.0.
    Win32-Version: 7.0.3300.0.
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 4.8.4510.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll.
----------------------------------------
System.Web
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4494.0 built by: NET48REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll.
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly-Version: 15.0.0.0.
    Win32-Version: 15.0.4569.1507.
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll.
----------------------------------------
office
    Assembly-Version: 15.0.0.0.
    Win32-Version: 15.0.4613.1000.
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll.
----------------------------------------
Microsoft.CSharp
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll.
----------------------------------------
CustomMarshalers
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll.
----------------------------------------
Google.Apis.Calendar.v3
    Assembly-Version: 1.54.0.2410.
    Win32-Version: 1.54.0.2410.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.Calendar.v3.DLL.
----------------------------------------
Google.Apis
    Assembly-Version: 1.54.0.0.
    Win32-Version: 1.54.0.0.
    CodeBase: file:///C:/Users/mallmann/AppData/Local/OutlookGoogleCalendarSync/app-2.9.5-alpha/Google.Apis.DLL.
----------------------------------------
System.Dynamic
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4084.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll.
----------------------------------------

************** JIT Debugging **************
To enable JIT debugging (Just-In-Time), the following must be specified in the
configuration file of the application or computer
(machine.config), the jitDebugging value must be set in the system.windows.forms section.
The application must be compiled with debugging enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled
exceptions will be sent to the JIT debugger that is registered on the
computer and not handled in this dialog box.
```
</details>

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8768452/OGcalsync.log)

**Comment by phw198** [comment] 2022-05-29 12:05
Duplicate of #1480 which has hotfix posted.

**Closed as not planned by phw198** 2022-05-29 12:05 UTC
Labels: bug, duplicate
