### ISSUE TITLE
Unable to connect to Google - quota exceeded

### ISSUE THREAD

**Issue by julianmk1987** [phw198/OutlookGoogleCalendarSync#1053] opened 2020-08-05 06:33 UTC
Hi Friends,

I received the error (pic attached) when starting the sync. Do you have a solution?

Thanks a lot

![image](https://user-images.githubusercontent.com/69234551/89379530-394f0400-d6f6-11ea-910f-fed135290c70.png)

**Comment by the-programmer** [comment] 2020-08-05 06:57
There is an closed issue https://github.com/phw198/OutlookGoogleCalendarSync/issues/603 mentioning the same problem. From what I can tell there a few options.

1. Wait until the problem resolves itself (every day at 8.00 [timezone] the quota is reset)
2. Follow the instructions here https://github.com/phw198/OutlookGoogleCalendarSync/issues/603#issuecomment-428962128 so you have your own quota
3. Ask @phw198 real nice if he can increase the quota

**Comment by SchietSchijf** [comment] 2020-08-05 07:05
I think it should be option 3 because now everyone is using the same project id. Reset of quota will just allow some people to use this awesome application.

Or option 2 should make it to the official documentation and requirements.

**Comment by julianmk1987** [comment] 2020-08-05 07:06
Thanks, but the real problem is not the quota but the first error: “ERROR : Unable to connect to Google”.

 

Then later, after I tried a couple times, the quota issue appeared.

 


---


Julian Kley


Co-founder & COO


+49 (0) 170 6755506

	

www.avimedical.com <http://www.avimedical.com/> m

**Comment by phw198** [comment] 2020-08-06 00:39
Yeah it's not a quota problem according to Google usage statistics (though there is a warning those stats might be inaccurate until 15 Aug!).

Could you upload your OGcalsync.log file so I can take a closer look?

**Comment by julianmk1987** [comment] 2020-08-06 12:59
Thank you @phw198, it now just works. I tried to identify the error by doing first O -> G and then G -> O instead of O <-> G but both worked individually and then it was fine all of the sudden 👍

**Comment by the-programmer** [comment] 2020-08-06 14:04
@phw198 Attached is the relevant portion of the log. 
[Logfile.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5035275/Logfile.txt)

**Comment by phw198** [comment] 2020-08-19 23:57
Looks like Google have started enforcing a [quota limit](https://developers.google.com/calendar/v3/errors#403_rate_limit_exceeded) in a different way.

:package: Please apply [v2.8.4.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5099920/v2.8.4.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and confirm if the problem goes away. Bear in mind the issue is sporadic, though normally seems to occur around 8-9am GMT.

Please let me know how it goes.

**Comment by the-programmer** [comment] 2020-08-20 06:49
If I try to launch the hotfix I get an exception in launch
![2020-08-20 08_48_29-OGCS](https://user-images.githubusercontent.com/3088971/90726420-f9754880-e2c1-11ea-8b41-554ee42366e7.png)
I guess nuget updated that DLL and you forgot to include it.

**Comment by AllanHejl** [comment] 2020-08-20 07:23
Had the quota issue, installed alpha version 2.8.4 and applied the [hotfix 2.8.4.8](https://github.com/phw198/OutlookGoogleCalendarSync/files/5099920/v2.8.4.8.zip) by following the guide ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
It now works for me, both 1 way and 2 ways without errors.

**Comment by Marek26** [comment] 2020-08-25 07:23
I switched to Version 2.8.4.8 but still encounter the same problem.

**Comment by phw198** [comment] 2020-08-25 19:02
@Marek26 I don't think you are reporting errors to the cloud? Could you upload your logfile for the period you got the error?

**Comment by Marek26** [comment] 2020-08-26 05:55
Hi Paul,

have a look here
https://gist.github.com/Marek26/ae2f453781d48bf44b2f25f35b900fb2

I am using the portable 2.8.4.8 version and tried to apply the hotfix by
copying the new .exe in the folder.
So there may have been a mistake?

Am Di., 25. Aug. 2020 um 21:02 Uhr schrieb Paul Woolcock <
notifications@github.com>:

**Comment by phw198** [comment] 2020-08-26 08:31
@Marek26 The gist you provided doesn't show you using the hotfix, just the alpha v2.8.4.0.

You should have replaced `C:\Users\marek.[...]\Dokumente\OGCS\OutlookGoogleCalendarSync.exe` with the extracted hotfix file.

**Comment by Marek26** [comment] 2020-08-26 08:35
@phw198 I did exactly that. The change date of OutlookGoogleCalendarSync.exe is 20.08.2020 00:54 which is exactly the date from the hotfix exe.
I can try to reproduce the error tomorrow morning.

**Comment by Marek26** [comment] 2020-08-26 08:43
@phw198 **Line 828:** 2020-08-25 08:56:02,466 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.8.4.8

**Comment by Ernst79** [comment] 2020-09-15 07:03
Unfortunately, I still have this issue after updating to 2.8.4.8. The hotfix is installed correctly. 

```
2020-09-15 08:46:56,520 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [0] -  Initialising error reporting to OFF
2020-09-15 08:46:56,544 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.4.8
```
I still get 'Fail' and "Error' messages about the Quato being exceeded. 

```
2020-09-15 08:48:03,127 FAIL  1 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]
```

```
2020-09-15 08:48:03,486 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403]
Errors [
	Message[Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'.] Location[ - ] Reason[rateLimitExceeded] Domain[usageLimits]
]
```

I've send a log file to your google drive.

**Comment by phw198** [comment] 2020-10-04 19:11
Thanks @Ernst79.

:package: ~~Please check if this is now resolved with [v2.8.4.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5324135/v2.8.4.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).~~

Please bear in mind the issue is sporadic, though normally seems to occur around 8-9 AM GMT.

**Comment by phw198** [comment] 2020-10-04 20:03
Actually, I've backed out 1671564 and cherry picked baf999877f02daad0d13e03775b9f0b1f682fef9 from development branch.

:package: Please test with [hotfix v2.8.4.12.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5324254/v2.8.4.12.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please bear in mind the issue is sporadic, though normally seems to occur around 8-9 AM GMT.

**Comment by Ernst79** [comment] 2020-10-05 06:55
Thanks, I've installed it and will keep an eye on it this week. I'll report back later this week.

**Comment by the-programmer** [comment] 2020-10-06 06:22
Attached below a new logfile.
[Logsnippet.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/5331736/Logsnippet.txt)

My solution is usually to delay the sync for 2 hours and everything is fine again. So I wound't mind an option for a extra long delay in case of an Quota exceeded message.

**Comment by Ernst79** [comment] 2020-10-09 06:26
@phw198 Had the following screen this morning, so still hitting the quota limit of the project. 

![image](https://user-images.githubusercontent.com/24375847/95550019-84440b00-0a08-11eb-8526-a5df304226b2.png)

Tip, in the log, you have a link to "get guaranteed quota's". When I follow tis link, I'm immediately directed to a PayPal page. Usually, a buyer would expect an explanation what he is going to buy first.

**Comment by phw198** [comment] 2020-10-10 17:18
Thanks for the feedback.

> So I wound't mind an option for a extra long delay in case of an Quota exceeded message.

@the-programmer When OGCS detects this issue correctly, it should automatically delay the next scheduled sync, as can be seen in the above screenshot.

:package: This issue should now be resolved with [v2.8.4.13.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5359468/v2.8.4.13.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please bear in mind the issue is sporadic, though normally seems to occur around 8-9 AM GMT.

**Comment by CStan77** [comment] 2020-10-16 10:39
@phw198 For my bug 'Multiple Sync Failed #1100 ', I downloaded version 2.8.4.13 but I have a loading error ...
![start_failed](https://user-images.githubusercontent.com/72907176/96248708-44eb6080-0fac-11eb-855b-887b5ece870a.PNG)

I just installed version 2.8.4.0 Alpha with patch 2.8.4.13 I have the same message but in the application
![bug](https://user-images.githubusercontent.com/72907176/96250561-4f5b2980-0faf-11eb-98d8-828aff4061f5.PNG)

**Comment by phw198** [comment] 2020-10-16 11:56
Hi @CStan77 Looks like the libraries across your install have got into a mess. Can you uninstall OGCS (all versions if more than one) and then install v2.8.4 and make sure that can at least load and connect to Google successfully first?

Then apply the patch here on top. If still problems, you could try the portable ZIP for 2.8.4.0 and apply the hotfix directly into the same extracted destination folder - see if that runs better for you.

**Comment by CStan77** [comment] 2020-10-16 15:58
Great !
@phw198 thank you for your quick response. It's super cool!
Indeed, before I had just overwritten my version 2.8.0 by the 2.8.4 and it did not work (token error)
By performing a new 2.8.4 installation with then patching with the 2.8.4.13 exe, this asks me again for the Google Calendar authorization to create the API token.
![sync_auth](https://user-images.githubusercontent.com/72907176/96280811-bb05bc80-0fd8-11eb-87e5-c8da1c97822a.PNG)

THANK YOU !!!!!!!!!!

I will get back to you to tell you if the synchronization problem (API quota) is resolved.

**Comment by CStan77** [comment] 2020-10-23 07:05
that's great ! thank you @phw198 
I just have the google quota alert displayed.
what is this daily value?
![sync_stop](https://user-images.githubusercontent.com/72907176/96966739-aeb8bc80-150e-11eb-896f-c67a72c04750.PNG)

**Closed as completed** 2020-10-25 19:16 UTC
Labels: bug, resolved
