### ISSUE TITLE
Sync is unable to create events on Google

### ISSUE THREAD

**Issue by Sjkoops** [phw198/OutlookGoogleCalendarSync#582] opened 2018-08-30 08:53 UTC
**OGCS Version**: v2.7.6.0  
**Installed or Portable**: Installed

**Problem Description**  
When syncing I recieve an error for each item that it tries to write to google.

New event failed to save.
Forbidden [403=Forbidden]

**Steps to Reproduce the Issue**  
Create a new item in outlook calendar and execute a sync.

**Any other information**  
Using Outlook 2016 (Office365) and Google calendar.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2335392/OGcalsync.log)

**Comment by alfre344** [comment] 2018-08-30 16:10
I get the same thing. I thought this error could be caused by a firewall, but was not able to figure out why and no records where actually transferred.  You can see my test sample it failed on a recurring event and if you press continue, it just loops and never stops.
![2018-08-30 09_05_43-](https://user-images.githubusercontent.com/9186925/44864423-779f3700-ac34-11e8-8fd6-c008093e4fa3.jpg)

**Comment by Sjkoops** [comment] 2018-09-10 07:48
Just tried an older version, but I get the same problem.
Installing this asked me to authorise the app with a code.
I checked the google account rights, there I can see that the app has access to the google account.

The message is a bit different:
![image](https://user-images.githubusercontent.com/42832738/45283547-7c8aa300-b4de-11e8-9803-a58f4a4ee18a.png)

The log file: 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2365637/OGcalsync.log)

Can you tell what is going wrong?

**Comment by Sjkoops** [comment] 2018-09-10 11:32
Found the issue.
It seems that when you authorise your Google calendar, the entry where it says what to sync displays calendar.
It is a dropdown box, once I changed that to the email address instead of the default calendar it started syncing.
After the sync it still show the email address there and all the other options are gone.
![image](https://user-images.githubusercontent.com/42832738/45295016-8ec80980-b4fd-11e8-9150-b71b726ed689.png)

**Comment by phw198** [comment] 2018-09-22 20:36
Thanks for reporting this @Sjkoops. I think the problem is that the first calendar on the drop down list is one that you don't have write access to.

:package: Please could you confirm this by applying [v2.7.6.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2408139/v2.7.6.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and then:
* Opening OGCS
* Clicking the `Retrieve Calendars` button on the Google settings tab
* Upload your `OGcalsync.log` file to this ticket again.

Thanks!

**Comment by phw198** [comment] 2021-04-06 10:56
Later versions of OGCS now clearly warn if trying to write to a read-only Google calendar.

**Closed as completed by phw198** 2021-04-06 10:56 UTC
Labels: old release, triage
