### ISSUE TITLE
 Authenticating with Google Preparing to authenticate with Google. Handshake successful.   Unable to get the list of Google calendars. The following error occurred:  Request had insufficient authentication scopes. [403=Forbidden]

### ISSUE THREAD

**Issue by adiromualdo** [phw198/OutlookGoogleCalendarSync#1987] opened 2024-10-03 17:51 UTC
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11
**Edition**: Installed /
**Sync Direction**: O<->G

**Bug Description**  
I am trying to add a Google Calendar for the first time. When I click "Retrieve Calendars" I get a pop-up that states the retrieval has failed and then it prompts me to test my internet connection. The sync says that the "request had insufficient authentication scopes. [403=Forbidden].

**Steps to Reproduce the Issue**  
1. Go to the Settings tab
2. Click on Retrieve Calendars

**Any other information**  
[OGcalsync.log](https://github.com/user-attachments/files/17248072/OGcalsync.log)

**Comment by phw198** [comment] 2024-10-06 13:14
If you're a new user and downloaded OGCS from the website,  immediately after you should have been taken to https://www.outlookgooglecalendarsync.com/blog/2024/09/01/2-11-0-beta-google-permissions.html

Also a duplicate of https://github.com/phw198/OutlookGoogleCalendarSync/issues/1937 which has a hotfix posted.

**Comment by adiromualdo** [comment] 2024-10-07 13:13
Well as expected this was a me being an idiot problem and not a you problem. I deleted the roaming folder and actually clicked the allow permissions box when I reauthenticated. Thanks for your help!

**Closed as completed** 2024-10-12 11:30 UTC
Labels: bug, duplicate
