### ISSUE TITLE
Deleted item in Outlook (one-way sync) no longer gets removed from Google calendar.

### ISSUE THREAD

**Issue by Comius13** [phw198/OutlookGoogleCalendarSync#1670] opened 2023-06-27 17:52 UTC
**OGCS Version**: v2.9.7.0
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
(This works correctly in 2.9.0.0, but not in 2.9.7.0)
If an outlook item is deleted (or changed to an excluded category) it is no longer deleted/removed from the google calendar.

**Comment by phw198** [comment] 2023-07-02 09:59
Duplicate of #1658 and fixed in v2.10.0

**Comment by lordscarlet** [comment] 2023-07-04 13:47
I don't know if it's the same issue, but I have 2.10.0 and it is showing no deletions, but there are 7 calendar items that have been deleted from my Outlook calendar and are not removed from my Google calendar.

**Comment by lordscarlet** [comment] 2023-07-04 13:56
~I downgraded to 2.9.0 and they are still not getting deleted~

They did in fact delete under 2.9.0

**Comment by phw198** [comment] 2023-07-05 22:38
So are you reporting a deletion in Outlook not removing, or an excluded category not removing?

The latter is fixed in 2.10.0, the former, if it is a deletion of an occurrence in a series, is fixed in #1653.

Try the [hotfix v2.10.0.2](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1653#issuecomment-1616617292) in #1653 and see if that resolves your issue(s).

**Comment by lordscarlet** [comment] 2023-07-11 11:02
Yes, my apologies, the former. I will try out the hotfix, thank you!

**Comment by cinzas** [comment] 2023-08-01 15:00
@phw198. I just copied the hotfix over 2.0.0.9 
It solved the issue, however it prompts to confirm the deletion even if the checkbox for the confirmation is not ticked.

Anyway, it solved the issue and is now deleting the event on google

Still says it is 2.10.0.1 :)
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/29240678/bbeaf008-c514-454a-903a-c7725c083c97)

**Comment by phw198** [comment] 2023-08-06 20:10
:arrow_double_up: Simplest now to upgrade to latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Let me know if the issue still persists.

**Closed as completed** 2023-09-13 08:35 UTC
Labels: bug, duplicate, dormant

**Comment by CC-70300** [comment] 2023-10-20 02:47
hi, I try the v2.10.1 version but still there are items deleted in Outlook not deleted in Google (one way sync Outlook -> Google)
Specifically, those items are Outlook invitation from others, not created by me in Outlook

**Comment by phw198** [comment] 2023-10-23 22:44
@CC-70300 Please raise a new issue and provide your log file for investigation.
