### ISSUE TITLE
412 Error

### ISSUE THREAD

**Issue by Robert-Heggett** [phw198/OutlookGoogleCalendarSync#1522] opened 2022-08-11 10:57 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.5.0
**Installed or Portable**: Installed

**Problem Description**  
Keep getting the error following error multiple times every time synch runs

Updated event failed to save.
Precondition Failed [412=PreconditionFailed]

**Steps to Reproduce the Issue**  
1. Start synch
1. 

**Any other information**  
Noticed this in the last 2 weeks

**Comment by phw198** [comment] 2022-08-16 23:48
Duplicate of #528

**Closed as completed by phw198** 2022-08-16 23:48 UTC
Labels: duplicate
