### ISSUE TITLE
Google event update failed????

### ISSUE THREAD

**Issue by mrdantzig** [phw198/OutlookGoogleCalendarSync#1439] opened 2022-04-20 02:29 UTC
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8517788/OGcalsync.log)
![image](https://user-images.githubusercontent.com/52942095/164134943-a2d74ec2-67d8-42a0-b40d-0fe0a92d90f3.png)
![image](https://user-images.githubusercontent.com/52942095/164134961-5b169617-5d32-4dd5-ba59-8fea5f10812a.png)
![image](https://user-images.githubusercontent.com/52942095/164134974-25afaf4b-ad09-44c4-974d-2397b366b734.png)

**Comment by anders-m** [comment] 2022-04-20 14:15
I have the same problem (I think, because I dont understand the languige from the screenshot). The log is attached:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8522224/OGcalsync.log)
.

**Comment by WarningU2** [comment] 2022-04-20 17:10
Having the same issue restarting the application does not resolve the issue.   Continuing the sync appears to get you past it sometimes until the next sync where it abends on the same event.    Now the event causing an abend each time so the app is unusable.  Stopping and awaiting fix.   **Product is no longer usable.**  

The event Angus Irrigation just triggered ... time popped.  

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8523714/OGcalsync.log)

2022-04-20 13:04:41,116 INFO  12 OutlookGoogleCalendarSync.Console [282] -  Comparing 64 existing Google calendar entries
2022-04-20 13:04:44,495 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 2022-04-20 **12:00 PM => "Angus Irrigation"**
2022-04-20 13:04:44,524 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  **Event update failed.**
2022-04-20 13:04:44,525 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-04-20 13:04:44,545 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-20 13:04:44,546 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-04-20 13:04:44,546 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557


Note  I have version 2.9.4.0  applied now after applying 2.9.3.11 earlier to troubleshoot another issue.

**Comment by WarningU2** [comment] 2022-04-20 17:20
Went back to 2.9.0.0 and all is correct with the world.

**Comment by MAC69Lyon** [comment] 2022-04-21 08:00
I have had the same concern and also went back to 2.9.0.0 Alpha and all is OK

**Comment by khobar** [comment] 2022-04-22 08:24
Hi having same issues with latest alpha 2.9.4

```
2022-04-22 09:45:02,950 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1046] -  Scanning 36 Google events for orphans to reclaim...
2022-04-22 09:45:02,952 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1096] -  0 unclaimed.
2022-04-22 09:45:03,212 DEBUG  12 OutlookGoogleCalendarSync.Sync.Engine+Calendar [506] -  Synchronising from Outlook to Google.
2022-04-22 09:45:03,214 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1173] -  Comparing Outlook items to Google events...
2022-04-22 09:45:03,215 INFO  12 OutlookGoogleCalendarSync.Console [282] -  Matching calendar items...
2022-04-22 09:45:04,150 INFO  12 OutlookGoogleCalendarSync.Console [282] -  1 Google calendar entries to be deleted.
2022-04-22 09:45:04,152 INFO  12 OutlookGoogleCalendarSync.Console [282] -  0 Google calendar entries to be created.
2022-04-22 09:45:04,153 INFO  12 OutlookGoogleCalendarSync.Console [282] -  35 calendar entries to be compared.
2022-04-22 09:45:04,186 INFO  12 OutlookGoogleCalendarSync.Console [282] -  Deleting 1 Google calendar entries
2022-04-22 09:45:04,449 DEBUG  12 OutlookGoogleCalendarSync.Console [280] -  2022-04-21 13:00 (R) "<REDACTED>"
2022-04-22 09:45:04,941 INFO  12 OutlookGoogleCalendarSync.Sync.Engine+Calendar [561] -  Done.
2022-04-22 09:45:04,941 INFO  12 OutlookGoogleCalendarSync.Console [282] -  Comparing 35 existing Google calendar entries
2022-04-22 09:45:04,963 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 2022-05-17 13:00 => "<REDACTED>"
2022-04-22 09:45:05,117 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-04-22 09:45:05,119 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-04-22 09:45:05,187 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-22 09:45:05,188 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-04-22 09:45:05,190 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-04-22 09:45:05,191 DEBUG  12 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
2022-04-22 09:45:05,255 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-04-22 09:45:06,466 DEBUG  12 System.Windows.Forms.OgcsMessageBox [87] -  Response: Yes
2022-04-22 09:45:06,470 DEBUG  12 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 2022-05-16 15:00 => "<REDACTED>"
2022-04-22 09:45:06,532 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-04-22 09:45:06,534 ERROR  12 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-04-22 09:45:06,571 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-22 09:45:06,573 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-04-22 09:45:06,574 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
```

**Comment by MAC69Lyon** [comment] 2022-04-22 09:37
No problem with Alpha version 2.9.0.0 !

**Comment by MarHelmer** [comment] 2022-04-23 02:13
Confirmed same issue on the brand-new v2.9.4 Alpha branch.  Here's another screenshot with the GUI's error output:
![2022-04-22 22_12_27-Outlook Google Calendar Sync - Joint](https://user-images.githubusercontent.com/36488074/164865422-85133bde-b317-4e58-81b4-c61e022063d1.png)

**Comment by anders-m** [comment] 2022-04-23 07:16
Is this the same problem as #1422 ? I ude Outlook colors a and will try the hotfix.

**Comment by phw198** [comment] 2022-04-23 14:47
Yes, it's a duplicate of #1422 which has a hotfix.

**Closed as completed** 2022-04-23 14:47 UTC
Labels: bug, duplicate

**Comment by mrdantzig** [comment] 2022-04-24 00:42
Good to hear that it's already resolved with hot fix. Please let me know where I can get the hotfix.

**Comment by mrdantzig** [comment] 2022-04-24 01:29
I've just applied the [hotfix v2.9.4.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8508550/v2.9.4.3.zip)  and it worked well. Thanks!
