### ISSUE TITLE
Copied/pasted event in Outlook doesn't sync to Google Calendar; Delete action attempted

### ISSUE THREAD

**Issue by mhowie22** [phw198/OutlookGoogleCalendarSync#924] opened 2019-12-14 14:47 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.2.0
**Installed or Portable**: Installed

**Problem Description**  
Discovered a bug when syncing bi-directionally between Outlook and Google Calendar- specifically, when one creates a new event (appointment) within Outlook by using an existing event (i.e., copy and paste an existing event into a new timeslot), the event is not synced to Google Calendar. 
In addition, and perhaps more concerning, OGCS will then actually delete this event in Outlook as the Outlook <--- Google sync process runs. It seems as if Google Calendar sort of recognized the event but since it didn't actually get synced over is viewed as a deleted event within Google and, therefore, the deletion process occurs.

**Steps to Reproduce the Issue**  
1. Repeatable

**Any other information**  
Can provide logfile via email. Today's version- with the reported bugs- would be available at midnight local as it appears OGCS creates a debug log daily at that time as I view the files available via the "Open Log" selection. I've pasted a representative sync screen below- each one of the entries under the Outlook <--- Google sync section are active Outlook events which were created by copying/pasting events of the same name (truly a copy/paste to a different date).

![image](https://user-images.githubusercontent.com/58883534/70850263-60e71880-1e56-11ea-9c44-3139c6b738e4.png)

**Comment by mhowie22** [comment] 2019-12-18 22:21
Is additional detail required or is this being investigated? I'm unsure how the bug verification/resolution process works with OGCS. Thanks.

**Comment by phw198** [comment] 2019-12-27 12:14
It's a documented [known issue](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#copied-outlook-appointments-cause-unexpected-deletions) - you need to make sure OGCS is running (and not actively syncing) when copy and pasting.

**Comment by YasharF** [comment] 2020-02-20 20:24
Is there a way to potentially address this known issue?  I missed an appointment earlier which I knew I had copied from its last occurrence to an upcoming timeslot.

My workflow doesn't involve having Outlook running all of the time and hence I don't have OGC running all the time either.  Sometimes I forget to open OGC after opening Outlook and it looks like the human error from my end to not copy calendar entries while OGC isn't open might be inevitable.

**Comment by Lusayalumino** [comment] 2020-03-05 12:31
Hi Yashar, FYI: I've been working on this with phw198 here at #946 https://github.com/phw198/OutlookGoogleCalendarSync/issues/946#issuecomment-586654986

**Comment by phw198** [comment] 2020-03-08 17:28
@YasharF So the issue is, some code needs to run to clean out the OGCS properties from a manually copied item in Outlook. Options currently are:

1. Ensure OGCS is running in the background to execute the necessary code
     1. Set OGCS to start on startup and leave in the background (eg start in task tray)
     1. Set OGCS to start whenever Outlook is started ([VBA code available](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Hints-&-Tips#start-ogcs-after-outlook))
1. Deploy some VBA code into Outlook that runs the equivalent code normally run by OGCS.
     1. This doesn't exist yet, but I'm playing with this option now - if people really don't want OGCS runing in the background, then this would be the only sure-fire way of avoiding the issue.

**Comment by Lusayalumino** [comment] 2020-03-08 23:09
As an fyi, I have an issue when starting my computer where I'm asked to "Allow" OGCS ... but it asks me about 5-8 times... so I set the "Start on login, with delay of" to the max of 300 seconds. Is this possibly part of my problem on https://github.com/phw198/OutlookGoogleCalendarSync/issues/946

**Comment by YasharF** [comment] 2020-03-09 09:37
I like option 2, assuming that the user isn't required to manually trigger the VBA code.
Other sync and export/import software that I have used, had some add-on components that sat within Outlook: MyPhoneExplorer, CodeTwo.  Before installing OGCS, I thought it is an add-on as well.

**Comment by phw198** [comment] 2020-03-29 22:38
@Lusayalumino I guess the delay could be part of the problem if you copy and paste an appointment during that delay when OGCS isn't actually running?

@YasharF OK, I've finally got round to completing that VBA code! [Posted up](https://github.com/phw198/OutlookGoogleCalendarSync/tree/outlook-vba) with some documentation on how to deploy it - let me know if you use it and how it goes...

**Comment by YasharF** [comment] 2020-03-30 15:56
I just followed the instructions, a few notes:
- Alt-F11 may not work for users that have [Nvidia drivers](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_excel-mso_win10-mso_2016/altf11-is-not-working-to-open-the-developer-tab-in/0a2079d9-b24e-4138-871e-780a9f02a91e). The users can open VBA by enabling the [Developer Tab](https://support.office.com/en-us/article/show-the-developer-tab-e1192344-5e56-4d45-931b-e5fd9bea2d45), and clicking on the VBA icon.
- Regarding ogcsDirectory config, it sounds like that every time that the user installed a new version/update of OGCS, then they will need to manually go in the VBA code and change the config, is that correct?  That can cause its own set of issues; I'm not sure what the best solution would be there.
- Unsigned Macros are disabled in Outlook by default, and the instructions and the macro as is don't work. I tried the code with lowering my security settings to "Notification for all macros", and it looks like that it runs now.  I also looked into self-signing the certificate, but there are a lot of steps involved in creating a certificate, installing it as a trusted certificate in Windows, and signing the code.  I suspect that may create friction for adoption.
![image](https://user-images.githubusercontent.com/6448697/77930678-0ab0b080-7260-11ea-8fbd-70423a6fe3f8.png)
- When Outlook starts, and the VBA code is executed, it opens the OGCS as a maximized window in front of the user blocking the Outlook window.

**Comment by YasharF** [comment] 2020-03-30 19:41
Reporting back: It looks like it is trying to delete an appointment that I copied about a couple of hours ago.  It looks like it took more than an hour for it to decide to delete the appointment:
![image](https://user-images.githubusercontent.com/6448697/77952810-15c80880-7281-11ea-842c-63a823363037.png)


**The copy event:**
```
2020-03-30 10:52:29,349 INFO  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Item paste event caught.
2020-03-30 10:52:29,365 DEBUG  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  We've got 1 items selected for copy.
2020-03-30 10:52:29,379 FINE  24 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:52:29,380 DEBUG  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  3/18/2020 4:00 PM => "SLG Budget"
2020-03-30 10:52:29,482 INFO  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Temporarily removing OGCS properties from copied Outlook appointment item.
2020-03-30 10:52:29,498 FINE  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Backing up googleCalendarID
2020-03-30 10:52:29,511 FINE  24 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Backing up googleEventID
2020-03-30 10:52:29,585 DEBUG  24 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Removed googleEventID property.
2020-03-30 10:52:29,634 DEBUG  24 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Removed googleCalendarID property.
2020-03-30 10:52:29,741 FINE  24 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Set userproperty locallyCopied=True
2020-03-30 10:52:31,765 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Repopulating IDs to original copied Outlook item
2020-03-30 10:52:33,767 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Untagging copied Outlook item
2020-03-30 10:52:33,799 FINE  8 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:52:33,801 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  3/31/2020 4:00 PM => "SLG Budget"
2020-03-30 10:52:33,938 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Removed locallyCopied property.
2020-03-30 10:52:34,094 FINE  8 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:52:34,095 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  3/31/2020 4:00 PM => "SLG Budget"
2020-03-30 10:52:34,134 FINE  8 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:52:34,135 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  3/31/2020 4:00 PM => "SLG Budget"

...

2020-03-30 10:54:26,236 FINE  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:54:26,237 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  3/31/2020 4:00 PM => "SLG Budget"
2020-03-30 10:54:26,251 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleCalendarID=yas****@****.com
2020-03-30 10:54:26,264 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleEventID=5rkpr966rm44l3loancl83ofcg

...

2020-03-30 10:54:30,434 FINE  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google Event ID
2020-03-30 10:54:30,520 FINE  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google Calendar ID
2020-03-30 10:54:30,572 FINE  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 10:54:30,573 FINE  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Checking 3/31/2020 4:00 PM => "SLG Budget"
```

**and now:**
```
2020-03-30 12:20:00,403 FINE  26 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2020-03-30 12:20:00,405 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  3/31/2020 4:00 PM => "SLG Budget"
2020-03-30 12:20:00,421 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleCalendarID=yas****@****.com
2020-03-30 12:20:00,434 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleEventID=5rkpr966rm44l3loancl83ofcg
2020-03-30 12:20:00,494 FINE  26 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event

...

2020-03-30 12:20:00,784 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  0 unclaimed.
2020-03-30 12:20:00,784 DEBUG  26 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google events to Outlook items...
2020-03-30 12:20:00,784 DEBUG  26 OutlookGoogleCalendarSync.Console [0] -  Matching calendar items...

...

2020-03-30 12:20:04,416 INFO  26 OutlookGoogleCalendarSync.Console [0] -  1 Outlook calendar entries to be deleted.
2020-03-30 12:20:04,417 INFO  26 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be created.
2020-03-30 12:20:04,417 INFO  26 OutlookGoogleCalendarSync.Console [0] -  12 calendar entries to be compared.
2020-03-30 12:20:04,486 INFO  26 OutlookGoogleCalendarSync.Console [0] -  Deleting 1 Outlook calendar entries
2020-03-30 12:20:04,499 FINE  26 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event

**Comment by YasharF** [comment] 2020-03-30 19:58
I am looking at my google calendar, and it looks like even though at 10:52 a copy event was recognized, it never created the event in my Google Calendar.

Clarification: I didn't copy the appointment, I moved it from 3/18 (past) to 3/31 (tomorrow).
I haven't said No to the above prompt and not closed it yet and it looks like the appointment at the old date (3/18) is still there in the google calendar, while it is showing on the new date of 3/31 in Outlook.  OGSC is trying to delete the new one in Outlook on 3/31.

**Comment by Lusayalumino** [comment] 2020-03-31 13:34
I'm really glad you guys are still working on this. FYI: I have an NVidea GPU. I've disabled OGCS for now -- it just wasn't usable until this is resolved. I hope you figure it out!

**Comment by YasharF** [comment] 2020-04-03 19:56
Another update, the delete prompt above for that appointment kept reappearing since my last update with every sync.  I have been choosing No. This morning I moved that appointment to noon today when OGCS was open.  Walked away for about an hour and now I see that at 11:30ish it tried to do a sync and the delete confirmation for the new timeslot of noon today is now popping up.

![image](https://user-images.githubusercontent.com/6448697/78399883-99983280-75aa-11ea-8324-514a4eaeded4.png)

**Comment by phw198** [comment] 2020-04-12 12:42
@YasharF Thanks for the feedback :+1: 

* Developer tab instructions added to readme
* OGCS config - now points to installation shortcut which should need updating so much
    * Alerts if OGCS executable doesn't exist in specified location
* Code added to set window initialisation size
* Macro instructions don't work? They say to select at least "Notification for all macros" which you said worked?
   * I could investigate code-signing, but don't want to burn too much time on this before knowing the  overall approach is viable

**Comment by phw198** [comment] 2020-04-12 12:58
@YasharF ~~Oh my....this is a huge bug! A move is being detected as a copy event - I'll track this one over on #912 where I never reached this conclusion.~~

**Comment by phw198** [comment] 2020-04-12 13:43
@YasharF Seems I jumped the gun there...slightly relieved as that bug would have been rather an oversight.

So after the item is moved or copied, the _original_ item OGCS properties are then restored (one and the same item in the case of a move).
```
2020-03-30 10:52:31,765 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Repopulating IDs to original copied Outlook item
2020-03-30 10:54:26,237 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  3/31/2020 4:00 PM => "SLG Budget"
2020-03-30 10:54:26,251 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleCalendarID=yas****@****.com
2020-03-30 10:54:26,264 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleEventID=5rkpr966rm44l3loancl83ofcg
```
So we need to figure out why the eventID of the Google item has changed. Could you turn on CSV export in OGCS settings - then when you get a delete prompt, check the `google_events.csv` file and see what the EventId is, whether this has changed and therefore whether it still matches Outlook (`5rkpr966rm44l3loancl83ofcg` in your previous example).

**Comment by YasharF** [comment] 2020-04-12 17:33
To answer your question, I don't see the event in google_events.csv

I think I figured out how to trigger the issue reliably, at least for one case.  The prerequisite is that the old items must have got synced before, but it is no longer within the date range that OCGS syncs at the time the appointment is being moved.

Steps to reproduce it:
1. Under the settings change Sync Options->When->Date range to be longer.  For example, if it is set to 5 days in the past, then set it to 10 days. Press Save.
2.  Under the Sync tab, press Start Sync in OGCS and wait until it finishes.
3.  Create an event in Outlook named `test-past` in a timeslot 7 days ago.
4.  If the sync hasn't started automatically, press Start Sync in OGCS and wait until it finishes.  It is OK to sync multiple times if not sure.
5.  Open calendar.google.com and verify that the `test-past` appointment has been created in the timeslot that was 7 days ago.
5. In OGSC, under the settings change Sync Options->When->Date range to be the original number of days.  For example, back to 5 days. Press Save.
6. In Outlook, move the test-past appointment from 7 days ago to tomorrow.
7.  If the sync hasn't started automatically, press Start Sync in OGCS and wait until it finishes
8.  Repeat sync in step 7 and press Start Sync a second time.
At this point, OGSC will (attempt to) delete  `test-past` from tomorrow's timeslot.

It looks like that the sync in step 7, is not putting anything in the calendar for tomorrow, and step 8 thinks 7 has worked but it doesn't see the appointment in Google and it concludes it must have got deleted in Google so it needs to be removed from Outlook as well.

In the above test scenario, we are changing the sync range, but in practice, time will pass and items will move outside of the sync period on their own.

Looking at Google Calendar the appointment that was 7 days ago is still there and hasn't moved.  I tried a couple of more steps after the ones above to cover potentially similar edge cases such as if the user has multiple computers with OGSC and different sync ranges, or if the user reinstalls OGSC and ends up with a different sync range (aka the default range in case if they had customized their settings):
9.  After step 8, and deletion of `test-past` from tomorrow in Outlook, go in the settings and change Sync Options->When->Date range to be a longer range, such as 10 days.
10.  If the sync hasn't started automatically, press Start Sync in OGCS and wait until it finishes

At this point, OGSC will (attempt to) delete the original `test-past` in Google Calendar from 7 days ago as well, and all traces of the original and the new appointment will be gone from both Outlook and Gmail.

The same issue might be applicable for appointments that are far out in the future when it comes to the "days in future" sync date range, but I haven't done any testing for that case.

**Comment by phw198** [comment] 2020-05-05 12:15
Thanks for the analysis @YasharF - yes certainly when calendar items move across sync window date bounds, what you describe will occur. For moves in Outlook, I have put in some detection of this and automatically adjust the sync window ranges to accomodate the moved item.

:package: If you could do some testing with [hotfix v2.8.3.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4580660/v2.8.3.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) it'd be greatly appreciated.

Note, for moves in Google, I don't think it's possible to detect the equivalent. I have started [capturing known limitations in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Limitations).

**Comment by YasharF** [comment] 2020-05-05 15:10
Does hotfix 2.8.3.8 include he fix in hotfix 2.8.3.1?  I'm currently running the 2.8.3.1 hotfix.  If it doesn't do you think if you can cut a release with all of the hotfixes?

Another potential change that might reduce the chances of someone running into an issue might be to increase the default sync window.  I have changed mine to 90 days for now.  I don't know what the best number would be but have entertained the idea of increasing it to match my Outlook Calendar Archive setting which is 6-months.

**Comment by phw198** [comment] 2020-05-05 16:45
:package: I've pulled the release branch into this fix, so you'll now have all the latest fixes with [v2.8.3.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4582243/v2.8.3.9.zip).

Please let me know how it goes.

(Note, we turned off the default O365 6-month archive for calendar items because it annoyed the business so much! Makes sense for email, less so for calendars).

**Comment by phw198** [comment] 2020-06-14 20:36
Hi @YasharF any further feedback on v2.8.3.9?

**Comment by YasharF** [comment] 2020-06-18 01:08
I haven't noticed any breaking issues.
There are a couple of minor UX issues, but I wouldn't consider them blockers:
1. The VBA script always tends to pop a security warning in Outlook on startup.  I can live with that.
2. The VBA script opens the OGSC as a maximized window covering the entire monitor screen.

Thanks for the great work.

**Closed as completed** 2020-06-24 14:19 UTC
Labels: enhancement, resolved
