### ISSUE TITLE
copied calendar items do not sync

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#226] opened 2017-06-01 19:17 UTC
One outlook, I often "copy" {ctrl-c} and paste {ctrl v} an event from one day to another, and change a few of the details.  this is easier than setting a recurring event if it only happens once or twice or on an odd pattern.  these events do not sync using OGC

**Comment by phw198** [comment] 2017-06-03 22:01
Are you two-way syncing? I can't replicate this when copying an Outlook item and syncing - the copy syncs across to Google fine.

If you are two-way syncing, I think this is a duplicate of issue #224, though this is reporting deletion of the copy instead of syncing it.

**Comment by jlrose13** [comment] 2017-06-04 01:12
#224 seems very similar.  I just ran these tests.  #3 may be key to this:
1) Created new event.  ctrl-c/ctrl-v to copy/paste same even to two new dates.  This test worked.

2) Copied existing event.  ctrl-c/ctrl-v to new date.  old event deleted.  new event never synced.  

3) Created new event.  ctrl-c/ctrl-v to copy/paste same even to two new dates.  Deleted the copied event.  copy/paste original event to third date.  Sync caught deletion but did not create new/third event.  

Is it possible that once an event has been synced, it is categorized somehow as "already copied" and the sync does not include it as new.  Therefore a copy/paste would in effect be creating what the software recognizes as an "old" event and not sync it?

I am on two way sync

**Comment by phw198** [comment] 2017-06-05 22:53
Yep, I'm pretty confident this is the same issue, so I'll close this one as a duplicate - please follow updates on #224.

**Closed as completed** 2017-06-05 22:53 UTC
Labels: duplicate
