### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by joncy92** [phw198/OutlookGoogleCalendarSync#1814] opened 2024-03-05 16:57 UTC
**Is your feature request related to a problem? Please describe.**
OGCS can obviously run only when my PC is powered on and outlook is running. For those times when I'm on the road and can't load up my PC my calendars fall far out of sync

**Describe the solution you'd like**
A docker build of this would mean it can run minimalistic and on a server 24/7

**Describe alternatives you've considered**
A windows machine powered on 24/7 but this is obviously not appropriate

**Comment by phw198** [comment] 2024-03-16 14:26
Except that the current version of OGCS needs the Outlook client installed and COM reportedly doesn't work properly on server versions (intentionally by MS).

This is a duplicate of #1563

**Closed as completed by phw198** 2024-03-16 14:26 UTC
Labels: duplicate, enhancement
