### ISSUE TITLE
Crashing everytime I run

### ISSUE THREAD

**Issue by jeffwash** [phw198/OutlookGoogleCalendarSync#842] opened 2019-09-13 14:14 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Every time I run the Sync, it crashes.  No error messages, just simply goes away.  I restart the app, and same thing.  If I go to the google settings, disconnect the account, and reconnect it works.  When I shut down it does it again.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2019-09-13 14:59
No log file = no support. Especially when not even specifying the version of OGCS being used.

If it is legitimately crashing you might need to check your Windows Event Viewer application log for an associated entry.

**Comment by jeffwash** [comment] 2019-09-13 17:16
Hi Paul,

I’m using version 2.8.1.0.  Attached is the log.

I found these items in the event viewer:

Application: OutlookGoogleCalendarSync.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getCalendarClientSecrets() at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.spawnOauth() at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<GetAuthenticated>b__14_0() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: OutlookGoogleCalendarSync.exe, version: 2.8.1.0, time stamp: 0x5d46bdb8
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0685fe88
Faulting process id: 0xc810
Faulting application start time: 0x01d56a3c8364071d
Faulting application path: C:\Users\jeff\AppData\Local\OutlookGoogleCalendarSync\app-2.8.1-alpha\OutlookGoogleCalendarSync.exe
Faulting module path: unknown
Report Id: 8943b41f-274e-4383-ac9e-c79667c29031
Faulting package full name:
Faulting package-relative application ID:

**Comment by phw198** [comment] 2019-10-20 12:58
Duplicate of (your?) ticket #855 and resolved #793.

Reinstall v2.8.1 or upgrade to v2.8.2

**Closed as completed by phw198** 2019-10-20 12:58 UTC
Labels: duplicate
