### ISSUE TITLE
Check for update fails after updating to 2.7.0.0

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#633] opened 2018-11-26 18:24 UTC
Check for update fails after updating to 2.7.0.0
```
2018-11-26 11:02:05,141 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'CompletedSyncs' updated to '12389'
2018-11-26 11:02:05,141 INFO  1 OutlookGoogleCalendarSync.Console [0] -  Sync finished with success!
2018-11-26 11:02:05,172 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '11/26/18 11:01:57 AM'
2018-11-26 11:02:05,172 INFO  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Next sync scheduled for November 26, 2018 - 1:01:57 PM
2018-11-26 11:02:05,172 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Registering for Outlook appointment change events...
2018-11-26 11:02:05,172 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Create the timer for the push synchronisation
2018-11-26 12:20:49,954 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Manual update check requested.
2018-11-26 12:20:49,954 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Removing proxy usage.
2018-11-26 12:20:49,954 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Checking for Squirrel update...
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.Updater [0] -  Failed checking for update.
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Net.Http.HttpRequestException: An error occurred while sending the request.
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131500;-2146233088
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  InnerException:-
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131509;-2146233079
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OutlookGoogleCalendarSync.Updater.<githubCheck>d__12.MoveNext()
2018-11-26 12:20:50,048 ERROR  1 OutlookGoogleCalendarSync.Updater [0] -  Failure checking for update. Object reference not set to an instance of an object.
```

**Comment by phw198** [comment] 2018-11-26 22:10
[Already documented](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-wont-ogcs-upgrade-i-know-theres-a-later-version-released) known issue.

Duplicate of #497.

**Closed as completed by phw198** 2018-11-26 22:10 UTC

**Comment by kwagner115** [comment] 2018-11-26 22:12
thx

**Comment by phw198** [comment] 2018-11-26 22:19
Yeah, it's going to be a nightmare when the next beta release comes out :cry:
