### ISSUE TITLE
Cannot find shared folder when opening

### ISSUE THREAD

**Issue by JohnJ62** [phw198/OutlookGoogleCalendarSync#211] opened 2017-05-21 21:17 UTC
Whilst this worked on my old XP laptop , it doesnt now on my Win 10 laptop. On opening I keep getting the message "could not find shared calendar".

Whilst I do not get that message on the old XP, now it also does not sync properly and has the same error messages, trying to delete every calendar entry as if nothing found to sync to.

XP was using Outlook 2003. Now trying this with Win 10 and using Outlook 2013 and in both cases the calendar is linked to a pop email account which is the default.

Any ideas how to get this to "find" the outlook calendar?...which I assume is what it is saying.

I have compared the settings in each and they do appear identical.

Many thanks﻿
John

**Comment by phw198** [comment] 2017-05-22 12:17
:page_facing_up: Thanks for posting - please provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by JohnJ62** [comment] 2017-05-22 23:42
Version 2.4.0.0

Problem proiduced when OGCS opened

Yes, happens eveey time opened. Displays dialofue box as:

Could not find shared calendar for".

 

I was using this on a XP laptop with Outlook 2003 and a pop related email calendar and it worked fine. Now on a WIn10 laptop with Outlook 2013, again with the same calendar linked to a pop email. The settings look the same.

 

I get this warning and then as it hasn't found the calendar. Then when starting the sync it attempts to delete all existing entries...and I have to click no to all dialogue box "Delete Confirmation" selection boxes as each is shown. There are many (last time I counted the "No" options I had to click and there were 53) and some times after reaching the end of them all it simply goes around again...and again and cycles through the whole set of entries prompting me to delete them, the same quantity again and again.

 

It does pass new entries from the calendar to the phone's google calendar and in reverse when last tested.

 

Sometimes I get a "Outlook appointment update failed. Continue with synchronisation?" message and if I click "Yes" find it's at the end anyway. The last entry the states "Sync finished with success!" 

 

I have attached one undated text file and the most recent dated "log" file having cagnged it to a txt file.

 

Many thanks

 

John

**Comment by phw198** [comment] 2017-05-22 23:56
Thanks for the extra detail, though I don't think you can attach your logfile to the Issue ticket when replying by email. Please login to GitHub and attach the file within the comment section at the bottom.

**Comment by JohnJ62** [comment] 2017-05-23 00:13
Hi Paul,Thanks, yes I did that. Hopefully it should be there for you to see. The same 2 files that I copied to you in the email. You should hopefully have everything now. The two files are one txt file and one .log file that has the most recent date. Again, many thanksJohn

**Comment by phw198** [comment] 2017-05-23 12:28
![image001](https://cloud.githubusercontent.com/assets/11843015/26354152/5da118aa-3fbb-11e7-9505-5bee69340a5f.png)

[Logfile](https://gist.github.com/phw198/dc665799d79fcc7e3fc3708c8afc9924#file-ogcalsync-log-L39-L40) as provided by another user.

**Comment by phw198** [comment] 2017-05-23 18:27
:package: This should now be resolved with [Hotfix-v2.4.0.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1023281/Hotfix-v2.4.0.3.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by phw198** [comment] 2017-06-01 10:05
@JohnJ62 Are you able to confirm if the issue is resolved for you with the hotfix posted above?

**Comment by JohnJ62** [comment] 2017-06-03 13:07
Hi Paul,

 

I regret not as I cannot see a hotfix above?

 

Thanks

 

John

**Comment by phw198** [comment] 2017-06-03 19:30
Given you've replied to the GitHub email notification, I can only assume you haven't actually [checked the Issue on GitHub](https://github.com/phw198/OutlookGoogleCalendarSync/issues/211#issuecomment-303490046)...

Never mind - the fix was rolled in to v2.5.0 which has just been released and you should be able to upgrade to.

**Closed as completed by phw198** 2017-06-03 19:30 UTC
Labels: bug, low, resolved
