### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Rosmaninho** [phw198/OutlookGoogleCalendarSync#1180] opened 2021-02-27 20:11 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

Everytime that OGCS goes through the scheduled syncing it fails at the first automated try and I always need to tell it to retry.

**OGCS Version**: v.2.8.6  
**Edition**: Installed 
**Sync Direction**: O->G 

These are the relevant lines in the log file:
```
2021-02-27 20:01:33,268 DEBUG  7 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [226] -  Getting active window inspector
2021-02-27 20:01:33,272 DEBUG  7 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [231] -  Done.
2021-02-27 20:01:33,291 DEBUG  7 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [63] -  Get the folders configured in Outlook
2021-02-27 20:01:33,296 DEBUG  7 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [317] -  Finding shared calendar
2021-02-27 20:01:33,302 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2021-02-27 20:01:33,303 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: getCalendarStore() in OutlookNew.cs:317:17
2021-02-27 20:01:33,304 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.getCalendarStore(NameSpace oNS) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 317
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.Connect() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 66
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.Reset() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 77
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetCalendarEntriesInRange(Boolean suppressAdvisories) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 126
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 371
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass24_0.<Start>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 218
2021-02-27 20:01:33,305 ERROR  7 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2021-02-27 20:01:39,173 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [208] -  User opted to retry sync straight away.
2021-02-27 20:01:39,174 INFO  3 OutlookGoogleCalendarSync.Console [282] -  Finding Calendar Entries
2021-02-27 20:01:39,182 INFO  3 OutlookGoogleCalendarSync.Console [282] -  Scanning Outlook calendar...
2021-02-27 20:01:39,437 FAIL  3 OutlookGoogleCalendarSync.OGCSexception [21] -  System.NullReferenceException: Object reference not set to an instance of an object.
2021-02-27 20:01:39,438 FAIL  3 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: GetCalendarEntriesInRange() in OutlookCalendar.cs:104:13
2021-02-27 20:01:39,438 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [75] -  Resetting connection to Outlook.
2021-02-27 20:01:39,439 DEBUG  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [115] -  De-referencing all Outlook application objects.
2021-02-27 20:01:39,456 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [130] -  Disconnecting from Outlook application.
2021-02-27 20:01:39,547 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [952] -  Attaching to the already running Outlook process.
2021-02-27 20:01:39,549 WARN  3 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [958] -  Attachment failed.
2021-02-27 20:01:39,549 FAIL  3 OutlookGoogleCalendarSync.OGCSexception [21] -  System.NullReferenceException: Object reference not set to an instance of an object.
2021-02-27 20:01:39,550 FAIL  3 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: GetCalendarEntriesInRange() in <Unknown File>
2021-02-27 20:01:39,551 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [997] -  Starting a new instance of Outlook.
2021-02-27 20:01:39,555 DEBUG  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [29] -  Setting up Outlook connection.
2021-02-27 20:01:39,567 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [48] -  Exchange server version: 15.0.1497.4004
2021-02-27 20:01:39,568 INFO  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [50] -  Exchange connection mode: olCachedConnectedFull
2021-02-27 20:01:39,572 DEBUG  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [226] -  Getting active window inspector
2021-02-27 20:01:39,577 DEBUG  3 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [231] -  Done.
```

**Comment by phw198** [comment] 2021-04-18 18:09
Although you raised this first, this looks like a duplicate of #1209 which has a hotfix posted for testing - please test that.

**Closed as completed by phw198** 2021-04-18 18:09 UTC
Labels: bug, duplicate
