### ISSUE TITLE
Sync error Failed to retrieve master for Google recurring event outside of sync range.

### ISSUE THREAD

**Issue by tdalon** [phw198/OutlookGoogleCalendarSync#1080] opened 2020-09-08 07:02 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
See log below and attached.
[ErrorReporting.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5186597/ErrorReporting.zip)
```
Sync version: 2.8.4.0

Sync started at 2020-09-08 08:56:59

Syncing from 2020-09-08 to 2020-11-08

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

59 Outlook calendar entries found.

Scanning Google calendar...
48 Google calendar entries found.

4 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...

Failed to retrieve master for Google recurring event outside of sync range.


Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Finding Calendar Entries
Scanning Outlook calendar...

59 Outlook calendar entries found.

Scanning Google calendar...


The following error was encountered during sync:-

ERROR: Unable to connect to the Google calendar.

Finding Calendar Entries
Scanning Outlook calendar...

59 Outlook calendar entries found.

Scanning Google calendar...
48 Google calendar entries found.

4 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...

Failed to retrieve master for Google recurring event outside of sync range.

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Sync aborted after 3 failed attempts!
```

**Comment by phw198** [comment] 2020-11-01 16:44
Duplicate of #1053 - fixed in v2.8.5.

**Closed as completed by phw198** 2020-11-01 16:44 UTC
Labels: bug, duplicate, old release
