### ISSUE TITLE
Unable to update existing entries in the Outlook calendar - The object does not support this method

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#897] opened 2019-11-17 22:29 UTC
**OGCS Version**: v2.8.2.0
**Edition**: Installed
**Sync Direction**: G->O 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3856197/OGcalsync.log)

**Bug Description**  
Same error happens on every sync on two different computers syncing G->O
Log says:

Comparing <number> Outlook calendar entries
Unable to update existing entries in the Outlook calendar
The object does not support this method
Sync aborted after 1 failed attempts!

**Steps to Reproduce the Issue**  
Secheduled sync causes the error every time.

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

NOTE: I have sync frequency set at one hour, but this error causes a sync to be scheduled in another 15 minutes, and every 15 minutes thereafter, creating one sync failed popup for each attempt, asking if I want to try again. If unattended, there is a large stack of popups. Because placement of those popups are not precise, they are not in order, which means individually closing them out is tedious. How about (1) stopping after "n" attempts of automatic retrying?

**Comment by phw198** [comment] 2019-11-24 12:29
Please could you increase your logging level to `FINE`, then restart OGCS, reproduce the problem and upload your logfile.

:thought_balloon: Also, ~~I think #858 may be related~~...

**Comment by phw198** [comment] 2019-11-24 12:45
I replicated it with this:
1. Create recurring series in Google, assign colour
1. Sync to OGCS including colours
1. Create exception in Google series, assign different colour to exception
1. Sync to OGCS - error

This is because Outlook does not support different categories on exceptions.

**Comment by phw198** [comment] 2019-11-24 13:02
:package: This should now be resolved with [hotfix v2.8.2.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3883576/v2.8.2.14.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by dutch55** [comment] 2019-11-25 03:41
hotfix v.2.8.2.14 eliminates the error. Good work! Thank you.

**Closed as completed** 2019-12-16 00:05 UTC
Labels: bug, resolved
