### ISSUE TITLE
1 erroneous delete in outlook - INFO

### ISSUE THREAD

**Issue by chipbite** [phw198/OutlookGoogleCalendarSync#1586] opened 2023-01-18 10:52 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.0.0
**Edition**: Installed
**Sync Direction**: O<->G

**Bug Description**  
Added two calendar events, sync - both get added.
For some reason, it sync again - and, surprisingly, **1 gets deleted**. (No edits were made between these syncs)

**Note:** I have confirmations on, and the **confirmation worked**: I got the question, and I reacted, because I know that I had not deleted anything. So, I approved it, to see if I was understanding it correctly, if it was really going to delete (I thought, "this can't be right, is it really deleting an event, I need to see what happens..."). 
Now, I wonder what I could have done at this point? I would have wanted to up the log level, but I think the modal dialogue blocks me from interacting with the UI, not sure. Maybe I could have declined, upped loglevel and synced again hoping it would have arrived at the same deletion decision. 

> ❓  **Q: What is the best approach here? (to get more info)**
For now, I have upped the loglevel to FINE. Does it purge old logs, looks like it from the log?

**Problem:** Unclear why deletion decision was made by sync. My trust in the sync is lowered.
**_Please see screenshot below._**

**Steps to Reproduce the Issue**  
No repro, issue not clear.

**Any other information**  
My log level was WARN, so the log doesn't say anything, really. 
But for forms sake, here it is:
https://gist.github.com/chipbite/7fd8efe2dbadfaf5f4fd7dfba23eb075

Similar issues found:
* This was reported 2 weeks ago: #1555 

* ⚠️ **Update:** Now, I started another sync and it wants to delete the event in google calendar also, finishing the job. The end result is scary, I really have to pay attention to the sync deletion confirmations or it will not work. 
My workaround will be to set it to one way sync, it should be able to handle that.

# Screenshots
### Here you can see both calendar windows side by side at this time, status after the sync with the deletion:
![image](https://user-images.githubusercontent.com/559199/213150255-b3392f71-14be-4f6e-a618-16e6e9e17ca2.png)

### Here is the sync window output at this time:
![image](https://user-images.githubusercontent.com/559199/213150677-f7b5c72f-8a92-4d7c-8aea-f3c5c0a4a117.png)

### Finishing the delete so no one ever sees it again (thankfully, I caught it this time):
<img width="502" alt="image" src="https://user-images.githubusercontent.com/559199/213154235-6dccdbe8-bac7-4faa-a6cd-2df620b6921d.png">

**_I report this to raise awareness of an issue. I will keep my eyes open now, hoping I can catch and provide more info._**

**Comment by westr029** [comment] 2023-01-24 09:05
I think this is a similar issue as #1583 , since looking to your screenshot, it is deleted seconds after you created it. Is that right?

**Comment by chipbite** [comment] 2023-01-24 18:22
Yes, the timing is similar. But it was not during the same sync - so create
in one sync, and delete after. But yes, the syncs happened directly, it
seems. It could be the same issue causing it.

**Comment by phw198** [comment] 2023-03-18 14:52
:arrow_double_up: In order to receive support you need to upgrade to latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Please then confirm if the issue still remains.

**Comment by phw198** [comment] 2023-03-26 12:26
> Yes, the timing is similar. But it was not during the same sync - so create in one sync, and delete after. But yes, the syncs happened directly, it seems. It could be the same issue causing it.

Your second screen shot shows the add to Google and the delete in Outlook within the same sync, so this is a duplicate of #1583.

Both tickets have ignored guidance to reproduce issues on the latest alpha release before reporting though...

**Closed as completed by phw198** 2023-03-26 12:26 UTC
Labels: bug, duplicate, old release
