### ISSUE TITLE
Objektverweis wurde nicht auf eine Objektinstanz festgelegt

### ISSUE THREAD

**Issue by Schommes** [phw198/OutlookGoogleCalendarSync#1449] opened 2022-04-27 07:30 UTC
I am using the installed version 2.9.4 on a windows 11 machine an Outlook from Office 365 for enterprise. Approximately since upgrading to the new version I am receiving the above error statement. Sync direction ist O ->G. 

> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8569835/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8569848/OGcalsync.log)

**Comment by gismo2004** [comment] 2022-04-27 16:03
As a workaround: "Set color/category" to "something you like" fixes this...

**Comment by Schommes** [comment] 2022-04-28 08:50
> As a workaround: "Set color/category" to "something you like" fixes this...

In my version "Set color/category" has no option called "something you like" (only "calender default" and the list of coloring options) or did you mean to say that I could choose any of the colorings listed?
Anyway following your hint I just disabled "Set color/category" entirely and that worked. So thank you for pointing me into the right direction. 👍

**Comment by Schommes** [comment] 2022-04-28 08:51
@everybody: Should I close this now on the basis of the workaround, or rather not, since the basic issue is not fixed?

**Comment by pkaak** [comment] 2022-04-28 11:56
I have the same problem. Not syncing the colors/categories and/or setting it to a default is not an option for my calendar. So please keep this open till it is properly fixed and this can be tracked.

**Comment by sansnil** [comment] 2022-05-02 15:24
I've been seeing this with 2.9.4 since released. No workaround for me so please leave open until fixed.

**Comment by phw198** [comment] 2022-05-02 17:54
Duplicate of #1422 which has a hotfix posted.

**Closed as completed by phw198** 2022-05-02 17:54 UTC
Labels: bug, duplicate

**Comment by Schommes** [comment] 2022-05-03 07:47
Hotfix worked. Thank you.
