### ISSUE TITLE
Crash: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jorgenbosman** [phw198/OutlookGoogleCalendarSync#1022] opened 2020-06-25 07:23 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4.0 alpha  
**Edition**: Installed
**Sync Direction**: G->O 

**Bug Description**  
```
2020-06-25 09:18:40,744 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  List Calendar folders
2020-06-25 09:18:40,754 WARN  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Outlook calendar selection changed to: Duofoto.be (ID: 00000000BD44488375F5D21191AC0008C7F952CB0100D52B906F6BD7DC49842701B1D16FE7E1000009288A200000)
2020-06-25 09:18:40,760 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2020-06-25 09:18:40,760 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2020-06-25 09:18:40,760 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Forms.Main.updateGUIsettings()
   at OutlookGoogleCalendarSync.Forms.Main..ctor(String startingTab)
   at OutlookGoogleCalendarSync.Program.Main(String[] args)
2020-06-25 09:18:40,761 FATAL  1 OutlookGoogleCalendarSync.Program [0] -  Application unexpectedly terminated!
2020-06-25 09:18:42,508 WARN  1 OutlookGoogleCalendarSync.Program [0] -  Tidying down any remaining Outlook references, as OGCS crashed out.
2020-06-25 09:18:42,509 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookOld [0] -  De-referencing all Outlook application objects.
2020-06-25 09:18:42,542 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookOld [0] -  Disconnecting from Outlook application.
2020-06-25 09:18:42,554 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Application closed.
```

**Steps to Reproduce the Issue**  
1. start application

**Any other information**  
Upgraded from 2.8.3.0 to 2.8.4.0 
:paperclip: 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4829628/OGcalsync.log)

**Comment by phw198** [comment] 2020-06-25 07:28
Surely a duplicate of #1020. Either apply that hotfix or just re-download 2.8.4.0 and reinstall.

**Closed as completed** 2020-06-25 22:52 UTC
Labels: bug, duplicate
