### ISSUE TITLE
"Unable to check for new version."

### ISSUE THREAD

**Issue by pnocero** [phw198/OutlookGoogleCalendarSync#595] opened 2018-09-17 16:59 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
\Whenever I select "Check for Update" on the "About" page, I receive the message "Unable to check for new version"

**Steps to Reproduce the Issue**  
1. \This happens every time I try it
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-09-17 17:27
Duplicate of #497

**Closed as completed by phw198** 2018-09-17 17:27 UTC
