### ISSUE TITLE
Add feature: Google contacts sync with outlook

### ISSUE THREAD

**Issue by nitinjs** [phw198/OutlookGoogleCalendarSync#2033] opened 2024-12-25 07:40 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Google contacts sync with outlook

**Describe alternatives you've considered**
Manually export and import google contacts in outlook

**Additional context**
-

**Comment by phw198** [comment] 2024-12-28 12:41
Duplicate of #407

**Closed as completed by phw198** 2024-12-28 12:41 UTC
Labels: enhancement
