### ISSUE TITLE
How to stop syncing and delete all synced events from Google Calendar

### ISSUE THREAD

**Issue by voodoochild1979** [phw198/OutlookGoogleCalendarSync#1187] opened 2021-03-10 22:14 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\I no longer need to sync Outlook to Google (may need it again in the future). I disconnected my Google account from OGCS and then uninstalled it, but all the synced Outlook events are still showing in my Google calendar years into the future. How can I eliminate all these synced events?

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2021-03-13 20:50
Duplicate of #125 which contains some instructions how this might be achieved.

**Closed as completed** 2021-04-18 18:41 UTC
Labels: duplicate
