### ISSUE TITLE
Full Sync Not Updating Cloaked Attendee Emails

### ISSUE THREAD

**Issue by lasagnacrab** [phw198/OutlookGoogleCalendarSync#1037] opened 2020-07-07 19:59 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.4-Alpha  
**Edition**: Installed  
**Sync Direction**: O->G 

**Bug Description**  
During a Full Sync, emails of attendees are not updated to .ogcs on existing Outlook -> Google meetings after cloaking checkbox has been ticked. Descriptions and locations are also not updating. New meetings do produce cloaked emails. Not sure if this is useful information, but I had to delete and reinstall OGCS recently, before making any updates to my settings and finding issues. OGCS should still be able to recognize the events synced from Outlook to Google from the previous install, correct?

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
I've been using OGCS for a bit and just realized that when I delete calendar events on Google it emails all the attendees, and has caused me quite some embarrassment and anxiety. Trying to get the cloaking option to work properly, but I cannot get the email addresses to update to .ogcs on the google side. I've attached my log file as well as my current options. I had more settings turned on, but pared them down as to not pass as much info between calendars. 

Thanks for any help!

![OGCS Settings](https://user-images.githubusercontent.com/67978700/86835844-52668580-c062-11ea-9429-fbc750292100.PNG)

:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4886892/OGcalsync.log)

**Comment by phw198** [comment] 2020-07-19 14:52
The non-update of description and location is by design, so as not remove information which _may_ not have been populated by OGCS sync (eg existed before and OGCS is merging calendars). For these you could just delete the appointment (after successfully cloaking attendees!) and let OGCS recreate them?

However, not cloaking/decloaking attendee email addresses is a bug.

:package: This bug should now be resolved with [hotfix v2.8.4.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4943852/v2.8.4.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by lasagnacrab** [comment] 2020-07-19 17:33
This worked, thank you so much! I hit an API limit, but will finish converting the addresses once it resets.

The Description and Location sync makes sense. I plan on just deleting the appointment after cloaking the emails and re-syncing like you suggested.

Cheers!

**Closed as completed** 2020-10-25 19:16 UTC
Labels: bug, resolved
