### ISSUE TITLE
certain events in outlook are deleted on sync to google

### ISSUE THREAD

**Issue by jlrose13** [phw198/OutlookGoogleCalendarSync#316] opened 2017-08-30 14:14 UTC
OGCS prompts for deletion of certain event that are created in outlook.  settings set to prompt for deletions.  sync is set to two way.  if I run one way sync outlook>Google, seems to solve issue on future two way syncs.

I created three events, all titled JMR Driver Ed, but on three different dates.  One date (Feb 13) syncs ok, but I get prompts for deletion of other two dates (Sep 25/Nov 28).  

[OGcalsync.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1263855/OGcalsync.zip)

**Comment by phw198** [comment] 2017-08-31 21:37
Your logfile barely has any content.

How are you creating the 3 appointments in Outlook? Do you 
1. create all 3 from scratch and then perform a sync; or
1. create one, perform a sync, copy the item on to the other days; perform another sync

**Comment by jlrose13** [comment] 2017-09-01 00:53
Created the first event, then copy/paste for the other two and just adjusted the date/time on each

**Comment by phw198** [comment] 2017-09-17 23:17
This will be a duplicate of #224, which should now be fixed in v2.6.2.

**Closed as completed** 2017-09-17 23:17 UTC
Labels: duplicate

**Comment by kostaslgr** [comment] 2019-02-05 12:11
Hello! I am using version 2.7.0.0 and I have this issue for quite a long period of time. even with previous versions.

Today i went to outlook calendar and made some changes. I moved some last week's events/reminders for this week. When I opened Outlook Google Calendar sync and then i got prompted to delete the outlook events that were moved from last week to this week. In addition the google calendar events from last week were not removed (as they should since i moved them to this week. This is probably because the sync is 1 day before today, so this makes sense). 

I was hoping that this issue with deletions would be fixed with new versions but it does not. Today i was able to document it better because i know what i did. Other times, i get prompted to delete an event and i do not know why i get that prompt. If i had not selected to get the notifications, i would lose information for these events.

To help the discussion, when i did the changes on the outlook, the OGCS was not opened on the tray. I went to find it on the tray, and it as not present, i found if through windows programs and when i went to the settings to set it to open on every start, whenever i checked the box, it would be unchecked.

If there are some logs that i can send to help the solution of the issue, i am willing to do it, just give me some directions to follow and i will do it.

regards,
Konstantinos

**Comment by phw198** [comment] 2019-04-10 22:59
@kostaslgr First you'd need to upgrade to the latest alpha release and see if your problems get resolved. If they do, please raise a new issue ticket.

Note, even with the latest version, if you click and drag Outlook appointments or copy and paste them, you must make sure OGCS is always running else problems will still occur.
