### ISSUE TITLE
Daylight savings issue

### ISSUE THREAD

**Issue by sidd7** [phw198/OutlookGoogleCalendarSync#645] opened 2018-12-24 06:30 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: 2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
I work in India and get Calendar invites from colleagues in the US. They're all coming across fine in Outlook, but OGCS is adding them to my Google calendar 1 hour early. I'm guessing you have not accounted for daylight savings?

**Steps to Reproduce the Issue**  
1. Send and invite from a US timezone to IST (or simulate the timezones) from Outlook to Outlook.
2. In OGCS, set up Outlook --> Google one way sync only.
3. Sync. You will notice that the recipient's Outlook in India adds it correctly in the default calendar, but when OGCS syncs, it shows up 1 hour earlier in Google Calendar

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-12-25 01:57
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by [downloading the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

Then perform a full sync by pressing `Shift` while clicking `Sync` - see if the issue remains.

**Comment by phw198** [comment] 2018-12-25 15:08
Thanks for confirming 👍🏻
Duplicate of #67

**Closed as completed** 2018-12-25 15:09 UTC
Labels: duplicate, old release
