### ISSUE TITLE
Birthday calendar event update failes

### ISSUE THREAD

**Issue by mayonezo** [phw198/OutlookGoogleCalendarSync#1797] opened 2024-02-07 09:23 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.3.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**
![Screenshot 2024-02-07 102035](https://github.com/phw198/OutlookGoogleCalendarSync/assets/5090215/fc97b9b8-9b36-428d-b869-fe6650c1f7b3)
This error message appears every sync run. 

**Steps to Reproduce the Issue**  
1. Add birthday to contact in Outlook.
2. Start sync.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: `OGcalsync.log` file via E-Mail.

**Comment by phw198** [comment] 2024-02-10 13:43
Duplicate of #1776 which has a hotfix.

**Closed as completed by phw198** 2024-02-10 13:43 UTC
Labels: bug, duplicate
