### ISSUE TITLE
Persistent recurrence error

### ISSUE THREAD

**Issue by SamuelStevenson** [phw198/OutlookGoogleCalendarSync#1467] opened 2022-05-12 22:39 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.4.0  
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Getting six of the following errors: "You changed one of the recurrences of this item, and this instance no longer exists. Close any open items and try again. If this keeps happening, please restart OGCS."

Error is persistent, even after restarting both OGCS and Outlook.

**Steps to Reproduce the Issue**  
1. Open OGCS
2. Attempt to sync.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8682929/OGcalsync.log)

**Comment by phw198** [comment] 2022-05-14 21:00
Duplicate of #1432

**Closed as completed by phw198** 2022-05-14 21:00 UTC
Labels: bug, duplicate
