### ISSUE TITLE
GOOGLE CALENDAR REMINDER AND GOOGLE CALENDAR BIRTHDAY SYNC ON OUTLOOK

### ISSUE THREAD

**Issue by paoloferrero1234** [phw198/OutlookGoogleCalendarSync#875] opened 2019-10-29 12:31 UTC
GOOGLE CALENDAR REMINDER AND GOOGLE CALENDAR BIRTHDAY SYNC ON OUTLOOK
IS IT POSSIBLE TO HAVE?
THANKS A LOT
Paolo

**Comment by phw198** [comment] 2019-10-29 22:37
Aren't they just the built in Google "Reminder" calendar and "Birthday" calendar? If you select them for sync to Outlook I should imagine it works? Not at my computer to test it right now...

**Comment by Kimble89** [comment] 2019-11-08 12:07
Same Problem.
Yes i can choose Google Contacs but this Calender is Read Only. So i synched the google contacts to outlook one time this worked. After that i chose my normal google calender for 2way synchronisation with outlook. The Problem is now: When i got a new Birthday in my Google contacts it will not synched with outlook because i cannot choose 2google calenders at the same time. so i see no chance to synch google contacts( Birthdays) permanently or?

![ogcs2](https://user-images.githubusercontent.com/57529094/68475502-95006580-0228-11ea-8843-50977870bfe1.JPG)

![ogcs1](https://user-images.githubusercontent.com/57529094/68475492-903bb180-0228-11ea-95dd-197c7d51d22e.JPG)

**Comment by Kimble89** [comment] 2019-11-08 12:13
for example i got a new birthday in google calender
![ogcs3](https://user-images.githubusercontent.com/57529094/68475860-8bc3c880-0229-11ea-9e98-b360501f9c48.JPG)
but this will not get synchronized to outlook
![ogcs4](https://user-images.githubusercontent.com/57529094/68475871-8fefe600-0229-11ea-9667-71ba7b1d9553.JPG)

**Comment by phw198** [comment] 2019-12-09 23:48
@Kimble89 So you want to sync multiple calendars? Common request over on #165 

Closing this now, as the original question from @paoloferrero1234 is answered, and I'm also irritated by their shouting :roll_eyes:

**Closed as completed by phw198** 2019-12-09 23:48 UTC
Labels: question
