### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by sattar** [phw198/OutlookGoogleCalendarSync#1294] opened 2021-09-22 17:17 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0  
**Edition**: Installed 
**Sync Direction**: O->G

**Bug Description**  
I recently updated the software version. Ever since the update, I get an error indicating a key is not present in the dictionary. No syncing is happening.

**Steps to Reproduce the Issue**  
1. Meetings were deleted in my outlook calendar
2. Changes are pushed to Google via the sync app whenever a change occurs in Outlook
3. Sync starts
4. Sync fails with the error "The given key was not present in the dictionary.".

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7212622/OGcalsync.log)
.

**Comment by phw198** [comment] 2021-09-22 20:43
Thanks, but this is a duplicate of #1289

**Closed as completed by phw198** 2021-09-22 20:43 UTC
Labels: bug, duplicate
