### ISSUE TITLE
Exceeded Quota Sync Failed

### ISSUE THREAD

**Issue by RayFromTLC** [phw198/OutlookGoogleCalendarSync#1107] opened 2020-10-26 19:34 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.8.0.0  
**Installed or Portable**: Installed

**Problem Description**  
\<Update here>
```
Sync version: 2.8.0.0

Sync started at 26/10/2020 19:21:20

Syncing from 25/09/2020 to 10/04/2021

Outlook ↔ Google

Finding Calendar Entries
Scanning Outlook calendar...

47 Outlook calendar entries found.

Scanning Google calendar...

43 Google calendar entries found.

Total inc. recurring items spanning sync date range...

Failed to retrieve Google event

Failed to retrieve master for Google recurring event outside of sync range.

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Finding Calendar Entries
Scanning Outlook calendar...

47 Outlook calendar entries found.

Scanning Google calendar...

43 Google calendar entries found.

Total inc. recurring items spanning sync date range...

Failed to retrieve Google event

Failed to retrieve Google event

Failed to retrieve Google event

Failed to retrieve master for Google recurring event outside of sync range.

Quota exceeded for quota group 'default' and limit 'Queries per day' of service 'calendar-json.googleapis.com' for consumer 'project_number:653617509806'. [403=Forbidden]

Operation aborted after 2 failed attempts!
Another sync has been scheduled to automatically run in 120 minutes time.
```
**Steps to Reproduce the Issue**  
1. \<Update> Restarted computer. Checked for update
1. 

**Any other information**  
\<Update here>

**Comment by bluebourbon** [comment] 2020-10-26 19:40
Same issue for me.  Rebooted, update, no change.

**Comment by LHuisingh** [comment] 2020-10-26 20:17
Just upgraded to 2.8.5 Alpha.  I'm getting these errors about Google quotas that I have never seen before.

I tried 2.8.4 just in case but I get run time errors.  Something has changed somewhere.

**Comment by RayFromTLC** [comment] 2020-10-26 20:30
Does anyone from the app check this forum? Hopefully they will get back with a solution as it seems to be a widely spread bug

**Comment by famco75** [comment] 2020-10-26 20:34
This too just started happening to me within the hour. It must be something
with Google...

**Comment by phillylewister** [comment] 2020-10-26 20:38
Might be a developer scheme to make money. Updated to 2.8.5.0 and I'm seeing a message saying pay some money to get guaranteed quota. "Unable to retrieve Google calendar's global timezone. Google's free daily Calendar quota has been exhausted! New quota comes into effect 08:00 GMT or get guaranteed quota for just £1/month."

**Comment by RayFromTLC** [comment] 2020-10-26 21:07
Hmmm so instead of being honest and open they are making life difficult.  If that is the case I am not impressed. I would happily have paid £1 a month for what used to be an excellent service but if they are now going to start charging extra and not tell the truth I think it may be time to dump this app. I will wait another 24 hours and then see what is happening.

**Comment by phw198** [comment] 2020-10-26 23:16
@RayFromTLC Yes someone from the app does check the GitHub issues - but there's only me and it's a spare time project.

So firstly, this is a duplicate of #1053 which provided a fix with the release of v2.8.5 yesterday, whereby Google had changed the error message which reported daily quota being exhausted.

However, today what seems to be a Google glitch started reporting quota exhausted at 18:00 GMT today - a good 12 hours at least before it usually happens. I can see the errors are tailing off too, which indicates quota wasn't really all used up. This has nothing to do with the #1053 fix.

![image](https://user-images.githubusercontent.com/11843015/97238196-b8794300-17e0-11eb-8440-a1413af309ef.png)

I've always been as clear as I possibly can be about costs; even have an [entire wiki page](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Is-OGCS-Free%3F) about it. I do my best to keep up with Google's changes and quirks, but I do have a day-job too...

**Comment by famco75** [comment] 2020-10-27 00:08
Mine is working now. Thanks for your help!

**Comment by RayFromTLC** [comment] 2020-10-27 14:46
phw198 Thanks for the clarification and the link to the wiki page. I did not know any of that.

**Closed as completed** 2020-11-29 17:01 UTC
Labels: duplicate
