### ISSUE TITLE
Errors after upgrading to latest version

### ISSUE THREAD

**Issue by PaulOckenden** [phw198/OutlookGoogleCalendarSync#206] opened 2017-05-15 11:16 UTC
I get this when I try to Sync:

**Comparing 22 existing Google calendar entries...
WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]**

It happens LOADS of times.

**Comment by Catskinner** [comment] 2017-05-16 04:59
I'm having the same problem. The error message seems to be identical:

**Comparing 32 existing Google calendar entries...
WARNING: Updated event failed to save.
Google.Apis.Requests.RequestError
Precondition Failed [412]
Errors [
	Message[Precondition Failed] Location[If-Match - header] Reason[conditionNotMet] Domain[global]
]**

However it repeats several time for each sync. I assume it's related to the number of events that are causing a problem.

**Comment by phw198** [comment] 2017-05-16 23:20
Looks like a duplicate of issue #83.

**Closed as completed by phw198** 2017-05-16 23:20 UTC
Labels: bug, duplicate
