### ISSUE TITLE
O<>G issues

### ISSUE THREAD

**Issue by thekidb** [phw198/OutlookGoogleCalendarSync#1131] opened 2020-12-01 21:42 UTC
> Checklist:-
> * [x ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ x] Reproduce the issue
> * [x ] Complete the information below
> * [x ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.5.0
**Edition**: Installed
**Sync Direction**:  O<->G

**Bug Description**  
Items created in Outlook are not synced to Google and are then deleted from Outlook when the direction is reversed.  This happens on bidirectional sync.  If created in Outlook and synced one way to Google, it works.  If created in Google and bi synced, it also works.  Issue is always when item is created in Outlook and bi-synced.

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5625585/OGcalsync.log)

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5625600/OGcalsync.log)

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by eddydee123** [comment] 2020-12-02 06:29
@thekidb Is this the same as #1123 ?

**Comment by thekidb** [comment] 2020-12-02 12:59
After reviewing #1123, it appears that I am having the same or a very similar issue.

**Comment by sergio-rsi** [comment] 2020-12-11 13:34
Hi,

I'm experiencing the same issue with version 2.8.5-alpha: when creating a new event in Outlook and sync starts, it is created in Google Calendar but then the sync is reversed (Outlook<-Google Calendar) and the event is deleted in Outlook.

When the next synchronization starts, the event can still be found in Google Calendar but as it was deleted in Outlook it does the same in Google Calendar.

I had to check the "Confirm Deletions" option in order to manually stop these deletions.

**Comment by amig500** [comment] 2020-12-15 10:15
+1

**Comment by xcatasus** [comment] 2020-12-21 07:57
I have the same problem since I installed 2.8.5.0 version
In my case, i doesn't happen every time I make a new event in Outlook, but it does most of the time

**Comment by phw198** [comment] 2020-12-27 18:42
Yes, this is a duplicate of #1123 - I'll close this issue as there's a potential hotfix posted on the other.

**Closed as completed by phw198** 2020-12-27 18:42 UTC
Labels: bug, duplicate

**Comment by amig500** [comment] 2020-12-28 09:12
The suggested hotfix does not work.

**Comment by phw198** [comment] 2020-12-28 12:06
@amig500 Because, as far as I can tell, it's not related to your issue.

**Comment by amig500** [comment] 2021-01-04 14:00
I confirm that this describes my problem too and the bug is still there.
