### ISSUE TITLE
login fail - Could not load file or assembly 'office, Version=12.0.0.0'

### ISSUE THREAD

**Issue by drmorris66** [phw198/OutlookGoogleCalendarSync#659] opened 2019-01-26 15:45 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.0.0  
**Installed or Portable**: Installed

**Problem Description** 
login fail

**Steps to Reproduce the Issue**  

![image](https://user-images.githubusercontent.com/47060819/51789423-a1776e00-2180-11e9-89ee-57eeade0c8b9.png)

1. 

**Any other information**
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2799162/OGcalsync.log)
Medion akoya notebook; Win10,Office 365 Personal

**Comment by drmorris66** [comment] 2019-01-26 15:47
Apologies; noob but it's working great at work, even with my "it'sthe NHS,we've locked down your computer like you're a kid"

**Comment by phw198** [comment] 2019-01-26 17:07
Looks like a duplicate of #455 - basically just upgrade to latest alpha ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by [downloading the latest version directly from the project website](https://phw198.github.io/OutlookGoogleCalendarSync/).

**Comment by drmorris66** [comment] 2019-01-31 17:40
That did it. Thanks

Sent from Mail for Windows 10

**Closed as completed** 2019-01-31 17:48 UTC
Labels: duplicate, old release
