### ISSUE TITLE
Error With Sync

### ISSUE THREAD

**Issue by MiktaNaji** [phw198/OutlookGoogleCalendarSync#218] opened 2017-05-25 17:38 UTC
I am getting an error when I am doing a one way push sync from Outlook to Google.

Below is the Debug output contained in the log:
```
2017-05-25 11:33:56,790 DEBUG 1 OutlookGoogleCalendarSync.SyncTimer [0] - Scheduled sync triggered.
2017-05-25 11:33:56,798 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Scheduled sync started.
2017-05-25 11:33:56,880 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Sync version: 2.4.0.0
2017-05-25 11:33:56,882 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Sync started at 5/25/2017 11:33:56
2017-05-25 11:33:56,884 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Syncing from 5/24/2017 to 9/23/2017
2017-05-25 11:33:56,888 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Outlook → Google
2017-05-25 11:33:56,889 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2017-05-25 11:33:56,890 INFO 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Deregistering from Outlook appointment change events...
2017-05-25 11:33:56,890 DEBUG 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Removing 1 Outlook event handler hooks.
2017-05-25 11:33:57,018 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - Reading Outlook Calendar Entries...
2017-05-25 11:33:57,221 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - 29 Outlook calendar entries found.
2017-05-25 11:33:57,323 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2017-05-25 11:33:57,425 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - Reading Google Calendar Entries...
2017-05-25 11:33:57,425 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all events from Google: 5/24/2017 -> 9/23/2017
2017-05-25 11:33:57,695 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
2017-05-25 11:33:57,830 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - 12 Google calendar entries found.
2017-05-25 11:33:57,830 DEBUG 19 OutlookGoogleCalendarSync.Recurrence [0] - Identifying exceptions in recurring Google events.
2017-05-25 11:33:57,830 DEBUG 19 OutlookGoogleCalendarSync.Recurrence [0] - Found 0 exceptions.
2017-05-25 11:33:57,934 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2017-05-25 11:33:58,036 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - Total inc. recurring items spanning sync date range...
2017-05-25 11:33:58,099 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID upv9r0ikjrm5o1j2nthrsoi428
2017-05-25 11:33:58,315 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID ev8ajki4am0733guopb5lgob34
2017-05-25 11:33:58,496 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all events from Google: 9/8/2010 -> 9/9/2010
2017-05-25 11:33:58,643 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Page 1 received.
2017-05-25 11:33:58,643 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Scanning 0 Google events for orphans to reclaim...
2017-05-25 11:33:58,643 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - 0 unclaimed.
2017-05-25 11:33:58,645 WARN 19 OutlookGoogleCalendarSync.Recurrence [0] - Failed to find master Google event for: 9/8/2010 (R) => "My Anniversary with Laura"
2017-05-25 11:33:58,729 DEBUG 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID 0cfaejr59rsudomp69pe425gc4
2017-05-25 11:33:58,873 WARN 19 OutlookGoogleCalendarSync.GoogleCalendar [0] - Found Google item missing Outlook IDs. 1/2/2014 7:00 (R) => "Renew Solarwinds Orion Agreement"
2017-05-25 11:33:59,050 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - Failed to retrieve master for Google recurring event.
2017-05-25 11:33:59,155 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - The following error was encountered during sync:-
2017-05-25 11:33:59,279 INFO 19 OutlookGoogleCalendarSync.MainForm [0] - Object reference not set to an instance of an object.
2017-05-25 11:33:59,280 ERROR 19 OutlookGoogleCalendarSync.OGCSexception [0] - System.NullReferenceException: Object reference not set to an instance of an object.
2017-05-25 11:33:59,280 ERROR 19 OutlookGoogleCalendarSync.OGCSexception [0] - Code: 0x80004003;-2147467261
2017-05-25 11:33:59,280 ERROR 19 OutlookGoogleCalendarSync.OGCSexception [0] -    at OutlookGoogleCalendarSync.MainForm.synchronize()
   at OutlookGoogleCalendarSync.MainForm.<>c__DisplayClass2.<sync_Start>b__0(Object o, DoWorkEventArgs args)
2017-05-25 11:36:25,989 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Setting 'CompletedSyncs' updated to '0'
2017-05-25 11:36:25,995 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Operation aborted after 1 failed attempts!
2017-05-25 11:36:25,995 INFO 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Registering for Outlook appointment change events...
2017-05-25 11:36:25,995 DEBUG 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Create the timer for the push synchronisation
2017-05-25 11:36:26,023 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Setting 'LastSyncDate' updated to '5/25/2017 11:33:56'
2017-05-25 11:36:26,025 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Another sync has been scheduled to automatically run in 5 minutes time.
2017-05-25 11:36:26,026 INFO 1 OutlookGoogleCalendarSync.SyncTimer [0] - Next sync scheduled for Thursday, May 25, 2017 - 11:41:26
```

**Comment by phw198** [comment] 2017-05-25 17:57
Duplicate of issue #82.

**Closed as completed by phw198** 2017-05-25 17:57 UTC
Labels: duplicate
