### ISSUE TITLE
Recurring Item Changed Does Not Change

### ISSUE THREAD

**Issue by CPapas** [phw198/OutlookGoogleCalendarSync#1812] opened 2024-03-01 12:41 UTC
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.10.2.0
**Edition**: Installed 
**Sync Direction**:  O->G 

**Bug Description**  
Weekly recurring calendar item doesn't sync a single change.  My supervisor has created a weekly recurring TEAMS calendar item that syncs to Outlook, every Thursday at 1:30 pm.  When a single event is changed - example February 29 meeting moved to March 1, the February 29 meeting is still on my Google calendar, and there is nothing on my March 1 calendar.

**Steps to Reproduce the Issue**  
1.  Weekly Recurring item Feb 29
2. Change just that one item to march 1.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14461126/OGcalsync.log)

**Comment by tracesva** [comment] 2024-03-01 14:58
I'm having the same issue.  Full transparency, today is the first day I've ever used the tool so theres a good chance I may be doing something wrong, but when I searched for the issue, this is the exact same issue I'm having so thought I'd comment on it to follow.

**Comment by rensec** [comment] 2024-03-08 09:41
Having the same issue, but in the direction G -> O: I changed a recurring event in Google but the change does not show up in Outlook. However, I also moved another event on the same day which is properly synced.

**Comment by phw198** [comment] 2024-03-16 15:19
@CPapas I can't reproduce this. You mention the recurring series is being created through Teams - I'm assuming you can see the occurrence has actually moved in the Outlook client? If so, does it make any difference closing down Outlook and restarting it?

@tracesva Outlook is very bad at caching changes that aren't immediately detectable by the API - this is especially true if you move an item by clicking and dragging it in Outlook. It's often better to double click, make an edit and then Close and Save - but either way, it should eventually sync to Google.

@rensec What was the change? If you _deleted_ an occurrence in Google, there is a bug fixed in v2.10.3 where deletions weren't syncing to Outlook.

**Closed as completed** 2024-04-23 08:35 UTC
Labels: bug, dormant
