### ISSUE TITLE
Could not load file or assembly 'office,version=12.0.0'

### ISSUE THREAD

**Issue by mjlipton** [phw198/OutlookGoogleCalendarSync#717] opened 2019-04-20 17:55 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Hi  -  just tried to run OGCS for first time and got error message "could not load file or assembly 'office,version=12.0.0., culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies.  The system cannot find the file specified."    Please advise.   

**Steps to Reproduce the Issue**  
Error recurs every time I try to run.   

**Any other information**  
Running on new Lenovo ThinkPad  64 bit Windows 10 Pro

**Comment by phw198** [comment] 2019-04-22 10:11
You've not said the version of OGCS you're trying to run, but assuming v2.7.0, then this is a duplicate of #455 and you just need to upgrade to the latest alpha release.

**Closed as completed by phw198** 2019-04-22 10:11 UTC
Labels: duplicate
