### ISSUE TITLE
"1 Outlook items would have been deleted, but you have deletions disabled." - Could it be possible to show which items could be deleted?

### ISSUE THREAD

**Issue by tadeas1** [phw198/OutlookGoogleCalendarSync#1656] opened 2023-05-29 08:05 UTC
"1 Outlook items would have been deleted, but you have deletions disabled." - Could it be possible to show which items could be deleted?

Thank you very much

Best regards

Tomas

**Comment by VictorStankov** [comment] 2023-05-30 15:59
Hi @tadeas1, you should consider upgrading as this is already a feature in [v2.9.7-alpha](https://www.outlookgooglecalendarsync.com/release-notes#v2970---alpha).

**Comment by phw198** [comment] 2023-05-30 20:20
Yep, this is a duplicate of #1594

**Closed as completed by phw198** 2023-05-30 20:20 UTC
Labels: duplicate, enhancement
