### ISSUE TITLE
Trying to install version 2.8.0.0

### ISSUE THREAD

**Issue by cw1961** [phw198/OutlookGoogleCalendarSync#937] opened 2020-01-07 15:34 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
When trying to install the application, it does not initialize (just stops).  Attaching OGcalsync.log

**Steps to Reproduce the Issue**  
1. Execute Setup.exe
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4031293/OGcalsync.log)

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2020-01-07 21:45
Looks like it fails at the line `CheckShortcut: directory=Startup; subdir=`. 

Is it actually crashing with an unhandled exception? If so, is there an entry in the Windows Event Viewer under "Application"?

Does the alpha v2.8.3 behave any differently?

**Comment by phw198** [comment] 2020-01-07 21:57
Yep, pretty sure this was fixed in v2.8.1 via #782

**Comment by Carottinger** [comment] 2020-04-15 15:01
I try to install a freshly downloaded 2.8.0 Beta in my companies Lenovo running Win10 1809. I get the same CheckShortCut Line (as DEBUG) and there are exception in the event log:
a) Application:
Name der fehlerhaften Anwendung: OutlookGoogleCalendarSync.exe, Version: 2.8.0.0, Zeitstempel: 0x5cf616d4
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.914, Zeitstempel: 0x6cc9b5fd
Ausnahmecode: 0xe0434352
Fehleroffset: 0x001219b2
ID des fehlerhaften Prozesses: 0x4fd8
Startzeit der fehlerhaften Anwendung: 0x01d6133599f7d775
Pfad der fehlerhaften Anwendung: C:\Users\stefan.haas.VF-ROOT\AppData\Local\OutlookGoogleCalendarSync\app-2.8.0-beta\OutlookGoogleCalendarSync.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 76361479-3052-4bb8-9c72-2930202668a0
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

b) .Net Runtime
Anwendung: OutlookGoogleCalendarSync.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ComponentModel.Win32Exception
   bei System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   bei System.Diagnostics.Process.Start()
   bei System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   bei OutlookGoogleCalendarSync.Program.isNewVersion(Boolean)
   bei OutlookGoogleCalendarSync.Program.Main(System.String[])

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/4482000/OGcalsync.log)

**Comment by phw198** [comment] 2020-04-18 21:32
@Carottinger The issue is already reported under 2.8.0 - would be more worthwhile confirming if the issue has been resolved in v2.8.1 and onwards...

**Closed as completed** 2020-06-14 20:42 UTC
Labels: old release
