### ISSUE TITLE
Multiple Outlook Calendars to one Google calendar

### ISSUE THREAD

**Issue by lammertsm** [phw198/OutlookGoogleCalendarSync#1207] opened 2021-04-14 08:43 UTC
Current only one Outlook calendar can be synced to Google.
Is it possible that there comes support for multiple calendars? So that you can sync Multiple Outlook calendar to one Google calendar for example?

**Comment by BrainWaveCC** [comment] 2021-04-15 17:53
I just came to ask for this very thing.  I now have two accounts in Outlook, and while I can connect one or the other, I am unable to connect both at the same time.

**Comment by phw198** [comment] 2021-04-24 17:26
Duplicate of #165

**Closed as completed by phw198** 2021-04-24 17:26 UTC
Labels: duplicate, enhancement
