### ISSUE TITLE
Appointment Update Failed - String was not recognised 

### ISSUE THREAD

**Issue by famco75** [phw198/OutlookGoogleCalendarSync#919] opened 2019-12-11 02:59 UTC
**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.
:paperclip: Attach your `OGcalsync.log` file.

**Comment by famco75** [comment] 2019-12-11 03:06
I copied and pasted images and files. Can they be seen? I am having trouble synchronizing my calendar. I am getting two error messages at the end of the synchronization "Appointment Update Failed - String was not recognised". Can someone please explain to me what the problem is? 

I tried to research to Github but am having trouble looking for a 'search' or area where I can investigate this... 

Thanks,
Franco

**Comment by famco75** [comment] 2019-12-11 03:17
I uploaded files via Google Form. I am not sure if you received them properly by me copying and pasting in here. 

Thanks,
Franco

**Comment by phw198** [comment] 2019-12-12 21:38
@famco75 This is a duplicate of #870 which has a hotfix posted.

**Closed as completed** 2019-12-12 21:38 UTC
Labels: bug, duplicate
