### ISSUE TITLE
Unable to change to an alternative mailbox

### ISSUE THREAD

**Issue by Chrys000** [phw198/OutlookGoogleCalendarSync#1809] opened 2024-02-24 19:09 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: 2.10.3.0 pre-release (tested with 2.10.2.0 alpha as well)
**Edition**: Installed
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
There is 3 Google email accounts (IMAP) in MS Office 365 Outlook (Windows 11 23H2). I want to set an alternative mailbox for sync in OGCS. I got an error and the Default mailbox will be set again.
You can see the message in the attached picture.

The accounts can be synchronized with Google in Outlook.

**Steps to Reproduce the Issue**  
Simply try to change the alternative mailbox to an other one.

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

![Screenshot 2024-02-24 194706](https://github.com/phw198/OutlookGoogleCalendarSync/assets/87262342/3d7ffe43-6c99-45c6-a073-3ca612a778c3)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14394120/OGcalsync.log)

**Comment by Chrys000** [comment] 2024-02-24 19:37
![Screenshot 2024-02-24 203406](https://github.com/phw198/OutlookGoogleCalendarSync/assets/87262342/3bc9bd26-9e04-4779-9bfe-ee0cd9e56050)

**Comment by phw198** [comment] 2024-03-16 13:48
I think this is a duplicate of #673 which has a confirmed hotfix available - let me know if that works.

**Closed as completed** 2024-04-23 08:35 UTC
Labels: bug, dormant
