### ISSUE TITLE
new vwersion causes an issue with sync

### ISSUE THREAD

**Issue by Simmst111** [phw198/OutlookGoogleCalendarSync#1433] opened 2022-04-15 17:43 UTC
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v1.2.3.4  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[](url
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8497292/OGcalsync.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8497293/OGcalsync.log)
)

**Comment by phw198** [comment] 2022-04-24 12:14
Duplicate of #1422 which has a hotfix posted.

**Closed as completed by phw198** 2022-04-24 12:14 UTC
Labels: bug, duplicate
