### ISSUE TITLE
Syncing Outlook  to google calendar is creating 2 reminders. Notification and email.

### ISSUE THREAD

**Issue by Ian1324** [phw198/OutlookGoogleCalendarSync#578] opened 2018-08-27 13:01 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.6.0
**Installed or Portable**: Portable
**Problem Description**  
Syncing Outlook  to google calendar is creating both notifcation and email reminder. It previously didin't. I only want notification, no emails for each calendar event.

**Steps to Reproduce the Issue**  
1. Create event in Outlook
2. Sync to google calendar

**Any other information**  
\<Update here>

**Comment by phw198** [comment] 2018-08-27 15:10
I'm pretty sure if you check in the Google calendar configuration, you'll find you've set a default reminder? Remove that and then you'll only get the synced OGCS reminder.

**Comment by phw198** [comment] 2018-11-25 11:53
Duplicate of #366

**Closed as completed by phw198** 2018-11-25 11:53 UTC
