### ISSUE TITLE
Deleting appointments from appointment series in sync

### ISSUE THREAD

**Issue by ladydi2023** [phw198/OutlookGoogleCalendarSync#1653] opened 2023-05-24 20:43 UTC
Sorry, i´m german, i hope you understand my problem:

Deleted appointments from appointment series from Outlook are not deleted in the synchronization, only individual appointments are removed. Concerns sync Outlook --> Google-Calendar, "confirm deletion" ist activated.

**Comment by phw198** [comment] 2023-05-25 22:48
Hi @ladydi2023 

You mean to say deleted occurrences from an Outlook recurring series are not being removed from Google? 

Please try these steps:
1. Restart Outlook to see if that fixes the issue
1. Try a "Full Sync" by pressing `Shift` and clicking `Sync`
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

**Comment by Kivi-Berlin** [comment] 2023-06-30 18:05
Same here with 2.10.0

Created a series once a week in Outlook
Sync into Google: OK --> Whole series is in Google
Deleted one element of the series in Outlook
Shift Sync into Google: NOK --> Still the whole series is in Google
Deleted the whole series in Outlook
Sync into Google: OK --> whole series is deleted in Google

I forwarded the logfile to your mail address.

**Comment by phw198** [comment] 2023-07-01 20:56
@Kivi-Berlin Following your steps through, it deleted the occurrence in Google for me.

Your log file has:
```
27.06.2023 12:00 (R) => "Series"
This is a recurring appointment with 1 exceptions that will now be iteratively compared.
Finding Google instance for deleted Outlook exception:-
Original date: 04.07.2023
Google exception event is not cached. Retrieving all recurring instances...
Retrieving all recurring event instances from Google for e7utonhajlk75tkarujo9mdthk
Page 1 received.
Matching Google Event recurrence found.
Another deleted occurrence on the same date 04-Jul-2023 found, so this Google item that has moved to that date will not be deleted.
```
The last line means that you deleted an occurrence, and then moved a different occurrence to the same date as the one just deleted, and _then_ also deleted that.

That's how I've replicated the issue anyway!

1. Created a series once a day in Outlook
1. Sync into Google: OK --> Whole series is in Google
1. Deleted one element of the series in Outlook, eg 30-Jun
1. Sync into Google: OK --> 30-Jun deleted in Outlook
1. Move the 1-Jul to the 30-Jun in Outlook
1. Sync into Google: OK --> 1-Jul moves to 30-Jun
1. Delete the moved 30-Jun occurrence in Outlook
1. Sync into Google: Not OK --> Item is not deleted with log entry `Another deleted occurrence on the same date 30-Jun-2023 found, so this Google item that has moved to that date will not be deleted.`

The problem is, due to Outlook shortcomings, it's not possible to know which occurrence is the original after an item is moved to the same date as a previously deleted occurrence.

I think the only option here is for manual intervention and to popup a box asking the user if they want to proceed with the deletion....

**Comment by phw198** [comment] 2023-07-01 22:01
:package: Please try with [hotfix v2.10.0.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11927209/v2.10.0.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) - this should now prompt if you want to delete.

Please let me know how it goes!

**Comment by Kivi-Berlin** [comment] 2023-07-02 09:23
@phw198 I followed the instruction and installed the fix.
I'll send the logfile in a separate mail.
Only during the first run were a lot of popups, but it did not synchronized the one removed occurrence in Outlook to Google.
Regarding the popups I suggest to consider the "Sync Settings", button "Sync Options", section "How": two checkboxes for deletions.

I didn't do that: _The last line means that you deleted an occurrence, and then moved a different occurrence to the same date as the one just deleted, and then also deleted that._
I just created a series. Synced it. Removed one occurence. Synced it again.

**Comment by phw198** [comment] 2023-07-02 10:43
In the log file, I only see
* The "Series" being created, but then no change detected afterwards.
    * Please can you close and reopen Outlook and try another sync (sometimes Outlook is really bad at caching appointments so other programs can't "see" the change for a while).
* The first run is just resolving the items that should have been deleted before - once gone, subsequent runs are clear
* When I followed your steps, I can't reproduce the issue. Also your first log includes lines that are only relevant if an occurrence is moved to the date of a deleted occurrence. We need to get your "Series" change synced to determine if it gets removed silently or you get a popup...

Update: OK, I have now reproduced the issue:
1. Follow your steps, but before you sync the deleted Outlook occurrence on date `x`
2. Ensure there is a _different_ recurring series in Google that already has an occurence on date `x` that is deleted/cancelled

This is certainly a bug :disappointed:

**Comment by Kivi-Berlin** [comment] 2023-07-02 11:09
I repeated the action to follow you advices:
Created a Google series
Synched
I closed Outlook and reopened it
I deleted the second occurence of the series
I closed Outlook and reopened it
Now OGCS did the sync fine. The second one was remove in Google
I tied it with another occurence of the series and it was also removed now from Google without restarting Outlook.

So I think the fix is well done.

**Comment by Kivi-Berlin** [comment] 2023-07-02 11:24
I did some more checks.
There was no difference whether I did the sync between creating the series and deleting one item or after it.
It only works after I restarted Outlook.

**Comment by phw198** [comment] 2023-07-02 11:47
> Update: OK, I have now reproduced the issue:
> 
> Follow your steps, but before you sync the deleted Outlook occurrence on date `x`
Ensure there is a _different_ recurring series in Google that already has an occurence on date `x` that is deleted/cancelled
This is certainly a bug

:package: Please test further with [hotfix v2.10.0.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11929365/v2.10.0.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Hopefully this is the full fix.

**Comment by Kivi-Berlin** [comment] 2023-07-02 16:37
Yes. v2.10.0.2 is fine.
When you create a series and delete an occurence before the next sync, then OGCS sync the series to Google and deletes the deleted occurence in Google.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/131468162/5858506b-48aa-4fd9-9e70-ce9e3a0321c4)

Minor point: If you delete another occurence from the same series after the sync, then the next sync deletes the occurence as it should. Fine so far. But there is no point in the sync output list about that.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/131468162/713c90ac-8e61-4b00-bedc-50b40e919e16)
It's only mentioned, if you delete the whole series.
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/131468162/dc63f0e9-9ea3-4681-a0c5-cdfbd1b9f9c2)

**Comment by phw198** [comment] 2023-07-02 20:19
Yes. I had been noticing the inconsistencies with the console output for series occurrence changes - I'll improve that in the next alpha release :+1: 

Thanks for confirming the fix!

**Comment by Gezzen** [comment] 2023-07-26 07:29
Hi, I faced the same issue, will test the hotfix. Thanks a lot for the prompt support all the time.

Something I realized, linked to this issue (probably rather a google issue):
When I deleted the entries manually in google calendar, it asks if I want to send decline notes. When clicking "No" it still sends them. I saw that ogcs adds the .ogcs to the email address, to prevent weird mails. So I assume this is known and if not mistaken for years not solved by google?

**Comment by phw198** [comment] 2023-07-26 22:40
@Gezzen Yes, it's [documented in the wiki](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#why-are-my-meeting-attendees-getting-notified-of-updates-to-events-in-google) and it's a shockingly awful bug that Google have simply refused to fix for years! OGCS is just a victim of this and the `.ogcs` appending is an equally "awful" workaround :slightly_smiling_face:

**Closed as completed** 2023-07-30 15:12 UTC
Labels: bug, resolved
