### ISSUE TITLE
v2.8.5 regression - popup when no network/VPN available

### ISSUE THREAD

**Issue by mkraftman** [phw198/OutlookGoogleCalendarSync#886] opened 2019-11-05 14:42 UTC
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
Synchronisation repeatedly stops with error pop-ups. The errors seem to be transient and a re-sync works fine.

**Steps to Reproduce the Issue**  
N/A

**Any other information**  
It would be great if a user could update their preferences within settings to retry or abort synchronisation rather than having it interrupted and needing to select a choice each time. It is annoying when away from your computer that synchronisation can be stopped for hours (or days when on vacation).

**Comment by ScottRochford** [comment] 2020-11-26 22:20
I'm pretty sure there used to be an option to suppress error pop-ups, especially for failed synchronisations when the network (or VPN in my case) is unavailable, but in 2.8.5.0 the behaviour has changed and they are back, and I can't find any option to turn them off.

**Comment by phw198** [comment] 2020-11-29 15:07
Zero information upon which to troubleshoot this in any way.

In order to receive support, you need to:
1. [Upgrade OGCS](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) and reproduce the issue on the latest ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
1. Provide your `OGcalsync.log` file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).

On the off chance the errors are quota related, the hotfix on #1120 might help.

**Comment by ScottRochford** [comment] 2020-11-30 22:26
I guess that's because the issue is less about the synchronisation failure, and more about the application behaviour when it does fail.  I am running 2.8.5.0 (as mentioned).  I've uploaded my latest OGCalSync.log via the google form.  

Incidentally, the log upload instructions say to contact you directly via https://github.com/phw198, but I can't actually see any contact methods on there?  Unless one is a tweeter perhaps?  I don't even know if they are private, I assume not.

This is a wonderful tool and your work really is appreciated!

**Comment by phw198** [comment] 2020-12-20 16:14
Hi @ScottRochford The issue you describe with your VPN not being ready on the first sync of the day, is a regression bug in the code for v2.8.5 (certainly not what the OP was reporting, but I've repurposed this ticket).

:package: This should now be resolved with [hotfix v2.8.5.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5721018/v2.8.5.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) - let me know how it goes.

And thanks for letting me know about the profile page - I'd made my email private, so I've updated the log upload instructions :+1:

**Comment by kuraikaze** [comment] 2020-12-28 07:00
No re-occurrence since hotfix v2.8.5.11 applied as per  https://github.com/phw198/OutlookGoogleCalendarSync/issues/886#issuecomment-748627877
It was intermittent rather than consistently reproducible, but I've slept/resumed the machine half a dozen times now without problem so it looks like that did the job.

**Comment by ScottRochford** [comment] 2020-12-28 22:57
Same here... thanks!

**Closed as completed** 2021-01-23 21:31 UTC
Labels: bug, resolved

**Comment by kuraikaze** [comment] 2024-04-13 22:31
Problem has started again with version v2.10.4-alpha (2.10.4.0)
i.e.
After PC resumes from S3 sleep or hibernation OGCS attempts a sync cycle immediately, frequently before the network stack has completed re-initialisation, leading to a connection failure which generates the error popup.
