### ISSUE TITLE
COM Exception encountered [0x80080005 CO_E_SERVER_EXEC_FAILURE]

### ISSUE THREAD

**Issue by jody-bossle** [phw198/OutlookGoogleCalendarSync#239] opened 2017-06-15 12:36 UTC
OGcalsync.log file attached; renamed to TXT as GitHub had an issue with LOG and ZIP.
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1077591/OGcalsync.txt)

**Comment by phw198** [comment] 2017-06-18 11:11
Looks like OGCS ran OK on the second attempt at starting it?

The full error message was:
`System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).`

Have you deployed OGCS to a server with Outlook on it? Was this just a one-off error, or does it happen repeatedly? What are the steps to replicate the problem?

**Comment by phw198** [comment] 2017-06-18 11:33
As luck would have it (or not), I _think_ I just had this same issue, though it didn't capture any logs so can't be sure. Anyway, an Office update was pushed out to me and my computer reboot. When it came back up OGCS tried to start on startup, which also starts up Outlook - but because Office was busy finishing the updates it errored out.

In the Windows event log I see `The server {0006F03A-0000-0000-C000-000000000046} did not register with DCOM within the required timeout.`. When Googling CO_E_SERVER_EXEC_FAILURE there is also a lot of mention of DCOM, so I think this is all tied together.

It's been requested for a while to have a delayed startup for OGCS after the machine has boot, so I'll log this issue as an enhancement request.

**Comment by phw198** [comment] 2017-08-26 19:33
Duplicate of #268

**Closed as completed by phw198** 2017-08-26 19:33 UTC
Labels: duplicate
